---
title: "Prétraitement"
author: "Serge-Étienne Parent"
date: "`r format(Sys.Date())`"
output: github_document
---

# Explorer R {#chapitre-preprocess}

 ***
️\ **Objectifs spécifiques**:

À la fin de ce chapitre, vous

- serez en mesure d'identifier les sources d'information principales sur le développement de R et de ses modules
- comprendrez l'importance du prétraitement des données, en particulier dans le cadre de l'analyse de données compositionnelles, et saurez effectuer un prétraitement adéquat
- saurez comment acquérir des données météo d'Environnement Canada avec le module [weathercan](http://ropensci.github.io/weathercan/)
- saurez identifier les modules d'analyse de sols ([soiltexture](https://github.com/julienmoeys/soiltexture) et [aqp](http://ncss-tech.github.io/aqp/docs/))
- saurez créer des cartes
- etc.

 ***

L'apprentissage de R peut être étourdissant. Cette section est une petite pause fourre-tout qui vous introduira aux nombreuses possibilités de R.

## R sur le web

## Transformation

## Standardisation

## À l'échelle de la plage

## Box-Cox

## Encodage catégoriel

## Analyse compositionnelle

- Transforamtion de données
- Encodage catégoriel
- Standardisation
- Logarithme
- Log-ratios et analyse compositionnelle

## Acquérir des données météo

## Analyse de sols

## Cartographier