<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Analyse et modélisation d’agroécosystèmes</title>
  <meta name="description" content="Ce cours a pour objectif de former les étudiants gradués en génie agroenvironnemental, génie civil, génie écologique, agronomie, biologie, foresterie et écologie en analyse et modélisation de systèmes vivants. Les sujets traités sont l’introduction au langage de programmation R, l’analyse statistique descriptive, la visualisation, la modélisation inférentielle, prédictive et déterministe.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Analyse et modélisation d’agroécosystèmes" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Ce cours a pour objectif de former les étudiants gradués en génie agroenvironnemental, génie civil, génie écologique, agronomie, biologie, foresterie et écologie en analyse et modélisation de systèmes vivants. Les sujets traités sont l’introduction au langage de programmation R, l’analyse statistique descriptive, la visualisation, la modélisation inférentielle, prédictive et déterministe." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Analyse et modélisation d’agroécosystèmes" />
  
  <meta name="twitter:description" content="Ce cours a pour objectif de former les étudiants gradués en génie agroenvironnemental, génie civil, génie écologique, agronomie, biologie, foresterie et écologie en analyse et modélisation de systèmes vivants. Les sujets traités sont l’introduction au langage de programmation R, l’analyse statistique descriptive, la visualisation, la modélisation inférentielle, prédictive et déterministe." />
  

<meta name="author" content="Serge-Étienne Parent">


<meta name="date" content="2018-11-28">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="lanalyse-de-variance.html">
<link rel="next" href="autoapprentissage.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Préface</a></li>
<li class="chapter" data-level="2" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="definitions.html"><a href="definitions.html"><i class="fa fa-check"></i><b>3</b> Définitions</a></li>
<li class="chapter" data-level="4" data-path="a-qui-sadresse-ce-manuel.html"><a href="a-qui-sadresse-ce-manuel.html"><i class="fa fa-check"></i><b>4</b> À qui s’adresse ce manuel?</a></li>
<li class="chapter" data-level="5" data-path="les-logiciels-libres.html"><a href="les-logiciels-libres.html"><i class="fa fa-check"></i><b>5</b> Les logiciels libres</a></li>
<li class="chapter" data-level="6" data-path="langage-de-programmation.html"><a href="langage-de-programmation.html"><i class="fa fa-check"></i><b>6</b> Langage de programmation</a><ul>
<li class="chapter" data-level="6.1" data-path="langage-de-programmation.html"><a href="langage-de-programmation.html#r"><i class="fa fa-check"></i><b>6.1</b> R</a></li>
<li class="chapter" data-level="6.2" data-path="langage-de-programmation.html"><a href="langage-de-programmation.html#pourquoi-pas-python"><i class="fa fa-check"></i><b>6.2</b> Pourquoi pas Python?</a></li>
<li class="chapter" data-level="6.3" data-path="langage-de-programmation.html"><a href="langage-de-programmation.html#pourquoi-pas-matlab"><i class="fa fa-check"></i><b>6.3</b> Pourquoi pas Matlab?</a></li>
<li class="chapter" data-level="6.4" data-path="langage-de-programmation.html"><a href="langage-de-programmation.html#pourquoi-pas-______"><i class="fa fa-check"></i><b>6.4</b> Pourquoi pas ______ ?</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="comment-utiliser-ce-manuel.html"><a href="comment-utiliser-ce-manuel.html"><i class="fa fa-check"></i><b>7</b> Comment utiliser ce manuel?</a></li>
<li class="chapter" data-level="8" data-path="lectures-complementaires.html"><a href="lectures-complementaires.html"><i class="fa fa-check"></i><b>8</b> Lectures complémentaires</a><ul>
<li class="chapter" data-level="8.1" data-path="lectures-complementaires.html"><a href="lectures-complementaires.html#ecologie-mathematique"><i class="fa fa-check"></i><b>8.1</b> Écologie mathématique</a></li>
<li class="chapter" data-level="8.2" data-path="lectures-complementaires.html"><a href="lectures-complementaires.html#programmation"><i class="fa fa-check"></i><b>8.2</b> Programmation</a></li>
<li class="chapter" data-level="8.3" data-path="lectures-complementaires.html"><a href="lectures-complementaires.html#divers"><i class="fa fa-check"></i><b>8.3</b> Divers</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="besoin-daide.html"><a href="besoin-daide.html"><i class="fa fa-check"></i><b>9</b> Besoin d’aide?</a></li>
<li class="chapter" data-level="10" data-path="a-propos-de-lauteur.html"><a href="a-propos-de-lauteur.html"><i class="fa fa-check"></i><b>10</b> À propos de l’auteur</a></li>
<li class="chapter" data-level="11" data-path="un-cours-complementaire-a-dautres-cours.html"><a href="un-cours-complementaire-a-dautres-cours.html"><i class="fa fa-check"></i><b>11</b> Un cours complémentaire à d’autres cours</a></li>
<li class="chapter" data-level="12" data-path="contribuer-au-manuel.html"><a href="contribuer-au-manuel.html"><i class="fa fa-check"></i><b>12</b> Contribuer au manuel</a></li>
<li class="chapter" data-level="13" data-path="la-science-des-donnees-avec-r.html"><a href="la-science-des-donnees-avec-r.html"><i class="fa fa-check"></i><b>13</b> La science des données avec R</a></li>
<li class="chapter" data-level="14" data-path="statistiques-ou-science-des-donnees.html"><a href="statistiques-ou-science-des-donnees.html"><i class="fa fa-check"></i><b>14</b> Statistiques ou Science des données?</a></li>
<li class="chapter" data-level="15" data-path="organiser-son-environnement-de-travail-en-r.html"><a href="organiser-son-environnement-de-travail-en-r.html"><i class="fa fa-check"></i><b>15</b> Organiser son environnement de travail en R</a></li>
<li class="chapter" data-level="16" data-path="preparer-son-flux-de-travail.html"><a href="preparer-son-flux-de-travail.html"><i class="fa fa-check"></i><b>16</b> Préparer son flux de travail</a><ul>
<li class="chapter" data-level="16.1" data-path="preparer-son-flux-de-travail.html"><a href="preparer-son-flux-de-travail.html#installation-classique"><i class="fa fa-check"></i><b>16.1</b> Installation classique</a></li>
<li class="chapter" data-level="16.2" data-path="preparer-son-flux-de-travail.html"><a href="preparer-son-flux-de-travail.html#r-notebooks"><i class="fa fa-check"></i><b>16.2</b> R notebooks</a></li>
<li class="chapter" data-level="16.3" data-path="preparer-son-flux-de-travail.html"><a href="preparer-son-flux-de-travail.html#installation-avec-anaconda"><i class="fa fa-check"></i><b>16.3</b> Installation avec Anaconda</a></li>
<li class="chapter" data-level="16.4" data-path="preparer-son-flux-de-travail.html"><a href="preparer-son-flux-de-travail.html#utilisation-de-azure-notebooks"><i class="fa fa-check"></i><b>16.4</b> Utilisation de Azure notebooks</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="premiers-pas-avec-r.html"><a href="premiers-pas-avec-r.html"><i class="fa fa-check"></i><b>17</b> Premiers pas avec R</a><ul>
<li class="chapter" data-level="17.1" data-path="premiers-pas-avec-r.html"><a href="premiers-pas-avec-r.html#types-de-donnees"><i class="fa fa-check"></i><b>17.1</b> Types de données</a></li>
<li class="chapter" data-level="17.2" data-path="premiers-pas-avec-r.html"><a href="premiers-pas-avec-r.html#les-collections-de-donnees"><i class="fa fa-check"></i><b>17.2</b> Les collections de données</a><ul>
<li class="chapter" data-level="17.2.1" data-path="premiers-pas-avec-r.html"><a href="premiers-pas-avec-r.html#vecteurs"><i class="fa fa-check"></i><b>17.2.1</b> Vecteurs</a></li>
<li class="chapter" data-level="17.2.2" data-path="premiers-pas-avec-r.html"><a href="premiers-pas-avec-r.html#matrices"><i class="fa fa-check"></i><b>17.2.2</b> Matrices</a></li>
<li class="chapter" data-level="17.2.3" data-path="premiers-pas-avec-r.html"><a href="premiers-pas-avec-r.html#listes"><i class="fa fa-check"></i><b>17.2.3</b> Listes</a></li>
<li class="chapter" data-level="17.2.4" data-path="premiers-pas-avec-r.html"><a href="premiers-pas-avec-r.html#tableaux"><i class="fa fa-check"></i><b>17.2.4</b> Tableaux</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="premiers-pas-avec-r.html"><a href="premiers-pas-avec-r.html#les-fonctions"><i class="fa fa-check"></i><b>17.3</b> Les fonctions</a></li>
<li class="chapter" data-level="17.4" data-path="premiers-pas-avec-r.html"><a href="premiers-pas-avec-r.html#les-boucles"><i class="fa fa-check"></i><b>17.4</b> Les boucles</a></li>
<li class="chapter" data-level="17.5" data-path="premiers-pas-avec-r.html"><a href="premiers-pas-avec-r.html#conditions-if-else-if-else"><i class="fa fa-check"></i><b>17.5</b> Conditions: if, else if, else</a></li>
<li class="chapter" data-level="17.6" data-path="premiers-pas-avec-r.html"><a href="premiers-pas-avec-r.html#installer-et-charger-un-module"><i class="fa fa-check"></i><b>17.6</b> Installer et charger un module</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="enfin.html"><a href="enfin.html"><i class="fa fa-check"></i><b>18</b> Enfin…</a></li>
<li class="chapter" data-level="19" data-path="visualisation.html"><a href="visualisation.html"><i class="fa fa-check"></i><b>19</b> Visualisation</a></li>
<li class="chapter" data-level="20" data-path="pourquoi-explorer-graphiquement.html"><a href="pourquoi-explorer-graphiquement.html"><i class="fa fa-check"></i><b>20</b> Pourquoi explorer graphiquement?</a></li>
<li class="chapter" data-level="21" data-path="publier-un-graphique.html"><a href="publier-un-graphique.html"><i class="fa fa-check"></i><b>21</b> Publier un graphique</a><ul>
<li class="chapter" data-level="21.1" data-path="publier-un-graphique.html"><a href="publier-un-graphique.html#cinq-qualites-dun-bon-graphique"><i class="fa fa-check"></i><b>21.1</b> Cinq qualités d’un bon graphique</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="choisir-le-type-de-graphique-le-plus-approprie.html"><a href="choisir-le-type-de-graphique-le-plus-approprie.html"><i class="fa fa-check"></i><b>22</b> Choisir le type de graphique le plus approprié</a></li>
<li class="chapter" data-level="23" data-path="choisir-son-outils-de-visualisation.html"><a href="choisir-son-outils-de-visualisation.html"><i class="fa fa-check"></i><b>23</b> Choisir son outils de visualisation</a><ul>
<li class="chapter" data-level="23.1" data-path="choisir-son-outils-de-visualisation.html"><a href="choisir-son-outils-de-visualisation.html#approche-imperative"><i class="fa fa-check"></i><b>23.1</b> Approche impérative</a></li>
<li class="chapter" data-level="23.2" data-path="choisir-son-outils-de-visualisation.html"><a href="choisir-son-outils-de-visualisation.html#approche-declarative"><i class="fa fa-check"></i><b>23.2</b> Approche déclarative</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="visualisation-en-r.html"><a href="visualisation-en-r.html"><i class="fa fa-check"></i><b>24</b> Visualisation en R</a></li>
<li class="chapter" data-level="25" data-path="module-de-base-pour-les-graphiques.html"><a href="module-de-base-pour-les-graphiques.html"><i class="fa fa-check"></i><b>25</b> Module de base pour les graphiques</a></li>
<li class="chapter" data-level="26" data-path="la-grammaire-graphique-ggplot2.html"><a href="la-grammaire-graphique-ggplot2.html"><i class="fa fa-check"></i><b>26</b> La grammaire graphique ggplot2</a><ul>
<li class="chapter" data-level="26.1" data-path="la-grammaire-graphique-ggplot2.html"><a href="la-grammaire-graphique-ggplot2.html#mon-premier-ggplot"><i class="fa fa-check"></i><b>26.1</b> Mon premier ggplot</a><ul>
<li class="chapter" data-level="26.1.1" data-path="la-grammaire-graphique-ggplot2.html"><a href="la-grammaire-graphique-ggplot2.html#les-facettes"><i class="fa fa-check"></i><b>26.1.1</b> Les facettes</a></li>
</ul></li>
<li class="chapter" data-level="26.2" data-path="la-grammaire-graphique-ggplot2.html"><a href="la-grammaire-graphique-ggplot2.html#plusieurs-sources-de-donnees"><i class="fa fa-check"></i><b>26.2</b> Plusieurs sources de données</a></li>
<li class="chapter" data-level="26.3" data-path="la-grammaire-graphique-ggplot2.html"><a href="la-grammaire-graphique-ggplot2.html#exporter-avec-style"><i class="fa fa-check"></i><b>26.3</b> Exporter avec style</a></li>
<li class="chapter" data-level="26.4" data-path="la-grammaire-graphique-ggplot2.html"><a href="la-grammaire-graphique-ggplot2.html#nuages-de-points"><i class="fa fa-check"></i><b>26.4</b> Nuages de points</a></li>
<li class="chapter" data-level="26.5" data-path="la-grammaire-graphique-ggplot2.html"><a href="la-grammaire-graphique-ggplot2.html#diagrammes-en-lignes"><i class="fa fa-check"></i><b>26.5</b> Diagrammes en lignes</a></li>
<li class="chapter" data-level="26.6" data-path="la-grammaire-graphique-ggplot2.html"><a href="la-grammaire-graphique-ggplot2.html#les-histogrammes"><i class="fa fa-check"></i><b>26.6</b> Les histogrammes</a></li>
<li class="chapter" data-level="26.7" data-path="la-grammaire-graphique-ggplot2.html"><a href="la-grammaire-graphique-ggplot2.html#boxplots"><i class="fa fa-check"></i><b>26.7</b> Boxplots</a></li>
<li class="chapter" data-level="26.8" data-path="la-grammaire-graphique-ggplot2.html"><a href="la-grammaire-graphique-ggplot2.html#les-diagrammes-en-barre"><i class="fa fa-check"></i><b>26.8</b> Les diagrammes en barre</a></li>
<li class="chapter" data-level="26.9" data-path="la-grammaire-graphique-ggplot2.html"><a href="la-grammaire-graphique-ggplot2.html#exporter-un-graphique"><i class="fa fa-check"></i><b>26.9</b> Exporter un graphique</a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="les-graphiques-comme-outil-dexploration-des-donnees.html"><a href="les-graphiques-comme-outil-dexploration-des-donnees.html"><i class="fa fa-check"></i><b>27</b> Les graphiques comme outil d’exploration des données</a><ul>
<li class="chapter" data-level="27.1" data-path="les-graphiques-comme-outil-dexploration-des-donnees.html"><a href="les-graphiques-comme-outil-dexploration-des-donnees.html#des-graphiques-interactifs"><i class="fa fa-check"></i><b>27.1</b> Des graphiques intéractifs!</a></li>
<li class="chapter" data-level="27.2" data-path="les-graphiques-comme-outil-dexploration-des-donnees.html"><a href="les-graphiques-comme-outil-dexploration-des-donnees.html#des-extensions-de-ggplot2"><i class="fa fa-check"></i><b>27.2</b> Des extensions de ggplot2</a></li>
<li class="chapter" data-level="27.3" data-path="les-graphiques-comme-outil-dexploration-des-donnees.html"><a href="les-graphiques-comme-outil-dexploration-des-donnees.html#aller-plus-loin-avec-ggplot2"><i class="fa fa-check"></i><b>27.3</b> Aller plus loin avec ggplot2</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="choisir-les-bonnes-couleurs.html"><a href="choisir-les-bonnes-couleurs.html"><i class="fa fa-check"></i><b>28</b> Choisir les bonnes couleurs</a></li>
<li class="chapter" data-level="29" data-path="regles-particulieres.html"><a href="regles-particulieres.html"><i class="fa fa-check"></i><b>29</b> Règles particulières</a><ul>
<li class="chapter" data-level="29.1" data-path="regles-particulieres.html"><a href="regles-particulieres.html#ne-tronquez-pas-inutilement-laxe-des-y"><i class="fa fa-check"></i><b>29.1</b> Ne tronquez pas inutilement l’axe des <span class="math inline">\(y\)</span></a></li>
<li class="chapter" data-level="29.2" data-path="regles-particulieres.html"><a href="regles-particulieres.html#utilisez-un-encrage-proportionnel"><i class="fa fa-check"></i><b>29.2</b> Utilisez un encrage proportionnel</a></li>
<li class="chapter" data-level="29.3" data-path="regles-particulieres.html"><a href="regles-particulieres.html#publiez-vos-donnees"><i class="fa fa-check"></i><b>29.3</b> Publiez vos données</a></li>
<li class="chapter" data-level="29.4" data-path="regles-particulieres.html"><a href="regles-particulieres.html#evitez-de-distraire-avec-des-decorations-futiles"><i class="fa fa-check"></i><b>29.4</b> Évitez de distraire avec des décorations futiles</a></li>
<li class="chapter" data-level="29.5" data-path="regles-particulieres.html"><a href="regles-particulieres.html#visitez-www.junkcharts.typepad.com-de-temps-a-autre"><i class="fa fa-check"></i><b>29.5</b> Visitez www.junkcharts.typepad.com de temps à autre</a></li>
</ul></li>
<li class="chapter" data-level="30" data-path="organisation-des-donnees-et-operations-sur-des-tableaux.html"><a href="organisation-des-donnees-et-operations-sur-des-tableaux.html"><i class="fa fa-check"></i><b>30</b> Organisation des données et opérations sur des tableaux</a></li>
<li class="chapter" data-level="31" data-path="les-collections-de-donnees-1.html"><a href="les-collections-de-donnees-1.html"><i class="fa fa-check"></i><b>31</b> Les collections de données</a></li>
<li class="chapter" data-level="32" data-path="organiser-un-tableau-de-donnees.html"><a href="organiser-un-tableau-de-donnees.html"><i class="fa fa-check"></i><b>32</b> Organiser un tableau de données</a></li>
<li class="chapter" data-level="33" data-path="formats-de-tableau.html"><a href="formats-de-tableau.html"><i class="fa fa-check"></i><b>33</b> Formats de tableau</a><ul>
<li class="chapter" data-level="33.1" data-path="formats-de-tableau.html"><a href="formats-de-tableau.html#xls-ou-xlsx"><i class="fa fa-check"></i><b>33.1</b> <em>xls</em> ou <em>xlsx</em></a></li>
<li class="chapter" data-level="33.2" data-path="formats-de-tableau.html"><a href="formats-de-tableau.html#csv"><i class="fa fa-check"></i><b>33.2</b> <em>csv</em></a></li>
<li class="chapter" data-level="33.3" data-path="formats-de-tableau.html"><a href="formats-de-tableau.html#json"><i class="fa fa-check"></i><b>33.3</b> <em>json</em></a></li>
<li class="chapter" data-level="33.4" data-path="formats-de-tableau.html"><a href="formats-de-tableau.html#sqlite"><i class="fa fa-check"></i><b>33.4</b> SQLite</a></li>
<li class="chapter" data-level="33.5" data-path="formats-de-tableau.html"><a href="formats-de-tableau.html#suggestion"><i class="fa fa-check"></i><b>33.5</b> Suggestion</a></li>
</ul></li>
<li class="chapter" data-level="34" data-path="entreposer-ses-donnees.html"><a href="entreposer-ses-donnees.html"><i class="fa fa-check"></i><b>34</b> Entreposer ses données</a></li>
<li class="chapter" data-level="35" data-path="manipuler-des-donnees-en-mode-tidyverse.html"><a href="manipuler-des-donnees-en-mode-tidyverse.html"><i class="fa fa-check"></i><b>35</b> Manipuler des données en mode tidyverse</a><ul>
<li class="chapter" data-level="35.1" data-path="manipuler-des-donnees-en-mode-tidyverse.html"><a href="manipuler-des-donnees-en-mode-tidyverse.html#importer-vos-donnees-dans-voter-session-de-travail"><i class="fa fa-check"></i><b>35.1</b> Importer vos données dans voter session de travail</a></li>
<li class="chapter" data-level="35.2" data-path="manipuler-des-donnees-en-mode-tidyverse.html"><a href="manipuler-des-donnees-en-mode-tidyverse.html#comment-selectionner-et-filtrer-des-donnees"><i class="fa fa-check"></i><b>35.2</b> Comment sélectionner et filtrer des données?</a><ul>
<li class="chapter" data-level="35.2.1" data-path="manipuler-des-donnees-en-mode-tidyverse.html"><a href="manipuler-des-donnees-en-mode-tidyverse.html#selectionner"><i class="fa fa-check"></i><b>35.2.1</b> Sélectionner</a></li>
<li class="chapter" data-level="35.2.2" data-path="manipuler-des-donnees-en-mode-tidyverse.html"><a href="manipuler-des-donnees-en-mode-tidyverse.html#filtrer"><i class="fa fa-check"></i><b>35.2.2</b> Filtrer</a></li>
</ul></li>
<li class="chapter" data-level="35.3" data-path="manipuler-des-donnees-en-mode-tidyverse.html"><a href="manipuler-des-donnees-en-mode-tidyverse.html#le-format-long-et-le-format-large"><i class="fa fa-check"></i><b>35.3</b> Le format long et le format large</a></li>
<li class="chapter" data-level="35.4" data-path="manipuler-des-donnees-en-mode-tidyverse.html"><a href="manipuler-des-donnees-en-mode-tidyverse.html#combiner-des-tableaux"><i class="fa fa-check"></i><b>35.4</b> Combiner des tableaux</a></li>
<li class="chapter" data-level="35.5" data-path="manipuler-des-donnees-en-mode-tidyverse.html"><a href="manipuler-des-donnees-en-mode-tidyverse.html#operations-sur-les-tableaux"><i class="fa fa-check"></i><b>35.5</b> Opérations sur les tableaux</a></li>
<li class="chapter" data-level="35.6" data-path="manipuler-des-donnees-en-mode-tidyverse.html"><a href="manipuler-des-donnees-en-mode-tidyverse.html#exemple-difficile"><i class="fa fa-check"></i><b>35.6</b> Exemple (difficile)</a></li>
<li class="chapter" data-level="35.7" data-path="manipuler-des-donnees-en-mode-tidyverse.html"><a href="manipuler-des-donnees-en-mode-tidyverse.html#exporter-un-tableau"><i class="fa fa-check"></i><b>35.7</b> Exporter un tableau</a></li>
<li class="chapter" data-level="35.8" data-path="manipuler-des-donnees-en-mode-tidyverse.html"><a href="manipuler-des-donnees-en-mode-tidyverse.html#aller-plus-loin-dans-le-tidyverse"><i class="fa fa-check"></i><b>35.8</b> Aller plus loin dans le tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="36" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>36</b> Références</a></li>
<li class="chapter" data-level="37" data-path="biostatistiques.html"><a href="biostatistiques.html"><i class="fa fa-check"></i><b>37</b> Biostatistiques</a></li>
<li class="chapter" data-level="38" data-path="populations-et-echantillons.html"><a href="populations-et-echantillons.html"><i class="fa fa-check"></i><b>38</b> Populations et échantillons</a></li>
<li class="chapter" data-level="39" data-path="les-variables.html"><a href="les-variables.html"><i class="fa fa-check"></i><b>39</b> Les variables</a><ul>
<li class="chapter" data-level="39.1" data-path="les-variables.html"><a href="les-variables.html#variables-quantitatives"><i class="fa fa-check"></i><b>39.1</b> Variables quantitatives</a></li>
<li class="chapter" data-level="39.2" data-path="les-variables.html"><a href="les-variables.html#variables-qualitatives"><i class="fa fa-check"></i><b>39.2</b> Variables qualitatives</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="les-probabilites.html"><a href="les-probabilites.html"><i class="fa fa-check"></i><b>40</b> Les probabilités</a></li>
<li class="chapter" data-level="41" data-path="les-distributions.html"><a href="les-distributions.html"><i class="fa fa-check"></i><b>41</b> Les distributions</a><ul>
<li class="chapter" data-level="41.1" data-path="les-distributions.html"><a href="les-distributions.html#distribution-binomiale"><i class="fa fa-check"></i><b>41.1</b> Distribution binomiale</a></li>
<li class="chapter" data-level="41.2" data-path="les-distributions.html"><a href="les-distributions.html#distribution-de-poisson"><i class="fa fa-check"></i><b>41.2</b> Distribution de Poisson</a></li>
<li class="chapter" data-level="41.3" data-path="les-distributions.html"><a href="les-distributions.html#distribution-uniforme"><i class="fa fa-check"></i><b>41.3</b> Distribution uniforme</a></li>
<li class="chapter" data-level="41.4" data-path="les-distributions.html"><a href="les-distributions.html#distribution-normale"><i class="fa fa-check"></i><b>41.4</b> Distribution normale</a></li>
</ul></li>
<li class="chapter" data-level="42" data-path="statistiques-descriptives.html"><a href="statistiques-descriptives.html"><i class="fa fa-check"></i><b>42</b> Statistiques descriptives</a></li>
<li class="chapter" data-level="43" data-path="tests-dhypotheses-a-un-et-deux-echantillons.html"><a href="tests-dhypotheses-a-un-et-deux-echantillons.html"><i class="fa fa-check"></i><b>43</b> Tests d’hypothèses à un et deux échantillons</a><ul>
<li class="chapter" data-level="43.0.1" data-path="tests-dhypotheses-a-un-et-deux-echantillons.html"><a href="tests-dhypotheses-a-un-et-deux-echantillons.html#information-lhypothese-nulle"><i class="fa fa-check"></i><b>43.0.1</b> Information: l’hypothèse nulle</a></li>
<li class="chapter" data-level="43.1" data-path="tests-dhypotheses-a-un-et-deux-echantillons.html"><a href="tests-dhypotheses-a-un-et-deux-echantillons.html#test-de-t-a-un-seul-echantillon"><i class="fa fa-check"></i><b>43.1</b> Test de t à un seul échantillon</a><ul>
<li class="chapter" data-level="43.1.1" data-path="tests-dhypotheses-a-un-et-deux-echantillons.html"><a href="tests-dhypotheses-a-un-et-deux-echantillons.html#information-la-p-value"><i class="fa fa-check"></i><b>43.1.1</b> Information: la <em>p-value</em></a></li>
</ul></li>
<li class="chapter" data-level="43.2" data-path="tests-dhypotheses-a-un-et-deux-echantillons.html"><a href="tests-dhypotheses-a-un-et-deux-echantillons.html#attention-mauvaises-interpretations-des-p-values"><i class="fa fa-check"></i><b>43.2</b> Attention: mauvaises interprétations des <em>p-values</em></a><ul>
<li class="chapter" data-level="43.2.1" data-path="tests-dhypotheses-a-un-et-deux-echantillons.html"><a href="tests-dhypotheses-a-un-et-deux-echantillons.html#attention-au-p-hacking"><i class="fa fa-check"></i><b>43.2.1</b> Attention au <em>p-hacking</em></a></li>
</ul></li>
<li class="chapter" data-level="43.3" data-path="tests-dhypotheses-a-un-et-deux-echantillons.html"><a href="tests-dhypotheses-a-un-et-deux-echantillons.html#test-de-wilcoxon-a-un-seul-echantillon"><i class="fa fa-check"></i><b>43.3</b> Test de Wilcoxon à un seul échantillon</a></li>
<li class="chapter" data-level="43.4" data-path="tests-dhypotheses-a-un-et-deux-echantillons.html"><a href="tests-dhypotheses-a-un-et-deux-echantillons.html#tests-de-t-a-deux-echantillons"><i class="fa fa-check"></i><b>43.4</b> Tests de t à deux échantillons</a><ul>
<li class="chapter" data-level="43.4.1" data-path="tests-dhypotheses-a-un-et-deux-echantillons.html"><a href="tests-dhypotheses-a-un-et-deux-echantillons.html#enregistrer-les-resultats-dun-test"><i class="fa fa-check"></i><b>43.4.1</b> Enregistrer les résultats d’un test</a></li>
</ul></li>
<li class="chapter" data-level="43.5" data-path="tests-dhypotheses-a-un-et-deux-echantillons.html"><a href="tests-dhypotheses-a-un-et-deux-echantillons.html#comparaison-des-variances"><i class="fa fa-check"></i><b>43.5</b> Comparaison des variances</a></li>
<li class="chapter" data-level="43.6" data-path="tests-dhypotheses-a-un-et-deux-echantillons.html"><a href="tests-dhypotheses-a-un-et-deux-echantillons.html#tests-de-wilcoxon-a-deux-echantillons"><i class="fa fa-check"></i><b>43.6</b> Tests de Wilcoxon à deux échantillons</a></li>
<li class="chapter" data-level="43.7" data-path="tests-dhypotheses-a-un-et-deux-echantillons.html"><a href="tests-dhypotheses-a-un-et-deux-echantillons.html#les-tests-paires"><i class="fa fa-check"></i><b>43.7</b> Les tests pairés</a></li>
</ul></li>
<li class="chapter" data-level="44" data-path="lanalyse-de-variance.html"><a href="lanalyse-de-variance.html"><i class="fa fa-check"></i><b>44</b> L’analyse de variance</a></li>
<li class="chapter" data-level="45" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html"><i class="fa fa-check"></i><b>45</b> Les modèles statistiques</a><ul>
<li class="chapter" data-level="45.1" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#modeles-a-effets-fixes"><i class="fa fa-check"></i><b>45.1</b> Modèles à effets fixes</a><ul>
<li class="chapter" data-level="45.1.1" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#modele-lineaire-univarie-avec-variable-continue"><i class="fa fa-check"></i><b>45.1.1</b> Modèle linéaire univarié avec variable continue</a></li>
<li class="chapter" data-level="45.1.2" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#analyse-des-residus"><i class="fa fa-check"></i><b>45.1.2</b> Analyse des résidus</a></li>
<li class="chapter" data-level="45.1.3" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#regression-multiple"><i class="fa fa-check"></i><b>45.1.3</b> Régression multiple</a></li>
<li class="chapter" data-level="45.1.4" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#modeles-lineaires-univaries-avec-variable-categorielle-nominale"><i class="fa fa-check"></i><b>45.1.4</b> Modèles linéaires univariés avec variable catégorielle <strong>nominale</strong></a></li>
<li class="chapter" data-level="45.1.5" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#modeles-lineaires-univaries-avec-variable-categorielle-ordinale"><i class="fa fa-check"></i><b>45.1.5</b> Modèles linéaires univariés avec variable catégorielle <strong>ordinale</strong></a></li>
<li class="chapter" data-level="45.1.6" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#regression-multiple-a-plusieurs-variables"><i class="fa fa-check"></i><b>45.1.6</b> Régression multiple à plusieurs variables</a></li>
<li class="chapter" data-level="45.1.7" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#attention-a-ne-pas-surcharger-le-modele"><i class="fa fa-check"></i><b>45.1.7</b> Attention à ne pas surcharger le modèle</a></li>
<li class="chapter" data-level="45.1.8" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#les-modeles-lineaires-generalises"><i class="fa fa-check"></i><b>45.1.8</b> Les modèles linéaires généralisés</a></li>
<li class="chapter" data-level="45.1.9" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#les-modeles-non-lineaires"><i class="fa fa-check"></i><b>45.1.9</b> Les modèles non-linéaires</a></li>
</ul></li>
<li class="chapter" data-level="45.2" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#modeles-a-effets-mixtes"><i class="fa fa-check"></i><b>45.2</b> Modèles à effets mixtes</a><ul>
<li class="chapter" data-level="45.2.1" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#modeles-mixtes-non-lineaires"><i class="fa fa-check"></i><b>45.2.1</b> Modèles mixtes non-linéaires</a></li>
</ul></li>
<li class="chapter" data-level="45.3" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#aller-plus-loin"><i class="fa fa-check"></i><b>45.3</b> Aller plus loin</a><ul>
<li class="chapter" data-level="45.3.1" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#statistiques-generales"><i class="fa fa-check"></i><b>45.3.1</b> Statistiques générales:</a></li>
<li class="chapter" data-level="45.3.2" data-path="les-modeles-statistiques.html"><a href="les-modeles-statistiques.html#statistiques-avec-r"><i class="fa fa-check"></i><b>45.3.2</b> Statistiques avec R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="46" data-path="autoapprentissage.html"><a href="autoapprentissage.html"><i class="fa fa-check"></i><b>46</b> Autoapprentissage</a><ul>
<li class="chapter" data-level="46.1" data-path="autoapprentissage.html"><a href="autoapprentissage.html#objectifs"><i class="fa fa-check"></i><b>46.1</b> Objectifs</a></li>
<li class="chapter" data-level="46.2" data-path="autoapprentissage.html"><a href="autoapprentissage.html#lexique"><i class="fa fa-check"></i><b>46.2</b> Lexique</a></li>
<li class="chapter" data-level="46.3" data-path="autoapprentissage.html"><a href="autoapprentissage.html#demarche"><i class="fa fa-check"></i><b>46.3</b> Démarche</a><ul>
<li class="chapter" data-level="46.3.1" data-path="autoapprentissage.html"><a href="autoapprentissage.html#pretraitement"><i class="fa fa-check"></i><b>46.3.1</b> Prétraitement</a></li>
<li class="chapter" data-level="46.3.2" data-path="autoapprentissage.html"><a href="autoapprentissage.html#entrainement-et-test"><i class="fa fa-check"></i><b>46.3.2</b> Entraînement et test</a></li>
<li class="chapter" data-level="46.3.3" data-path="autoapprentissage.html"><a href="autoapprentissage.html#sousapprentissage-et-surapprentissage"><i class="fa fa-check"></i><b>46.3.3</b> Sousapprentissage et surapprentissage</a></li>
<li class="chapter" data-level="46.3.4" data-path="autoapprentissage.html"><a href="autoapprentissage.html#validation-croisee"><i class="fa fa-check"></i><b>46.3.4</b> Validation croisée</a></li>
<li class="chapter" data-level="46.3.5" data-path="autoapprentissage.html"><a href="autoapprentissage.html#choix-de-lalgorithme-dapprentissage"><i class="fa fa-check"></i><b>46.3.5</b> Choix de l’algorithme d’apprentissage</a></li>
<li class="chapter" data-level="46.3.6" data-path="autoapprentissage.html"><a href="autoapprentissage.html#deploiement"><i class="fa fa-check"></i><b>46.3.6</b> Déploiement</a></li>
</ul></li>
<li class="chapter" data-level="46.4" data-path="autoapprentissage.html"><a href="autoapprentissage.html#algorithmes"><i class="fa fa-check"></i><b>46.4</b> Algorithmes</a></li>
<li class="chapter" data-level="46.5" data-path="autoapprentissage.html"><a href="autoapprentissage.html#lautoapprentissage-en-r"><i class="fa fa-check"></i><b>46.5</b> L’autoapprentissage en R</a></li>
<li class="chapter" data-level="46.6" data-path="autoapprentissage.html"><a href="autoapprentissage.html#les-k-plus-proches-voisins"><i class="fa fa-check"></i><b>46.6</b> Les <em>k</em> plus proches voisins</a><ul>
<li class="chapter" data-level="46.6.1" data-path="autoapprentissage.html"><a href="autoapprentissage.html#exemple-dapplication-1"><i class="fa fa-check"></i><b>46.6.1</b> Exemple d’application</a></li>
</ul></li>
<li class="chapter" data-level="46.7" data-path="autoapprentissage.html"><a href="autoapprentissage.html#les-arbres-decisionnels"><i class="fa fa-check"></i><b>46.7</b> Les arbres décisionnels</a></li>
</ul></li>
<li class="chapter" data-level="47" data-path="les-reseaux-neuronaux.html"><a href="les-reseaux-neuronaux.html"><i class="fa fa-check"></i><b>47</b> Les réseaux neuronaux</a><ul>
<li class="chapter" data-level="47.0.1" data-path="les-reseaux-neuronaux.html"><a href="les-reseaux-neuronaux.html#les-reseaux-neuronnaux-sur-r-avec-keras"><i class="fa fa-check"></i><b>47.0.1</b> Les réseaux neuronnaux sur R avec Keras</a></li>
<li class="chapter" data-level="47.0.2" data-path="les-reseaux-neuronaux.html"><a href="les-reseaux-neuronaux.html#pour-aller-plus-loin"><i class="fa fa-check"></i><b>47.0.2</b> Pour aller plus loin</a></li>
</ul></li>
<li class="chapter" data-level="48" data-path="les-processus-gaussiens.html"><a href="les-processus-gaussiens.html"><i class="fa fa-check"></i><b>48</b> Les processus gaussiens</a><ul>
<li class="chapter" data-level="48.1" data-path="les-processus-gaussiens.html"><a href="les-processus-gaussiens.html#un-approche-intuitive"><i class="fa fa-check"></i><b>48.1</b> Un approche intuitive</a><ul>
<li class="chapter" data-level="48.1.1" data-path="les-processus-gaussiens.html"><a href="les-processus-gaussiens.html#les-processus-gaussiens-en-r"><i class="fa fa-check"></i><b>48.1.1</b> Les processus gaussiens en <code>R</code></a></li>
<li class="chapter" data-level="48.1.2" data-path="les-processus-gaussiens.html"><a href="les-processus-gaussiens.html#application-pratique"><i class="fa fa-check"></i><b>48.1.2</b> Application pratique</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="49" data-path="modelisation-deterministe.html"><a href="modelisation-deterministe.html"><i class="fa fa-check"></i><b>49</b> Modélisation déterministe</a><ul>
<li class="chapter" data-level="49.1" data-path="modelisation-deterministe.html"><a href="modelisation-deterministe.html#equations-differentielles"><i class="fa fa-check"></i><b>49.1</b> Équations différentielles</a></li>
<li class="chapter" data-level="49.2" data-path="modelisation-deterministe.html"><a href="modelisation-deterministe.html#objectifs-1"><i class="fa fa-check"></i><b>49.2</b> Objectifs</a></li>
<li class="chapter" data-level="49.3" data-path="modelisation-deterministe.html"><a href="modelisation-deterministe.html#les-equations-differentielles-ordinaires-en-modelisation-ecologique"><i class="fa fa-check"></i><b>49.3</b> Les équations différentielles ordinaires en modélisation écologique</a><ul>
<li class="chapter" data-level="49.3.1" data-path="modelisation-deterministe.html"><a href="modelisation-deterministe.html#evolution-dune-seule-population-en-fonction-du-temps"><i class="fa fa-check"></i><b>49.3.1</b> Évolution d’une seule population en fonction du temps</a></li>
<li class="chapter" data-level="49.3.2" data-path="modelisation-deterministe.html"><a href="modelisation-deterministe.html#population-exploitee"><i class="fa fa-check"></i><b>49.3.2</b> Population exploitée</a></li>
<li class="chapter" data-level="49.3.3" data-path="modelisation-deterministe.html"><a href="modelisation-deterministe.html#interactions-biologiques"><i class="fa fa-check"></i><b>49.3.3</b> Intéractions biologiques</a></li>
</ul></li>
<li class="chapter" data-level="49.4" data-path="modelisation-deterministe.html"><a href="modelisation-deterministe.html#les-equations-differentielles-partielles-en-modelisation-ecologique"><i class="fa fa-check"></i><b>49.4</b> Les équations différentielles partielles en modélisation écologique</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analyse et modélisation d’agroécosystèmes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="les-modeles-statistiques" class="section level1">
<h1><span class="header-section-number">45</span> Les modèles statistiques</h1>
<p>La modélisation statistique consiste à lier de manière explicite des variables de sortie <span class="math inline">\(y\)</span> (ou variables-réponse ou variables dépendantes) à des variables explicatives <span class="math inline">\(x\)</span> (ou variables prédictives / indépendantes / covariables). Les variables-réponse sont modélsées par une fonction des variables explicatives ou prédictives.</p>
<p>Pourquoi garder les termes <em>explicatives</em> et <em>prédictives</em>? Parce que les modèles statistiques (basés sur des données et non pas sur des mécanismes) sont de deux ordres. D’abord, les modèles <strong>prédictifs</strong> sont conçus pour prédire de manière fiable une ou plusieurs variables-réponse à partir des informations contenues dans les variables qui sont, dans ce cas, prédictives. Ces modèles sont couverts dans le chapitre 11 de ce manuel (en développement). Lorsque l’on désire tester des hypothèses pour évaluer quelles variables expliquent la réponse, on parlera de modélisation (et de variables) <strong>explicatives</strong>. En inférence statistique, on évaluera les <em>corrélations</em> entre les variables explicatives et les variables-réponse. Un lien de corrélation n’est pas un lien de causalité. L’inférence causale peut en revanche être évaluée par des <a href="https://www.amazon.com/Cause-Correlation-Biology-Structural-Equations/dp/1107442591"><em>modèles d’équations structurelles</em></a>, sujet qui fera éventuellement partie de ce cours.</p>
<p>Cette section couvre la modélisation explicative. Les variables qui contribuent à créer les modèles peuvent être de différentes natures et distribuées selon différentes lois de probabilité. Alors que les modèles linéaires simples (<em>lm</em>) impliquent une variable-réponse distribuée de manière continue, les modèles linéaires généralisés peuvent aussi expliquer des variables de sorties discrètes.</p>
<p>Dans les deux cas, on distinguera les variables fixes et les variables aléatoires. Les <strong>variables fixes</strong> sont des les variables testées lors de l’expérience: dose du traitement, espèce/cultivar, météo, etc. Les <strong>variables aléatoires</strong> sont les sources de variation qui génèrent du bruit dans le modèle: les unités expérimentales ou le temps lors de mesures répétées. Les modèles incluant des effets fixes seulement sont des modèles à effets fixes. Généralement, les modèles incluant des variables aléatoires incluent aussi des variables fixes: on parlera alors de modèles mixtes. Nous couvrirons ces deux types de modèle.</p>
<div id="modeles-a-effets-fixes" class="section level2">
<h2><span class="header-section-number">45.1</span> Modèles à effets fixes</h2>
<p>Les tests de t et de Wilcoxon, explorés précédemment, sont des modèles statistiques à une seule variable. Nous avons vu dans l’<em>interface-formule</em> qu’une variable-réponse peut être liée à une variable explicative avec le tilde <code>~</code>. En particulier, le test de t est régression linéaire univariée (à une seule variable explicative) dont la variable explicative comprend deux catégories. De même, l’anova est une régression linéaire univariée dont la variable explicative comprend plusieurs catégories. Or l’interface-formule peut être utilisé dans plusieurs circonstance, notamment pour ajouter plusieurs variables de différents types: on parlera de régression multivariée.</p>
<p>La plupart des modèles statistiques peuvent être approximés comme une combinaison linéaire de variables: ce sont des modèles linéaires. Les modèles non-linéaires impliquent des stratégies computationnelles complexes qui rendent leur utilisation plus difficile à manoeuvrer.</p>
<p>Un modèle linéaire univarié prendra la forme <span class="math inline">\(y = \beta_0 + \beta_1 x + \epsilon\)</span>, où <span class="math inline">\(\beta_0\)</span> est l’intercept et <span class="math inline">\(\beta_1\)</span> est la pente et <span class="math inline">\(\epsilon\)</span> est l’erreur.</p>
<p>Vous verrez parfois la notation <span class="math inline">\(\hat{y} = \beta_0 + \beta_1 x\)</span>. La notation avec le chapeau <span class="math inline">\(\hat{y}\)</span> exprime qu’il s’agit des valeurs générées par le modèle. En fait, <span class="math inline">\(y = \hat{y} - \epsilon\)</span>.</p>
<div id="modele-lineaire-univarie-avec-variable-continue" class="section level3">
<h3><span class="header-section-number">45.1.1</span> Modèle linéaire univarié avec variable continue</h3>
<p>Prenons les données <a href="https://rdrr.io/cran/agridat/man/lasrosas.corn.html"><code>lasrosas.corn</code></a> incluses dans le module <code>agridat</code>, où l’on retrouve le rendement d’une production de maïs à dose d’azote variable, en Argentine.</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb307-1" data-line-number="1"><span class="kw">library</span>(<span class="st">&quot;agridat&quot;</span>)</a>
<a class="sourceLine" id="cb307-2" data-line-number="2"><span class="kw">data</span>(<span class="st">&quot;lasrosas.corn&quot;</span>)</a>
<a class="sourceLine" id="cb307-3" data-line-number="3"><span class="kw">sample_n</span>(lasrosas.corn, <span class="dv">10</span>)</a></code></pre></div>
<pre><code>##      year       lat      long  yield nitro topo     bv rep nf
## 2172 2001 -33.05109 -63.84451  94.15  50.6    E 173.54  R1 N2
## 3066 2001 -33.04908 -63.84830  90.19  99.8    W  91.74  R3 N4
## 949  1999 -33.05165 -63.84257  73.60   0.0   LO 173.23  R2 N0
## 1909 2001 -33.05175 -63.84320 108.95  75.4   LO 163.38  R1 N3
## 2173 2001 -33.05111 -63.84444 101.67  50.6    E 174.00  R1 N2
## 2770 2001 -33.05139 -63.84244  98.74  50.6   LO 167.86  R2 N2
## 1737 1999 -33.05121 -63.84224  81.70  29.0   LO 166.59  R3 N1
## 2261 2001 -33.05088 -63.84491  50.59  39.0    E 179.56  R1 N1
## 1501 1999 -33.05103 -63.84404  61.44   0.0    E 166.84  R3 N0
## 2149 2001 -33.05052 -63.84613  46.06  50.6   HT 178.54  R1 N2</code></pre>
<p>Ces données comprennent plusieurs variables. Prenons le rendement (<code>yield</code>) comme variable de sortie et, pour le moment, ne retenons que la dose d’azote (<code>nitro</code>) comme variable explicative: il s’agit d’une régression univariée. Les deux variables sont continuent. Explorons d’abord le nuage de points de l’une et l’autre.</p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb309-1" data-line-number="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> lasrosas.corn, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> nitro, <span class="dt">y =</span> yield)) <span class="op">+</span></a>
<a class="sourceLine" id="cb309-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-136-1.png" width="672" /></p>
<p>L’hypothèse nulle est que la dose d’azote n’affecte pas le rendement, c’est à dire que le coefficient de pente et nul. Une autre hypothèse est que l’intercept est nul: donc qu’à dose de 0, rendement de 0. Un modèle linéaire à variable de sortie continue est créé avec la fonction <code>lm()</code>, pour <em>linear model</em>.</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb310-1" data-line-number="1">modlin_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(yield <span class="op">~</span><span class="st"> </span>nitro, <span class="dt">data =</span> lasrosas.corn)</a>
<a class="sourceLine" id="cb310-2" data-line-number="2"><span class="kw">summary</span>(modlin_<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ nitro, data = lasrosas.corn)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -53.183 -15.341  -3.079  13.725  45.897 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 65.843213   0.608573 108.193  &lt; 2e-16 ***
## nitro        0.061717   0.007868   7.845 5.75e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 19.66 on 3441 degrees of freedom
## Multiple R-squared:  0.01757,    Adjusted R-squared:  0.01728 
## F-statistic: 61.54 on 1 and 3441 DF,  p-value: 5.754e-15</code></pre>
<p>Le diagnostic du modèle comprend plusieurs informations. D’abord la formule utilisée, affichée pour la tracabilité. Viens ensuite un aperçu de la distribution des résidus. La médiane devrait s’approcher de la moyenne des résidus (qui est toujours de 0). Bien que le -3.079 peut sembler important, il faut prendre en considération de l’échelle de y, et ce -3.079 est exprimé en terme de rendement, ici en quintaux (i.e. 100 kg) par hectare. La distribution des résidus mérite d’être davantage investiguée. Nous verrons cela un peu plus tard.</p>
<p>Les coefficients apparaissent ensuite. Les estimés sont les valeurs des effets. R fournit aussi l’erreur standard associée, la valeur de t ainsi que la p-value (la probabilité d’obtenir cet effet ou un effet plus extrême si en réalité il y avait absence d’effet). L’intercept est bien sûr plus élevé que 0 (à dose nulle, on obtient 65.8 quintaux par hectare en moyenne). La pente de la variable <code>nitro</code> est de ~0.06: pour chaque augmentation d’un kg/ha de dose, on a obtenu ~0.06 quintaux/ha de plus de maïs. Donc pour 100 kg/ha de N, on a obtenu un rendement moyen de 6 quintaux de plus que l’intercept. Soulignons que l’ampleur du coefficient est très important pour guider la fertilisation: ne rapporter que la p-value, ou ne rapporter que le fait qu’elle est inférieure à 0.05 (ce qui arrive souvent dans la littérature), serait très insuffisant pour l’interprétation des statistiques. La p-value nous indique néanmoins qu’il serait très improbable qu’une telle pente ait été générée alors que celle-ci est nulle en réalité. Les étoiles à côté des p-values indiquent l’ampleur selon l’échelle <code>Signif. codes</code> indiquée en-dessous du tableau des coefficients.</p>
<p>Sous ce tableau, R offre d’autres statistiques. En outre, les R² et R² ajustés indiquent si la régression passe effectivement par les points. Le R² prend un maximum de 1 lorsque la droite passe exactement sur les points.</p>
<p>Enfin, le test de F génère une p-value indiquant la probabilité que les coefficients de pente ait été générés si les vrais coefficients étaient nuls. Dans le cas d’une régression univariée, cela répète l’information sur l’unique coefficient.</p>
<p>On pourra également obtenir les intervalles de confiance avec la fonction <code>confint()</code>.</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb312-1" data-line-number="1"><span class="kw">confint</span>(modlin_<span class="dv">1</span>, <span class="dt">level =</span> <span class="fl">0.95</span>)</a></code></pre></div>
<pre><code>##                   2.5 %      97.5 %
## (Intercept) 64.65001137 67.03641474
## nitro        0.04629164  0.07714271</code></pre>
<p>Ou soutirer l’information de différentes manières, comme avec la fonction <code>coefficients()</code>.</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb314-1" data-line-number="1"><span class="kw">coefficients</span>(modlin_<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## (Intercept)       nitro 
## 65.84321305  0.06171718</code></pre>
<p>Également, on pourra exécuter le modèle sur les données qui ont servi à le générer:</p>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb316-1" data-line-number="1"><span class="kw">predict</span>(modlin_<span class="dv">1</span>)[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>]</a></code></pre></div>
<pre><code>##        1        2        3        4        5 
## 73.95902 73.95902 73.95902 73.95902 73.95902</code></pre>
<p>Ou sur des données externes.</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb318-1" data-line-number="1">nouvelles_donnees &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">nitro =</span> <span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">0</span>, <span class="dt">to =</span> <span class="dv">100</span>, <span class="dt">by =</span> <span class="dv">5</span>))</a>
<a class="sourceLine" id="cb318-2" data-line-number="2"><span class="kw">predict</span>(modlin_<span class="dv">1</span>, <span class="dt">newdata =</span> nouvelles_donnees)[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>]</a></code></pre></div>
<pre><code>##        1        2        3        4        5 
## 65.84321 66.15180 66.46038 66.76897 67.07756</code></pre>
</div>
<div id="analyse-des-residus" class="section level3">
<h3><span class="header-section-number">45.1.2</span> Analyse des résidus</h3>
<p>Les résidus sont les erreurs du modèle. C’est le vecteur <span class="math inline">\(\epsilon\)</span>, qui est un délage entre les données et le modèle. Le R² est un indicateur de l’ampleur du décalage, mais une régression linéaire explicative en bonne et due forme devrait être acompagnée d’une analyse des résidus. On peut les calculés par <span class="math inline">\(\epsilon = y - \hat{y}\)</span>, mais aussi bien utiliser la fonction <code>residuals()</code>.</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb320-1" data-line-number="1">res_df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">nitro =</span> lasrosas.corn<span class="op">$</span>nitro,</a>
<a class="sourceLine" id="cb320-2" data-line-number="2">                     <span class="dt">residus_lm =</span> <span class="kw">residuals</span>(modlin_<span class="dv">1</span>), </a>
<a class="sourceLine" id="cb320-3" data-line-number="3">                     <span class="dt">residus_calcul =</span> lasrosas.corn<span class="op">$</span>yield <span class="op">-</span><span class="st"> </span><span class="kw">predict</span>(modlin_<span class="dv">1</span>))</a>
<a class="sourceLine" id="cb320-4" data-line-number="4"><span class="kw">sample_n</span>(res_df, <span class="dv">10</span>)</a></code></pre></div>
<pre><code>##      nitro  residus_lm residus_calcul
## 124   66.0 -18.5165468    -18.5165468
## 691   66.0  -7.5965468     -7.5965468
## 459   53.0  -2.6342234     -2.6342234
## 2783  39.0  26.5998170     26.5998170
## 2519  99.8 -20.7825873    -20.7825873
## 954    0.0  -0.1132131     -0.1132131
## 2039   0.0 -16.9032131    -16.9032131
## 651  131.5   2.6109781      2.6109781
## 2856  39.0  36.5598170     36.5598170
## 128   66.0 -20.2665468    -20.2665468</code></pre>
<p>Dans une bonne régression linéaire, on ne retrouvera pas de structure identifiable dans les résidus, c’est-à-dire que les résidus sont bien distribués de part et d’autre du modèle de régression.</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb322-1" data-line-number="1"><span class="kw">ggplot</span>(res_df, <span class="kw">aes</span>(<span class="dt">x =</span> nitro, <span class="dt">y =</span> residus_lm)) <span class="op">+</span></a>
<a class="sourceLine" id="cb322-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb322-3" data-line-number="3"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Dose N&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Residus&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb322-4" data-line-number="4"><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-143-1.png" width="672" /></p>
<p>Bien que le jugement soit subjectif, on peut dire confiamment qu’il n’y a pas structure particulière. En revanche, on pourrait générer un <span class="math inline">\(y\)</span> qui varie de manière quadratique avec <span class="math inline">\(x\)</span>, un modèle linéaire montrera une structure évidente.</p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb323-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">36164</span>)</a>
<a class="sourceLine" id="cb323-2" data-line-number="2">x &lt;-<span class="st"> </span><span class="dv">0</span><span class="op">:</span><span class="dv">100</span></a>
<a class="sourceLine" id="cb323-3" data-line-number="3">y &lt;-<span class="st"> </span><span class="dv">10</span> <span class="op">+</span><span class="st"> </span>x<span class="op">*</span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>x<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="fl">0.05</span> <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="kw">length</span>(x), <span class="dv">0</span>, <span class="dv">50</span>)</a>
<a class="sourceLine" id="cb323-4" data-line-number="4">modlin_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x)</a>
<a class="sourceLine" id="cb323-5" data-line-number="5"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(x, <span class="dt">residus =</span> <span class="kw">residuals</span>(modlin_<span class="dv">2</span>)),</a>
<a class="sourceLine" id="cb323-6" data-line-number="6">       <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> residus)) <span class="op">+</span></a>
<a class="sourceLine" id="cb323-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb323-8" data-line-number="8"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;x&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Residus&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb323-9" data-line-number="9"><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-144-1.png" width="672" /></p>
<p>De même, les résidus ne devraient pas croître avec <span class="math inline">\(x\)</span>.</p>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb324-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">3984</span>)</a>
<a class="sourceLine" id="cb324-2" data-line-number="2">x &lt;-<span class="st"> </span><span class="dv">0</span><span class="op">:</span><span class="dv">100</span></a>
<a class="sourceLine" id="cb324-3" data-line-number="3">y &lt;-<span class="st">  </span><span class="dv">10</span> <span class="op">+</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span>x <span class="op">*</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="kw">length</span>(x), <span class="dv">0</span>, <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb324-4" data-line-number="4">modlin_<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x)</a>
<a class="sourceLine" id="cb324-5" data-line-number="5"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(x, <span class="dt">residus =</span> <span class="kw">residuals</span>(modlin_<span class="dv">3</span>)),</a>
<a class="sourceLine" id="cb324-6" data-line-number="6">       <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> residus)) <span class="op">+</span></a>
<a class="sourceLine" id="cb324-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb324-8" data-line-number="8"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;x&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Residus&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb324-9" data-line-number="9"><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-145-1.png" width="672" /></p>
<p>On pourra aussi inspecter les résidus avec un graphique de leur distribution. Reprenons notre modèle de rendement du maïs.</p>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb325-1" data-line-number="1"><span class="kw">ggplot</span>(res_df, <span class="kw">aes</span>(<span class="dt">x =</span> residus_lm)) <span class="op">+</span></a>
<a class="sourceLine" id="cb325-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">2</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb325-3" data-line-number="3"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Residual&quot;</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-146-1.png" width="672" /></p>
<p>L’histogramme devrait présenter une distribution normale. Les tests de nomalité comme le test de Shapiro-Wilk peuvent aider, mais ils sont généralement très sévères.</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb326-1" data-line-number="1"><span class="kw">shapiro.test</span>(res_df<span class="op">$</span>residus_lm)</a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  res_df$residus_lm
## W = 0.94868, p-value &lt; 2.2e-16</code></pre>
<p>L’hypothèse nulle que la distribution est normale est rejetée au seuil 0.05. Dans notre cas, il est évident que la sévérité du test n’est pas en cause, car les résidus semble générer trois ensembles. Ceci indique que les variables explicatives sont insuffisantes pour expliquer la variabilité de la variable-réponse.</p>
</div>
<div id="regression-multiple" class="section level3">
<h3><span class="header-section-number">45.1.3</span> Régression multiple</h3>
<p>Comme c’est le cas pour bien des phénomènes en écologie, le rendement d’une culture n’est certainement pas expliqué seulement par la dose d’azote.</p>
<p>Lorsque l’on combine plusieurs variables explicatives, on crée un modèle de régression multivariée, ou une régression multiple. Bien que les tendances puissent semblées non-linéaires, l’ajout de variables et le calcul des coefficients associés reste un problème d’algèbre linéaire.</p>
<p>On pourra en effet généraliser les modèles linéaires, univariés et multivariés, de la manière suivante.</p>
<p><span class="math display">\[ y = X \beta + \epsilon \]</span></p>
<p>où:</p>
<p><span class="math inline">\(X\)</span> est la matrice du modèle à <span class="math inline">\(n\)</span> observations et <span class="math inline">\(p\)</span> variables.</p>
<p><span class="math display">\[ X = \left( \begin{matrix} 
1 &amp; x_{11} &amp; \cdots &amp; x_{1p}  \\ 
1 &amp; x_{21} &amp; \cdots &amp; x_{2p}  \\ 
\vdots &amp; \vdots &amp; \ddots &amp; \vdots  \\ 
1 &amp; x_{n1} &amp; \cdots &amp; x_{np}
\end{matrix} \right) \]</span></p>
<p><span class="math inline">\(\beta\)</span> est la matrice des <span class="math inline">\(p\)</span> coefficients, <span class="math inline">\(\beta_0\)</span> étant l’intercept qui multiplie la première colonne de la matrice <span class="math inline">\(X\)</span>.</p>
<p><span class="math display">\[ \beta = \left( \begin{matrix} 
\beta_0  \\ 
\beta_1  \\ 
\vdots \\ 
\beta_p 
\end{matrix} \right) \]</span></p>
<p><span class="math inline">\(\epsilon\)</span> est l’erreur de chaque observation.</p>
<p><span class="math display">\[ \epsilon = \left( \begin{matrix} 
\epsilon_0  \\ 
\epsilon_1  \\ 
\vdots \\ 
\epsilon_n
\end{matrix} \right) \]</span></p>
</div>
<div id="modeles-lineaires-univaries-avec-variable-categorielle-nominale" class="section level3">
<h3><span class="header-section-number">45.1.4</span> Modèles linéaires univariés avec variable catégorielle <strong>nominale</strong></h3>
<p>Une variable catégorielle nominale (non ordonnée) utilisée à elle seule dans un modèle comme variable explicative, est un cas particulier de régression multiple. En effet, l’<strong>encodage catégoriel</strong> (ou <em>dummyfication</em>) transforme une variable catégorielle nominale en une matrice de modèle comprenant une colonne désignant l’intercept (une série de 1) désignant la catégorie de référence, ainsi que des colonnes pour chacune des autres catégories désignant l’appartenance (1) ou la non appartenance (0) de la catégorie désignée par la colonne.</p>
<div id="lencodage-categoriel" class="section level4">
<h4><span class="header-section-number">45.1.4.1</span> L’encodage catégoriel</h4>
<p>Une variable à <span class="math inline">\(C\)</span> catégories pourra être déclinée en <span class="math inline">\(C\)</span> variables dont chaque colonne désigne par un 1 l’appartenance au groupe de la colonne et par un 0 la non-appartenance. Pour l’exemple, créons un vecteur désignant le cultivar de pomme de terre.</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb328-1" data-line-number="1">data &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">cultivar =</span> <span class="kw">c</span>(<span class="st">&#39;Superior&#39;</span>, <span class="st">&#39;Superior&#39;</span>, <span class="st">&#39;Superior&#39;</span>, <span class="st">&#39;Russet&#39;</span>, <span class="st">&#39;Kenebec&#39;</span>, <span class="st">&#39;Russet&#39;</span>))</a>
<a class="sourceLine" id="cb328-2" data-line-number="2"><span class="kw">model.matrix</span>(<span class="op">~</span>cultivar, data)</a></code></pre></div>
<pre><code>##   (Intercept) cultivarRusset cultivarSuperior
## 1           1              0                1
## 2           1              0                1
## 3           1              0                1
## 4           1              1                0
## 5           1              0                0
## 6           1              1                0
## attr(,&quot;assign&quot;)
## [1] 0 1 1
## attr(,&quot;contrasts&quot;)
## attr(,&quot;contrasts&quot;)$cultivar
## [1] &quot;contr.treatment&quot;</code></pre>
<p>Nous avons trois catégories, encodées en trois colonnes. La première colonne est un intercept et les deux autres décrivent l’absence (0) ou la présence (1) des cultivars Russet et Superior. Le cultivar Kenebec est absent du tableau. En effet, en partant du principe que l’appartenance à une catégorie est mutuellement exclusive, c’est-à-dire qu’un échantillon ne peut être assigné qu’à une seule catégorie, on peut déduire une catégorie à partir de l’information sur toutes les autres. Par exemple, si <code>cultivar_Russet</code> et <code>cultivar_Superior</code> sont toutes deux égales à <span class="math inline">\(0\)</span>, on concluera que <code>cultivar_Kenebec</code> est nécessairement égal à <span class="math inline">\(1\)</span>. Et si l’un d’entre <code>cultivar_Russet</code> et <code>cultivar_Superior</code> est égal à <span class="math inline">\(1\)</span>, <code>cultivar_Kenebec</code> est nécessairement égal à <span class="math inline">\(0\)</span>. L’information contenue dans un nombre <span class="math inline">\(C\)</span> de catégorie peut être encodée dans un nombre <span class="math inline">\(C-1\)</span> de colonnes. C’est pourquoi, dans une analyse statistique, on désignera une catégorie comme une référence, que l’on détecte lorsque toutes les autres catégories sont encodées avec des <span class="math inline">\(0\)</span>: cette référence sera incluse dans l’intercept. La catégorie de référence par défaut en R est celle la première catégorie dans l’ordre aphabétique. On pourra modifier cette référence avec la fonction <code>relevel()</code>.</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb330-1" data-line-number="1">data<span class="op">$</span>cultivar &lt;-<span class="st"> </span><span class="kw">relevel</span>(data<span class="op">$</span>cultivar, <span class="dt">ref =</span> <span class="st">&quot;Superior&quot;</span>)</a>
<a class="sourceLine" id="cb330-2" data-line-number="2"><span class="kw">model.matrix</span>(<span class="op">~</span>cultivar, data)</a></code></pre></div>
<pre><code>##   (Intercept) cultivarKenebec cultivarRusset
## 1           1               0              0
## 2           1               0              0
## 3           1               0              0
## 4           1               0              1
## 5           1               1              0
## 6           1               0              1
## attr(,&quot;assign&quot;)
## [1] 0 1 1
## attr(,&quot;contrasts&quot;)
## attr(,&quot;contrasts&quot;)$cultivar
## [1] &quot;contr.treatment&quot;</code></pre>
<p>Pour certains modèles, vous devrez vous assurer vous-même de l’encodage catégoriel. Pour d’autre, en particulier avec l’<em>interface par formule</em> de R, ce sera fait automatiquement.</p>
</div>
<div id="exemple-dapplication" class="section level4">
<h4><span class="header-section-number">45.1.4.2</span> Exemple d’application</h4>
<p>Prenons la topographie du terrain, qui peut prendre plusieurs niveaux.</p>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb332-1" data-line-number="1"><span class="kw">levels</span>(lasrosas.corn<span class="op">$</span>topo)</a></code></pre></div>
<pre><code>## [1] &quot;E&quot;  &quot;HT&quot; &quot;LO&quot; &quot;W&quot;</code></pre>
<p>Explorons le rendement selon la topographie.</p>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb334-1" data-line-number="1"><span class="kw">ggplot</span>(lasrosas.corn, <span class="kw">aes</span>(<span class="dt">x =</span> topo, <span class="dt">y =</span> yield)) <span class="op">+</span></a>
<a class="sourceLine" id="cb334-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-151-1.png" width="672" /></p>
<p>Les différences sont évidentes, et la modélisation devrait montrer des effets significatifs.</p>
<p>L’encodage catégoriel peut être visualisé en générant la matrice de modèle avec la fonction <code>model.matrix()</code> et l’interface-formule - sans la variable-réponse.</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb335-1" data-line-number="1"><span class="kw">model.matrix</span>(<span class="op">~</span><span class="st"> </span>topo, <span class="dt">data =</span> lasrosas.corn) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb335-2" data-line-number="2"><span class="st">    </span><span class="kw">tbl_df</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># tbl_df pour transformer la matrice en tableau</span></a>
<a class="sourceLine" id="cb335-3" data-line-number="3"><span class="st">    </span><span class="kw">sample_n</span>(<span class="dv">10</span>) </a></code></pre></div>
<pre><code>## # A tibble: 10 x 4
##    `(Intercept)` topoHT topoLO topoW
##            &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1             1      0      1     0
##  2             1      0      0     1
##  3             1      0      0     0
##  4             1      0      0     1
##  5             1      0      0     1
##  6             1      0      0     1
##  7             1      0      0     0
##  8             1      0      0     0
##  9             1      1      0     0
## 10             1      0      0     1</code></pre>
<p>Dans le cas d’un modèle avec une variable catégorielle nominale seule, l’intercept représente la catégorie de référence, ici <code>E</code>. Les autres colonnes spécifient l’appartenance (1) ou la non-appartenance (0) de la catégorie pour chaque observation.</p>
<p>Cette matrice de modèle utilisée pour la régression donnera un intercept, qui indiquera l’effet de la catégorie de référence, puis les différences entre les catégories subséquentes et la catégorie de référence.</p>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb337-1" data-line-number="1">modlin_<span class="dv">4</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(yield <span class="op">~</span><span class="st"> </span>topo, <span class="dt">data =</span> lasrosas.corn)</a>
<a class="sourceLine" id="cb337-2" data-line-number="2"><span class="kw">summary</span>(modlin_<span class="dv">4</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ topo, data = lasrosas.corn)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -47.371 -11.933  -1.593  11.080  44.119 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  78.6653     0.5399 145.707   &lt;2e-16 ***
## topoHT      -30.0526     0.7500 -40.069   &lt;2e-16 ***
## topoLO        6.2832     0.7293   8.615   &lt;2e-16 ***
## topoW       -11.8841     0.7039 -16.883   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.59 on 3439 degrees of freedom
## Multiple R-squared:  0.4596, Adjusted R-squared:  0.4591 
## F-statistic:   975 on 3 and 3439 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Le modèle linéaire est équivalent à l’anova, mais les résultats de <code>lm</code> sont plus élaborés.</p>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb339-1" data-line-number="1"><span class="kw">summary</span>(<span class="kw">aov</span>(yield <span class="op">~</span><span class="st"> </span>topo, <span class="dt">data =</span> lasrosas.corn))</a></code></pre></div>
<pre><code>##               Df Sum Sq Mean Sq F value Pr(&gt;F)    
## topo           3 622351  207450     975 &lt;2e-16 ***
## Residuals   3439 731746     213                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>L’analyse de résidus peut être effectuée de la même manière.</p>
</div>
</div>
<div id="modeles-lineaires-univaries-avec-variable-categorielle-ordinale" class="section level3">
<h3><span class="header-section-number">45.1.5</span> Modèles linéaires univariés avec variable catégorielle <strong>ordinale</strong></h3>
<p>Bien que j’introduise la régression sur variable catégorielle ordinale à la suite de la section sur les variables nominales, nous revenons dans ce cas à une rérgession simple, univariée. Voyons un cas à 5 niveaux.</p>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb341-1" data-line-number="1">statut &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Totalement en désaccort&quot;</span>, </a>
<a class="sourceLine" id="cb341-2" data-line-number="2">            <span class="st">&quot;En désaccord&quot;</span>,</a>
<a class="sourceLine" id="cb341-3" data-line-number="3">            <span class="st">&quot;Ni en accord, ni en désaccord&quot;</span>,</a>
<a class="sourceLine" id="cb341-4" data-line-number="4">            <span class="st">&quot;En accord&quot;</span>,</a>
<a class="sourceLine" id="cb341-5" data-line-number="5">            <span class="st">&quot;Totalement en accord&quot;</span>)</a>
<a class="sourceLine" id="cb341-6" data-line-number="6">statut_o &lt;-<span class="st"> </span><span class="kw">factor</span>(statut, <span class="dt">levels =</span> statut, <span class="dt">ordered=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb341-7" data-line-number="7"><span class="kw">model.matrix</span>(<span class="op">~</span>statut_o) <span class="co"># ou bien, sans passer par model.matrix, contr.poly(5) où 5 est le nombre de niveaux</span></a></code></pre></div>
<pre><code>##   (Intercept) statut_o.L statut_o.Q    statut_o.C statut_o^4
## 1           1 -0.6324555  0.5345225 -3.162278e-01  0.1195229
## 2           1 -0.3162278 -0.2672612  6.324555e-01 -0.4780914
## 3           1  0.0000000 -0.5345225 -4.095972e-16  0.7171372
## 4           1  0.3162278 -0.2672612 -6.324555e-01 -0.4780914
## 5           1  0.6324555  0.5345225  3.162278e-01  0.1195229
## attr(,&quot;assign&quot;)
## [1] 0 1 1 1 1
## attr(,&quot;contrasts&quot;)
## attr(,&quot;contrasts&quot;)$statut_o
## [1] &quot;contr.poly&quot;</code></pre>
<p>La matrice de modèle a 5 colonnes, soit le nombre de niveaux: un intercept, puis 4 autres désignant différentes valeurs que peuvent prendre les niveaux. Ces niveaux croient-ils linéairement? De manière quadratique, cubique ou plus loin dans des distributions polynomiales?</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb343-1" data-line-number="1">modmat_tidy &lt;-<span class="st"> </span><span class="kw">data.frame</span>(statut, <span class="kw">model.matrix</span>(<span class="op">~</span>statut_o)[, <span class="dv">-1</span>]) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb343-2" data-line-number="2"><span class="st">    </span><span class="kw">gather</span>(variable, valeur, <span class="op">-</span>statut)</a>
<a class="sourceLine" id="cb343-3" data-line-number="3">modmat_tidy<span class="op">$</span>statut &lt;-<span class="st"> </span><span class="kw">factor</span>(modmat_tidy<span class="op">$</span>statut, </a>
<a class="sourceLine" id="cb343-4" data-line-number="4">                             <span class="dt">levels =</span> statut, </a>
<a class="sourceLine" id="cb343-5" data-line-number="5">                             <span class="dt">ordered=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb343-6" data-line-number="6"><span class="kw">ggplot</span>(<span class="dt">data =</span> modmat_tidy, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> statut, <span class="dt">y =</span> valeur)) <span class="op">+</span></a>
<a class="sourceLine" id="cb343-7" data-line-number="7"><span class="st">    </span><span class="kw">facet_wrap</span>(. <span class="op">~</span><span class="st"> </span>variable) <span class="op">+</span></a>
<a class="sourceLine" id="cb343-8" data-line-number="8"><span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb343-9" data-line-number="9"><span class="st">    </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">45</span>, <span class="dt">hjust =</span> <span class="dv">1</span>))</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-156-1.png" width="672" /></p>
<p>Règle générale, pour les variables ordinales, on préférera une distribution linéaire, et c’est l’option par défaut de la fonction <code>lm()</code>. L’utilisation d’une autre distribution peut être effectuée à la mitaine en utilisant dans le modèle la colonne désirée de la sortie de la fonction <code>model.matrix()</code>.</p>
</div>
<div id="regression-multiple-a-plusieurs-variables" class="section level3">
<h3><span class="header-section-number">45.1.6</span> Régression multiple à plusieurs variables</h3>
<p>Reprenons le tableau de données du rendement de maïs.</p>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb344-1" data-line-number="1"><span class="kw">head</span>(lasrosas.corn)</a></code></pre></div>
<pre><code>##   year       lat      long yield nitro topo     bv rep nf
## 1 1999 -33.05113 -63.84886 72.14 131.5    W 162.60  R1 N5
## 2 1999 -33.05115 -63.84879 73.79 131.5    W 170.49  R1 N5
## 3 1999 -33.05116 -63.84872 77.25 131.5    W 168.39  R1 N5
## 4 1999 -33.05117 -63.84865 76.35 131.5    W 176.68  R1 N5
## 5 1999 -33.05118 -63.84858 75.55 131.5    W 171.46  R1 N5
## 6 1999 -33.05120 -63.84851 70.24 131.5    W 170.56  R1 N5</code></pre>
<p>Pour ajouter des variables au modèle dans l’interface-formule, on additionne les noms de colonne. La variable <code>lat</code> désigne la latitude, la variable <code>long</code> désigne la latitude et la variable <code>bv</code> (<em>brightness value</em>) désigne la teneur en matière organique du sol (plus <code>bv</code> est élevée, plus faible est la teneur en matière organique).</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb346-1" data-line-number="1">modlin_<span class="dv">5</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(yield <span class="op">~</span><span class="st"> </span>lat <span class="op">+</span><span class="st"> </span>long <span class="op">+</span><span class="st"> </span>nitro <span class="op">+</span><span class="st"> </span>topo <span class="op">+</span><span class="st"> </span>bv,</a>
<a class="sourceLine" id="cb346-2" data-line-number="2">               <span class="dt">data =</span> lasrosas.corn)</a>
<a class="sourceLine" id="cb346-3" data-line-number="3"><span class="kw">summary</span>(modlin_<span class="dv">5</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ lat + long + nitro + topo + bv, data = lasrosas.corn)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -48.405 -11.071  -1.251  10.592  40.078 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.946e+05  3.309e+04   5.882 4.45e-09 ***
## lat          5.541e+03  4.555e+02  12.163  &lt; 2e-16 ***
## long         1.776e+02  4.491e+02   0.395    0.693    
## nitro        6.867e-02  5.451e-03  12.597  &lt; 2e-16 ***
## topoHT      -2.665e+01  1.087e+00 -24.520  &lt; 2e-16 ***
## topoLO       5.565e+00  1.035e+00   5.378 8.03e-08 ***
## topoW       -1.465e+01  1.655e+00  -8.849  &lt; 2e-16 ***
## bv          -5.089e-01  3.069e-02 -16.578  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.47 on 3435 degrees of freedom
## Multiple R-squared:  0.5397, Adjusted R-squared:  0.5387 
## F-statistic: 575.3 on 7 and 3435 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>L’ampleur des coefficients est relatif à l’échelle de la variable. En effet, un coefficient de 5541 sur la variable <code>lat</code> n’est pas comparable au coefficient de la variable <code>bv</code>, de -0.5089, étant donné que les variables ne sont pas exprimées avec la même échelle. Pour les comparer sur une même base, on peut centrer (soustraire la moyenne) et rédurie (diviser par l’écart-type).</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb348-1" data-line-number="1">scale_vec &lt;-<span class="st"> </span><span class="cf">function</span>(x) <span class="kw">as.vector</span>(<span class="kw">scale</span>(x)) <span class="co"># la fonction scale génère une matrice: nous désirons un vecteur</span></a>
<a class="sourceLine" id="cb348-2" data-line-number="2"></a>
<a class="sourceLine" id="cb348-3" data-line-number="3">lasrosas.corn_sc &lt;-<span class="st"> </span>lasrosas.corn <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb348-4" data-line-number="4"><span class="st">    </span><span class="kw">mutate_at</span>(<span class="kw">c</span>(<span class="st">&quot;lat&quot;</span>, <span class="st">&quot;long&quot;</span>, <span class="st">&quot;nitro&quot;</span>, <span class="st">&quot;bv&quot;</span>), </a>
<a class="sourceLine" id="cb348-5" data-line-number="5">                 scale_vec)</a>
<a class="sourceLine" id="cb348-6" data-line-number="6"></a>
<a class="sourceLine" id="cb348-7" data-line-number="7">modlin_<span class="dv">5</span>_sc &lt;-<span class="st"> </span><span class="kw">lm</span>(yield <span class="op">~</span><span class="st"> </span>lat <span class="op">+</span><span class="st"> </span>long <span class="op">+</span><span class="st"> </span>nitro <span class="op">+</span><span class="st"> </span>topo <span class="op">+</span><span class="st"> </span>bv,</a>
<a class="sourceLine" id="cb348-8" data-line-number="8">               <span class="dt">data =</span> lasrosas.corn_sc)</a>
<a class="sourceLine" id="cb348-9" data-line-number="9"><span class="kw">summary</span>(modlin_<span class="dv">5</span>_sc)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ lat + long + nitro + topo + bv, data = lasrosas.corn_sc)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -48.405 -11.071  -1.251  10.592  40.078 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  78.9114     0.6666 118.376  &lt; 2e-16 ***
## lat           3.9201     0.3223  12.163  &lt; 2e-16 ***
## long          0.3479     0.8796   0.395    0.693    
## nitro         2.9252     0.2322  12.597  &lt; 2e-16 ***
## topoHT      -26.6487     1.0868 -24.520  &lt; 2e-16 ***
## topoLO        5.5647     1.0347   5.378 8.03e-08 ***
## topoW       -14.6487     1.6555  -8.849  &lt; 2e-16 ***
## bv           -4.9253     0.2971 -16.578  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.47 on 3435 degrees of freedom
## Multiple R-squared:  0.5397, Adjusted R-squared:  0.5387 
## F-statistic: 575.3 on 7 and 3435 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Typiquement, les variables catégorielles, qui ne sont pas mises à l’échelle, donneront des coefficients plus élevées, et devrons être évaluées entre elles et non comparativement aux variables mises à l’échelle. Une manière conviviale de représenter des coefficients consiste à créer un tableau (fonction <code>tibble()</code>) incluant les coefficients ainsi que leurs intervalles de confiance, puis à les porter graphiquement.</p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb350-1" data-line-number="1">intervals &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">Estimate =</span> <span class="kw">coefficients</span>(modlin_<span class="dv">5</span>_sc)[<span class="op">-</span><span class="dv">1</span>], <span class="co"># [-1] enlever l&#39;intercept</span></a>
<a class="sourceLine" id="cb350-2" data-line-number="2">                    <span class="dt">LL =</span> <span class="kw">confint</span>(modlin_<span class="dv">5</span>_sc)[<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>], <span class="co"># [-1, ] enlever la première ligne, celle de l&#39;intercept</span></a>
<a class="sourceLine" id="cb350-3" data-line-number="3">                    <span class="dt">UL =</span> <span class="kw">confint</span>(modlin_<span class="dv">5</span>_sc)[<span class="op">-</span><span class="dv">1</span>, <span class="dv">2</span>],</a>
<a class="sourceLine" id="cb350-4" data-line-number="4">                    <span class="dt">variable =</span> <span class="kw">names</span>(<span class="kw">coefficients</span>(modlin_<span class="dv">5</span>_sc)[<span class="op">-</span><span class="dv">1</span>])) </a>
<a class="sourceLine" id="cb350-5" data-line-number="5">intervals</a></code></pre></div>
<pre><code>## # A tibble: 7 x 4
##   Estimate     LL     UL variable
##      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;   
## 1    3.92    3.29   4.55 lat     
## 2    0.348  -1.38   2.07 long    
## 3    2.93    2.47   3.38 nitro   
## 4  -26.6   -28.8  -24.5  topoHT  
## 5    5.56    3.54   7.59 topoLO  
## 6  -14.6   -17.9  -11.4  topoW   
## 7   -4.93   -5.51  -4.34 bv</code></pre>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb352-1" data-line-number="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> intervals, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> Estimate, <span class="dt">y =</span> variable)) <span class="op">+</span></a>
<a class="sourceLine" id="cb352-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="dv">0</span>, <span class="dt">lty =</span> <span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb352-3" data-line-number="3"><span class="st">    </span><span class="kw">geom_segment</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> LL, <span class="dt">xend =</span> UL, </a>
<a class="sourceLine" id="cb352-4" data-line-number="4">                               <span class="dt">y =</span> variable, <span class="dt">yend =</span> variable)) <span class="op">+</span></a>
<a class="sourceLine" id="cb352-5" data-line-number="5"><span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb352-6" data-line-number="6"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Coefficient standardisé&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;&quot;</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-161-1.png" width="672" /></p>
<p>On y voit qu’à l’exception de la variable <code>long</code>, tous les coefficients sont différents de 0. Le coefficient <code>bv</code> est négatif, indicant que plus la valeur de <code>bv</code> est élevé (donc plus le sol est pauvre en matière organique), plus le rendement est faible. Plus la latitude est élevée (plus on se dirige vers le Nord de l’Argentine), plus le rendement est élevé. La dose d’azote a aussi un effet statistique positif sur le rendement.</p>
<p>Quant aux catégories topographiques, elles sont toutes différentes de la catégorie <code>E</code>, ne croisant pas le zéro. De plus, les intervalles de confiance ne se chevauchant pas, on peut conclure en une différence significative d’une à l’autre. Bien sûr, tout cela au seuil de confiance de 0.05.</p>
<p>On pourra retrouver des cas où l’effet combiné de plusieurs variables diffère de l’effet des deux variables prises séparément. Par exemple, on pourrait évaluer l’effet de l’azote et celui de la topographie dans un même modèle, puis y ajouter une intéraction entre l’azote et la topographie, qui définira des effets supplémentaires de l’azote selon chaque catégorie topographique. C’est ce que l’on appelle une intéraction.</p>
<p>Dans l’interface-formule, l’intéraction entre l’azote et la topographie est notée <code>nitro:topo</code>. Pour ajouter cette intéraction, la formule deviendra <code>yield ~ nitro + topo + nitro:topo</code>. Une approche équivalente est d’utiliser le raccourci <code>yield ~ nitro*topo</code>.</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb353-1" data-line-number="1">modlin_<span class="dv">5</span>_sc &lt;-<span class="st"> </span><span class="kw">lm</span>(yield <span class="op">~</span><span class="st"> </span>nitro<span class="op">*</span>topo,</a>
<a class="sourceLine" id="cb353-2" data-line-number="2">               <span class="dt">data =</span> lasrosas.corn_sc)</a>
<a class="sourceLine" id="cb353-3" data-line-number="3"><span class="kw">summary</span>(modlin_<span class="dv">5</span>_sc)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ nitro * topo, data = lasrosas.corn_sc)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -47.984 -11.985  -1.388  10.339  40.636 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   78.6999     0.5322 147.870  &lt; 2e-16 ***
## nitro          1.8131     0.5351   3.388 0.000711 ***
## topoHT       -30.0052     0.7394 -40.578  &lt; 2e-16 ***
## topoLO         6.2026     0.7190   8.627  &lt; 2e-16 ***
## topoW        -11.9628     0.6939 -17.240  &lt; 2e-16 ***
## nitro:topoHT   1.2553     0.7461   1.682 0.092565 .  
## nitro:topoLO   0.5695     0.7186   0.792 0.428141    
## nitro:topoW    0.7702     0.6944   1.109 0.267460    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.38 on 3435 degrees of freedom
## Multiple R-squared:  0.4756, Adjusted R-squared:  0.4746 
## F-statistic: 445.1 on 7 and 3435 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Les résultats montre des effets de l’azote et des catégories topographiques, mais il y a davantage d’incertitude sur les intéractions, indiquant que l’effet statistique de l’azote est sensiblement le même indépendamment des niveaux topographiques.</p>
<hr />
</div>
<div id="attention-a-ne-pas-surcharger-le-modele" class="section level3">
<h3><span class="header-section-number">45.1.7</span> Attention à ne pas surcharger le modèle</h3>
<p>Il est possible d’ajouter des intéractions doubles, triples, quadruples, etc. Mais plus il y a d’intéractions, plus votre modèle comprendra de variables et vos tests d’hypothèse perdront en puissance statistique.</p>
<hr />
</div>
<div id="les-modeles-lineaires-generalises" class="section level3">
<h3><span class="header-section-number">45.1.8</span> Les modèles linéaires généralisés</h3>
<p>Dans un modèle linéaire ordinaire, un changement constant dans les variables explicatives résulte en un changement constant de la variable-réponse. Cette supposition ne serait pas adéquate si la variable-réponse était un décompte, si elle est booléenne ou si, de manière générale, la variable-réponse ne suivait pas une distribution continue. Ou, de manière plus spécifique, il n’y a pas moyen de retrouver une distribution normale des résidus? On pourra bien sûr transformer les variables (sujet du chapitre 6, en développement). Mais il pourrait s’avérer impossible, ou tout simplement non souhaitable de transformer les variables. Le modèle linéaire généralisé (MLG, ou <em>generalized linear model</em> - GLM) est une généralisation du modèle linéaire ordinaire chez qui la variable-réponse peut être caractérisé par une distribution de Poisson, de Bernouilli, etc.</p>
<p>Prenons d’abord cas d’un décompte de vers fil-de-fer (<code>worms</code>) retrouvés dans des parcelles sous différents traitements (<code>trt</code>). Les décomptes sont typiquement distribué selon une loi de Poisson.</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb355-1" data-line-number="1">cochran.wireworms <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> worms)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-163-1.png" width="672" /></p>
<p>Explorons les décomptes selon les traitements.</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb357-1" data-line-number="1">cochran.wireworms <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> trt, <span class="dt">y =</span> worms)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-164-1.png" width="672" /></p>
<p>Les traitements semble à première vue avoir un effet comparativement au contrôle. Lançons un MLG avec la fonction <code>glm()</code>, et spécifions que la sortie est une distribution de Poisson.</p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb358-1" data-line-number="1">modglm_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">glm</span>(worms <span class="op">~</span><span class="st"> </span>trt, cochran.wireworms, <span class="dt">family =</span> <span class="st">&quot;poisson&quot;</span>)</a>
<a class="sourceLine" id="cb358-2" data-line-number="2"><span class="kw">summary</span>(modglm_<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = worms ~ trt, family = &quot;poisson&quot;, data = cochran.wireworms)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.8279  -0.9455  -0.2862   0.6916   3.1888  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   0.1823     0.4082   0.447 0.655160    
## trtM          1.6422     0.4460   3.682 0.000231 ***
## trtN          1.7636     0.4418   3.991 6.57e-05 ***
## trtO          1.5755     0.4485   3.513 0.000443 ***
## trtP          1.3437     0.4584   2.931 0.003375 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 64.555  on 24  degrees of freedom
## Residual deviance: 38.026  on 20  degrees of freedom
## AIC: 125.64
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Il est très probable (p-value de ~0.66) qu’un intercept de 0.18 ayant une erreur standard de 0.4082 ait été généré depuis une population dont l’intercept est nul: autrement dit, le contrôle n’a probablement pas eu d’effet. Quant aux autres traitements, leurs effets sont tous significatifs au seuil 0.05, mais peuvent-ils être considérés comme équivalents?</p>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb360-1" data-line-number="1">intervals &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">Estimate =</span> <span class="kw">coefficients</span>(modglm_<span class="dv">1</span>), <span class="co"># [-1] enlever l&#39;intercept</span></a>
<a class="sourceLine" id="cb360-2" data-line-number="2">                    <span class="dt">LL =</span> <span class="kw">confint</span>(modglm_<span class="dv">1</span>)[, <span class="dv">1</span>], <span class="co"># [-1, ] enlever la première ligne, celle de l&#39;intercept</span></a>
<a class="sourceLine" id="cb360-3" data-line-number="3">                    <span class="dt">UL =</span> <span class="kw">confint</span>(modglm_<span class="dv">1</span>)[, <span class="dv">2</span>],</a>
<a class="sourceLine" id="cb360-4" data-line-number="4">                    <span class="dt">variable =</span> <span class="kw">names</span>(<span class="kw">coefficients</span>(modglm_<span class="dv">1</span>))) </a></code></pre></div>
<pre><code>## Waiting for profiling to be done...
## Waiting for profiling to be done...</code></pre>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb362-1" data-line-number="1">intervals</a></code></pre></div>
<pre><code>## # A tibble: 5 x 4
##   Estimate     LL    UL variable   
##      &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;      
## 1    0.182 -0.740 0.888 (Intercept)
## 2    1.64   0.840 2.62  trtM       
## 3    1.76   0.972 2.74  trtN       
## 4    1.58   0.766 2.56  trtO       
## 5    1.34   0.509 2.34  trtP</code></pre>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb364-1" data-line-number="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> intervals, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> Estimate, <span class="dt">y =</span> variable)) <span class="op">+</span></a>
<a class="sourceLine" id="cb364-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="dv">0</span>, <span class="dt">lty =</span> <span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb364-3" data-line-number="3"><span class="st">    </span><span class="kw">geom_segment</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> LL, <span class="dt">xend =</span> UL, </a>
<a class="sourceLine" id="cb364-4" data-line-number="4">                               <span class="dt">y =</span> variable, <span class="dt">yend =</span> variable)) <span class="op">+</span></a>
<a class="sourceLine" id="cb364-5" data-line-number="5"><span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb364-6" data-line-number="6"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Coefficient&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;&quot;</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-167-1.png" width="672" /></p>
<p>Les intervales de confiance se superposant, on ne peut pas conclure qu’un traitement est lié à une réduction plus importante de vers qu’un autre, au seuil 0.05.</p>
<p>Maintenant, à défaut de trouver un tableau de données plus approprié, prenons le tableau <code>mtcars</code>, qui rassemble des données sur des modèles de voitures. La colonne <code>vs</code>, pour v-shaped, inscrit 0 si les pistons sont droit et 1 s’ils sont placés en V dans le moteur. Peut-on expliquer la forme des pistons selon le poids du véhicule (<code>wt</code>)?</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb365-1" data-line-number="1">mtcars <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">sample_n</span>(<span class="dv">6</span>)</a></code></pre></div>
<pre><code>##                    mpg cyl  disp  hp drat    wt  qsec vs am gear carb
## Merc 450SLC       15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
## Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
## Honda Civic       30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
## Chrysler Imperial 14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
## Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
## AMC Javelin       15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2</code></pre>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb367-1" data-line-number="1">mtcars <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb367-2" data-line-number="2"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> wt, <span class="dt">y =</span> vs)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-169-1.png" width="672" /></p>
<p>Il semble y avoir une tendance: les véhicules plus lourds ont plutôt des pistons droits (<code>vs = 0</code>). Vérifions cela.</p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb368-1" data-line-number="1">modglm_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">glm</span>(vs <span class="op">~</span><span class="st"> </span>wt, <span class="dt">data =</span> mtcars, <span class="dt">family =</span> binomial)</a>
<a class="sourceLine" id="cb368-2" data-line-number="2"><span class="kw">summary</span>(modglm_<span class="dv">2</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = vs ~ wt, family = binomial, data = mtcars)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.9003  -0.7641  -0.1559   0.7223   1.5736  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)   5.7147     2.3014   2.483  0.01302 * 
## wt           -1.9105     0.7279  -2.625  0.00867 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 43.860  on 31  degrees of freedom
## Residual deviance: 31.367  on 30  degrees of freedom
## AIC: 35.367
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p><strong>Exercice</strong>. Analyser les résultats.</p>
</div>
<div id="les-modeles-non-lineaires" class="section level3">
<h3><span class="header-section-number">45.1.9</span> Les modèles non-linéaires</h3>
<p>La hauteur d’un arbre en fonction du temps n’est typiquement pas linéaire. Elle tend à croître de plus en plus lentement jusqu’à un plateau. De même, le rendement d’une culture traité avec des doses croissantes de fertilisants tend à atteindre un maximum, puis à se stabiliser.</p>
<p>Ces phénomènes ne peuvent pas être approximés par des modèles linéaires. Examinons les données du tableau <code>engelstad.nitro</code>.</p>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb370-1" data-line-number="1">engelstad.nitro <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">sample_n</span>(<span class="dv">10</span>)</a></code></pre></div>
<pre><code>##          loc year nitro yield
## 38 Knoxville 1963    67  73.2
## 40 Knoxville 1963   201  91.2
## 21   Jackson 1965   134  60.5
## 35 Knoxville 1962   268  78.4
## 22   Jackson 1965   201  70.2
## 12   Jackson 1963   335  87.0
## 24   Jackson 1965   335  73.0
## 20   Jackson 1965    67  47.6
## 15   Jackson 1964   134  55.2
## 48 Knoxville 1964   335  84.5</code></pre>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb372-1" data-line-number="1">engelstad.nitro <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb372-2" data-line-number="2"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> nitro, <span class="dt">y =</span> yield)) <span class="op">+</span></a>
<a class="sourceLine" id="cb372-3" data-line-number="3"><span class="st">        </span><span class="kw">facet_grid</span>(year <span class="op">~</span><span class="st"> </span>loc) <span class="op">+</span></a>
<a class="sourceLine" id="cb372-4" data-line-number="4"><span class="st">        </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb372-5" data-line-number="5"><span class="st">        </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-172-1.png" width="672" /></p>
<p>Le modèle de Mitscherlich pourrait être utilisé.</p>
<p><span class="math display">\[ y = A \left( 1 - e^{-R \left( E + x \right)} \right) \]</span></p>
<p>où <span class="math inline">\(y\)</span> est le rendement, <span class="math inline">\(x\)</span> est la dose, <span class="math inline">\(A\)</span> est l’asymptote vers laquelle la courbe converge à dose croissante, <span class="math inline">\(E\)</span> est l’équivalent de dose fourni par l’environnement et <span class="math inline">\(R\)</span> est le taux de réponse.</p>
<p>Explorons la fonction.</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb373-1" data-line-number="1">mitscherlich_f &lt;-<span class="st"> </span><span class="cf">function</span>(x, A, E, R) {</a>
<a class="sourceLine" id="cb373-2" data-line-number="2">    A <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">exp</span>(<span class="op">-</span>R<span class="op">*</span>(E <span class="op">+</span><span class="st"> </span>x)))</a>
<a class="sourceLine" id="cb373-3" data-line-number="3">}</a>
<a class="sourceLine" id="cb373-4" data-line-number="4"></a>
<a class="sourceLine" id="cb373-5" data-line-number="5">x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">350</span>, <span class="dt">by =</span> <span class="dv">5</span>)</a>
<a class="sourceLine" id="cb373-6" data-line-number="6">y &lt;-<span class="st"> </span><span class="kw">mitscherlich_f</span>(x, <span class="dt">A =</span> <span class="dv">75</span>, <span class="dt">E =</span> <span class="dv">30</span>, <span class="dt">R =</span> <span class="fl">0.02</span>)</a>
<a class="sourceLine" id="cb373-7" data-line-number="7"></a>
<a class="sourceLine" id="cb373-8" data-line-number="8"><span class="kw">ggplot</span>(<span class="kw">tibble</span>(x, y), <span class="kw">aes</span>(x, y)) <span class="op">+</span></a>
<a class="sourceLine" id="cb373-9" data-line-number="9"><span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">data =</span> engelstad.nitro, <span class="kw">aes</span>(<span class="dt">x =</span> nitro, <span class="dt">y =</span> yield)) <span class="op">+</span></a>
<a class="sourceLine" id="cb373-10" data-line-number="10"><span class="st">    </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span><span class="kw">ylim</span>(<span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">100</span>))</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-173-1.png" width="672" /></p>
<p><strong>Exercice</strong>. Changez les paramètres pour visualiser comment la courbe réagit.</p>
<p>Nous pouvons décrire le modèle grâce à l’interface formule dans la fonction <code>nls()</code>. Notez que les modèles non-linéaires demandent des stratégies de calcul différentes de celles des modèles linéaires. En tout temps, nous devons identifier des valeurs de départ raisonnables pour les paramètres dans l’argument <code>start</code>. Vous réussirez rarement à obtenir une convergence du premier coup avec vos paramètres de départ. Le défi est d’en trouver qui permettront au modèle de converger. Parfois, le modèle ne convergera jamais. D’autres fois, il convergera vers des solutions différentes selon les variables de départ choisies.
&lt;</p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb374-1" data-line-number="1"><span class="co">#modnl_1 &lt;- nls(yield ~ A * (1 - exp(-R*(E + nitro))),</span></a>
<a class="sourceLine" id="cb374-2" data-line-number="2"><span class="co">#                data = engelstad.nitro,</span></a>
<a class="sourceLine" id="cb374-3" data-line-number="3"><span class="co">#                start = list(A = 50, E = 10, R = 0.2))</span></a></code></pre></div>
<p>Le modèle ne coverge pas. Essayons les valeurs prises plus haut, lors de la création du graphique, qui semblent bien s’ajuster.</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb375-1" data-line-number="1">modnl_<span class="dv">1</span> &lt;-<span class="st">  </span><span class="kw">nls</span>(yield <span class="op">~</span><span class="st"> </span>A <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">exp</span>(<span class="op">-</span>R<span class="op">*</span>(E <span class="op">+</span><span class="st"> </span>nitro))),</a>
<a class="sourceLine" id="cb375-2" data-line-number="2">                <span class="dt">data =</span> engelstad.nitro,</a>
<a class="sourceLine" id="cb375-3" data-line-number="3">                <span class="dt">start =</span> <span class="kw">list</span>(<span class="dt">A =</span> <span class="dv">75</span>, <span class="dt">E =</span> <span class="dv">30</span>, <span class="dt">R =</span> <span class="fl">0.02</span>))</a></code></pre></div>
<p>Bingo! Voyons maintenant le sommaire.</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb376-1" data-line-number="1"><span class="kw">summary</span>(modnl_<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## 
## Formula: yield ~ A * (1 - exp(-R * (E + nitro)))
## 
## Parameters:
##    Estimate Std. Error t value Pr(&gt;|t|)    
## A 75.023427   3.331860  22.517   &lt;2e-16 ***
## E 66.164110  27.251591   2.428   0.0184 *  
## R  0.012565   0.004881   2.574   0.0127 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.34 on 57 degrees of freedom
## 
## Number of iterations to convergence: 5 
## Achieved convergence tolerance: 8.067e-06</code></pre>
<p>Les paramètres sont significativement différents de zéro au seuil 0.05, et donnent la courbe suivante.</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb378-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">350</span>, <span class="dt">by =</span> <span class="dv">5</span>)</a>
<a class="sourceLine" id="cb378-2" data-line-number="2">y &lt;-<span class="st"> </span><span class="kw">mitscherlich_f</span>(x,</a>
<a class="sourceLine" id="cb378-3" data-line-number="3">                    <span class="dt">A =</span> <span class="kw">coefficients</span>(modnl_<span class="dv">1</span>)[<span class="dv">1</span>],</a>
<a class="sourceLine" id="cb378-4" data-line-number="4">                    <span class="dt">E =</span> <span class="kw">coefficients</span>(modnl_<span class="dv">1</span>)[<span class="dv">2</span>],</a>
<a class="sourceLine" id="cb378-5" data-line-number="5">                    <span class="dt">R =</span> <span class="kw">coefficients</span>(modnl_<span class="dv">1</span>)[<span class="dv">3</span>])</a>
<a class="sourceLine" id="cb378-6" data-line-number="6"></a>
<a class="sourceLine" id="cb378-7" data-line-number="7"><span class="kw">ggplot</span>(<span class="kw">tibble</span>(x, y), <span class="kw">aes</span>(x, y)) <span class="op">+</span></a>
<a class="sourceLine" id="cb378-8" data-line-number="8"><span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">data =</span> engelstad.nitro, <span class="kw">aes</span>(<span class="dt">x =</span> nitro, <span class="dt">y =</span> yield)) <span class="op">+</span></a>
<a class="sourceLine" id="cb378-9" data-line-number="9"><span class="st">    </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span><span class="kw">ylim</span>(<span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">100</span>))</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-177-1.png" width="672" /></p>
<p>Et les résidus…</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb379-1" data-line-number="1"><span class="kw">tibble</span>(<span class="dt">res =</span> <span class="kw">residuals</span>(modnl_<span class="dv">1</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb379-2" data-line-number="2"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> res)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">20</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-178-1.png" width="672" /></p>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb380-1" data-line-number="1"><span class="kw">tibble</span>(<span class="dt">nitro =</span> engelstad.nitro<span class="op">$</span>nitro, <span class="dt">res =</span> <span class="kw">residuals</span>(modnl_<span class="dv">1</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb380-2" data-line-number="2"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> nitro, <span class="dt">y =</span> res)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb380-3" data-line-number="3"><span class="st">        </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb380-4" data-line-number="4"><span class="st">        </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-179-1.png" width="672" /></p>
<p>Les résidus ne sont pas distribués normalement, mais semble bien partagés de part et d’autre de la courbe.</p>
</div>
</div>
<div id="modeles-a-effets-mixtes" class="section level2">
<h2><span class="header-section-number">45.2</span> Modèles à effets mixtes</h2>
<p>Lorsque l’on combine des variables fixes (testées lors de l’expérience) et des variables aléatoire (variation des unités expérimentales), on obtient un modèle mixte. Les modèles mixtes peuvent être univariés, multivariés, linéaires ordinaires ou généralisés ou non linéaires.</p>
<p>À la différence d’un effet fixe, un effet aléatoire sera toujours distribué normalement avec une moyenne de 0 et une certaine variance. Dans un modèle linéaire où l’effet aléatoire est un décalage d’intercept, cet effet s’additionne aux effets fixes:</p>
<p><span class="math display">\[ y = X \beta + Z b + \epsilon \]</span></p>
<p>où:</p>
<p><span class="math inline">\(Z\)</span> est la matrice du modèle à <span class="math inline">\(n\)</span> observations et <span class="math inline">\(p\)</span> variables aléatoires. Les variables aléatoires sont souvent des variables nominales qui subissent un encodage catégoriel.</p>
<p><span class="math display">\[ Z = \left( \begin{matrix} 
z_{11} &amp; \cdots &amp; z_{1p}  \\ 
z_{21} &amp; \cdots &amp; z_{2p}  \\ 
\vdots &amp; \ddots &amp; \vdots  \\ 
z_{n1} &amp; \cdots &amp; z_{np}
\end{matrix} \right) \]</span></p>
<p><span class="math inline">\(b\)</span> est la matrice des <span class="math inline">\(p\)</span> coefficients aléatoires.</p>
<p><span class="math display">\[ b = \left( \begin{matrix} 
b_0  \\ 
b_1  \\ 
\vdots \\ 
b_p 
\end{matrix} \right) \]</span></p>
<p>Le tableau <code>lasrosas.corn</code>, utilisé précédemment, contenait trois répétitions effectués au cours de deux années, 1999 et 2001. Étant donné que la répétition R1 de 1999 n’a rien à voir avec la répétition R1 de 2001, on dit qu’elle est <strong>emboîtée</strong> dans l’année.</p>
<p>Le module <code>nlme</code> nous aidera à monter notre modèle mixte.</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb381-1" data-line-number="1"><span class="kw">library</span>(<span class="st">&quot;nlme&quot;</span>)</a>
<a class="sourceLine" id="cb381-2" data-line-number="2"></a>
<a class="sourceLine" id="cb381-3" data-line-number="3">mmodlin_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">lme</span>(<span class="dt">fixed =</span> yield <span class="op">~</span><span class="st"> </span>lat <span class="op">+</span><span class="st"> </span>long <span class="op">+</span><span class="st"> </span>nitro <span class="op">+</span><span class="st"> </span>topo <span class="op">+</span><span class="st"> </span>bv,</a>
<a class="sourceLine" id="cb381-4" data-line-number="4">                 <span class="dt">random =</span> <span class="op">~</span><span class="st"> </span><span class="dv">1</span><span class="op">|</span>year<span class="op">/</span>rep,</a>
<a class="sourceLine" id="cb381-5" data-line-number="5">                 <span class="dt">data =</span> lasrosas.corn)</a></code></pre></div>
<p>À ce stade vous devriez commencer à être familier avec l’interface formule et vous deviez saisir l’argument <code>fixed</code>, qui désigne l’effet fixe. L’effet aléatoire, <code>random</code>, suit un tilde <code>~</code>. À gauche de la barre verticale <code>|</code>, on place les variables désignant les effets aléatoire sur la pente. Nous n’avons pas couvert cet aspect, alors nous le laissons à <code>1</code>. À droite, on retrouve un structure d’emboîtement désignant l’effet aléatoire: le premier niveau est l’année, dans laquelle est emboîtée la répétition.</p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb382-1" data-line-number="1"><span class="kw">summary</span>(mmodlin_<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## Linear mixed-effects model fit by REML
##  Data: lasrosas.corn 
##        AIC      BIC    logLik
##   26535.37 26602.93 -13256.69
## 
## Random effects:
##  Formula: ~1 | year
##         (Intercept)
## StdDev:    20.35425
## 
##  Formula: ~1 | rep %in% year
##         (Intercept) Residual
## StdDev:    11.17447 11.35617
## 
## Fixed effects: yield ~ lat + long + nitro + topo + bv 
##                  Value Std.Error   DF    t-value p-value
## (Intercept) -1379436.9  55894.55 3430 -24.679273   0.000
## lat           -25453.0   1016.53 3430 -25.039084   0.000
## long           -8432.3    466.05 3430 -18.092988   0.000
## nitro              0.0      0.00 3430   1.739757   0.082
## topoHT           -27.7      0.92 3430 -30.122438   0.000
## topoLO             6.8      0.88 3430   7.804733   0.000
## topoW            -16.7      1.40 3430 -11.944793   0.000
## bv                -0.5      0.03 3430 -19.242424   0.000
##  Correlation: 
##        (Intr) lat    long   nitro  topoHT topoLO topoW 
## lat     0.897                                          
## long    0.866  0.555                                   
## nitro   0.366  0.391  0.247                            
## topoHT  0.300 -0.017  0.582  0.024                     
## topoLO -0.334 -0.006 -0.621 -0.038 -0.358              
## topoW   0.403 -0.004  0.762  0.027  0.802 -0.545       
## bv     -0.121 -0.012 -0.214 -0.023 -0.467  0.346 -0.266
## 
## Standardized Within-Group Residuals:
##         Min          Q1         Med          Q3         Max 
## -4.32360269 -0.66781575 -0.07450856  0.61587533  3.96434001 
## 
## Number of Observations: 3443
## Number of Groups: 
##          year rep %in% year 
##             2             6</code></pre>
<p>La sortie est semblable à celle de la fonction <code>lm()</code>.</p>
<div id="modeles-mixtes-non-lineaires" class="section level3">
<h3><span class="header-section-number">45.2.1</span> Modèles mixtes non-linéaires</h3>
<p>Le modèle non linéaire créé plus haut liait le rendement à la dose d’azote. Toutefois, les unités expérimentales (le site <code>loc</code> et l’année <code>year</code>) n’étaient pas pris en considération. Nous allons maintenant les considérer.</p>
<p>Nous devons décider la structure de l’effet aléatoire, et sur quelles variables il doit être appliqué - la décision appartient à l’analyste. Il me semble plus convenable de supposer que le site et l’année affectera le rendement maximum plutôt que l’environnement et le taux: les effets aléatoires seront donc affectés à la variable <code>A</code>. Les effets aléatoires n’ont pas de structure d’emboîtement. L’effet de l’année sur A sera celui d’une pente et l’effet de site sera celui de l’intercept. La fonction que nous utiliserons est <code>nlme()</code>.</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb384-1" data-line-number="1">mm &lt;-<span class="st"> </span><span class="kw">nlme</span>(yield <span class="op">~</span><span class="st"> </span>A <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">exp</span>(<span class="op">-</span>R<span class="op">*</span>(E <span class="op">+</span><span class="st"> </span>nitro))),</a>
<a class="sourceLine" id="cb384-2" data-line-number="2">           <span class="dt">data =</span> engelstad.nitro, </a>
<a class="sourceLine" id="cb384-3" data-line-number="3">           <span class="dt">start =</span> <span class="kw">c</span>(<span class="dt">A =</span> <span class="dv">75</span>, <span class="dt">E =</span> <span class="dv">30</span>, <span class="dt">R =</span> <span class="fl">0.02</span>), </a>
<a class="sourceLine" id="cb384-4" data-line-number="4">           <span class="dt">fixed =</span> <span class="kw">list</span>(A <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, E <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, R <span class="op">~</span><span class="st"> </span><span class="dv">1</span>), </a>
<a class="sourceLine" id="cb384-5" data-line-number="5">           <span class="dt">random =</span> A <span class="op">~</span><span class="st"> </span>year <span class="op">|</span><span class="st"> </span>loc)</a>
<a class="sourceLine" id="cb384-6" data-line-number="6"><span class="kw">summary</span>(mm)</a></code></pre></div>
<pre><code>## Nonlinear mixed-effects model fit by maximum likelihood
##   Model: yield ~ A * (1 - exp(-R * (E + nitro))) 
##  Data: engelstad.nitro 
##        AIC     BIC    logLik
##   477.2286 491.889 -231.6143
## 
## Random effects:
##  Formula: A ~ year | loc
##  Structure: General positive-definite, Log-Cholesky parametrization
##               StdDev       Corr  
## A.(Intercept)  2.611534836 A.(In)
## A.year         0.003066832 -0.556
## Residual      11.152757999       
## 
## Fixed effects: list(A ~ 1, E ~ 1, R ~ 1) 
##                  Value Std.Error DF   t-value p-value
## A.(Intercept) 74.58222  4.722715 56 15.792234  0.0000
## E             65.56721 25.533993 56  2.567840  0.0129
## R              0.01308  0.004808 56  2.720215  0.0087
##  Correlation: 
##   A.(In) E     
## E  0.379       
## R -0.483 -0.934
## 
## Standardized Within-Group Residuals:
##         Min          Q1         Med          Q3         Max 
## -1.83373132 -0.89293033  0.07418165  0.68353577  1.82434347 
## 
## Number of Observations: 60
## Number of Groups: 2</code></pre>
<p>Les modèles mixtes non linéaires peuvent devenir très complexes lorsque les paramètres, par exemple A, E et R, sont eux-même affectés linéairement par des variables (par exemple <code>A ~ topo</code>). Pour aller plus loin, consultez <a href="https://doi.org/10.3389/fenvs.2017.00081">Parent et al. (2017)</a> ainsi que les <a href="https://github.com/essicolo/site-specific-multilevel-modeling-of-potato-response-to-nitrogen-fertilization">calculs associés à l’article</a>. Ou écrivez-moi un courriel pour en discuter!</p>
<p><strong>Note</strong>. L’interprétation de p-values sur les modèles mixtes est controversée. À ce sujet, ??? Bates a écrit une longue lettre à la communauté de développement du module <code>lme4</code>, une alternative à <code>nlme</code>, qui remet en cause l’utilisation des p-values, <a href="https://stat.ethz.ch/pipermail/r-help/2006-May/094765.html">ici</a>. De plus en plus, pour les modèles mixtes, on se tourne vers les statistiques bayésiennes, couvertes dans l’annexe de cette section (<code>statitiques_bayes.ipynb</code>, en développement). À cet effet, le module <a href="https://github.com/paul-buerkner/brms"><code>brms</code></a> automatise bien des aspects de la modélisation mixte bayésienne.</p>
</div>
</div>
<div id="aller-plus-loin" class="section level2">
<h2><span class="header-section-number">45.3</span> Aller plus loin</h2>
<div id="statistiques-generales" class="section level3">
<h3><span class="header-section-number">45.3.1</span> Statistiques générales:</h3>
<ul>
<li><a href="https://ariane25.bibl.ulaval.ca/ariane/wicket/detail?c=ariane&amp;m=S&amp;rq.ct=PE&amp;rq.fa=false&amp;rq.r.esc=false&amp;rq.r.l%5B0%5D.c=TI&amp;rq.r.l%5B0%5D.ex=false&amp;rq.r.l%5B0%5D.op=AND&amp;rq.r.l%5B0%5D.v=the+analysis+of+biological+data&amp;rq.r.la=*&amp;rq.r.loc=*&amp;rq.r.pft=true&amp;rq.r.ta=*&amp;rq.r.td=*&amp;rq.rows=5&amp;rq.st=1">The analysis of biological data</a></li>
</ul>
</div>
<div id="statistiques-avec-r" class="section level3">
<h3><span class="header-section-number">45.3.2</span> Statistiques avec R</h3>
<ul>
<li>Disponibles en version électronique à la bibliothèque de l’Université Laval:
<ul>
<li>Introduction aux statistiques avec R: <a href="https://ariane25.bibl.ulaval.ca/ariane/wicket/detail?c=ariane&amp;m=S&amp;rq.ct=PE&amp;rq.fa=false&amp;rq.r.esc=false&amp;rq.r.l%5B0%5D.c=TI&amp;rq.r.l%5B0%5D.ex=false&amp;rq.r.l%5B0%5D.op=AND&amp;rq.r.l%5B0%5D.v=Introductory+statistics+with+R&amp;rq.r.la=*&amp;rq.r.loc=*&amp;rq.r.pft=true&amp;rq.r.ta=*&amp;rq.r.td=*&amp;rq.rows=1&amp;rq.st=0">Introductory statistics with R</a></li>
<li>Approfondir les statistiques avec R: <a href="https://ariane25.bibl.ulaval.ca/ariane/wicket/detail?c=ariane&amp;m=S&amp;rq.ct=PE&amp;rq.fa=false&amp;rq.r.esc=false&amp;rq.r.l%5B0%5D.c=TI&amp;rq.r.l%5B0%5D.ex=false&amp;rq.r.l%5B0%5D.op=AND&amp;rq.r.l%5B0%5D.v=the+r+book&amp;rq.r.la=*&amp;rq.r.loc=*&amp;rq.r.pft=true&amp;rq.r.ta=*&amp;rq.r.td=*&amp;rq.rows=15&amp;rq.st=2">The R Book, Second edition</a></li>
<li>Approfondir les modèles à effets mixtes acec R: <a href="https://ariane25.bibl.ulaval.ca/ariane/wicket/detail?c=ariane&amp;m=S&amp;rq.ct=PE&amp;rq.fa=false&amp;rq.r.esc=false&amp;rq.r.l%5B0%5D.c=TI&amp;rq.r.l%5B0%5D.ex=false&amp;rq.r.l%5B0%5D.op=AND&amp;rq.r.l%5B0%5D.v=Mixed+Effects+Models+and+Extensions+in+Ecology+with+R&amp;rq.r.la=*&amp;rq.r.loc=*&amp;rq.r.pft=false&amp;rq.r.ta=*&amp;rq.r.td=*&amp;rq.rows=2&amp;rq.st=1">Mixed Effects Models and Extensions in Ecology with R</a></li>
</ul></li>
<li><a href="https://moderndive.com/index.html">ModernDive</a>, un livre en ligne offrant une approche moderne avec le package <code>moderndive</code>.</li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="lanalyse-de-variance.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="autoapprentissage.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
