<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Analyse et modélisation d’agroécosystèmes</title>
  <meta name="description" content="Ce cours a pour objectif de former les étudiants gradués en génie agroenvironnemental, génie civil, génie écologique, agronomie, biologie, foresterie et écologie en analyse et modélisation de systèmes vivants. Les sujets traités sont l’introduction au langage de programmation R, l’analyse statistique descriptive, la visualisation, la modélisation inférentielle, prédictive et déterministe." />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Analyse et modélisation d’agroécosystèmes" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Ce cours a pour objectif de former les étudiants gradués en génie agroenvironnemental, génie civil, génie écologique, agronomie, biologie, foresterie et écologie en analyse et modélisation de systèmes vivants. Les sujets traités sont l’introduction au langage de programmation R, l’analyse statistique descriptive, la visualisation, la modélisation inférentielle, prédictive et déterministe." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Analyse et modélisation d’agroécosystèmes" />
  
  <meta name="twitter:description" content="Ce cours a pour objectif de former les étudiants gradués en génie agroenvironnemental, génie civil, génie écologique, agronomie, biologie, foresterie et écologie en analyse et modélisation de systèmes vivants. Les sujets traités sont l’introduction au langage de programmation R, l’analyse statistique descriptive, la visualisation, la modélisation inférentielle, prédictive et déterministe." />
  

<meta name="author" content="Serge-Étienne Parent" />


<meta name="date" content="2020-02-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chapitre-biostats.html"/>
<link rel="next" href="chapitre-explorer.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/viz-1.8.2/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.5/grViz.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#définitions"><i class="fa fa-check"></i><b>1.1</b> Définitions</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#à-qui-sadresse-ce-manuel"><i class="fa fa-check"></i><b>1.2</b> À qui s’adresse ce manuel?</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#les-logiciels-libres"><i class="fa fa-check"></i><b>1.3</b> Les logiciels libres</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#langage-de-programmation"><i class="fa fa-check"></i><b>1.4</b> Langage de programmation</a><ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#r"><i class="fa fa-check"></i><b>1.4.1</b> R</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#pourquoi-pas-python"><i class="fa fa-check"></i><b>1.4.2</b> Pourquoi pas Python?</a></li>
<li class="chapter" data-level="1.4.3" data-path="index.html"><a href="index.html#pourquoi-pas-matlab"><i class="fa fa-check"></i><b>1.4.3</b> Pourquoi pas Matlab?</a></li>
<li class="chapter" data-level="1.4.4" data-path="index.html"><a href="index.html#et-sas"><i class="fa fa-check"></i><b>1.4.4</b> Et… SAS?</a></li>
<li class="chapter" data-level="1.4.5" data-path="index.html"><a href="index.html#mais-pourquoi-pas-______"><i class="fa fa-check"></i><b>1.4.5</b> Mais pourquoi pas ______ ?</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#contenu-du-manuel"><i class="fa fa-check"></i><b>1.5</b> Contenu du manuel</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#objectifs-généraux"><i class="fa fa-check"></i><b>1.6</b> Objectifs généraux</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#lectures-complémentaires"><i class="fa fa-check"></i><b>1.7</b> Lectures complémentaires</a><ul>
<li class="chapter" data-level="1.7.1" data-path="index.html"><a href="index.html#écologie-mathématique"><i class="fa fa-check"></i><b>1.7.1</b> Écologie mathématique</a></li>
<li class="chapter" data-level="1.7.2" data-path="index.html"><a href="index.html#programmation"><i class="fa fa-check"></i><b>1.7.2</b> Programmation</a></li>
<li class="chapter" data-level="1.7.3" data-path="index.html"><a href="index.html#divers"><i class="fa fa-check"></i><b>1.7.3</b> Divers</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#besoin-daide"><i class="fa fa-check"></i><b>1.8</b> Besoin d’aide?</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#à-propos-de-lauteur"><i class="fa fa-check"></i><b>1.9</b> À propos de l’auteur</a></li>
<li class="chapter" data-level="1.10" data-path="index.html"><a href="index.html#un-cours-complémentaire-à-dautres-cours"><i class="fa fa-check"></i><b>1.10</b> Un cours complémentaire à d’autres cours</a></li>
<li class="chapter" data-level="1.11" data-path="index.html"><a href="index.html#contribuer-au-manuel"><i class="fa fa-check"></i><b>1.11</b> Contribuer au manuel</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html"><i class="fa fa-check"></i><b>2</b> La science des données avec R</a><ul>
<li class="chapter" data-level="2.1" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#statistiques-ou-science-des-données"><i class="fa fa-check"></i><b>2.1</b> Statistiques ou science des données?</a></li>
<li class="chapter" data-level="2.2" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#débuter-en-r"><i class="fa fa-check"></i><b>2.2</b> Débuter en R</a></li>
<li class="chapter" data-level="2.3" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#préparer-son-flux-de-travail"><i class="fa fa-check"></i><b>2.3</b> Préparer son flux de travail</a><ul>
<li class="chapter" data-level="2.3.1" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#installation-classique"><i class="fa fa-check"></i><b>2.3.1</b> Installation classique</a></li>
<li class="chapter" data-level="2.3.2" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#installation-avec-anaconda"><i class="fa fa-check"></i><b>2.3.2</b> Installation avec Anaconda</a></li>
<li class="chapter" data-level="2.3.3" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#utilisation-infonuagique"><i class="fa fa-check"></i><b>2.3.3</b> Utilisation infonuagique</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#premiers-pas-avec-r"><i class="fa fa-check"></i><b>2.4</b> Premiers pas avec R</a><ul>
<li class="chapter" data-level="2.4.1" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#types-de-données"><i class="fa fa-check"></i><b>2.4.1</b> Types de données</a></li>
<li class="chapter" data-level="2.4.2" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#les-collections-de-données"><i class="fa fa-check"></i><b>2.4.2</b> Les collections de données</a></li>
<li class="chapter" data-level="2.4.3" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#les-fonctions"><i class="fa fa-check"></i><b>2.4.3</b> Les fonctions</a></li>
<li class="chapter" data-level="2.4.4" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#les-boucles"><i class="fa fa-check"></i><b>2.4.4</b> Les boucles</a></li>
<li class="chapter" data-level="2.4.5" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#conditions-if-else-if-else"><i class="fa fa-check"></i><b>2.4.5</b> Conditions: <code>if</code>, <code>else if</code>, <code>else</code></a></li>
<li class="chapter" data-level="2.4.6" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#installer-et-charger-un-module"><i class="fa fa-check"></i><b>2.4.6</b> Installer et charger un module</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#enfin"><i class="fa fa-check"></i><b>2.5</b> Enfin…</a></li>
<li class="chapter" data-level="2.6" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#petit-truc"><i class="fa fa-check"></i><b>2.6</b> Petit truc!</a></li>
<li class="chapter" data-level="2.7" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#extra-jupyter"><i class="fa fa-check"></i><b>2.7</b> Extra: Utiliser R avec Jupyter</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html"><i class="fa fa-check"></i><b>3</b> Organisation des données et opérations sur des tableaux</a><ul>
<li class="chapter" data-level="3.1" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#les-collections-de-données-1"><i class="fa fa-check"></i><b>3.1</b> Les collections de données</a></li>
<li class="chapter" data-level="3.2" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#organiser-un-tableau-de-données"><i class="fa fa-check"></i><b>3.2</b> Organiser un tableau de données</a></li>
<li class="chapter" data-level="3.3" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#formats-de-tableau"><i class="fa fa-check"></i><b>3.3</b> Formats de tableau</a><ul>
<li class="chapter" data-level="3.3.1" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#xls-ou-xlsx"><i class="fa fa-check"></i><b>3.3.1</b> <em>xls</em> ou <em>xlsx</em></a></li>
<li class="chapter" data-level="3.3.2" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#csv"><i class="fa fa-check"></i><b>3.3.2</b> <em>csv</em></a></li>
<li class="chapter" data-level="3.3.3" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#json"><i class="fa fa-check"></i><b>3.3.3</b> <em>json</em></a></li>
<li class="chapter" data-level="3.3.4" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#sqlite"><i class="fa fa-check"></i><b>3.3.4</b> SQLite</a></li>
<li class="chapter" data-level="3.3.5" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#suggestion"><i class="fa fa-check"></i><b>3.3.5</b> Suggestion</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#entreposer-ses-données"><i class="fa fa-check"></i><b>3.4</b> Entreposer ses données</a></li>
<li class="chapter" data-level="3.5" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#manipuler-des-données-en-mode-tidyverse"><i class="fa fa-check"></i><b>3.5</b> Manipuler des données en mode tidyverse</a><ul>
<li class="chapter" data-level="3.5.1" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#importer-vos-données-dans-votre-session-de-travail"><i class="fa fa-check"></i><b>3.5.1</b> Importer vos données dans votre session de travail</a></li>
<li class="chapter" data-level="3.5.2" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#comment-sélectionner-et-filtrer-des-données"><i class="fa fa-check"></i><b>3.5.2</b> Comment sélectionner et filtrer des données ?</a></li>
<li class="chapter" data-level="3.5.3" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#le-format-long-et-le-format-large"><i class="fa fa-check"></i><b>3.5.3</b> Le format long et le format large</a></li>
<li class="chapter" data-level="3.5.4" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#combiner-des-tableaux"><i class="fa fa-check"></i><b>3.5.4</b> Combiner des tableaux</a></li>
<li class="chapter" data-level="3.5.5" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#opérations-sur-les-tableaux"><i class="fa fa-check"></i><b>3.5.5</b> Opérations sur les tableaux</a></li>
<li class="chapter" data-level="3.5.6" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#exemple-difficile"><i class="fa fa-check"></i><b>3.5.6</b> Exemple (difficile)</a></li>
<li class="chapter" data-level="3.5.7" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#exporter-un-tableau"><i class="fa fa-check"></i><b>3.5.7</b> Exporter un tableau</a></li>
<li class="chapter" data-level="3.5.8" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#aller-plus-loin-dans-le-tidyverse"><i class="fa fa-check"></i><b>3.5.8</b> Aller plus loin dans le tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#références"><i class="fa fa-check"></i><b>3.6</b> Références</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html"><i class="fa fa-check"></i><b>4</b> Visualisation</a><ul>
<li class="chapter" data-level="4.1" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#pourquoi-explorer-graphiquement"><i class="fa fa-check"></i><b>4.1</b> Pourquoi explorer graphiquement?</a></li>
<li class="chapter" data-level="4.2" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#publier-un-graphique"><i class="fa fa-check"></i><b>4.2</b> Publier un graphique</a><ul>
<li class="chapter" data-level="4.2.1" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#cinq-qualités-dun-bon-graphique"><i class="fa fa-check"></i><b>4.2.1</b> Cinq qualités d’un bon graphique</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#choisir-le-type-de-graphique-le-plus-approprié"><i class="fa fa-check"></i><b>4.3</b> Choisir le type de graphique le plus approprié</a></li>
<li class="chapter" data-level="4.4" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#choisir-son-outil-de-visualisation"><i class="fa fa-check"></i><b>4.4</b> Choisir son outil de visualisation</a><ul>
<li class="chapter" data-level="4.4.1" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#approche-impérative"><i class="fa fa-check"></i><b>4.4.1</b> Approche impérative</a></li>
<li class="chapter" data-level="4.4.2" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#approche-déclarative"><i class="fa fa-check"></i><b>4.4.2</b> Approche déclarative</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#visualisation-en-r"><i class="fa fa-check"></i><b>4.5</b> Visualisation en R</a></li>
<li class="chapter" data-level="4.6" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#module-de-base-pour-les-graphiques"><i class="fa fa-check"></i><b>4.6</b> Module de base pour les graphiques</a></li>
<li class="chapter" data-level="4.7" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#la-grammaire-graphique-ggplot2"><i class="fa fa-check"></i><b>4.7</b> La grammaire graphique <strong><code>ggplot2</code></strong></a></li>
<li class="chapter" data-level="4.8" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#mon-premier-ggplot"><i class="fa fa-check"></i><b>4.8</b> Mon premier ggplot</a><ul>
<li class="chapter" data-level="4.8.1" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#plusieurs-sources-de-données"><i class="fa fa-check"></i><b>4.8.1</b> Plusieurs sources de données</a></li>
<li class="chapter" data-level="4.8.2" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#exporter-avec-style"><i class="fa fa-check"></i><b>4.8.2</b> Exporter avec style</a></li>
<li class="chapter" data-level="4.8.3" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#nuages-de-points"><i class="fa fa-check"></i><b>4.8.3</b> Nuages de points</a></li>
<li class="chapter" data-level="4.8.4" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#diagrammes-en-lignes"><i class="fa fa-check"></i><b>4.8.4</b> Diagrammes en lignes</a></li>
<li class="chapter" data-level="4.8.5" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#les-histogrammes"><i class="fa fa-check"></i><b>4.8.5</b> Les histogrammes</a></li>
<li class="chapter" data-level="4.8.6" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#boxplots"><i class="fa fa-check"></i><b>4.8.6</b> Boxplots</a></li>
<li class="chapter" data-level="4.8.7" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#les-diagrammes-en-barre"><i class="fa fa-check"></i><b>4.8.7</b> Les diagrammes en barre</a></li>
<li class="chapter" data-level="4.8.8" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#exporter-un-graphique"><i class="fa fa-check"></i><b>4.8.8</b> Exporter un graphique</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#les-graphiques-comme-outil-dexploration-des-données"><i class="fa fa-check"></i><b>4.9</b> Les graphiques comme outil d’exploration des données</a><ul>
<li class="chapter" data-level="4.9.1" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#des-graphiques-interactifs"><i class="fa fa-check"></i><b>4.9.1</b> Des graphiques interactifs!</a></li>
<li class="chapter" data-level="4.9.2" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#des-extensions-de-ggplot2"><i class="fa fa-check"></i><b>4.9.2</b> Des extensions de <strong><code>ggplot2</code></strong></a></li>
<li class="chapter" data-level="4.9.3" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#aller-plus-loin-avec-ggplot2"><i class="fa fa-check"></i><b>4.9.3</b> Aller plus loin avec <strong><code>ggplot2</code></strong></a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#extra-règles-particulières"><i class="fa fa-check"></i><b>4.10</b> Extra: Règles particulières</a><ul>
<li class="chapter" data-level="4.10.1" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#ne-tronquez-pas-inutilement-laxe-des-y"><i class="fa fa-check"></i><b>4.10.1</b> Ne tronquez pas inutilement l’axe des <span class="math inline">\(y\)</span></a></li>
<li class="chapter" data-level="4.10.2" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#utilisez-un-encrage-proportionnel"><i class="fa fa-check"></i><b>4.10.2</b> Utilisez un encrage proportionnel</a></li>
<li class="chapter" data-level="4.10.3" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#publiez-vos-données"><i class="fa fa-check"></i><b>4.10.3</b> Publiez vos données</a></li>
<li class="chapter" data-level="4.10.4" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#visitez-www.junkcharts.typepad.com-de-temps-à-autre"><i class="fa fa-check"></i><b>4.10.4</b> Visitez www.junkcharts.typepad.com de temps à autre</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chapitre-git.html"><a href="chapitre-git.html"><i class="fa fa-check"></i><b>5</b> Science ouverte et reproductibilité</a><ul>
<li class="chapter" data-level="5.1" data-path="chapitre-git.html"><a href="chapitre-git.html#un-code-reproductible"><i class="fa fa-check"></i><b>5.1</b> Un code reproductible</a><ul>
<li class="chapter" data-level="5.1.1" data-path="chapitre-git.html"><a href="chapitre-git.html#structure-dun-projet"><i class="fa fa-check"></i><b>5.1.1</b> Structure d’un projet</a></li>
<li class="chapter" data-level="5.1.2" data-path="chapitre-git.html"><a href="chapitre-git.html#le-format-r-markdown"><i class="fa fa-check"></i><b>5.1.2</b> Le format <span>R markdown</span></a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="chapitre-git.html"><a href="chapitre-git.html#introduction-à-github"><i class="fa fa-check"></i><b>5.2</b> Introduction à GitHub</a></li>
<li class="chapter" data-level="5.3" data-path="chapitre-git.html"><a href="chapitre-git.html#introduction-à-pakrat"><i class="fa fa-check"></i><b>5.3</b> Introduction à Pakrat 📦🐀</a></li>
<li class="chapter" data-level="5.4" data-path="chapitre-git.html"><a href="chapitre-git.html#pour-terminer-le-reprex"><i class="fa fa-check"></i><b>5.4</b> Pour terminer, le <strong>reprex</strong></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html"><i class="fa fa-check"></i><b>6</b> Biostatistiques</a><ul>
<li class="chapter" data-level="6.1" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#populations-et-échantillons"><i class="fa fa-check"></i><b>6.1</b> Populations et échantillons</a></li>
<li class="chapter" data-level="6.2" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#les-variables"><i class="fa fa-check"></i><b>6.2</b> Les variables</a><ul>
<li class="chapter" data-level="6.2.1" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#variables-quantitatives"><i class="fa fa-check"></i><b>6.2.1</b> Variables quantitatives</a></li>
<li class="chapter" data-level="6.2.2" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#variables-qualitatives"><i class="fa fa-check"></i><b>6.2.2</b> Variables qualitatives</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#les-probabilités"><i class="fa fa-check"></i><b>6.3</b> Les probabilités</a></li>
<li class="chapter" data-level="6.4" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#les-distributions"><i class="fa fa-check"></i><b>6.4</b> Les distributions</a><ul>
<li class="chapter" data-level="6.4.1" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#distribution-binomiale"><i class="fa fa-check"></i><b>6.4.1</b> Distribution binomiale</a></li>
<li class="chapter" data-level="6.4.2" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#distribution-de-poisson"><i class="fa fa-check"></i><b>6.4.2</b> Distribution de Poisson</a></li>
<li class="chapter" data-level="6.4.3" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#distribution-uniforme"><i class="fa fa-check"></i><b>6.4.3</b> Distribution uniforme</a></li>
<li class="chapter" data-level="6.4.4" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#distribution-normale"><i class="fa fa-check"></i><b>6.4.4</b> Distribution normale</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#statistiques-descriptives"><i class="fa fa-check"></i><b>6.5</b> Statistiques descriptives</a></li>
<li class="chapter" data-level="6.6" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#tests-dhypothèses-à-un-et-deux-échantillons"><i class="fa fa-check"></i><b>6.6</b> Tests d’hypothèses à un et deux échantillons</a><ul>
<li class="chapter" data-level="6.6.1" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#test-de-t-à-un-seul-échantillon"><i class="fa fa-check"></i><b>6.6.1</b> Test de t à un seul échantillon</a></li>
<li class="chapter" data-level="6.6.2" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#attention-mauvaises-interprétations-des-p-values"><i class="fa fa-check"></i><b>6.6.2</b> Attention: mauvaises interprétations des <em>p-values</em></a></li>
<li class="chapter" data-level="6.6.3" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#test-de-wilcoxon-à-un-seul-échantillon"><i class="fa fa-check"></i><b>6.6.3</b> Test de Wilcoxon à un seul échantillon</a></li>
<li class="chapter" data-level="6.6.4" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#tests-de-t-à-deux-échantillons"><i class="fa fa-check"></i><b>6.6.4</b> Tests de t à deux échantillons</a></li>
<li class="chapter" data-level="6.6.5" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#comparaison-des-variances"><i class="fa fa-check"></i><b>6.6.5</b> Comparaison des variances</a></li>
<li class="chapter" data-level="6.6.6" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#tests-de-wilcoxon-à-deux-échantillons"><i class="fa fa-check"></i><b>6.6.6</b> Tests de Wilcoxon à deux échantillons</a></li>
<li class="chapter" data-level="6.6.7" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#les-tests-pairés"><i class="fa fa-check"></i><b>6.6.7</b> Les tests pairés</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#lanalyse-de-variance"><i class="fa fa-check"></i><b>6.7</b> L’analyse de variance</a></li>
<li class="chapter" data-level="6.8" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#les-modèles-statistiques"><i class="fa fa-check"></i><b>6.8</b> Les modèles statistiques</a><ul>
<li class="chapter" data-level="6.8.1" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#modèles-à-effets-fixes"><i class="fa fa-check"></i><b>6.8.1</b> Modèles à effets fixes</a></li>
<li class="chapter" data-level="6.8.2" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#modèles-à-effets-mixtes"><i class="fa fa-check"></i><b>6.8.2</b> Modèles à effets mixtes</a></li>
<li class="chapter" data-level="6.8.3" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#aller-plus-loin"><i class="fa fa-check"></i><b>6.8.3</b> Aller plus loin</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html"><i class="fa fa-check"></i><b>7</b> Introduction à l’analyse bayésienne en écologie</a><ul>
<li class="chapter" data-level="7.1" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#quest-ce-que-cest"><i class="fa fa-check"></i><b>7.1</b> Qu’est-ce que c’est?</a></li>
<li class="chapter" data-level="7.2" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#pourquoi-lutiliser"><i class="fa fa-check"></i><b>7.2</b> Pourquoi l’utiliser?</a></li>
<li class="chapter" data-level="7.3" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#comment-lutiliser"><i class="fa fa-check"></i><b>7.3</b> Comment l’utiliser?</a></li>
<li class="chapter" data-level="7.4" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#faucons-pélerins"><i class="fa fa-check"></i><b>7.4</b> Faucons pélerins</a></li>
<li class="chapter" data-level="7.5" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#statistiques-dune-population"><i class="fa fa-check"></i><b>7.5</b> Statistiques d’une population</a><ul>
<li class="chapter" data-level="7.5.1" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#calcul-analytique"><i class="fa fa-check"></i><b>7.5.1</b> Calcul analytique</a></li>
<li class="chapter" data-level="7.5.2" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#greta"><i class="fa fa-check"></i><b>7.5.2</b> greta</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#test-de-t-différence-entre-des-groupes"><i class="fa fa-check"></i><b>7.6</b> Test de t: Différence entre des groupes</a></li>
<li class="chapter" data-level="7.7" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#modélisation-multiniveau"><i class="fa fa-check"></i><b>7.7</b> Modélisation multiniveau</a></li>
<li class="chapter" data-level="7.8" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#pour-aller-plus-loin"><i class="fa fa-check"></i><b>7.8</b> Pour aller plus loin</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html"><i class="fa fa-check"></i><b>8</b> Explorer R</a><ul>
<li class="chapter" data-level="8.1" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#r-sur-le-web"><i class="fa fa-check"></i><b>8.1</b> R sur le web</a><ul>
<li class="chapter" data-level="8.1.1" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#github"><i class="fa fa-check"></i><b>8.1.1</b> GitHub</a></li>
<li class="chapter" data-level="8.1.2" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#twitter"><i class="fa fa-check"></i><b>8.1.2</b> Twitter</a></li>
<li class="chapter" data-level="8.1.3" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#nouvelles"><i class="fa fa-check"></i><b>8.1.3</b> Nouvelles</a></li>
<li class="chapter" data-level="8.1.4" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#des-questions"><i class="fa fa-check"></i><b>8.1.4</b> Des questions?</a></li>
<li class="chapter" data-level="8.1.5" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#participer"><i class="fa fa-check"></i><b>8.1.5</b> Participer</a></li>
<li class="chapter" data-level="8.1.6" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#mise-en-garde"><i class="fa fa-check"></i><b>8.1.6</b> Mise en garde</a></li>
<li class="chapter" data-level="8.1.7" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#prendre-tout-ça-en-note"><i class="fa fa-check"></i><b>8.1.7</b> Prendre tout ça en note</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#r-en-chaire-et-en-os"><i class="fa fa-check"></i><b>8.2</b> R en chaire et en os</a></li>
<li class="chapter" data-level="8.3" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#quelques-outils-en-écologie-mathématique-avec-r"><i class="fa fa-check"></i><b>8.3</b> Quelques outils en écologie mathématique avec R</a><ul>
<li class="chapter" data-level="8.3.1" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#prétraitement-des-données"><i class="fa fa-check"></i><b>8.3.1</b> Prétraitement des données</a></li>
<li class="chapter" data-level="8.3.2" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#acquérir-des-données-météo"><i class="fa fa-check"></i><b>8.3.2</b> Acquérir des données météo</a></li>
<li class="chapter" data-level="8.3.3" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#pédométrie-avec-r"><i class="fa fa-check"></i><b>8.3.3</b> Pédométrie avec R</a></li>
<li class="chapter" data-level="8.3.4" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#méta-analyses-en-r"><i class="fa fa-check"></i><b>8.3.4</b> Méta-analyses en R</a></li>
<li class="chapter" data-level="8.3.5" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#créer-des-applications-avec-r"><i class="fa fa-check"></i><b>8.3.5</b> Créer des applications avec R</a></li>
<li class="chapter" data-level="8.3.6" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#travailler-en-python"><i class="fa fa-check"></i><b>8.3.6</b> Travailler en Python</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html"><i class="fa fa-check"></i><b>9</b> Association, partitionnement et ordination</a><ul>
<li class="chapter" data-level="9.1" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#espaces-danalyse"><i class="fa fa-check"></i><b>9.1</b> Espaces d’analyse</a><ul>
<li class="chapter" data-level="9.1.1" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#abondance-et-occurence"><i class="fa fa-check"></i><b>9.1.1</b> Abondance et occurence</a></li>
<li class="chapter" data-level="9.1.2" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#environnement"><i class="fa fa-check"></i><b>9.1.2</b> Environnement</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#analyse-dassociation"><i class="fa fa-check"></i><b>9.2</b> Analyse d’association</a><ul>
<li class="chapter" data-level="9.2.1" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#association-entre-objets-mode-q"><i class="fa fa-check"></i><b>9.2.1</b> Association entre objets (mode Q)</a></li>
<li class="chapter" data-level="9.2.2" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#associations-entre-variables-mode-r"><i class="fa fa-check"></i><b>9.2.2</b> Associations entre variables (mode R)</a></li>
<li class="chapter" data-level="9.2.3" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#conclusion-sur-les-associations"><i class="fa fa-check"></i><b>9.2.3</b> Conclusion sur les associations</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#partitionnement"><i class="fa fa-check"></i><b>9.3</b> Partitionnement</a><ul>
<li class="chapter" data-level="9.3.1" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#évaluation-dun-partitionnement"><i class="fa fa-check"></i><b>9.3.1</b> Évaluation d’un partitionnement</a></li>
<li class="chapter" data-level="9.3.2" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#partitionnement-non-hiérarchique"><i class="fa fa-check"></i><b>9.3.2</b> Partitionnement non hiérarchique</a></li>
<li class="chapter" data-level="9.3.3" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#partitionnement-hiérarchique"><i class="fa fa-check"></i><b>9.3.3</b> Partitionnement hiérarchique</a></li>
<li class="chapter" data-level="9.3.4" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#partitionnement-hiérarchique-basée-sur-la-densité-des-points"><i class="fa fa-check"></i><b>9.3.4</b> Partitionnement hiérarchique basée sur la densité des points</a></li>
<li class="chapter" data-level="9.3.5" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#conclusion-sur-le-partitionnement"><i class="fa fa-check"></i><b>9.3.5</b> Conclusion sur le partitionnement</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#ordination"><i class="fa fa-check"></i><b>9.4</b> Ordination</a><ul>
<li class="chapter" data-level="9.4.1" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#ordination-non-contraignante"><i class="fa fa-check"></i><b>9.4.1</b> Ordination non contraignante</a></li>
<li class="chapter" data-level="9.4.2" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#ordination-contraignante"><i class="fa fa-check"></i><b>9.4.2</b> Ordination contraignante</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chapitre-outliers.html"><a href="chapitre-outliers.html"><i class="fa fa-check"></i><b>10</b> Détection de valeurs aberrantes et imputation de données manquantes</a><ul>
<li class="chapter" data-level="10.1" data-path="chapitre-outliers.html"><a href="chapitre-outliers.html#données-manquantes-définition-origine-typologie-et-traitement"><i class="fa fa-check"></i><b>10.1</b> Données manquantes: définition, origine, typologie et traitement</a><ul>
<li class="chapter" data-level="10.1.1" data-path="chapitre-outliers.html"><a href="chapitre-outliers.html#définition"><i class="fa fa-check"></i><b>10.1.1</b> Définition</a></li>
<li class="chapter" data-level="10.1.2" data-path="chapitre-outliers.html"><a href="chapitre-outliers.html#origines-des-données-manquantes"><i class="fa fa-check"></i><b>10.1.2</b> Origines des données manquantes</a></li>
<li class="chapter" data-level="10.1.3" data-path="chapitre-outliers.html"><a href="chapitre-outliers.html#profils-des-données-manquantes"><i class="fa fa-check"></i><b>10.1.3</b> Profils des données manquantes</a></li>
<li class="chapter" data-level="10.1.4" data-path="chapitre-outliers.html"><a href="chapitre-outliers.html#traitement-des-données-manquantes"><i class="fa fa-check"></i><b>10.1.4</b> Traitement des données manquantes</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="chapitre-outliers.html"><a href="chapitre-outliers.html#valeurs-et-échantillons-aberrants-définition-origines-méthodes-de-détection-et-traitement"><i class="fa fa-check"></i><b>10.2</b> Valeurs et échantillons aberrants: définition, origines, méthodes de détection et traitement</a><ul>
<li class="chapter" data-level="10.2.1" data-path="chapitre-outliers.html"><a href="chapitre-outliers.html#définitions-1"><i class="fa fa-check"></i><b>10.2.1</b> Définitions</a></li>
<li class="chapter" data-level="10.2.2" data-path="chapitre-outliers.html"><a href="chapitre-outliers.html#origines"><i class="fa fa-check"></i><b>10.2.2</b> Origines</a></li>
<li class="chapter" data-level="10.2.3" data-path="chapitre-outliers.html"><a href="chapitre-outliers.html#détection-et-traitement-des-échantillons-aberrants-multivariés"><i class="fa fa-check"></i><b>10.2.3</b> Détection et traitement des échantillons aberrants multivariés</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chapitre-temps.html"><a href="chapitre-temps.html"><i class="fa fa-check"></i><b>11</b> Les séries temporelles</a><ul>
<li class="chapter" data-level="11.1" data-path="chapitre-temps.html"><a href="chapitre-temps.html#opérations-sur-les-données-temporelles"><i class="fa fa-check"></i><b>11.1</b> Opérations sur les données temporelles</a></li>
<li class="chapter" data-level="11.2" data-path="chapitre-temps.html"><a href="chapitre-temps.html#analyse-de-séries-temporelles"><i class="fa fa-check"></i><b>11.2</b> Analyse de séries temporelles</a><ul>
<li class="chapter" data-level="11.2.1" data-path="chapitre-temps.html"><a href="chapitre-temps.html#créer-et-visualiser-des-séries-temporelles"><i class="fa fa-check"></i><b>11.2.1</b> Créer et visualiser des séries temporelles</a></li>
<li class="chapter" data-level="11.2.2" data-path="chapitre-temps.html"><a href="chapitre-temps.html#structures-dans-les-séries-temporelles"><i class="fa fa-check"></i><b>11.2.2</b> Structures dans les séries temporelles</a></li>
<li class="chapter" data-level="11.2.3" data-path="chapitre-temps.html"><a href="chapitre-temps.html#lautocorrélation"><i class="fa fa-check"></i><b>11.2.3</b> L’autocorrélation</a></li>
<li class="chapter" data-level="11.2.4" data-path="chapitre-temps.html"><a href="chapitre-temps.html#signification-statistique-dune-série-temporelle"><i class="fa fa-check"></i><b>11.2.4</b> Signification statistique d’une série temporelle</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="chapitre-temps.html"><a href="chapitre-temps.html#modélisation-de-séries-temporelles"><i class="fa fa-check"></i><b>11.3</b> Modélisation de séries temporelles</a><ul>
<li class="chapter" data-level="11.3.1" data-path="chapitre-temps.html"><a href="chapitre-temps.html#méthode-naïve"><i class="fa fa-check"></i><b>11.3.1</b> Méthode naïve</a></li>
<li class="chapter" data-level="11.3.2" data-path="chapitre-temps.html"><a href="chapitre-temps.html#méthode-ses"><i class="fa fa-check"></i><b>11.3.2</b> Méthode SES</a></li>
<li class="chapter" data-level="11.3.3" data-path="chapitre-temps.html"><a href="chapitre-temps.html#la-méthode-arima"><i class="fa fa-check"></i><b>11.3.3</b> La méthode ARIMA</a></li>
<li class="chapter" data-level="11.3.4" data-path="chapitre-temps.html"><a href="chapitre-temps.html#les-modèles-dynamiques"><i class="fa fa-check"></i><b>11.3.4</b> Les modèles dynamiques</a></li>
<li class="chapter" data-level="11.3.5" data-path="chapitre-temps.html"><a href="chapitre-temps.html#les-modèles-tbats"><i class="fa fa-check"></i><b>11.3.5</b> Les modèles TBATS</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="chapitre-temps.html"><a href="chapitre-temps.html#pour-terminer"><i class="fa fa-check"></i><b>11.4</b> Pour terminer…</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="chapitre-ml.html"><a href="chapitre-ml.html"><i class="fa fa-check"></i><b>12</b> Introduction à l’autoapprentissage</a><ul>
<li class="chapter" data-level="12.1" data-path="chapitre-ml.html"><a href="chapitre-ml.html#lexique"><i class="fa fa-check"></i><b>12.1</b> Lexique</a></li>
<li class="chapter" data-level="12.2" data-path="chapitre-ml.html"><a href="chapitre-ml.html#démarche"><i class="fa fa-check"></i><b>12.2</b> Démarche</a><ul>
<li class="chapter" data-level="12.2.1" data-path="chapitre-ml.html"><a href="chapitre-ml.html#prétraitement"><i class="fa fa-check"></i><b>12.2.1</b> Prétraitement</a></li>
<li class="chapter" data-level="12.2.2" data-path="chapitre-ml.html"><a href="chapitre-ml.html#entraînement-et-test"><i class="fa fa-check"></i><b>12.2.2</b> Entraînement et test</a></li>
<li class="chapter" data-level="12.2.3" data-path="chapitre-ml.html"><a href="chapitre-ml.html#sousapprentissage-et-surapprentissage"><i class="fa fa-check"></i><b>12.2.3</b> Sousapprentissage et surapprentissage</a></li>
<li class="chapter" data-level="12.2.4" data-path="chapitre-ml.html"><a href="chapitre-ml.html#validation-croisée"><i class="fa fa-check"></i><b>12.2.4</b> Validation croisée</a></li>
<li class="chapter" data-level="12.2.5" data-path="chapitre-ml.html"><a href="chapitre-ml.html#choix-de-lalgorithme-dapprentissage"><i class="fa fa-check"></i><b>12.2.5</b> Choix de l’algorithme d’apprentissage</a></li>
<li class="chapter" data-level="12.2.6" data-path="chapitre-ml.html"><a href="chapitre-ml.html#déploiement"><i class="fa fa-check"></i><b>12.2.6</b> Déploiement</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="chapitre-ml.html"><a href="chapitre-ml.html#lautoapprentissage-en-r"><i class="fa fa-check"></i><b>12.3</b> L’autoapprentissage en R</a></li>
<li class="chapter" data-level="12.4" data-path="chapitre-ml.html"><a href="chapitre-ml.html#algorithmes"><i class="fa fa-check"></i><b>12.4</b> Algorithmes</a><ul>
<li class="chapter" data-level="12.4.1" data-path="chapitre-ml.html"><a href="chapitre-ml.html#les-k-plus-proches-voisins"><i class="fa fa-check"></i><b>12.4.1</b> Les <em>k</em> plus proches voisins</a></li>
<li class="chapter" data-level="12.4.2" data-path="chapitre-ml.html"><a href="chapitre-ml.html#les-arbres-décisionnels"><i class="fa fa-check"></i><b>12.4.2</b> Les arbres décisionnels</a></li>
<li class="chapter" data-level="12.4.3" data-path="chapitre-ml.html"><a href="chapitre-ml.html#les-réseaux-neuronaux"><i class="fa fa-check"></i><b>12.4.3</b> Les réseaux neuronaux</a></li>
<li class="chapter" data-level="12.4.4" data-path="chapitre-ml.html"><a href="chapitre-ml.html#les-processus-gaussiens"><i class="fa fa-check"></i><b>12.4.4</b> Les processus gaussiens</a></li>
<li class="chapter" data-level="12.4.5" data-path="chapitre-ml.html"><a href="chapitre-ml.html#les-processus-gaussiens-en-r"><i class="fa fa-check"></i><b>12.4.5</b> Les processus gaussiens en <code>R</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="chapitre-geo.html"><a href="chapitre-geo.html"><i class="fa fa-check"></i><b>13</b> Les données géospatiales</a><ul>
<li class="chapter" data-level="13.1" data-path="chapitre-geo.html"><a href="chapitre-geo.html#les-données-spatiales"><i class="fa fa-check"></i><b>13.1</b> Les données spatiales</a></li>
<li class="chapter" data-level="13.2" data-path="chapitre-geo.html"><a href="chapitre-geo.html#cartographier-avec-le-module-ggmap"><i class="fa fa-check"></i><b>13.2</b> Cartographier avec le module <strong><code>ggmap</code></strong></a></li>
<li class="chapter" data-level="13.3" data-path="chapitre-geo.html"><a href="chapitre-geo.html#types-génériques-de-données-spatiales"><i class="fa fa-check"></i><b>13.3</b> Types génériques de données spatiales</a></li>
<li class="chapter" data-level="13.4" data-path="chapitre-geo.html"><a href="chapitre-geo.html#les-choroplèthe"><i class="fa fa-check"></i><b>13.4</b> Les choroplèthe</a></li>
<li class="chapter" data-level="13.5" data-path="chapitre-geo.html"><a href="chapitre-geo.html#les-rasters"><i class="fa fa-check"></i><b>13.5</b> Les rasters</a></li>
<li class="chapter" data-level="13.6" data-path="chapitre-geo.html"><a href="chapitre-geo.html#autoapprentissage-spatial"><i class="fa fa-check"></i><b>13.6</b> Autoapprentissage spatial</a></li>
<li class="chapter" data-level="13.7" data-path="chapitre-geo.html"><a href="chapitre-geo.html#les-objets-spatialisés-en-r"><i class="fa fa-check"></i><b>13.7</b> Les objets spatialisés en R</a><ul>
<li class="chapter" data-level="13.7.1" data-path="chapitre-geo.html"><a href="chapitre-geo.html#données-vectorielles-points-lignes-et-polygones"><i class="fa fa-check"></i><b>13.7.1</b> Données vectorielles (points, lignes et polygones)</a></li>
<li class="chapter" data-level="13.7.2" data-path="chapitre-geo.html"><a href="chapitre-geo.html#données-raster"><i class="fa fa-check"></i><b>13.7.2</b> Données raster</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="chapitre-geo.html"><a href="chapitre-geo.html#section-systeme-coord"><i class="fa fa-check"></i><b>13.8</b> Les systèmes de coordonnées</a></li>
<li class="chapter" data-level="13.9" data-path="chapitre-geo.html"><a href="chapitre-geo.html#manipuler-des-tableaux-sf"><i class="fa fa-check"></i><b>13.9</b> Manipuler des tableaux <code>sf</code></a></li>
<li class="chapter" data-level="13.10" data-path="chapitre-geo.html"><a href="chapitre-geo.html#manipuler-des-objets-raster"><i class="fa fa-check"></i><b>13.10</b> Manipuler des objets raster</a></li>
<li class="chapter" data-level="13.11" data-path="chapitre-geo.html"><a href="chapitre-geo.html#graphiques-dobjets-spatialisés"><i class="fa fa-check"></i><b>13.11</b> Graphiques d’objets spatialisés</a></li>
<li class="chapter" data-level="13.12" data-path="chapitre-geo.html"><a href="chapitre-geo.html#ressources-complémentaires"><i class="fa fa-check"></i><b>13.12</b> Ressources complémentaires</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="chapitre-ode.html"><a href="chapitre-ode.html"><i class="fa fa-check"></i><b>14</b> Modélisation de mécanismes écologiques</a><ul>
<li class="chapter" data-level="14.1" data-path="chapitre-ode.html"><a href="chapitre-ode.html#équations-différentielles"><i class="fa fa-check"></i><b>14.1</b> Équations différentielles</a></li>
<li class="chapter" data-level="14.2" data-path="chapitre-ode.html"><a href="chapitre-ode.html#les-équations-différentielles-ordinaires-en-modélisation-écologique"><i class="fa fa-check"></i><b>14.2</b> Les équations différentielles ordinaires en modélisation écologique</a><ul>
<li class="chapter" data-level="14.2.1" data-path="chapitre-ode.html"><a href="chapitre-ode.html#évolution-dune-seule-population-en-fonction-du-temps"><i class="fa fa-check"></i><b>14.2.1</b> Évolution d’une seule population en fonction du temps</a></li>
<li class="chapter" data-level="14.2.2" data-path="chapitre-ode.html"><a href="chapitre-ode.html#population-exploitée"><i class="fa fa-check"></i><b>14.2.2</b> Population exploitée</a></li>
<li class="chapter" data-level="14.2.3" data-path="chapitre-ode.html"><a href="chapitre-ode.html#interactions-biologiques"><i class="fa fa-check"></i><b>14.2.3</b> Interactions biologiques</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analyse et modélisation d’agroécosystèmes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapitre-biostats-bayes" class="section level1">
<h1><span class="header-section-number">7</span> Introduction à l’analyse bayésienne en écologie</h1>
<hr />
<p>️ <strong>Objectifs spécifiques</strong>:</p>
<p><strong>Ce chapitre est un extra. Il ne fait pas partie des objectifs du cours. Il ne sera pas évalué.</strong></p>
<p>À la fin de ce chapitre, vous</p>
<ul>
<li>serez en mesure de définir ce que sont les statistiques bayésiennes</li>
<li>serez en mesure de calculer des statistiques descriptives de base en mode bayésien avec le module <a href="https://greta-stats.org/"><strong><code>greta</code></strong></a>.</li>
</ul>
<hr />
<p>Les statistiques bayésiennes forment une trousse d’outils à garder dans votre <em>packsack</em>.</p>
<div id="quest-ce-que-cest" class="section level2">
<h2><span class="header-section-number">7.1</span> Qu’est-ce que c’est?</h2>
<p>En deux mots: modélisation probabiliste. Un approche de modélisation probabiliste se servant au mieux de l’information disponible. Pour calculer les probabilités d’une variable inconnu en mode bayésien, nous avons besoin:</p>
<ul>
<li>De données</li>
<li>D’un modèle</li>
<li>D’une idée plus ou moins précise du résultat avant d’avoir analysé les données</li>
</ul>
<p>De manière plus formelle, le théorème de Bayes (qui forme la base de l’analyse bayéseienne), dit que la distribution de probabilité des paramètres d’un modèle (par exemple, la moyenne ou une pente) est proportionnelle à la mutliplication de la distribution de probabilité estimée des paramètres et la distribution de probabilité émergeant des données.</p>
<p>Plus formellement,</p>
<p><span class="math display">\[P\left(\theta | y \right) = \frac{P\left(y | \theta \right) \times P\left(\theta\right)}{P\left(y \right)}\]</span>,</p>
<p>où <span class="math inline">\(P\left(\theta | y \right)\)</span> <span class="math inline">\(-\)</span> la probabilité d’obtenir des paramètres <span class="math inline">\(\theta\)</span> à partir des données <span class="math inline">\(y\)</span> <span class="math inline">\(-\)</span> est la distribution de probabilité <em>a posteriori</em>, calculée à partir de votre <em>a prioti</em> <span class="math inline">\(P\left(\theta\right)\)</span> <span class="math inline">\(-\)</span> la probabilité d’obtenir des paramètres <span class="math inline">\(\theta\)</span> sans égard aux données, selon votre connaissance du phénomène <span class="math inline">\(-\)</span> et vos données observées <span class="math inline">\(P\left(y | \theta \right)\)</span> <span class="math inline">\(-\)</span> la probabilité d’obtenir les données <span class="math inline">\(y\)</span> étant donnés les paramètres <span class="math inline">\(\theta\)</span> qui régissent le phénomène. <span class="math inline">\(P\left(y\right)\)</span>, la probabilité d’observer les données, est appellée la <em>vraissemblance marginale</em>, et assure que la somme des probabilités est nulle.</p>
</div>
<div id="pourquoi-lutiliser" class="section level2">
<h2><span class="header-section-number">7.2</span> Pourquoi l’utiliser?</h2>
<p>Avec la notion fréquentielle de probabilité, on teste la probabilité d’observer les données recueillies étant donnée l’absence d’effet réel (qui est l’hypothèse nulle généralement adoptée). La notion bayésienne de probabilité combine la connaissance que l’on a d’un phénomène et les données observées pour estimer la probabilité qu’il existe un effet réel. En d’autre mots, les stats fréquentielles testent si les données concordent avec un modèle du réel, tandis que les stats bayésiennes évaluent, selon les données, la probabilité que le modèle soit réel.</p>
<p>Le hic, c’est que lorsqu’on utilise les statistiques fréquentielles pour répondre à une question bayésienne, on s’expose à de mauvaises interprétations. Par exemple, lors d’un projet considérant la vie sur Mars, les stats fréquentielles évalueront si les données recueillies sont conformes ou non avec l’hypothèse de la vie sur Mars. Par contre, pour évaluer la <em>probabilité de l’existance de vie sur Mars</em>, on devra passer par les stats bayésiennes (exemple tirée du billet <a href="https://dynamicecology.wordpress.com/2011/10/11/frequentist-vs-bayesian-statistics-resources-to-help-you-choose/">Dynamic Ecology – Frequentist vs. Bayesian statistics: resources to help you choose</a>).</p>
</div>
<div id="comment-lutiliser" class="section level2">
<h2><span class="header-section-number">7.3</span> Comment l’utiliser?</h2>
<p>Bien que la formule du théorème de Bayes soit plutôt simple, calculer une fonction <em>a posteriori</em> demandera de passer par des algorithmes de simulation, ce qui pourrait demander une bonne puissance de calcul, et des outils appropriés. R comporte une panoplie d’outils pour le calcul bayésien générique (<a href="https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started"><strong><code>rstan</code></strong></a>, <a href="https://cran.r-project.org/web/packages/rjags/index.html"><strong><code>rjags</code></strong></a>, <a href="https://cran.r-project.org/web/packages/MCMCpack/index.html"><strong><code>MCMCpack</code></strong></a>, etc.), et d’autres outils pour des besoins particuliers (<a href="https://github.com/paul-buerkner/brms"><strong><code>brms</code></strong>: R package for Bayesian generalized multivariate non-linear multilevel models using Stan</a>). Nous utiliserons ici le module générique <a href="https://greta-stats.org/"><strong><code>greta</code></strong></a>, qui permet de générer de manière conviviale plusieurs types de modèles bayésiens.</p>
<p>Pour installer greta, vous devez préalablement installer Python, gréé des modules tensorflow et tensorflow-probability en suivant <a href="https://greta-stats.org/articles/get_started.html">le guide</a>. En somme, vous devez d’abord installer greta (<code>install.packages(&quot;greta&quot;)</code>). Puis vous devez installer une distribution de Python – je vous suggère <a href="https://www.anaconda.com/download">Anaconda</a> (~500 Mo) ou <a href="https://conda.io/miniconda.html">Miniconda</a> pour une installation minimale (~60 Mo). Enfin, lancez les commandes suivantes (une connection internet est nécessaire pour télécharger les modules). Si vous avez installé la version complète d’Anaconda, vous avez accès à Anaconda-navigator, une interface pour la gestion de vos environnements de calcul: assurez-vous qu’il soit fermé pour éviter que la commande se butte à des fichiers verouillés.</p>
<pre><code> greta::install_tensorflow(
    method = &quot;conda&quot;,
    envname = &quot;r-greta&quot;,
    version = &quot;1.14.0&quot;,
    extra_packages = &quot;tensorflow-probability==0.7.0&quot;
  )</code></pre>
</div>
<div id="faucons-pélerins" class="section level2">
<h2><span class="header-section-number">7.4</span> Faucons pélerins</h2>
<p>Empruntons un exemple du livre <a href="https://www.elsevier.com/books/introduction-to-winbugs-for-ecologists/kery/978-0-12-378605-0">Introduction to WinBUGS for Ecologists: A Bayesian Approach to Regression, ANOVA and Related Analyses</a>, de Marc Kéry et examinons la masse de faucons pélerins. Mais alors que Marc Kéry utilise WinBUGS, un logiciel de résolution de problème en mode bayésien, nous utiliserons greta.</p>
<p><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Falco_peregrinus_-_01.jpg/1024px-Falco_peregrinus_-_01.jpg" />
Source: <a href="https://commons.wikimedia.org/wiki/File:Falco_peregrinus_-_01.jpg">Wikimedia Commons</a></p>
<p>Pour une première approche, nous allons estimer la masse moyenne d’une population de faucons pélerins.</p>
<p>À titre de données, générons des nombres aléatoires. Cette stratégie permet de valider les statistiques en les comparant aux paramètre que l’on impose. Ici, nous imposons une moyenne de 600 grammes et un écart-type de 30 grammes. Générons une séries de données avec 20 échantillons.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1"><span class="kw">library</span>(<span class="st">&quot;tidyverse&quot;</span>)</a></code></pre></div>
<pre><code>## ── Attaching packages ───────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.2.1     ✓ purrr   0.3.3
## ✓ tibble  2.1.3     ✓ dplyr   0.8.4
## ✓ tidyr   1.0.2     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.4.0</code></pre>
<pre><code>## ── Conflicts ──────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">5682</span>)</a>
<a class="sourceLine" id="cb6-2" data-line-number="2">y20 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">20</span>, <span class="dt">mean=</span><span class="dv">600</span>, <span class="dt">sd =</span> <span class="dv">30</span>)</a>
<a class="sourceLine" id="cb6-3" data-line-number="3">y200 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">200</span>, <span class="dt">mean=</span><span class="dv">600</span>, <span class="dt">sd =</span> <span class="dv">30</span>)</a>
<a class="sourceLine" id="cb6-4" data-line-number="4"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb6-5" data-line-number="5"><span class="kw">hist</span>(y20, <span class="dt">breaks=</span><span class="dv">5</span>)</a>
<a class="sourceLine" id="cb6-6" data-line-number="6"><span class="kw">hist</span>(y200, <span class="dt">breaks=</span><span class="dv">20</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/bayes-falcon-data-1.png" width="672" /></p>
<p>Je crée une fonction qui retourne la moyenne et l’erreur sur la moyenne ou sur la distribution. Calculons les statistiques classiques.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1">confidence_interval &lt;-<span class="st"> </span><span class="cf">function</span>(x, <span class="dt">on=</span><span class="st">&quot;deviation&quot;</span>, <span class="dt">distribution=</span><span class="st">&quot;t&quot;</span>, <span class="dt">level=</span><span class="fl">0.95</span>) {</a>
<a class="sourceLine" id="cb7-2" data-line-number="2">  m &lt;-<span class="st"> </span><span class="kw">mean</span>(x)</a>
<a class="sourceLine" id="cb7-3" data-line-number="3">  se &lt;-<span class="st"> </span><span class="kw">sd</span>(x)</a>
<a class="sourceLine" id="cb7-4" data-line-number="4">  n &lt;-<span class="st"> </span><span class="kw">length</span>(x)</a>
<a class="sourceLine" id="cb7-5" data-line-number="5">  <span class="cf">if</span> (distribution <span class="op">==</span><span class="st"> &quot;t&quot;</span>) {</a>
<a class="sourceLine" id="cb7-6" data-line-number="6">    error &lt;-<span class="st"> </span>se <span class="op">*</span><span class="st"> </span><span class="kw">qt</span>((<span class="dv">1</span><span class="op">+</span>level)<span class="op">/</span><span class="dv">2</span>, n<span class="dv">-1</span>)</a>
<a class="sourceLine" id="cb7-7" data-line-number="7">  } <span class="cf">else</span> <span class="cf">if</span> (distribution <span class="op">==</span><span class="st"> &quot;normal&quot;</span>) {</a>
<a class="sourceLine" id="cb7-8" data-line-number="8">    error &lt;-<span class="st"> </span>se <span class="op">*</span><span class="st"> </span><span class="kw">qnorm</span>((<span class="dv">1</span><span class="op">+</span>level)<span class="op">/</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb7-9" data-line-number="9">  }</a>
<a class="sourceLine" id="cb7-10" data-line-number="10">  <span class="cf">if</span> (on <span class="op">==</span><span class="st"> &quot;error&quot;</span>) {</a>
<a class="sourceLine" id="cb7-11" data-line-number="11">    error &lt;-<span class="st"> </span>error<span class="op">/</span><span class="kw">sqrt</span>(n)</a>
<a class="sourceLine" id="cb7-12" data-line-number="12">  }</a>
<a class="sourceLine" id="cb7-13" data-line-number="13">  <span class="kw">return</span>(<span class="kw">c</span>(<span class="dt">ll =</span> m<span class="op">-</span>error, <span class="dt">mean =</span> m, <span class="dt">ul =</span> m<span class="op">+</span>error))</a>
<a class="sourceLine" id="cb7-14" data-line-number="14">}</a></code></pre></div>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1"><span class="kw">print</span>(<span class="st">&quot;Déviation, 95%&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Déviation, 95%&quot;</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1"><span class="kw">print</span>(<span class="kw">round</span>(<span class="kw">confidence_interval</span>(y20, <span class="dt">on=</span><span class="st">&#39;deviation&#39;</span>, <span class="dt">level=</span><span class="fl">0.95</span>), <span class="dv">2</span>))</a></code></pre></div>
<pre><code>##     ll   mean     ul 
## 532.23 598.85 665.47</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1"><span class="kw">print</span>(<span class="st">&quot;Erreur, 95%&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Erreur, 95%&quot;</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1"><span class="kw">print</span>(<span class="kw">round</span>(<span class="kw">confidence_interval</span>(y20, <span class="dt">on=</span><span class="st">&#39;error&#39;</span>, <span class="dt">level=</span><span class="fl">0.95</span>), <span class="dv">2</span>))</a></code></pre></div>
<pre><code>##     ll   mean     ul 
## 583.96 598.85 613.75</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1"><span class="kw">print</span>(<span class="st">&quot;Écart-type&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Écart-type&quot;</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"><span class="kw">print</span>(<span class="kw">round</span>(<span class="kw">sd</span>(y20), <span class="dv">2</span>))</a></code></pre></div>
<pre><code>## [1] 31.83</code></pre>
<p>En faisant cela, nous prenons pour acquis que les données sont distribuées normalement. En fait, nous savons qu’elles devraient l’être pour de grands échantillons, puisque nous avons nous-même généré les données. Par contre, comme observateur par exemple de la série de 20 données générées, la distribution est définitivement asymétrique. Sous cet angle, la moyenne, ainsi que l’écart-type, pourraient être des paramètres biaisés. Nous pouvons justifier le choix d’une loi normale par des connaissances a priori des distributions de masse parmi des espèces d’oiseau. Ou bien transformer les données pour rendre leur distribution normale (chapitre <a href="chapitre-explorer.html#chapitre-explorer">8</a>).</p>
</div>
<div id="statistiques-dune-population" class="section level2">
<h2><span class="header-section-number">7.5</span> Statistiques d’une population</h2>
<div id="calcul-analytique" class="section level3">
<h3><span class="header-section-number">7.5.1</span> Calcul analytique</h3>
<p>Supposer une distribution normale d’une population implique d’estimer deux paramètres: sa moyenne et son écart-type. Toutefois, pour cet exemple, nous supposons que l’écart-type est connu, ce qui n’est à toute fin pratique jamais le cas, mais vous découvrirez bientôt pourquoi nous laisse tomber l’écart-type à cette étape. Nous allons donc estimer la moyenne d’une population de faucons dont l’écart-type est de 30: <span class="math inline">\(X \sim \mathcal{N}(\mu, 30)\)</span>.</p>
<p>On sait qu’une distribution normale est définir par la fonction suivante.</p>
<p><span class="math display">\[f(x) = \frac{1}{\sigma \sqrt{2\pi} } e^{-\frac{1}{2}\left(\frac{x-\mu}{\sigma}\right)^2}\]</span></p>
<p>Ou, en R:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1">normdist &lt;-<span class="st"> </span><span class="cf">function</span>(x, mean, sd) {</a>
<a class="sourceLine" id="cb20-2" data-line-number="2">  f &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">/</span><span class="st"> </span>(sd <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">2</span><span class="op">*</span>pi)) <span class="op">*</span><span class="st"> </span><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span><span class="st"> </span>((x<span class="op">-</span>mean)<span class="op">/</span>sd)<span class="op">^</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb20-3" data-line-number="3">  <span class="kw">return</span>(f)</a>
<a class="sourceLine" id="cb20-4" data-line-number="4">}</a></code></pre></div>
<p>Ce qui n’est utile que pour une petite démonstration, étant donnée cette opération peut être effectuée avec la fonction <code>dnorm()</code>, qui vient avec le module <strong><code>stats</code></strong> chargé en R par défaut.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1">x_ &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">2000</span>, <span class="dv">100</span>)</a>
<a class="sourceLine" id="cb21-2" data-line-number="2"><span class="kw">plot</span>(x_, <span class="kw">dnorm</span>(<span class="dt">x =</span> x_, <span class="dt">mean =</span> <span class="dv">750</span>, <span class="dt">sd =</span> <span class="dv">300</span>), <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">4</span>, <span class="dt">col =</span> <span class="st">&quot;pink&quot;</span>)</a>
<a class="sourceLine" id="cb21-3" data-line-number="3"><span class="kw">points</span>(x_, <span class="kw">normdist</span>(<span class="dt">x =</span> x_, <span class="dt">mean =</span> <span class="dv">750</span>, <span class="dt">sd =</span> <span class="dv">300</span>))</a></code></pre></div>
<p><img src="_main_files/figure-html/bayes-normal-distribution-plot-1.png" width="672" /></p>
<p>Reprenons notre équation de Bayes.</p>
<p><span class="math display">\[P\left(\theta | y \right) = \frac{P\left(y | \theta \right) \times P\left(\theta\right)}{P\left(y \right)}\]</span>,</p>
<p>En mode bayésien, nous devons définir la connaissance <em>a priori</em>, P(), sous forme de variables aléatoires non-observées selon une distribution. Prenons l’exemple des faucons pélerins. Disons que nous ne savons pas à quoi ressemble la moyenne du groupe a priori. Nous pouvons utiliser un <em>a priori</em> peu informatif, où la masse moyenne peut prendre n’importe quelle valeur entre 0 et 2000 grammes, sans préférence: nous lui imposons donc un a priori selon une distribution uniforme. Idem pour l’écart-type. C’est ce qu’on appelle des <em>a priori</em> plats. Mais il est plutôt conseiller (<a href="http://www.stat.columbia.edu/~gelman/book/">Gelman et al., 2013</a>) d’utiliser des <em>a priori</em> vagues plutôt que plats ou non-informatifs. En effet, des masses de 0 g ou 2000 g ne sont pas aussi probables qu’une masse de 750 g. Si vous étudiez les faucons pélerins (ce qui n’est pas mon cas), vous aurez une idée de sa masse, ne serait-ce qu’en arcourrant la littérature à son sujet. Mais disons que j’estime très vaguement qu’une masse moyenne échantillonale devrait être autour de 750 g, avec un large écart-type de 200 g sur la moyenne. Il s’agit de l’écart-type de la moyenne, pas de l’écart-type de l’échantillon que nous supposons être connu. Notez que l’<em>a priori</em> peu avoir la forme que l’on désire: il s’agit seulement de créer un vecteur. Toutefois, générer ce vecteur avec des distributions connues est aussi pratique qu’élégant.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1">x_mean &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">400</span>, <span class="dv">1200</span>, <span class="dv">5</span>)</a>
<a class="sourceLine" id="cb22-2" data-line-number="2">prob &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">mass =</span> x_mean, </a>
<a class="sourceLine" id="cb22-3" data-line-number="3">               <span class="dt">Prior =</span> <span class="kw">dnorm</span>(<span class="dt">x =</span> x_mean, <span class="dt">mean =</span> <span class="dv">750</span>, <span class="dt">sd =</span> <span class="dv">200</span>))</a>
<a class="sourceLine" id="cb22-4" data-line-number="4"></a>
<a class="sourceLine" id="cb22-5" data-line-number="5">prob<span class="op">$</span>Prior &lt;-<span class="st"> </span>prob<span class="op">$</span>Prior <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(prob<span class="op">$</span>Prior)</a>
<a class="sourceLine" id="cb22-6" data-line-number="6"></a>
<a class="sourceLine" id="cb22-7" data-line-number="7">prob <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb22-8" data-line-number="8"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(mass, Prior))<span class="op">+</span></a>
<a class="sourceLine" id="cb22-9" data-line-number="9"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb22-10" data-line-number="10"><span class="st">  </span><span class="kw">expand_limits</span>(<span class="dt">y=</span><span class="dv">0</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/bayes-mass-prior-plot-1.png" width="672" /></p>
<p>Note sur le jargon: étant donnée que cet <em>a priori</em> aura la même distribution que l’<em>a posteriori</em>, on dit que cet <em>a priori</em> est <em>conjugué</em>.</p>
<p>Nous allons également utiliser nos données pour créer une fonction de vraissemblance (likelihood), <span class="math inline">\(P\left(y | \theta \right)\)</span>, qui est la distribution de probabilité issue des données: une distribution normale avec une moyenne calculée et une variance connue.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1">prob<span class="op">$</span>Likelihood &lt;-<span class="st"> </span><span class="kw">dnorm</span>(<span class="dt">x =</span> x_mean, <span class="dt">mean =</span> <span class="kw">mean</span>(y20), <span class="dt">sd =</span> <span class="dv">30</span>)</a>
<a class="sourceLine" id="cb23-2" data-line-number="2">prob<span class="op">$</span>Likelihood &lt;-<span class="st"> </span>prob<span class="op">$</span>Likelihood <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(prob<span class="op">$</span>Likelihood)</a>
<a class="sourceLine" id="cb23-3" data-line-number="3"></a>
<a class="sourceLine" id="cb23-4" data-line-number="4">prob <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb23-5" data-line-number="5"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="op">-</span>mass, <span class="dt">names_to =</span> <span class="st">&quot;type&quot;</span>, <span class="dt">values_to =</span> <span class="st">&quot;probability&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb23-6" data-line-number="6"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(mass, probability, <span class="dt">colour =</span> type)) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb23-8" data-line-number="8"><span class="st">  </span><span class="kw">expand_limits</span>(<span class="dt">y=</span><span class="dv">0</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/bayes-mass-likelihood-plot-1.png" width="672" /></p>
<p>Noter distribution <em>a posteriori</em> est proportionnelle à la multiplication de l’<em>a priori</em> et de la vraissemblance. Puis nous allons normaliser l’<em>a posteriori</em> pour faire en sorte que la somme des probabilités soit de 1.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1">prob<span class="op">$</span>Posterior &lt;-<span class="st"> </span>prob<span class="op">$</span>Likelihood <span class="op">*</span><span class="st"> </span>prob<span class="op">$</span>Prior</a>
<a class="sourceLine" id="cb24-2" data-line-number="2">prob<span class="op">$</span>Posterior &lt;-<span class="st"> </span>prob<span class="op">$</span>Posterior <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(prob<span class="op">$</span>Posterior)</a>
<a class="sourceLine" id="cb24-3" data-line-number="3"></a>
<a class="sourceLine" id="cb24-4" data-line-number="4">prob <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb24-5" data-line-number="5"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="op">-</span>mass, <span class="dt">names_to =</span> <span class="st">&quot;type&quot;</span>, <span class="dt">values_to =</span> <span class="st">&quot;probability&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb24-6" data-line-number="6"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(mass, probability, <span class="dt">colour =</span> type)) <span class="op">+</span></a>
<a class="sourceLine" id="cb24-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb24-8" data-line-number="8"><span class="st">  </span><span class="kw">expand_limits</span>(<span class="dt">y=</span><span class="dv">0</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/bayes-mass-posterior-plot-1.png" width="672" /></p>
<p>La distribution <em>a posteriori</em> est presque callée sur les données. Pas étonnant, étant donnée que l’<em>a priori</em> est très vague. En revanche, un <em>a priori</em> plus affirmé, avec un écart-type plus faible, aurait davantage de poids sur l’<em>a posteriori</em>.</p>
<blockquote>
<p><strong>Exercice</strong>. Changez l’<em>a priori</em> et visualisez l’effet sur l’<em>a posteriori</em>.</p>
</blockquote>
<p>Maintenant, imaginez ajouter l’écart-type. Cela reste faisable en calcul analytique, mais ça complique le calcul pour normaliser les proabilité. Ajoutez encore une variable et le calcul bayésien devient un véritable casse-tête. En fait, en bayésien, la difficulté de mettre à l’échelle de plus d’un paramètre rend rare la multiplication distributions de probabilité. C’est pourquoi l’on préfère les simuler et échantillonnant, à l’aide de différents algorithmes, la distribution <em>a posteriori</em>. En R, le module <strong><code>greta</code></strong> est conçu pour cela.</p>
</div>
<div id="greta" class="section level3">
<h3><span class="header-section-number">7.5.2</span> greta</h3>
<p>Chargeons d’abord les modules nécessaires. Avant de charger <strong><code>greta</code></strong>, il faut sélectionner l’environnement conda (Python) auquel se connecter. Lors de l’installation, nous avions spécifié que l’installation se fasse dans l’environnement nommé <code>r-greta</code>.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1">reticulate<span class="op">::</span><span class="kw">use_condaenv</span>(<span class="st">&quot;r-greta&quot;</span>, <span class="dt">required =</span> <span class="ot">TRUE</span>) </a>
<a class="sourceLine" id="cb25-2" data-line-number="2"><span class="kw">library</span>(<span class="st">&quot;greta&quot;</span>)</a></code></pre></div>
<pre><code>## 
## Attaching package: &#39;greta&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     slice</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     binomial, cov2cor, poisson</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     %*%, apply, backsolve, beta, chol2inv, colMeans, colSums, diag,
##     eigen, forwardsolve, gamma, identity, rowMeans, rowSums, sweep,
##     tapply</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1"><span class="kw">library</span>(<span class="st">&quot;DiagrammeR&quot;</span>)</a>
<a class="sourceLine" id="cb30-2" data-line-number="2"><span class="kw">library</span> (<span class="st">&quot;bayesplot&quot;</span>)</a></code></pre></div>
<pre><code>## This is bayesplot version 1.7.1</code></pre>
<pre><code>## - Online documentation and vignettes at mc-stan.org/bayesplot</code></pre>
<pre><code>## - bayesplot theme set to bayesplot::theme_default()</code></pre>
<pre><code>##    * Does _not_ affect other ggplot2 plots</code></pre>
<pre><code>##    * See ?bayesplot_theme_set for details on theme setting</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" data-line-number="1"><span class="kw">library</span>(<span class="st">&quot;tidybayes&quot;</span>)</a></code></pre></div>
<p>Reprenons l’<em>a piori</em> utilisé précédemment. Dans <strong><code>greta</code></strong>, nous définissons notre <em>a priori</em> ainsi.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1">param_mean &lt;-<span class="st"> </span><span class="kw">normal</span>(<span class="dt">mean =</span> <span class="dv">750</span>, <span class="dv">200</span>)</a></code></pre></div>
<p>L’écart-type d’un échantillon ne peut pas être négatif. Il est commun pour les écarts-types d’utiliser une distribution en tronquée à 0. On pourrait utiliser une normale tronquée, mais la cauchy tronquée est souvent recommandée (e.g. <a href="http://www.stat.columbia.edu/~gelman/research/published/taumain.pdf">Gelman, 2006</a>) puisque la queue, plus épaisse que la distribution normale, permet davantage de flexibilité. Disons que nous supposons un écart-type d’une moyenne de 50, et d’un écart-type de 100, tronqué à 0.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1">x_ &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">500</span>, <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb38-2" data-line-number="2"><span class="kw">plot</span>(x_, <span class="kw">dcauchy</span>(<span class="dt">x =</span> x_, <span class="dt">location =</span> <span class="dv">50</span>, <span class="dt">scale =</span> <span class="dv">100</span>), <span class="st">&quot;l&quot;</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/bayes-greta-sd-prior-1.png" width="672" /></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1">param_sd &lt;-<span class="st"> </span><span class="kw">cauchy</span>(<span class="dt">location =</span> <span class="dv">50</span>, <span class="dt">scale =</span> <span class="dv">100</span>, <span class="dt">dim =</span> <span class="ot">NULL</span>, <span class="dt">truncation =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="ot">Inf</span>))</a></code></pre></div>
<p>La fonction <em>a porteriori</em> inclue la fonction de vraissemblance ainsi que la connaissance <em>a priori</em>.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1"><span class="kw">distribution</span>(y20) &lt;-<span class="st"> </span><span class="kw">normal</span>(param_mean, param_sd)</a></code></pre></div>
<p>Le tout forme un modèle pour apprécier la masse des faucons pélerins.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" data-line-number="1">m &lt;-<span class="st"> </span><span class="kw">model</span>(param_mean, param_sd)</a>
<a class="sourceLine" id="cb41-2" data-line-number="2"><span class="kw">plot</span>(m)</a></code></pre></div>
<div id="htmlwidget-ec918378a8d1036e9b2d" style="width:672px;height:480px;" class="grViz html-widget"></div>
<script type="application/json" data-for="htmlwidget-ec918378a8d1036e9b2d">{"x":{"diagram":"digraph {\n\ngraph [layout = \"dot\",\n       outputorder = \"edgesfirst\",\n       bgcolor = \"white\",\n       rankdir = \"LR\"]\n\nnode [fontname = \"Helvetica\",\n      fontsize = \"10\",\n      shape = \"circle\",\n      fixedsize = \"true\",\n      width = \"0.5\",\n      style = \"filled\",\n      fillcolor = \"aliceblue\",\n      color = \"gray70\",\n      fontcolor = \"gray50\"]\n\nedge [fontname = \"Helvetica\",\n     fontsize = \"8\",\n     len = \"1.5\",\n     color = \"gray80\",\n     arrowsize = \"0.5\"]\n\n  \"1\" [label = \"param_mean\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"#E0D2EE\", width = \"0.6\", height = \"0.48\", fillcolor = \"#F4F0F9\"] \n  \"2\" [label = \"normal\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"3\" [label = \"750\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"4\" [label = \"200\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"5\" [label = \"normal\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"6\" [label = \"param_sd\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"#E0D2EE\", width = \"0.6\", height = \"0.48\", fillcolor = \"#F4F0F9\"] \n  \"7\" [label = \"cauchy\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"8\" [label = \"50\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"9\" [label = \"100\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"10\" [label = \"\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n\"1\"->\"5\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"mean\", style = \"solid\"] \n\"2\"->\"1\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"3\"->\"2\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"mean\", style = \"solid\"] \n\"4\"->\"2\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"sd\", style = \"solid\"] \n\"5\"->\"10\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"6\"->\"5\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"sd\", style = \"solid\"] \n\"7\"->\"6\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"8\"->\"7\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"location\", style = \"solid\"] \n\"9\"->\"7\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"scale\", style = \"solid\"] \n}","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
<p><strong>Légende</strong>:</p>
<p><img src="images/5-1_legende.png" /></p>
<p>Le graphique du modèle montre que deux paramètres, <code>praram_sd</code> et <code>param_mean</code> sont attachés à leur distribution respective pour générer une distribution de sortie.</p>
<p>Lançons le modèle avec 2000 échantillons suivant une phase d’initiation (<em>warmup</em>) de 1000 échantillons. La phase d’initiation donne à l’échantillonnage l’occasion de converger avant d’être considérée la la distribution <em>a posteriori</em>. Ces nombres, 2000 et 1000, pourraient être plus élevés. Je les garde bas pour accélérer les calculs.</p>
<p>Le taux d’amincissement, <em>thin</em>, spécifie qu’e l’on ne retient qu’un échantillon sur la valeur indiquée, ce qui permet de contrôler l’autocorrélation dans la chaîne de Markov. Dans ce cas, nous allons utiliser 2. La valeur par défaut est de 1.</p>
<p>L’échantillonnage peut utiliser autant de chaînes de Markov qu’il y a de processeurs sur l’ordinateur.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" data-line-number="1">draws &lt;-<span class="st"> </span><span class="kw">mcmc</span>(m, <span class="dt">n_samples =</span> <span class="dv">2000</span>, <span class="dt">warmup =</span> <span class="dv">1000</span>, <span class="dt">thin =</span> <span class="dv">2</span>, <span class="dt">chains =</span> <span class="dv">4</span>)</a></code></pre></div>
<pre><code>## 
## running 4 chains simultaneously on up to 4 cores</code></pre>
<pre><code>## 
    warmup                                           0/1000 | eta:  ?s          
    warmup ==                                       50/1000 | eta:  1m | 24% bad
    warmup ====                                    100/1000 | eta: 33s | 12% bad
    warmup ======                                  150/1000 | eta: 25s | 8% bad 
    warmup ========                                200/1000 | eta: 21s | 6% bad 
    warmup ==========                              250/1000 | eta: 18s | 5% bad 
    warmup ===========                             300/1000 | eta: 16s | 4% bad 
    warmup =============                           350/1000 | eta: 14s | 4% bad 
    warmup ===============                         400/1000 | eta: 12s | 3% bad 
    warmup =================                       450/1000 | eta: 11s | 3% bad 
    warmup ===================                     500/1000 | eta: 10s | 2% bad 
    warmup =====================                   550/1000 | eta:  9s | 2% bad 
    warmup =======================                 600/1000 | eta:  8s | 2% bad 
    warmup =========================               650/1000 | eta:  7s | 2% bad 
    warmup ===========================             700/1000 | eta:  6s | 2% bad 
    warmup ============================            750/1000 | eta:  5s | 2% bad 
    warmup ==============================          800/1000 | eta:  4s | 2% bad 
    warmup ================================        850/1000 | eta:  3s | 1% bad 
    warmup ==================================      900/1000 | eta:  2s | 1% bad 
    warmup ====================================    950/1000 | eta:  1s | 1% bad 
    warmup ====================================== 1000/1000 | eta:  0s | 1% bad 
## 
  sampling                                           0/2000 | eta:  ?s          
  sampling =                                        50/2000 | eta: 15s          
  sampling ==                                      100/2000 | eta: 15s          
  sampling ===                                     150/2000 | eta: 13s          
  sampling ====                                    200/2000 | eta: 14s          
  sampling =====                                   250/2000 | eta: 13s          
  sampling ======                                  300/2000 | eta: 13s          
  sampling =======                                 350/2000 | eta: 13s          
  sampling ========                                400/2000 | eta: 13s          
  sampling =========                               450/2000 | eta: 12s          
  sampling ==========                              500/2000 | eta: 12s          
  sampling ==========                              550/2000 | eta: 11s          
  sampling ===========                             600/2000 | eta: 11s          
  sampling ============                            650/2000 | eta: 10s          
  sampling =============                           700/2000 | eta: 10s          
  sampling ==============                          750/2000 | eta: 10s          
  sampling ===============                         800/2000 | eta:  9s          
  sampling ================                        850/2000 | eta:  9s          
  sampling =================                       900/2000 | eta:  9s          
  sampling ==================                      950/2000 | eta:  8s          
  sampling ===================                    1000/2000 | eta:  8s          
  sampling ====================                   1050/2000 | eta:  8s          
  sampling =====================                  1100/2000 | eta:  7s          
  sampling ======================                 1150/2000 | eta:  7s          
  sampling =======================                1200/2000 | eta:  6s          
  sampling ========================               1250/2000 | eta:  6s          
  sampling =========================              1300/2000 | eta:  6s          
  sampling ==========================             1350/2000 | eta:  5s          
  sampling ===========================            1400/2000 | eta:  5s          
  sampling ============================           1450/2000 | eta:  4s          
  sampling ============================           1500/2000 | eta:  4s          
  sampling =============================          1550/2000 | eta:  4s          
  sampling ==============================         1600/2000 | eta:  3s          
  sampling ===============================        1650/2000 | eta:  3s          
  sampling ================================       1700/2000 | eta:  2s          
  sampling =================================      1750/2000 | eta:  2s          
  sampling ==================================     1800/2000 | eta:  2s          
  sampling ===================================    1850/2000 | eta:  1s          
  sampling ====================================   1900/2000 | eta:  1s          
  sampling =====================================  1950/2000 | eta:  0s          
  sampling ====================================== 2000/2000 | eta:  0s</code></pre>
<p>L’inspection de l’échantillonnage peut être effectuée grâce au module bayesplot.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" data-line-number="1"><span class="kw">mcmc_combo</span>(draws, <span class="dt">combo =</span> <span class="kw">c</span>(<span class="st">&quot;hist&quot;</span>, <span class="st">&quot;trace&quot;</span>)) <span class="co"># &quot;dens&quot; pour les courbes de densité</span></a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/bayes-greta-plot-simple-1.png" width="672" /></p>
<p>À gauche, nous obtenons la distribution des paramètres. À droite, nous pouvons observer que l’échantillonnage semble stable: la <em>“chenille”</em> est droite avec un bruit constant. Dans le cas où il ne le serait pas, il faudrait revoir le modèle, peut-être en changeatn sa structure ou en changeant les paramètres de convergence. Nous pouvons calculer des intervales de crédibilté.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" data-line-number="1">draws_tidy &lt;-<span class="st"> </span>draws <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb47-2" data-line-number="2"><span class="st">  </span><span class="kw">spread_draws</span>(param_mean, param_sd)</a>
<a class="sourceLine" id="cb47-3" data-line-number="3"></a>
<a class="sourceLine" id="cb47-4" data-line-number="4">draws_mean &lt;-<span class="st"> </span><span class="kw">confidence_interval</span>(<span class="dt">x =</span> draws_tidy<span class="op">$</span>param_mean, <span class="dt">on =</span> <span class="st">&quot;deviation&quot;</span>, <span class="dt">distribution =</span> <span class="st">&quot;normal&quot;</span>, <span class="dt">level =</span> <span class="fl">0.95</span>)</a>
<a class="sourceLine" id="cb47-5" data-line-number="5"><span class="kw">print</span>(<span class="st">&quot;Moyenne:&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Moyenne:&quot;</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" data-line-number="1">draws_mean</a></code></pre></div>
<pre><code>##       ll     mean       ul 
## 583.8359 599.0186 614.2012</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" data-line-number="1">draws_sd &lt;-<span class="st"> </span><span class="kw">confidence_interval</span>(<span class="dt">x =</span> draws_tidy<span class="op">$</span>param_sd, <span class="dt">on =</span> <span class="st">&quot;deviation&quot;</span>, <span class="dt">distribution =</span> <span class="st">&quot;normal&quot;</span>, <span class="dt">level =</span> <span class="fl">0.95</span>)</a>
<a class="sourceLine" id="cb51-2" data-line-number="2"><span class="kw">print</span>(<span class="st">&quot;Écart-type:&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Écart-type:&quot;</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" data-line-number="1">draws_sd</a></code></pre></div>
<pre><code>##       ll     mean       ul 
## 22.17231 34.26929 46.36627</code></pre>
<p>L’<em>a priori</em> étant vague, les résultats de l’analyse bayésienne sont comparables aux statistiques fréquentielles.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" data-line-number="1"><span class="kw">print</span>(<span class="st">&quot;Erreur, 95%&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Erreur, 95%&quot;</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" data-line-number="1"><span class="kw">print</span>(<span class="kw">round</span>(<span class="kw">confidence_interval</span>(y20, <span class="dt">on=</span><span class="st">&#39;error&#39;</span>, <span class="dt">level=</span><span class="fl">0.95</span>), <span class="dv">2</span>))</a></code></pre></div>
<pre><code>##     ll   mean     ul 
## 583.96 598.85 613.75</code></pre>
<p>Les résultats des deux approches doivent néanmoins être interprétés de manière différente. En ce qui a trait à la moyenne:</p>
<ul>
<li><p><strong>Fréquentiel</strong>. Il y a une probabilité de 95% que mes données aient été générées à partir d’une moyenne se situant entre 584 et 614 grammes.</p></li>
<li><p><strong>Bayésien</strong>. Étant donnée mes connaissances (vagues) de la moyenne et de l’écart-type avant de procéder à l’analyse (<em>a priori</em>), il y a une probabilité de 95% que la moyenne de la masse de la population se situe entre 583.8 et 614.2 grammes.</p></li>
</ul>
<p>Nous avons une idée de la distribution des paramètres… mais pas de la masse dans la population. Pas de problème: nous avons des échantillons de moyennes et d’écart-type. Nous pouvons les échantilonnés avec remplacement pour générer des possibilités de distrbution, puis échantillonné une masse selon ces distributions échantillonnées. Disons… 10000?</p>
<div class="figure" style="text-align: center"><span id="fig:starwars10000"></span>
<img src="https://media.giphy.com/media/ZEaHzwGBp2qC0LN9Ye/giphy.gif" alt="Source: Star Wars, a new hope" width="100%" />
<p class="caption">
Figure 7.1: Source: Star Wars, a new hope
</p>
</div>
<p>Yep, 10 000.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" data-line-number="1">n_mass &lt;-<span class="st"> </span><span class="dv">10000</span></a>
<a class="sourceLine" id="cb59-2" data-line-number="2">sim_mass &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, n_mass)</a>
<a class="sourceLine" id="cb59-3" data-line-number="3"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>n_mass) {</a>
<a class="sourceLine" id="cb59-4" data-line-number="4">  sim_mean &lt;-<span class="st"> </span><span class="kw">sample</span>(draws_tidy<span class="op">$</span>param_mean)</a>
<a class="sourceLine" id="cb59-5" data-line-number="5">  sim_sd &lt;-<span class="st"> </span><span class="kw">sample</span>(draws_tidy<span class="op">$</span>param_sd)</a>
<a class="sourceLine" id="cb59-6" data-line-number="6">  sim_mass[i] &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">1</span>, sim_mean, sim_sd)</a>
<a class="sourceLine" id="cb59-7" data-line-number="7">}</a></code></pre></div>
<p>La distribution avec laquelle j’ai créé les données <code>y20</code> plus haut avait une moyenne de 600 et un écart-type de 30. Je la superpose ici avec La distribution modélisée avec notre petit modèle bayésien.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" data-line-number="1">x_ &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">450</span>, <span class="dv">750</span>, <span class="dv">5</span>)</a>
<a class="sourceLine" id="cb60-2" data-line-number="2"><span class="kw">plot</span>(x_, <span class="kw">dnorm</span>(x_, <span class="dv">600</span>, <span class="dv">30</span>), <span class="dt">lty =</span> <span class="dv">3</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;Mass (g)&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Density&quot;</span>)</a>
<a class="sourceLine" id="cb60-3" data-line-number="3"><span class="kw">lines</span>(<span class="kw">density</span>(sim_mass), <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb60-4" data-line-number="4"></a>
<a class="sourceLine" id="cb60-5" data-line-number="5">sim_mass_limits &lt;-<span class="st"> </span><span class="kw">confidence_interval</span>(<span class="dt">x =</span> sim_mass, <span class="dt">on =</span> <span class="st">&quot;deviation&quot;</span>, <span class="dt">distribution =</span> <span class="st">&quot;normal&quot;</span>, <span class="dt">level =</span> <span class="fl">0.95</span>)</a>
<a class="sourceLine" id="cb60-6" data-line-number="6"><span class="kw">abline</span>(<span class="dt">v =</span> sim_mass_limits[<span class="dv">1</span>], <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb60-7" data-line-number="7"><span class="kw">abline</span>(<span class="dt">v =</span> sim_mass_limits[<span class="dv">3</span>], <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb60-8" data-line-number="8"><span class="kw">text</span>(<span class="dt">x =</span> sim_mass_limits[<span class="dv">1</span>], <span class="dt">y =</span> <span class="fl">0.01</span>, <span class="dt">labels =</span> <span class="kw">round</span>(sim_mass_limits[<span class="dv">1</span>]), <span class="dt">pos =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb60-9" data-line-number="9"><span class="kw">text</span>(<span class="dt">x =</span> sim_mass_limits[<span class="dv">3</span>], <span class="dt">y =</span> <span class="fl">0.01</span>, <span class="dt">labels =</span> <span class="kw">round</span>(sim_mass_limits[<span class="dv">3</span>]), <span class="dt">pos =</span> <span class="dv">4</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/bayes-greta-posterior-mass-density-1.png" width="672" /></p>
<p>Raisonnement bayésien: Étant donnée mes connaissances vagues de la moyenne et de l’écart-type avant de procéder à l’analyse, il y a une probabilité de 95% que la masse de la population se situe entre 529.2 et 669.4 grammes.</p>
<p>Nous avons maintenant une idée de la distribution de moyenne de la population. Mais, rarement, une analyse s’arrêtera à ce stade. Il arrive souvent que l’on doive comparer les paramètres de deux, voire plusieurs groupes. Par exemple, comparer des populations vivants dans des écosystèmes différents, ou comparer un traitement à un placébo. Ou bien, comparer, dans une même population de faucons pélerins, l’envergure des ailes des mâles et celle des femelles.</p>
</div>
</div>
<div id="test-de-t-différence-entre-des-groupes" class="section level2">
<h2><span class="header-section-number">7.6</span> Test de t: Différence entre des groupes</h2>
<p>Pour comparer des groupes, on exprime généralement une hypothèse nulle, qui typiquement pose qu’il n’y a pas de différence entre les groupes. Puis, on choisit un test statistique <strong>pour déterminer si les distributions des données observées sont plausibles dans si l’hypothèse nulle est vraie</strong>.</p>
<p>En d’autres mots, le test statistique exprime la probabilité que l’on obtienne les données obtenues s’il n’y avait pas de différence entre les groupes.</p>
<p>Par exemple, si</p>
<ol style="list-style-type: decimal">
<li>vous obtenez une <em>p-value</em> de moins de 0.05 après un test de comparaison et</li>
<li>l’hypothèse nulle pose qu’il n’y a pas de différence entre les groupes,</li>
</ol>
<p>cela signifie qu’il y a une probabilité de 5% que vous ayiez obtenu ces données s’il n’y avait en fait pas de différence entre les groupe. Il serait donc peu probable que vos données euent été générées comme telles s’il n’y avait en fait pas de différence.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" data-line-number="1">n_f &lt;-<span class="st"> </span><span class="dv">30</span></a>
<a class="sourceLine" id="cb61-2" data-line-number="2">moy_f &lt;-<span class="st"> </span><span class="dv">105</span></a>
<a class="sourceLine" id="cb61-3" data-line-number="3">n_m &lt;-<span class="st"> </span><span class="dv">20</span></a>
<a class="sourceLine" id="cb61-4" data-line-number="4">moy_m &lt;-<span class="st"> </span><span class="fl">77.5</span></a>
<a class="sourceLine" id="cb61-5" data-line-number="5">sd_fm &lt;-<span class="st"> </span><span class="fl">2.75</span></a>
<a class="sourceLine" id="cb61-6" data-line-number="6"></a>
<a class="sourceLine" id="cb61-7" data-line-number="7"><span class="kw">set.seed</span>(<span class="dv">21526</span>)</a>
<a class="sourceLine" id="cb61-8" data-line-number="8">envergure_f &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">mean=</span>moy_f, <span class="dt">sd=</span>sd_fm, <span class="dt">n=</span>n_f)</a>
<a class="sourceLine" id="cb61-9" data-line-number="9">envergure_m &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">mean=</span>moy_m, <span class="dt">sd=</span>sd_fm, <span class="dt">n=</span>n_m)</a>
<a class="sourceLine" id="cb61-10" data-line-number="10"></a>
<a class="sourceLine" id="cb61-11" data-line-number="11">envergure_f_df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Sex =</span> <span class="st">&quot;Female&quot;</span>, <span class="dt">Wingspan =</span> envergure_f)</a>
<a class="sourceLine" id="cb61-12" data-line-number="12">envergure_m_df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Sex =</span> <span class="st">&quot;Male&quot;</span>, <span class="dt">Wingspan =</span> envergure_m)</a>
<a class="sourceLine" id="cb61-13" data-line-number="13">envergure_df &lt;-<span class="st"> </span><span class="kw">rbind</span>(envergure_f_df, envergure_m_df)</a>
<a class="sourceLine" id="cb61-14" data-line-number="14"></a>
<a class="sourceLine" id="cb61-15" data-line-number="15">envergure_df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb61-16" data-line-number="16"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Wingspan)) <span class="op">+</span></a>
<a class="sourceLine" id="cb61-17" data-line-number="17"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y=</span>..density.., <span class="dt">fill=</span>Sex)) <span class="op">+</span></a>
<a class="sourceLine" id="cb61-18" data-line-number="18"><span class="st">  </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">value=</span>Sex, <span class="dt">y=</span>..density..))</a></code></pre></div>
<pre><code>## Warning: Ignoring unknown aesthetics: value</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/bayes-greta-model-t-data-1.png" width="672" /></p>
<p>Et les statistiques des deux groupes.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" data-line-number="1">envergure_df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb64-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(Sex) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb64-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(Wingspan),</a>
<a class="sourceLine" id="cb64-4" data-line-number="4">            <span class="dt">sd =</span> <span class="kw">sd</span>(Wingspan),</a>
<a class="sourceLine" id="cb64-5" data-line-number="5">            <span class="dt">n =</span> <span class="kw">n</span>())</a></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   Sex     mean    sd     n
##   &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1 Female 105.   2.46    30
## 2 Male    77.0  3.19    20</code></pre>
<p>Évaluer s’il y a une différence significative peut se faire avec un test de t (ou de Student).</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" data-line-number="1"><span class="kw">t.test</span>(envergure_f, envergure_m)</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  envergure_f and envergure_m
## t = 33.235, df = 33.665, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  26.29232 29.71848
## sample estimates:
## mean of x mean of y 
## 105.04267  77.03727</code></pre>
<p>La probabilité que les données ait été générées de la sorte si les deux groupes n’était semblables est très faible (<code>p-value &lt; 2.2e-16</code>). On obtiendrait sensiblement les mêmes résultats avec une régression linéaire.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" data-line-number="1">linmod &lt;-<span class="st"> </span><span class="kw">lm</span>(Wingspan <span class="op">~</span><span class="st"> </span>Sex, envergure_df)</a>
<a class="sourceLine" id="cb68-2" data-line-number="2"><span class="kw">summary</span>(linmod)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Wingspan ~ Sex, data = envergure_df)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.221 -1.938  0.219  2.046  4.686 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 105.0427     0.5062  207.51   &lt;2e-16 ***
## SexMale     -28.0054     0.8004  -34.99   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.773 on 48 degrees of freedom
## Multiple R-squared:  0.9623, Adjusted R-squared:  0.9615 
## F-statistic:  1224 on 1 and 48 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Le modèle linéaire est plus informatif. Il nous apprend que l’envergure des ailes des mâles est en moyenne plus faible de 28.0 cm que celle des femelles…</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" data-line-number="1"><span class="kw">confint</span>(linmod, <span class="dt">level =</span> <span class="fl">0.95</span>)</a></code></pre></div>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) 104.02487 106.06047
## SexMale     -29.61468 -26.39612</code></pre>
<p>… avec un intervalle de confiance entre -29.6 cm à -26.4 cm.</p>
<p>Utilisons l’information dérivée de statistiques classiques dans nos a priori. Oui-oui, on peut faire ça. Mais attention, un a priori trop précis ou trop collé sur nos données orientera le modèle vers une solution préalablement établie: ce qui constituerait aucune avancée par rapport à l’<em>a priori</em>. Nous allons utiliser a priori pour les deux groupes la moyenne des deux groupes, et comme dispersion la moyenne le double de l’écart-type. Rappelons que cet écart-type est l’a priori de écart-type sur la moyenne, non pas de la population.</p>
<p>Procédons à la création d’un modèle greta. Nous utiliserons la régression linéaire préférablement au test de t.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" data-line-number="1">is_female &lt;-<span class="st"> </span><span class="kw">model.matrix</span>(<span class="op">~</span>envergure_df<span class="op">$</span>Sex)[, <span class="dv">2</span>]</a></code></pre></div>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" data-line-number="1">int &lt;-<span class="st"> </span><span class="kw">normal</span>(<span class="dv">600</span>, <span class="dv">30</span>)</a>
<a class="sourceLine" id="cb73-2" data-line-number="2">coef &lt;-<span class="st"> </span><span class="kw">normal</span>(<span class="dv">30</span>, <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb73-3" data-line-number="3">sd &lt;-<span class="st"> </span><span class="kw">cauchy</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dt">truncation =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="ot">Inf</span>))</a>
<a class="sourceLine" id="cb73-4" data-line-number="4"></a>
<a class="sourceLine" id="cb73-5" data-line-number="5">mu &lt;-<span class="st"> </span>int <span class="op">+</span><span class="st"> </span>coef <span class="op">*</span><span class="st"> </span>is_female</a>
<a class="sourceLine" id="cb73-6" data-line-number="6"></a>
<a class="sourceLine" id="cb73-7" data-line-number="7"><span class="kw">distribution</span>(envergure_df<span class="op">$</span>Wingspan) &lt;-<span class="st"> </span><span class="kw">normal</span>(mu, sd)</a>
<a class="sourceLine" id="cb73-8" data-line-number="8"></a>
<a class="sourceLine" id="cb73-9" data-line-number="9">m &lt;-<span class="st"> </span><span class="kw">model</span>(int, coef, sd, mu)</a>
<a class="sourceLine" id="cb73-10" data-line-number="10"><span class="kw">plot</span>(m)</a></code></pre></div>
<div id="htmlwidget-eae5d38340b4a4d1014d" style="width:672px;height:480px;" class="grViz html-widget"></div>
<script type="application/json" data-for="htmlwidget-eae5d38340b4a4d1014d">{"x":{"diagram":"digraph {\n\ngraph [layout = \"dot\",\n       outputorder = \"edgesfirst\",\n       bgcolor = \"white\",\n       rankdir = \"LR\"]\n\nnode [fontname = \"Helvetica\",\n      fontsize = \"10\",\n      shape = \"circle\",\n      fixedsize = \"true\",\n      width = \"0.5\",\n      style = \"filled\",\n      fillcolor = \"aliceblue\",\n      color = \"gray70\",\n      fontcolor = \"gray50\"]\n\nedge [fontname = \"Helvetica\",\n     fontsize = \"8\",\n     len = \"1.5\",\n     color = \"gray80\",\n     arrowsize = \"0.5\"]\n\n  \"1\" [label = \"int\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"#E0D2EE\", width = \"0.6\", height = \"0.48\", fillcolor = \"#F4F0F9\"] \n  \"2\" [label = \"normal\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"3\" [label = \"600\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"4\" [label = \"30\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"5\" [label = \"mu\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"lightgray\", width = \"0.2\", height = \"0.16\", fillcolor = \"#D3D3D3\"] \n  \"6\" [label = \"normal\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"7\" [label = \"sd\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"#E0D2EE\", width = \"0.6\", height = \"0.48\", fillcolor = \"#F4F0F9\"] \n  \"8\" [label = \"cauchy\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"9\" [label = \"0\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"10\" [label = \"10\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"11\" [label = \"\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"12\" [label = \"\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"lightgray\", width = \"0.2\", height = \"0.16\", fillcolor = \"#D3D3D3\"] \n  \"13\" [label = \"coef\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"#E0D2EE\", width = \"0.6\", height = \"0.48\", fillcolor = \"#F4F0F9\"] \n  \"14\" [label = \"normal\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"15\" [label = \"30\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"16\" [label = \"10\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"17\" [label = \"\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n\"1\"->\"5\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"add\", style = \"solid\"] \n\"2\"->\"1\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"3\"->\"2\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"mean\", style = \"solid\"] \n\"4\"->\"2\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"sd\", style = \"solid\"] \n\"5\"->\"6\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"mean\", style = \"solid\"] \n\"6\"->\"11\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"7\"->\"6\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"sd\", style = \"solid\"] \n\"8\"->\"7\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"9\"->\"8\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"location\", style = \"solid\"] \n\"10\"->\"8\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"scale\", style = \"solid\"] \n\"12\"->\"5\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"add\", style = \"solid\"] \n\"13\"->\"12\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"multiply\", style = \"solid\"] \n\"14\"->\"13\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"15\"->\"14\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"mean\", style = \"solid\"] \n\"16\"->\"14\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"sd\", style = \"solid\"] \n\"17\"->\"12\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"multiply\", style = \"solid\"] \n}","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
<p>Utilisons 1000 échatillons, un warmup de 1000 (par défaut) et un thin de 1 (par défaut), et go!</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" data-line-number="1">draws &lt;-<span class="st"> </span><span class="kw">mcmc</span>(m, <span class="dt">n_samples =</span> <span class="dv">1000</span>)</a></code></pre></div>
<pre><code>## 
## running 4 chains simultaneously on up to 4 cores</code></pre>
<pre><code>## 
    warmup                                           0/1000 | eta:  ?s          
    warmup ==                                       50/1000 | eta:  1m | 18% bad
    warmup ====                                    100/1000 | eta:  1m | 9% bad 
    warmup ======                                  150/1000 | eta: 49s | 6% bad 
    warmup ========                                200/1000 | eta: 41s | 4% bad 
    warmup ==========                              250/1000 | eta: 39s | 4% bad 
    warmup ===========                             300/1000 | eta: 36s | 3% bad 
    warmup =============                           350/1000 | eta: 33s | 3% bad 
    warmup ===============                         400/1000 | eta: 30s | 2% bad 
    warmup =================                       450/1000 | eta: 27s | 2% bad 
    warmup ===================                     500/1000 | eta: 23s | 2% bad 
    warmup =====================                   550/1000 | eta: 20s | 2% bad 
    warmup =======================                 600/1000 | eta: 18s | 2% bad 
    warmup =========================               650/1000 | eta: 15s | 1% bad 
    warmup ===========================             700/1000 | eta: 13s | 1% bad 
    warmup ============================            750/1000 | eta: 11s | 1% bad 
    warmup ==============================          800/1000 | eta:  8s | 1% bad 
    warmup ================================        850/1000 | eta:  6s | 1% bad 
    warmup ==================================      900/1000 | eta:  4s | 1% bad 
    warmup ====================================    950/1000 | eta:  2s | &lt;1% bad
    warmup ====================================== 1000/1000 | eta:  0s | &lt;1% bad
## 
  sampling                                           0/1000 | eta:  ?s          
  sampling ==                                       50/1000 | eta: 19s          
  sampling ====                                    100/1000 | eta: 17s          
  sampling ======                                  150/1000 | eta: 16s          
  sampling ========                                200/1000 | eta: 14s          
  sampling ==========                              250/1000 | eta: 13s          
  sampling ===========                             300/1000 | eta: 12s          
  sampling =============                           350/1000 | eta: 11s          
  sampling ===============                         400/1000 | eta: 10s          
  sampling =================                       450/1000 | eta:  9s          
  sampling ===================                     500/1000 | eta:  8s          
  sampling =====================                   550/1000 | eta:  8s          
  sampling =======================                 600/1000 | eta:  7s          
  sampling =========================               650/1000 | eta:  6s          
  sampling ===========================             700/1000 | eta:  5s          
  sampling ============================            750/1000 | eta:  5s          
  sampling ==============================          800/1000 | eta:  4s          
  sampling ================================        850/1000 | eta:  3s          
  sampling ==================================      900/1000 | eta:  2s          
  sampling ====================================    950/1000 | eta:  1s          
  sampling ====================================== 1000/1000 | eta:  0s</code></pre>
<p>Et les résultats.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" data-line-number="1"><span class="kw">mcmc_combo</span>(draws, <span class="dt">combo =</span> <span class="kw">c</span>(<span class="st">&quot;dens&quot;</span>, <span class="st">&quot;trace&quot;</span>), <span class="dt">pars =</span> <span class="kw">c</span>(<span class="st">&quot;int&quot;</span>, <span class="st">&quot;coef&quot;</span>, <span class="st">&quot;sd&quot;</span>))</a></code></pre></div>
<p><img src="_main_files/figure-html/bayes-greta-model-t-results-1.png" width="672" /></p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" data-line-number="1">draws_tidy &lt;-<span class="st"> </span>draws <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb78-2" data-line-number="2"><span class="st">  </span><span class="kw">spread_draws</span>(int, coef, sd)</a>
<a class="sourceLine" id="cb78-3" data-line-number="3">draws_tidy</a></code></pre></div>
<pre><code>## # A tibble: 4,000 x 6
##    .chain .iteration .draw   int  coef    sd
##     &lt;int&gt;      &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1      1          1     1  104. -26.3  2.57
##  2      1          2     2  105. -27.4  2.57
##  3      1          3     3  105. -27.6  2.77
##  4      1          4     4  106. -28.1  2.42
##  5      1          5     5  105. -27.0  2.69
##  6      1          6     6  105. -28.9  2.78
##  7      1          7     7  106. -28.8  3.15
##  8      1          8     8  105. -27.1  2.67
##  9      1          9     9  104. -26.6  2.74
## 10      1         10    10  105. -27.8  2.87
## # … with 3,990 more rows</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" data-line-number="1"><span class="kw">print</span>(<span class="st">&quot;Intercept:&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Intercept:&quot;</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" data-line-number="1"><span class="kw">confidence_interval</span>(<span class="dt">x =</span> draws_tidy<span class="op">$</span>int, <span class="dt">on =</span> <span class="st">&quot;deviation&quot;</span>, <span class="dt">distribution =</span> <span class="st">&quot;normal&quot;</span>, <span class="dt">level =</span> <span class="fl">0.95</span>)</a></code></pre></div>
<pre><code>##       ll     mean       ul 
## 104.0205 105.0512 106.0819</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb84-1" data-line-number="1"><span class="kw">print</span>(<span class="st">&quot;Pente:&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Pente:&quot;</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" data-line-number="1"><span class="kw">confidence_interval</span>(<span class="dt">x =</span> draws_tidy<span class="op">$</span>coef, <span class="dt">on =</span> <span class="st">&quot;deviation&quot;</span>, <span class="dt">distribution =</span> <span class="st">&quot;normal&quot;</span>, <span class="dt">level =</span> <span class="fl">0.95</span>)</a></code></pre></div>
<pre><code>##        ll      mean        ul 
## -29.41920 -27.77398 -26.12877</code></pre>
</div>
<div id="modélisation-multiniveau" class="section level2">
<h2><span class="header-section-number">7.7</span> Modélisation multiniveau</h2>
<p>Vous souvenez-vous en quoi consiste un effet aléatoire? Pour rappel, il s’agit d’un effet global nul mais variable d’un groupe à l’autre, alors qu’un effet fixe ne subit pas la contrainte d’effet nul. En modélisation linéaire, l’effet aléatoire peut se trouver sur l’intercept ou sur une pente (ou plusieurs pentes). Ce concept peut être porté naturellement en modélisation bayésienne en ajoutant à l’intercept ou à une pente un effet dont l’<em>a priori</em> est une distribution étalée autour de zéro (effet global nul, mais variable).</p>
<p>Reprenons le modèle considéré à la section <a href="chapitre-biostats.html#chapitre-biostats">6</a>.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" data-line-number="1"><span class="kw">data</span>(lasrosas.corn, <span class="dt">package =</span> <span class="st">&quot;agridat&quot;</span>)</a>
<a class="sourceLine" id="cb88-2" data-line-number="2">lasrosas.corn<span class="op">$</span>year_rep &lt;-<span class="st"> </span><span class="kw">paste0</span>(lasrosas.corn<span class="op">$</span>year, <span class="st">&quot;_&quot;</span>, lasrosas.corn<span class="op">$</span>rep)</a>
<a class="sourceLine" id="cb88-3" data-line-number="3"></a>
<a class="sourceLine" id="cb88-4" data-line-number="4">lasrosas.corn_sc &lt;-<span class="st"> </span>lasrosas.corn <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb88-5" data-line-number="5"><span class="st">  </span><span class="kw">select</span>(lat, long, nitro, bv) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb88-6" data-line-number="6"><span class="st">  </span><span class="kw">mutate_all</span>(scale) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb88-7" data-line-number="7"><span class="st">  </span><span class="kw">bind_cols</span>(lasrosas.corn <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="op">-</span>lat, <span class="op">-</span>long, <span class="op">-</span>nitro, <span class="op">-</span>bv)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb88-8" data-line-number="8"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year =</span> <span class="kw">as.factor</span>(year))</a>
<a class="sourceLine" id="cb88-9" data-line-number="9"></a>
<a class="sourceLine" id="cb88-10" data-line-number="10">mmodlin_<span class="dv">1</span> &lt;-<span class="st"> </span>nlme<span class="op">::</span><span class="kw">lme</span>(<span class="dt">fixed =</span> yield <span class="op">~</span><span class="st"> </span>lat <span class="op">+</span><span class="st"> </span>long <span class="op">+</span><span class="st"> </span>nitro <span class="op">+</span><span class="st"> </span>topo <span class="op">+</span><span class="st"> </span>bv,</a>
<a class="sourceLine" id="cb88-11" data-line-number="11">                 <span class="dt">random =</span> <span class="op">~</span><span class="st"> </span><span class="dv">1</span><span class="op">|</span>year<span class="op">/</span>rep,</a>
<a class="sourceLine" id="cb88-12" data-line-number="12">                 <span class="dt">data =</span> lasrosas.corn_sc)</a>
<a class="sourceLine" id="cb88-13" data-line-number="13"><span class="kw">summary</span>(mmodlin_<span class="dv">1</span>)<span class="op">$</span>tTable</a></code></pre></div>
<pre><code>##                   Value  Std.Error   DF    t-value       p-value
## (Intercept)  79.5805716 15.1088003 3430   5.267167  1.470786e-07
## lat         -18.0079499  0.7191936 3430 -25.039084 3.198953e-127
## long        -16.5163635  0.9128599 3430 -18.092988  5.875248e-70
## nitro         0.3662844  0.2105377 3430   1.739757  8.199138e-02
## topoHT      -27.6678268  0.9185122 3430 -30.122438 4.581721e-177
## topoLO        6.8439746  0.8769006 3430   7.804733  7.858215e-15
## topoW       -16.7194235  1.3997249 3430 -11.944793  2.988775e-32
## bv           -4.8456960  0.2518236 3430 -19.242424  1.932870e-78</code></pre>
<p>En <strong><code>greta</code></strong>, nous travaillerons avec une matrice modèle des effets fixes.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" data-line-number="1">corn_modmat &lt;-<span class="st"> </span><span class="kw">model.matrix</span>(<span class="op">~</span>lat <span class="op">+</span><span class="st"> </span>long <span class="op">+</span><span class="st"> </span>nitro <span class="op">+</span><span class="st"> </span>topo <span class="op">+</span><span class="st"> </span>bv, <span class="dt">data =</span> lasrosas.corn_sc)</a>
<a class="sourceLine" id="cb90-2" data-line-number="2"><span class="kw">head</span>(corn_modmat)</a></code></pre></div>
<pre><code>##   (Intercept)        lat      long    nitro topoHT topoLO topoW         bv
## 1           1 -0.3702410 -1.830177 1.571194      0      0     1 -1.2209419
## 2           1 -0.3873435 -1.794005 1.571194      0      0     1 -0.4057786
## 3           1 -0.4044460 -1.757828 1.571194      0      0     1 -0.6227422
## 4           1 -0.4215485 -1.721656 1.571194      0      0     1  0.2337474
## 5           1 -0.4386510 -1.685485 1.571194      0      0     1 -0.3055621
## 6           1 -0.4557535 -1.649313 1.571194      0      0     1 -0.3985465</code></pre>
<p>Nous devons définir nos <em>a priori</em> sur les paramètres du modèle. Nous avons l’intercept, ainsi que les pentes des effets fixes et des effets aléatoires. Nous pourrions créer un <em>a priori</em> par paramètre, ou bien créer un seul jeu d’<em>a priori</em> pour les pentes et l’intercept. Je préfère le séparer.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" data-line-number="1">intercept &lt;-<span class="st"> </span><span class="kw">normal</span>(<span class="dv">0</span>, <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb92-2" data-line-number="2">b_fixed &lt;-<span class="st"> </span><span class="kw">normal</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dt">dim =</span> <span class="dv">7</span>) <span class="co"># pentes effet fixes</span></a></code></pre></div>
<p>Les effets aléatoires fonctionnent en donnant une valeur de décalage par identifiant.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb93-1" data-line-number="1">year_id &lt;-<span class="st"> </span>lasrosas.corn_sc<span class="op">$</span>year</a>
<a class="sourceLine" id="cb93-2" data-line-number="2">year_sd &lt;-<span class="st"> </span><span class="kw">lognormal</span>(<span class="dv">0</span>, <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb93-3" data-line-number="3">year_offset &lt;-<span class="st"> </span><span class="kw">normal</span>(<span class="dv">0</span>, year_sd, <span class="dt">dim =</span> <span class="kw">length</span>(<span class="kw">unique</span>(year_id))<span class="op">-</span><span class="dv">1</span> )</a>
<a class="sourceLine" id="cb93-4" data-line-number="4">year_effect &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="dv">0</span>, year_offset)</a>
<a class="sourceLine" id="cb93-5" data-line-number="5"></a>
<a class="sourceLine" id="cb93-6" data-line-number="6">rep_id &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">as.factor</span>(lasrosas.corn_sc<span class="op">$</span>year_rep))</a>
<a class="sourceLine" id="cb93-7" data-line-number="7">rep_sd &lt;-<span class="st"> </span><span class="kw">lognormal</span>(<span class="dv">0</span>, <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb93-8" data-line-number="8">rep_offset &lt;-<span class="st"> </span><span class="kw">normal</span>(<span class="dv">0</span>, rep_sd, <span class="dt">dim =</span> <span class="kw">length</span>(<span class="kw">unique</span>(rep_id))<span class="op">-</span><span class="dv">1</span> )</a>
<a class="sourceLine" id="cb93-9" data-line-number="9">rep_effect &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="dv">0</span>, rep_offset)</a></code></pre></div>
<p>Le modèle est monté en ajoutant aux effets fixes des valeurs dépendantes de l’année et de la répétition. Dans ce cas, ce sont bien des effets aléatoires sur l’intercept.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" data-line-number="1">mu &lt;-<span class="st"> </span>intercept <span class="op">+</span><span class="st"> </span><span class="co"># intercept du modèle (effet fixe)</span></a>
<a class="sourceLine" id="cb94-2" data-line-number="2"><span class="st">  </span>corn_modmat[, <span class="dv">2</span><span class="op">:</span><span class="dv">8</span>] <span class="op">%*%</span><span class="st"> </span>b_fixed <span class="op">+</span><span class="st"> </span><span class="co"># pentes du modèle (effet fixe)</span></a>
<a class="sourceLine" id="cb94-3" data-line-number="3"><span class="st">  </span>year_effect[year_id] <span class="op">+</span><span class="st"> </span><span class="co"># décalage par année sur l&#39;intercept du modèle (effet aléatoire)</span></a>
<a class="sourceLine" id="cb94-4" data-line-number="4"><span class="st">  </span>rep_effect[rep_id] <span class="co"># décalage par répétition par année sur l&#39;intercept du modèle (effet aléatoire)</span></a>
<a class="sourceLine" id="cb94-5" data-line-number="5">sd &lt;-<span class="st"> </span><span class="kw">cauchy</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dt">truncation =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="ot">Inf</span>)) <span class="co"># a priori sur l&#39;erreur du modèle</span></a>
<a class="sourceLine" id="cb94-6" data-line-number="6"><span class="kw">distribution</span>(lasrosas.corn_sc<span class="op">$</span>yield) &lt;-<span class="st"> </span><span class="kw">normal</span>(mu, sd)</a>
<a class="sourceLine" id="cb94-7" data-line-number="7">m &lt;-<span class="st"> </span><span class="kw">model</span>(intercept, b_fixed, year_effect, rep_effect, sd, mu)</a>
<a class="sourceLine" id="cb94-8" data-line-number="8"><span class="kw">plot</span>(m)</a></code></pre></div>
<div id="htmlwidget-3fdc4e6a0e820f474225" style="width:672px;height:480px;" class="grViz html-widget"></div>
<script type="application/json" data-for="htmlwidget-3fdc4e6a0e820f474225">{"x":{"diagram":"digraph {\n\ngraph [layout = \"dot\",\n       outputorder = \"edgesfirst\",\n       bgcolor = \"white\",\n       rankdir = \"LR\"]\n\nnode [fontname = \"Helvetica\",\n      fontsize = \"10\",\n      shape = \"circle\",\n      fixedsize = \"true\",\n      width = \"0.5\",\n      style = \"filled\",\n      fillcolor = \"aliceblue\",\n      color = \"gray70\",\n      fontcolor = \"gray50\"]\n\nedge [fontname = \"Helvetica\",\n     fontsize = \"8\",\n     len = \"1.5\",\n     color = \"gray80\",\n     arrowsize = \"0.5\"]\n\n  \"1\" [label = \"intercept\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"#E0D2EE\", width = \"0.6\", height = \"0.48\", fillcolor = \"#F4F0F9\"] \n  \"2\" [label = \"normal\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"3\" [label = \"0\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"4\" [label = \"10\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"5\" [label = \"\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"lightgray\", width = \"0.2\", height = \"0.16\", fillcolor = \"#D3D3D3\"] \n  \"6\" [label = \"\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"lightgray\", width = \"0.2\", height = \"0.16\", fillcolor = \"#D3D3D3\"] \n  \"7\" [label = \"mu\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"lightgray\", width = \"0.2\", height = \"0.16\", fillcolor = \"#D3D3D3\"] \n  \"8\" [label = \"normal\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"9\" [label = \"sd\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"#E0D2EE\", width = \"0.6\", height = \"0.48\", fillcolor = \"#F4F0F9\"] \n  \"10\" [label = \"cauchy\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"11\" [label = \"0\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"12\" [label = \"3\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"13\" [label = \"\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"14\" [label = \"\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"lightgray\", width = \"0.2\", height = \"0.16\", fillcolor = \"#D3D3D3\"] \n  \"15\" [label = \"rep_effect\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"lightgray\", width = \"0.2\", height = \"0.16\", fillcolor = \"#D3D3D3\"] \n  \"16\" [label = \"0\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"17\" [label = \"rep_offset\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"#E0D2EE\", width = \"0.6\", height = \"0.48\", fillcolor = \"#F4F0F9\"] \n  \"18\" [label = \"normal\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"19\" [label = \"0\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"20\" [label = \"rep_sd\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"#E0D2EE\", width = \"0.6\", height = \"0.48\", fillcolor = \"#F4F0F9\"] \n  \"21\" [label = \"lognormal\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"22\" [label = \"0\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"23\" [label = \"1\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"24\" [label = \"\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"lightgray\", width = \"0.2\", height = \"0.16\", fillcolor = \"#D3D3D3\"] \n  \"25\" [label = \"year_effect\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"lightgray\", width = \"0.2\", height = \"0.16\", fillcolor = \"#D3D3D3\"] \n  \"26\" [label = \"0\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"27\" [label = \"year_offset\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"#E0D2EE\", width = \"0.6\", height = \"0.48\", fillcolor = \"#F4F0F9\"] \n  \"28\" [label = \"normal\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"29\" [label = \"0\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"30\" [label = \"year_sd\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"#E0D2EE\", width = \"0.6\", height = \"0.48\", fillcolor = \"#F4F0F9\"] \n  \"31\" [label = \"lognormal\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"32\" [label = \"0\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"33\" [label = \"1\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"34\" [label = \"\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"lightgray\", width = \"0.2\", height = \"0.16\", fillcolor = \"#D3D3D3\"] \n  \"35\" [label = \"\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"36\" [label = \"b_fixed\n\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"circle\", color = \"#E0D2EE\", width = \"0.6\", height = \"0.48\", fillcolor = \"#F4F0F9\"] \n  \"37\" [label = \"normal\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"diamond\", color = \"#B797D7\", width = \"1\", height = \"0.8\", fillcolor = \"#E0D2EE\"] \n  \"38\" [label = \"0\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n  \"39\" [label = \"10\", fontcolor = \"#8960B3\", fontsize = \"12\", penwidth = \"2\", shape = \"square\", color = \"#E0D2EE\", width = \"0.5\", height = \"0.4\", fillcolor = \"#FFFFFF\"] \n\"1\"->\"5\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"add\", style = \"solid\"] \n\"2\"->\"1\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"3\"->\"2\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"mean\", style = \"solid\"] \n\"4\"->\"2\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"sd\", style = \"solid\"] \n\"5\"->\"6\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"add\", style = \"solid\"] \n\"6\"->\"7\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"add\", style = \"solid\"] \n\"7\"->\"8\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"mean\", style = \"solid\"] \n\"8\"->\"13\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"9\"->\"8\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"sd\", style = \"solid\"] \n\"10\"->\"9\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"11\"->\"10\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"location\", style = \"solid\"] \n\"12\"->\"10\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"scale\", style = \"solid\"] \n\"14\"->\"7\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"add\", style = \"solid\"] \n\"15\"->\"14\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"extract\", style = \"solid\"] \n\"16\"->\"15\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"rbind\", style = \"solid\"] \n\"17\"->\"15\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"rbind\", style = \"solid\"] \n\"18\"->\"17\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"19\"->\"18\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"mean\", style = \"solid\"] \n\"20\"->\"18\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"sd\", style = \"solid\"] \n\"21\"->\"20\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"22\"->\"21\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"meanlog\", style = \"solid\"] \n\"23\"->\"21\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"sdlog\", style = \"solid\"] \n\"24\"->\"6\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"add\", style = \"solid\"] \n\"25\"->\"24\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"extract\", style = \"solid\"] \n\"26\"->\"25\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"rbind\", style = \"solid\"] \n\"27\"->\"25\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"rbind\", style = \"solid\"] \n\"28\"->\"27\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"29\"->\"28\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"mean\", style = \"solid\"] \n\"30\"->\"28\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"sd\", style = \"solid\"] \n\"31\"->\"30\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"32\"->\"31\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"meanlog\", style = \"solid\"] \n\"33\"->\"31\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"sdlog\", style = \"solid\"] \n\"34\"->\"5\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"add\", style = \"solid\"] \n\"35\"->\"34\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"matrix multiply\", style = \"solid\"] \n\"36\"->\"34\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"matrix multiply\", style = \"solid\"] \n\"37\"->\"36\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", penwidth = \"3\", style = \"dashed\"] \n\"38\"->\"37\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"mean\", style = \"solid\"] \n\"39\"->\"37\" [color = \"Gainsboro\", fontname = \"Helvetica\", fontcolor = \"gray\", fontsize = \"11\", penwidth = \"3\", label = \"sd\", style = \"solid\"] \n}","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
<p>Le modèle peut prendre une minute ou deux à échantillonner.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb95-1" data-line-number="1">draws &lt;-<span class="st"> </span>greta<span class="op">::</span><span class="kw">mcmc</span>(m, <span class="dt">n_samples =</span> <span class="dv">5000</span>, <span class="dt">warmup =</span> <span class="dv">1000</span>, <span class="dt">thin =</span> <span class="dv">10</span>)</a></code></pre></div>
<pre><code>## 
## running 4 chains simultaneously on up to 4 cores</code></pre>
<pre><code>## 
    warmup                                           0/1000 | eta:  ?s          
    warmup ==                                       50/1000 | eta:  5m | 18% bad
    warmup ====                                    100/1000 | eta:  4m | 9% bad 
    warmup ======                                  150/1000 | eta:  3m | 6% bad 
    warmup ========                                200/1000 | eta:  3m | 5% bad 
    warmup ==========                              250/1000 | eta:  2m | 4% bad 
    warmup ===========                             300/1000 | eta:  2m | 3% bad 
    warmup =============                           350/1000 | eta:  2m | 3% bad 
    warmup ===============                         400/1000 | eta:  2m | 2% bad 
    warmup =================                       450/1000 | eta:  2m | 2% bad 
    warmup ===================                     500/1000 | eta:  1m | 2% bad 
    warmup =====================                   550/1000 | eta:  1m | 2% bad 
    warmup =======================                 600/1000 | eta:  1m | 2% bad 
    warmup =========================               650/1000 | eta:  1m | 1% bad 
    warmup ===========================             700/1000 | eta:  1m | 1% bad 
    warmup ============================            750/1000 | eta: 45s | 1% bad 
    warmup ==============================          800/1000 | eta: 37s | 1% bad 
    warmup ================================        850/1000 | eta: 27s | 1% bad 
    warmup ==================================      900/1000 | eta: 18s | 1% bad 
    warmup ====================================    950/1000 | eta:  9s | &lt;1% bad
    warmup ====================================== 1000/1000 | eta:  0s | &lt;1% bad
## 
  sampling                                           0/5000 | eta:  ?s          
  sampling                                          50/5000 | eta:  4m          
  sampling =                                       100/5000 | eta:  5m          
  sampling =                                       150/5000 | eta:  5m          
  sampling ==                                      200/5000 | eta:  6m          
  sampling ==                                      250/5000 | eta:  5m          
  sampling ==                                      300/5000 | eta:  5m          
  sampling ===                                     350/5000 | eta:  4m          
  sampling ===                                     400/5000 | eta:  4m          
  sampling ===                                     450/5000 | eta:  4m          
  sampling ====                                    500/5000 | eta:  4m          
  sampling ====                                    550/5000 | eta:  4m          
  sampling =====                                   600/5000 | eta:  4m          
  sampling =====                                   650/5000 | eta:  4m          
  sampling =====                                   700/5000 | eta:  4m          
  sampling ======                                  750/5000 | eta:  4m          
  sampling ======                                  800/5000 | eta:  4m          
  sampling ======                                  850/5000 | eta:  4m          
  sampling =======                                 900/5000 | eta:  4m          
  sampling =======                                 950/5000 | eta:  4m          
  sampling ========                               1000/5000 | eta:  4m          
  sampling ========                               1050/5000 | eta:  4m          
  sampling ========                               1100/5000 | eta:  4m          
  sampling =========                              1150/5000 | eta:  4m          
  sampling =========                              1200/5000 | eta:  4m          
  sampling ==========                             1250/5000 | eta:  3m          
  sampling ==========                             1300/5000 | eta:  3m          
  sampling ==========                             1350/5000 | eta:  3m          
  sampling ===========                            1400/5000 | eta:  3m          
  sampling ===========                            1450/5000 | eta:  3m          
  sampling ===========                            1500/5000 | eta:  3m          
  sampling ============                           1550/5000 | eta:  3m          
  sampling ============                           1600/5000 | eta:  3m          
  sampling =============                          1650/5000 | eta:  3m          
  sampling =============                          1700/5000 | eta:  3m          
  sampling =============                          1750/5000 | eta:  3m          
  sampling ==============                         1800/5000 | eta:  3m          
  sampling ==============                         1850/5000 | eta:  3m          
  sampling ==============                         1900/5000 | eta:  3m          
  sampling ===============                        1950/5000 | eta:  3m          
  sampling ===============                        2000/5000 | eta:  3m          
  sampling ================                       2050/5000 | eta:  3m          
  sampling ================                       2100/5000 | eta:  3m          
  sampling ================                       2150/5000 | eta:  3m          
  sampling =================                      2200/5000 | eta:  3m          
  sampling =================                      2250/5000 | eta:  3m          
  sampling =================                      2300/5000 | eta:  3m          
  sampling ==================                     2350/5000 | eta:  3m          
  sampling ==================                     2400/5000 | eta:  3m          
  sampling ===================                    2450/5000 | eta:  3m          
  sampling ===================                    2500/5000 | eta:  2m          
  sampling ===================                    2550/5000 | eta:  2m          
  sampling ====================                   2600/5000 | eta:  2m          
  sampling ====================                   2650/5000 | eta:  2m          
  sampling =====================                  2700/5000 | eta:  2m          
  sampling =====================                  2750/5000 | eta:  2m          
  sampling =====================                  2800/5000 | eta:  2m          
  sampling ======================                 2850/5000 | eta:  2m          
  sampling ======================                 2900/5000 | eta:  2m          
  sampling ======================                 2950/5000 | eta:  2m          
  sampling =======================                3000/5000 | eta:  2m          
  sampling =======================                3050/5000 | eta:  2m          
  sampling ========================               3100/5000 | eta:  2m          
  sampling ========================               3150/5000 | eta:  2m          
  sampling ========================               3200/5000 | eta:  2m          
  sampling =========================              3250/5000 | eta:  2m          
  sampling =========================              3300/5000 | eta:  2m          
  sampling =========================              3350/5000 | eta:  2m          
  sampling ==========================             3400/5000 | eta:  2m          
  sampling ==========================             3450/5000 | eta:  2m          
  sampling ===========================            3500/5000 | eta:  2m          
  sampling ===========================            3550/5000 | eta:  2m          
  sampling ===========================            3600/5000 | eta:  1m          
  sampling ============================           3650/5000 | eta:  1m          
  sampling ============================           3700/5000 | eta:  1m          
  sampling ============================           3750/5000 | eta:  1m          
  sampling =============================          3800/5000 | eta:  1m          
  sampling =============================          3850/5000 | eta:  1m          
  sampling ==============================         3900/5000 | eta:  1m          
  sampling ==============================         3950/5000 | eta:  1m          
  sampling ==============================         4000/5000 | eta:  1m          
  sampling ===============================        4050/5000 | eta:  1m          
  sampling ===============================        4100/5000 | eta:  1m          
  sampling ================================       4150/5000 | eta:  1m          
  sampling ================================       4200/5000 | eta: 49s          
  sampling ================================       4250/5000 | eta: 46s          
  sampling =================================      4300/5000 | eta: 43s          
  sampling =================================      4350/5000 | eta: 40s          
  sampling =================================      4400/5000 | eta: 37s          
  sampling ==================================     4450/5000 | eta: 34s          
  sampling ==================================     4500/5000 | eta: 31s          
  sampling ===================================    4550/5000 | eta: 27s          
  sampling ===================================    4600/5000 | eta: 24s          
  sampling ===================================    4650/5000 | eta: 21s          
  sampling ====================================   4700/5000 | eta: 18s          
  sampling ====================================   4750/5000 | eta: 15s          
  sampling ====================================   4800/5000 | eta: 12s          
  sampling =====================================  4850/5000 | eta:  9s          
  sampling =====================================  4900/5000 | eta:  6s          
  sampling ====================================== 4950/5000 | eta:  3s          
  sampling ====================================== 5000/5000 | eta:  0s</code></pre>
<p>Nous pouvons soutirer l’intercept.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb98-1" data-line-number="1"><span class="kw">mcmc_combo</span>(draws, <span class="dt">combo =</span> <span class="kw">c</span>(<span class="st">&quot;hist&quot;</span>, <span class="st">&quot;trace&quot;</span>), <span class="dt">regex_pars =</span> <span class="st">&quot;intercept&quot;</span>)</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/bayes-greta-mm-intercept-1.png" width="672" /></p>
<p>Et les coefficients des effets fixes.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb100-1" data-line-number="1"><span class="kw">mcmc_combo</span>(draws, <span class="dt">combo =</span> <span class="kw">c</span>(<span class="st">&quot;hist&quot;</span>, <span class="st">&quot;trace&quot;</span>), <span class="dt">regex_pars =</span> <span class="st">&quot;b_fixed</span><span class="ch">\\</span><span class="st">[[.[1234567]&quot;</span>)</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/bayes-greta-mm-b_fixed-1.png" width="672" /></p>
<p>L’intercept et les coefficients semblent avoir été bien échantillonnés. Les intervalles de confiance peuvent être présenter ainsi.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb102-1" data-line-number="1"><span class="kw">mcmc_intervals</span>(draws, <span class="dt">pars =</span> <span class="kw">paste0</span>(<span class="st">&quot;b_fixed[&quot;</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">7</span>, <span class="st">&quot;,1]&quot;</span>))</a></code></pre></div>
<p><img src="_main_files/figure-html/bayes-greta-mm-b-intervals-1.png" width="672" /></p>
<p>Ou encore mieux, nous pouvons tirer profit des statistiques bayésiennes pour les représenter sous forme de distributions.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb103-1" data-line-number="1"><span class="kw">mcmc_areas</span>(draws, <span class="dt">pars =</span> <span class="kw">paste0</span>(<span class="st">&quot;b_fixed[&quot;</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">7</span>, <span class="st">&quot;,1]&quot;</span>))</a></code></pre></div>
<p><img src="_main_files/figure-html/bayes-greta-mm-b-distributions-1.png" width="672" /></p>
<p>Il y a des manières plus élégantes d’extraire les valeurs, mais j’y vais de manière plus brutale. J’extrais les échantillonnages des coefficients <code>b_fixed</code> avec la fonction <code>calculate()</code>.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb104-1" data-line-number="1">b_calc &lt;-<span class="st"> </span>b_fixed <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb104-2" data-line-number="2"><span class="st">  </span><span class="kw">calculate</span>(draws)</a></code></pre></div>
<p>Le résultat, <code>b_calc</code>, est une liste des échantillons par chaîne de Markov. La première ligne du prochain bloc de code permet d’effectuer une moyenne des matrices élément par élément. Ensuite, j’effectue des opérations en chaîne pour en soutirer moyennes et intervalles (en utilisant une fonction définie peécédemment dans ce chapitre).</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb105-1" data-line-number="1">b_calc_chainmean &lt;-<span class="st"> </span><span class="kw">apply</span>(<span class="kw">simplify2array</span>(b_calc), <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>, mean) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">as_tibble</span>()</a>
<a class="sourceLine" id="cb105-2" data-line-number="2"></a>
<a class="sourceLine" id="cb105-3" data-line-number="3">b_calc_chainmean <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb105-4" data-line-number="4"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> <span class="kw">everything</span>()) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb105-5" data-line-number="5"><span class="st">  </span><span class="kw">group_by</span>(name) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb105-6" data-line-number="6"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(value),</a>
<a class="sourceLine" id="cb105-7" data-line-number="7">            <span class="dt">ll =</span> <span class="kw">confidence_interval</span>(value)[<span class="dv">1</span>],</a>
<a class="sourceLine" id="cb105-8" data-line-number="8">            <span class="dt">ul =</span> <span class="kw">confidence_interval</span>(value)[<span class="dv">3</span>])</a></code></pre></div>
<pre><code>## # A tibble: 7 x 4
##   name      mean      ll      ul
##   &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1 .[1,1] -18.1   -18.7   -17.4  
## 2 .[2,1] -16.0   -16.8   -15.2  
## 3 .[3,1]   0.366   0.161   0.571
## 4 .[4,1] -27.0   -27.8   -26.1  
## 5 .[5,1]   6.51    5.70    7.32 
## 6 .[6,1] -15.6   -16.9   -14.3  
## 7 .[7,1]  -4.91   -5.15   -4.66</code></pre>
<p>Visualisons maintenant les effets aléatoires par année.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb107-1" data-line-number="1"><span class="kw">mcmc_combo</span>(draws, <span class="dt">combo =</span> <span class="kw">c</span>(<span class="st">&quot;hist&quot;</span>, <span class="st">&quot;trace&quot;</span>), <span class="dt">regex_pars =</span> <span class="st">&quot;year_effect.&quot;</span>)</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/bayes-greta-mm-plot-ranef-year-1.png" width="672" /></p>
<p>Et par répétition.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" data-line-number="1"><span class="kw">mcmc_combo</span>(draws, <span class="dt">combo =</span> <span class="kw">c</span>(<span class="st">&quot;hist&quot;</span>, <span class="st">&quot;trace&quot;</span>), <span class="dt">regex_pars =</span> <span class="st">&quot;rep_effect.&quot;</span>)</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/bayes-greta-mm-plot-ranef-rep-1.png" width="672" /></p>
</div>
<div id="pour-aller-plus-loin" class="section level2">
<h2><span class="header-section-number">7.8</span> Pour aller plus loin</h2>
<p>Le module <strong><code>greta</code></strong> est conçu et maintenu par <a href="https://github.com/goldingn">Nick Golding</a>, du Quantitative &amp; Applied Ecology Group de l’University of Melbourne, Australie. La <a href="https://greta-stats.org/">documentation de greta</a> offre des <a href="https://greta-stats.org/articles/example_models.html">recettes</a> pour toutes sortes d’analyses en écologie.</p>
<p>Les livres de Mark Kéry, bien que rédigés pour les calculs en langage R et WinBUGS, offre une approche bien structurée et traduisible en <strong><code>greta</code></strong>, qui est plus moderne que WinBUGS.</p>
<ul>
<li><a href="https://www.amazon.com/Introduction-WinBUGS-Ecologists-Bayesian-regression/dp/0123786053">Introduction to WinBUGS for Ecologists (2010)</a></li>
<li><a href="https://www.amazon.com/Bayesian-Population-Analysis-using-WinBUGS/dp/0123870208">Bayesian Population Analysis using WinBUGS: A Hierarchical Perspective (2011)</a></li>
<li><a href="https://www.amazon.com/Applied-Hierarchical-Modeling-Ecology-distribution/dp/0128013788">Applied Hierarchical Modeling in Ecology: Analysis of distribution, abundance and species richness in R and BUGS (2015)</a></li>
</ul>
<p>Enfin, si comme moi vous aimez vous dérouiller en Python, le module PyMC3 est très bien documenté, en particulier dans le livre gratuit <a href="http://camdavidsonpilon.github.io/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/"><em>Probabilistic Programming &amp; Bayesian Methods for Hackers</em></a>, de Cam Davidson-Pilon.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chapitre-biostats.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chapitre-explorer.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
