<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>8 Association, partitionnement et ordination | Analyse et modélisation d’agroécosystèmes</title>
  <meta name="description" content="Ce cours a pour objectif de former les étudiants gradués en génie agroenvironnemental, génie civil, génie écologique, agronomie, biologie, foresterie et écologie en analyse et modélisation de systèmes vivants. Les sujets traités sont l’introduction au langage de programmation R, l’analyse statistique descriptive, la visualisation, la modélisation inférentielle, prédictive et déterministe.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="8 Association, partitionnement et ordination | Analyse et modélisation d’agroécosystèmes" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Ce cours a pour objectif de former les étudiants gradués en génie agroenvironnemental, génie civil, génie écologique, agronomie, biologie, foresterie et écologie en analyse et modélisation de systèmes vivants. Les sujets traités sont l’introduction au langage de programmation R, l’analyse statistique descriptive, la visualisation, la modélisation inférentielle, prédictive et déterministe." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Association, partitionnement et ordination | Analyse et modélisation d’agroécosystèmes" />
  
  <meta name="twitter:description" content="Ce cours a pour objectif de former les étudiants gradués en génie agroenvironnemental, génie civil, génie écologique, agronomie, biologie, foresterie et écologie en analyse et modélisation de systèmes vivants. Les sujets traités sont l’introduction au langage de programmation R, l’analyse statistique descriptive, la visualisation, la modélisation inférentielle, prédictive et déterministe." />
  

<meta name="author" content="Serge-Étienne Parent">


<meta name="date" content="2019-02-19">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="chapitre-explorer.html">
<link rel="next" href="chapitre-outliers.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#definitions"><i class="fa fa-check"></i><b>1.1</b> Définitions</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#a-qui-sadresse-ce-manuel"><i class="fa fa-check"></i><b>1.2</b> À qui s’adresse ce manuel?</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#les-logiciels-libres"><i class="fa fa-check"></i><b>1.3</b> Les logiciels libres</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#langage-de-programmation"><i class="fa fa-check"></i><b>1.4</b> Langage de programmation</a><ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#r"><i class="fa fa-check"></i><b>1.4.1</b> R</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#pourquoi-pas-python"><i class="fa fa-check"></i><b>1.4.2</b> Pourquoi pas Python?</a></li>
<li class="chapter" data-level="1.4.3" data-path="index.html"><a href="index.html#pourquoi-pas-matlab"><i class="fa fa-check"></i><b>1.4.3</b> Pourquoi pas Matlab?</a></li>
<li class="chapter" data-level="1.4.4" data-path="index.html"><a href="index.html#et-sas"><i class="fa fa-check"></i><b>1.4.4</b> Et… SAS?</a></li>
<li class="chapter" data-level="1.4.5" data-path="index.html"><a href="index.html#mais-pourquoi-pas-______"><i class="fa fa-check"></i><b>1.4.5</b> Mais pourquoi pas ______ ?</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#contenu-du-manuel"><i class="fa fa-check"></i><b>1.5</b> Contenu du manuel</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#objectifs-generaux"><i class="fa fa-check"></i><b>1.6</b> Objectifs généraux</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#lectures-complementaires"><i class="fa fa-check"></i><b>1.7</b> Lectures complémentaires</a><ul>
<li class="chapter" data-level="1.7.1" data-path="index.html"><a href="index.html#ecologie-mathematique"><i class="fa fa-check"></i><b>1.7.1</b> Écologie mathématique</a></li>
<li class="chapter" data-level="1.7.2" data-path="index.html"><a href="index.html#programmation"><i class="fa fa-check"></i><b>1.7.2</b> Programmation</a></li>
<li class="chapter" data-level="1.7.3" data-path="index.html"><a href="index.html#divers"><i class="fa fa-check"></i><b>1.7.3</b> Divers</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#besoin-daide"><i class="fa fa-check"></i><b>1.8</b> Besoin d’aide?</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#a-propos-de-lauteur"><i class="fa fa-check"></i><b>1.9</b> À propos de l’auteur</a></li>
<li class="chapter" data-level="1.10" data-path="index.html"><a href="index.html#un-cours-complementaire-a-dautres-cours"><i class="fa fa-check"></i><b>1.10</b> Un cours complémentaire à d’autres cours</a></li>
<li class="chapter" data-level="1.11" data-path="index.html"><a href="index.html#contribuer-au-manuel"><i class="fa fa-check"></i><b>1.11</b> Contribuer au manuel</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html"><i class="fa fa-check"></i><b>2</b> La science des données avec R</a><ul>
<li class="chapter" data-level="2.1" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#statistiques-ou-science-des-donnees"><i class="fa fa-check"></i><b>2.1</b> Statistiques ou Science des données?</a></li>
<li class="chapter" data-level="2.2" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#organiser-son-environnement-de-travail-en-r"><i class="fa fa-check"></i><b>2.2</b> Organiser son environnement de travail en R</a></li>
<li class="chapter" data-level="2.3" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#preparer-son-flux-de-travail"><i class="fa fa-check"></i><b>2.3</b> Préparer son flux de travail</a><ul>
<li class="chapter" data-level="2.3.1" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#installation-classique"><i class="fa fa-check"></i><b>2.3.1</b> Installation classique</a></li>
<li class="chapter" data-level="2.3.2" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#r-notebooks"><i class="fa fa-check"></i><b>2.3.2</b> R notebooks</a></li>
<li class="chapter" data-level="2.3.3" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#installation-avec-anaconda"><i class="fa fa-check"></i><b>2.3.3</b> Installation avec Anaconda</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#premiers-pas-avec-r"><i class="fa fa-check"></i><b>2.4</b> Premiers pas avec R</a><ul>
<li class="chapter" data-level="2.4.1" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#types-de-donnees"><i class="fa fa-check"></i><b>2.4.1</b> Types de données</a></li>
<li class="chapter" data-level="2.4.2" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#les-collections-de-donnees"><i class="fa fa-check"></i><b>2.4.2</b> Les collections de données</a></li>
<li class="chapter" data-level="2.4.3" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#les-fonctions"><i class="fa fa-check"></i><b>2.4.3</b> Les fonctions</a></li>
<li class="chapter" data-level="2.4.4" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#les-boucles"><i class="fa fa-check"></i><b>2.4.4</b> Les boucles</a></li>
<li class="chapter" data-level="2.4.5" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#conditions-if-else-if-else"><i class="fa fa-check"></i><b>2.4.5</b> Conditions: if, else if, else</a></li>
<li class="chapter" data-level="2.4.6" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#installer-et-charger-un-module"><i class="fa fa-check"></i><b>2.4.6</b> Installer et charger un module</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="chapitre-intro-a-R.html"><a href="chapitre-intro-a-R.html#enfin"><i class="fa fa-check"></i><b>2.5</b> Enfin…</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html"><i class="fa fa-check"></i><b>3</b> Organisation des données et opérations sur des tableaux</a><ul>
<li class="chapter" data-level="3.1" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#les-collections-de-donnees-1"><i class="fa fa-check"></i><b>3.1</b> Les collections de données</a></li>
<li class="chapter" data-level="3.2" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#organiser-un-tableau-de-donnees"><i class="fa fa-check"></i><b>3.2</b> Organiser un tableau de données</a></li>
<li class="chapter" data-level="3.3" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#formats-de-tableau"><i class="fa fa-check"></i><b>3.3</b> Formats de tableau</a><ul>
<li class="chapter" data-level="3.3.1" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#xls-ou-xlsx"><i class="fa fa-check"></i><b>3.3.1</b> <em>xls</em> ou <em>xlsx</em></a></li>
<li class="chapter" data-level="3.3.2" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#csv"><i class="fa fa-check"></i><b>3.3.2</b> <em>csv</em></a></li>
<li class="chapter" data-level="3.3.3" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#json"><i class="fa fa-check"></i><b>3.3.3</b> <em>json</em></a></li>
<li class="chapter" data-level="3.3.4" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#sqlite"><i class="fa fa-check"></i><b>3.3.4</b> SQLite</a></li>
<li class="chapter" data-level="3.3.5" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#suggestion"><i class="fa fa-check"></i><b>3.3.5</b> Suggestion</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#entreposer-ses-donnees"><i class="fa fa-check"></i><b>3.4</b> Entreposer ses données</a></li>
<li class="chapter" data-level="3.5" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#manipuler-des-donnees-en-mode-tidyverse"><i class="fa fa-check"></i><b>3.5</b> Manipuler des données en mode tidyverse</a><ul>
<li class="chapter" data-level="3.5.1" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#importer-vos-donnees-dans-voter-session-de-travail"><i class="fa fa-check"></i><b>3.5.1</b> Importer vos données dans voter session de travail</a></li>
<li class="chapter" data-level="3.5.2" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#comment-selectionner-et-filtrer-des-donnees"><i class="fa fa-check"></i><b>3.5.2</b> Comment sélectionner et filtrer des données?</a></li>
<li class="chapter" data-level="3.5.3" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#le-format-long-et-le-format-large"><i class="fa fa-check"></i><b>3.5.3</b> Le format long et le format large</a></li>
<li class="chapter" data-level="3.5.4" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#combiner-des-tableaux"><i class="fa fa-check"></i><b>3.5.4</b> Combiner des tableaux</a></li>
<li class="chapter" data-level="3.5.5" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#operations-sur-les-tableaux"><i class="fa fa-check"></i><b>3.5.5</b> Opérations sur les tableaux</a></li>
<li class="chapter" data-level="3.5.6" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#exemple-difficile"><i class="fa fa-check"></i><b>3.5.6</b> Exemple (difficile)</a></li>
<li class="chapter" data-level="3.5.7" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#exporter-un-tableau"><i class="fa fa-check"></i><b>3.5.7</b> Exporter un tableau</a></li>
<li class="chapter" data-level="3.5.8" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#aller-plus-loin-dans-le-tidyverse"><i class="fa fa-check"></i><b>3.5.8</b> Aller plus loin dans le tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="chapitre-tableaux.html"><a href="chapitre-tableaux.html#references"><i class="fa fa-check"></i><b>3.6</b> Références</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html"><i class="fa fa-check"></i><b>4</b> Visualisation</a><ul>
<li class="chapter" data-level="4.1" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#pourquoi-explorer-graphiquement"><i class="fa fa-check"></i><b>4.1</b> Pourquoi explorer graphiquement?</a></li>
<li class="chapter" data-level="4.2" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#publier-un-graphique"><i class="fa fa-check"></i><b>4.2</b> Publier un graphique</a><ul>
<li class="chapter" data-level="4.2.1" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#cinq-qualites-dun-bon-graphique"><i class="fa fa-check"></i><b>4.2.1</b> Cinq qualités d’un bon graphique</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#choisir-le-type-de-graphique-le-plus-approprie"><i class="fa fa-check"></i><b>4.3</b> Choisir le type de graphique le plus approprié</a></li>
<li class="chapter" data-level="4.4" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#choisir-son-outils-de-visualisation"><i class="fa fa-check"></i><b>4.4</b> Choisir son outils de visualisation</a><ul>
<li class="chapter" data-level="4.4.1" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#approche-imperative"><i class="fa fa-check"></i><b>4.4.1</b> Approche impérative</a></li>
<li class="chapter" data-level="4.4.2" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#approche-declarative"><i class="fa fa-check"></i><b>4.4.2</b> Approche déclarative</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#visualisation-en-r"><i class="fa fa-check"></i><b>4.5</b> Visualisation en R</a></li>
<li class="chapter" data-level="4.6" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#module-de-base-pour-les-graphiques"><i class="fa fa-check"></i><b>4.6</b> Module de base pour les graphiques</a></li>
<li class="chapter" data-level="4.7" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#la-grammaire-graphique-ggplot2"><i class="fa fa-check"></i><b>4.7</b> La grammaire graphique ggplot2</a></li>
<li class="chapter" data-level="4.8" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#mon-premier-ggplot"><i class="fa fa-check"></i><b>4.8</b> Mon premier ggplot</a><ul>
<li class="chapter" data-level="4.8.1" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#plusieurs-sources-de-donnees"><i class="fa fa-check"></i><b>4.8.1</b> Plusieurs sources de données</a></li>
<li class="chapter" data-level="4.8.2" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#exporter-avec-style"><i class="fa fa-check"></i><b>4.8.2</b> Exporter avec style</a></li>
<li class="chapter" data-level="4.8.3" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#nuages-de-points"><i class="fa fa-check"></i><b>4.8.3</b> Nuages de points</a></li>
<li class="chapter" data-level="4.8.4" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#diagrammes-en-lignes"><i class="fa fa-check"></i><b>4.8.4</b> Diagrammes en lignes</a></li>
<li class="chapter" data-level="4.8.5" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#les-histogrammes"><i class="fa fa-check"></i><b>4.8.5</b> Les histogrammes</a></li>
<li class="chapter" data-level="4.8.6" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#boxplots"><i class="fa fa-check"></i><b>4.8.6</b> Boxplots</a></li>
<li class="chapter" data-level="4.8.7" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#les-diagrammes-en-barre"><i class="fa fa-check"></i><b>4.8.7</b> Les diagrammes en barre</a></li>
<li class="chapter" data-level="4.8.8" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#exporter-un-graphique"><i class="fa fa-check"></i><b>4.8.8</b> Exporter un graphique</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#les-graphiques-comme-outil-dexploration-des-donnees"><i class="fa fa-check"></i><b>4.9</b> Les graphiques comme outil d’exploration des données</a><ul>
<li class="chapter" data-level="4.9.1" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#des-graphiques-interactifs"><i class="fa fa-check"></i><b>4.9.1</b> Des graphiques interactifs!</a></li>
<li class="chapter" data-level="4.9.2" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#des-extensions-de-ggplot2"><i class="fa fa-check"></i><b>4.9.2</b> Des extensions de ggplot2</a></li>
<li class="chapter" data-level="4.9.3" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#aller-plus-loin-avec-ggplot2"><i class="fa fa-check"></i><b>4.9.3</b> Aller plus loin avec ggplot2</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#choisir-les-bonnes-couleurs"><i class="fa fa-check"></i><b>4.10</b> Choisir les bonnes couleurs</a></li>
<li class="chapter" data-level="4.11" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#regles-particulieres"><i class="fa fa-check"></i><b>4.11</b> Règles particulières</a><ul>
<li class="chapter" data-level="4.11.1" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#ne-tronquez-pas-inutilement-laxe-des-y"><i class="fa fa-check"></i><b>4.11.1</b> Ne tronquez pas inutilement l’axe des <span class="math inline">\(y\)</span></a></li>
<li class="chapter" data-level="4.11.2" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#utilisez-un-encrage-proportionnel"><i class="fa fa-check"></i><b>4.11.2</b> Utilisez un encrage proportionnel</a></li>
<li class="chapter" data-level="4.11.3" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#publiez-vos-donnees"><i class="fa fa-check"></i><b>4.11.3</b> Publiez vos données</a></li>
<li class="chapter" data-level="4.11.4" data-path="chapitre-visualisation.html"><a href="chapitre-visualisation.html#visitez-www.junkcharts.typepad.com-de-temps-a-autre"><i class="fa fa-check"></i><b>4.11.4</b> Visitez www.junkcharts.typepad.com de temps à autre</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html"><i class="fa fa-check"></i><b>5</b> Biostatistiques</a><ul>
<li class="chapter" data-level="5.1" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#populations-et-echantillons"><i class="fa fa-check"></i><b>5.1</b> Populations et échantillons</a></li>
<li class="chapter" data-level="5.2" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#les-variables"><i class="fa fa-check"></i><b>5.2</b> Les variables</a><ul>
<li class="chapter" data-level="5.2.1" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#variables-quantitatives"><i class="fa fa-check"></i><b>5.2.1</b> Variables quantitatives</a></li>
<li class="chapter" data-level="5.2.2" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#variables-qualitatives"><i class="fa fa-check"></i><b>5.2.2</b> Variables qualitatives</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#les-probabilites"><i class="fa fa-check"></i><b>5.3</b> Les probabilités</a></li>
<li class="chapter" data-level="5.4" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#les-distributions"><i class="fa fa-check"></i><b>5.4</b> Les distributions</a><ul>
<li class="chapter" data-level="5.4.1" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#distribution-binomiale"><i class="fa fa-check"></i><b>5.4.1</b> Distribution binomiale</a></li>
<li class="chapter" data-level="5.4.2" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#distribution-de-poisson"><i class="fa fa-check"></i><b>5.4.2</b> Distribution de Poisson</a></li>
<li class="chapter" data-level="5.4.3" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#distribution-uniforme"><i class="fa fa-check"></i><b>5.4.3</b> Distribution uniforme</a></li>
<li class="chapter" data-level="5.4.4" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#distribution-normale"><i class="fa fa-check"></i><b>5.4.4</b> Distribution normale</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#statistiques-descriptives"><i class="fa fa-check"></i><b>5.5</b> Statistiques descriptives</a></li>
<li class="chapter" data-level="5.6" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#tests-dhypotheses-a-un-et-deux-echantillons"><i class="fa fa-check"></i><b>5.6</b> Tests d’hypothèses à un et deux échantillons</a><ul>
<li class="chapter" data-level="5.6.1" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#test-de-t-a-un-seul-echantillon"><i class="fa fa-check"></i><b>5.6.1</b> Test de t à un seul échantillon</a></li>
<li class="chapter" data-level="5.6.2" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#attention-mauvaises-interpretations-des-p-values"><i class="fa fa-check"></i><b>5.6.2</b> Attention: mauvaises interprétations des <em>p-values</em></a></li>
<li class="chapter" data-level="5.6.3" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#test-de-wilcoxon-a-un-seul-echantillon"><i class="fa fa-check"></i><b>5.6.3</b> Test de Wilcoxon à un seul échantillon</a></li>
<li class="chapter" data-level="5.6.4" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#tests-de-t-a-deux-echantillons"><i class="fa fa-check"></i><b>5.6.4</b> Tests de t à deux échantillons</a></li>
<li class="chapter" data-level="5.6.5" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#comparaison-des-variances"><i class="fa fa-check"></i><b>5.6.5</b> Comparaison des variances</a></li>
<li class="chapter" data-level="5.6.6" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#tests-de-wilcoxon-a-deux-echantillons"><i class="fa fa-check"></i><b>5.6.6</b> Tests de Wilcoxon à deux échantillons</a></li>
<li class="chapter" data-level="5.6.7" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#les-tests-paires"><i class="fa fa-check"></i><b>5.6.7</b> Les tests pairés</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#lanalyse-de-variance"><i class="fa fa-check"></i><b>5.7</b> L’analyse de variance</a></li>
<li class="chapter" data-level="5.8" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#les-modeles-statistiques"><i class="fa fa-check"></i><b>5.8</b> Les modèles statistiques</a><ul>
<li class="chapter" data-level="5.8.1" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#modeles-a-effets-fixes"><i class="fa fa-check"></i><b>5.8.1</b> Modèles à effets fixes</a></li>
<li class="chapter" data-level="5.8.2" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#modeles-a-effets-mixtes"><i class="fa fa-check"></i><b>5.8.2</b> Modèles à effets mixtes</a></li>
<li class="chapter" data-level="5.8.3" data-path="chapitre-biostats.html"><a href="chapitre-biostats.html#aller-plus-loin"><i class="fa fa-check"></i><b>5.8.3</b> Aller plus loin</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html"><i class="fa fa-check"></i><b>6</b> Introduction à l’analyse bayésienne en écologie</a><ul>
<li class="chapter" data-level="6.1" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#quest-ce-que-cest"><i class="fa fa-check"></i><b>6.1</b> Qu’est-ce que c’est?</a></li>
<li class="chapter" data-level="6.2" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#pourquoi-lutiliser"><i class="fa fa-check"></i><b>6.2</b> Pourquoi l’utiliser?</a></li>
<li class="chapter" data-level="6.3" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#comment-lutiliser"><i class="fa fa-check"></i><b>6.3</b> Comment l’utiliser?</a></li>
<li class="chapter" data-level="6.4" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#faucons-pelerins"><i class="fa fa-check"></i><b>6.4</b> Faucons pélerins</a></li>
<li class="chapter" data-level="6.5" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#statistiques-dune-population"><i class="fa fa-check"></i><b>6.5</b> Statistiques d’une population</a><ul>
<li class="chapter" data-level="6.5.1" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#greta"><i class="fa fa-check"></i><b>6.5.1</b> greta</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#test-de-t-difference-entre-des-groupes"><i class="fa fa-check"></i><b>6.6</b> Test de t: Différence entre des groupes</a></li>
<li class="chapter" data-level="6.7" data-path="chapitre-biostats-bayes.html"><a href="chapitre-biostats-bayes.html#pour-aller-plus-loin"><i class="fa fa-check"></i><b>6.7</b> Pour aller plus loin</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html"><i class="fa fa-check"></i><b>7</b> Explorer R</a><ul>
<li class="chapter" data-level="7.1" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#r-sur-le-web"><i class="fa fa-check"></i><b>7.1</b> R sur le web</a><ul>
<li class="chapter" data-level="7.1.1" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#github"><i class="fa fa-check"></i><b>7.1.1</b> GitHub</a></li>
<li class="chapter" data-level="7.1.2" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#twitter"><i class="fa fa-check"></i><b>7.1.2</b> Twitter</a></li>
<li class="chapter" data-level="7.1.3" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#nouvelles"><i class="fa fa-check"></i><b>7.1.3</b> Nouvelles</a></li>
<li class="chapter" data-level="7.1.4" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#des-questions"><i class="fa fa-check"></i><b>7.1.4</b> Des questions?</a></li>
<li class="chapter" data-level="7.1.5" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#participer"><i class="fa fa-check"></i><b>7.1.5</b> Participer</a></li>
<li class="chapter" data-level="7.1.6" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#mise-en-garde"><i class="fa fa-check"></i><b>7.1.6</b> Mise en garde</a></li>
<li class="chapter" data-level="7.1.7" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#prendre-tout-ca-en-note"><i class="fa fa-check"></i><b>7.1.7</b> Prendre tout ça en note</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#r-en-chaire-et-en-os"><i class="fa fa-check"></i><b>7.2</b> R en chaire et en os</a></li>
<li class="chapter" data-level="7.3" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#quelques-outils-en-ecologie-mathematique-avec-r"><i class="fa fa-check"></i><b>7.3</b> Quelques outils en écologie mathématique avec R</a><ul>
<li class="chapter" data-level="7.3.1" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#pretraitement-des-donnees"><i class="fa fa-check"></i><b>7.3.1</b> Prétraitement des données</a></li>
<li class="chapter" data-level="7.3.2" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#acquerir-des-donnees-meteo"><i class="fa fa-check"></i><b>7.3.2</b> Acquérir des données météo</a></li>
<li class="chapter" data-level="7.3.3" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#pedometrie-avec-r"><i class="fa fa-check"></i><b>7.3.3</b> Pédométrie avec R</a></li>
<li class="chapter" data-level="7.3.4" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#meta-analyses-en-r"><i class="fa fa-check"></i><b>7.3.4</b> Méta-analyses en R</a></li>
<li class="chapter" data-level="7.3.5" data-path="chapitre-explorer.html"><a href="chapitre-explorer.html#creer-des-applications-avec-r"><i class="fa fa-check"></i><b>7.3.5</b> Créer des applications avec R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html"><i class="fa fa-check"></i><b>8</b> Association, partitionnement et ordination</a><ul>
<li class="chapter" data-level="8.1" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#espaces-danalyse"><i class="fa fa-check"></i><b>8.1</b> Espaces d’analyse</a><ul>
<li class="chapter" data-level="8.1.1" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#abondance-et-occurence"><i class="fa fa-check"></i><b>8.1.1</b> Abondance et occurence</a></li>
<li class="chapter" data-level="8.1.2" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#environnement"><i class="fa fa-check"></i><b>8.1.2</b> Environnement</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#analyse-dassociation"><i class="fa fa-check"></i><b>8.2</b> Analyse d’association</a><ul>
<li class="chapter" data-level="8.2.1" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#association-entre-objets-mode-q"><i class="fa fa-check"></i><b>8.2.1</b> Association entre objets (mode Q)</a></li>
<li class="chapter" data-level="8.2.2" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#associations-entre-variables-mode-r"><i class="fa fa-check"></i><b>8.2.2</b> Associations entre variables (mode R)</a></li>
<li class="chapter" data-level="8.2.3" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#conclusion-sur-les-associations"><i class="fa fa-check"></i><b>8.2.3</b> Conclusion sur les associations</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#partitionnement"><i class="fa fa-check"></i><b>8.3</b> Partitionnement</a><ul>
<li class="chapter" data-level="8.3.1" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#evaluation-dun-partitionnement"><i class="fa fa-check"></i><b>8.3.1</b> Évaluation d’un partitionnement</a></li>
<li class="chapter" data-level="8.3.2" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#partitionnement-non-hierarchique"><i class="fa fa-check"></i><b>8.3.2</b> Partitionnement non hiérarchique</a></li>
<li class="chapter" data-level="8.3.3" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#partitionnement-hierarchique"><i class="fa fa-check"></i><b>8.3.3</b> Partitionnement hiérarchique</a></li>
<li class="chapter" data-level="8.3.4" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#partitionnement-hierarchique-basee-sur-la-densite-des-points"><i class="fa fa-check"></i><b>8.3.4</b> Partitionnement hiérarchique basée sur la densité des points</a></li>
<li class="chapter" data-level="8.3.5" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#conclusion-sur-le-partitionnement"><i class="fa fa-check"></i><b>8.3.5</b> Conclusion sur le partitionnement</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#ordination"><i class="fa fa-check"></i><b>8.4</b> Ordination</a><ul>
<li class="chapter" data-level="8.4.1" data-path="chapitre-ordination.html"><a href="chapitre-ordination.html#ordination-non-contraignante"><i class="fa fa-check"></i><b>8.4.1</b> Ordination non contraignante</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chapitre-outliers.html"><a href="chapitre-outliers.html"><i class="fa fa-check"></i><b>9</b> Détection de valeurs aberrantes et imputation</a></li>
<li class="chapter" data-level="10" data-path="chapitre-temps.html"><a href="chapitre-temps.html"><i class="fa fa-check"></i><b>10</b> Les séries temporelles</a></li>
<li class="chapter" data-level="11" data-path="chapitre-git.html"><a href="chapitre-git.html"><i class="fa fa-check"></i><b>11</b> Science ouverte et suivi de version</a></li>
<li class="chapter" data-level="12" data-path="chapitre-ml.html"><a href="chapitre-ml.html"><i class="fa fa-check"></i><b>12</b> Autoapprentissage</a><ul>
<li class="chapter" data-level="12.1" data-path="chapitre-ml.html"><a href="chapitre-ml.html#objectifs"><i class="fa fa-check"></i><b>12.1</b> Objectifs</a></li>
<li class="chapter" data-level="12.2" data-path="chapitre-ml.html"><a href="chapitre-ml.html#lexique"><i class="fa fa-check"></i><b>12.2</b> Lexique</a></li>
<li class="chapter" data-level="12.3" data-path="chapitre-ml.html"><a href="chapitre-ml.html#demarche"><i class="fa fa-check"></i><b>12.3</b> Démarche</a><ul>
<li class="chapter" data-level="12.3.1" data-path="chapitre-ml.html"><a href="chapitre-ml.html#pretraitement"><i class="fa fa-check"></i><b>12.3.1</b> Prétraitement</a></li>
<li class="chapter" data-level="12.3.2" data-path="chapitre-ml.html"><a href="chapitre-ml.html#entrainement-et-test"><i class="fa fa-check"></i><b>12.3.2</b> Entraînement et test</a></li>
<li class="chapter" data-level="12.3.3" data-path="chapitre-ml.html"><a href="chapitre-ml.html#sousapprentissage-et-surapprentissage"><i class="fa fa-check"></i><b>12.3.3</b> Sousapprentissage et surapprentissage</a></li>
<li class="chapter" data-level="12.3.4" data-path="chapitre-ml.html"><a href="chapitre-ml.html#validation-croisee"><i class="fa fa-check"></i><b>12.3.4</b> Validation croisée</a></li>
<li class="chapter" data-level="12.3.5" data-path="chapitre-ml.html"><a href="chapitre-ml.html#choix-de-lalgorithme-dapprentissage"><i class="fa fa-check"></i><b>12.3.5</b> Choix de l’algorithme d’apprentissage</a></li>
<li class="chapter" data-level="12.3.6" data-path="chapitre-ml.html"><a href="chapitre-ml.html#deploiement"><i class="fa fa-check"></i><b>12.3.6</b> Déploiement</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="chapitre-ml.html"><a href="chapitre-ml.html#algorithmes"><i class="fa fa-check"></i><b>12.4</b> Algorithmes</a></li>
<li class="chapter" data-level="12.5" data-path="chapitre-ml.html"><a href="chapitre-ml.html#lautoapprentissage-en-r"><i class="fa fa-check"></i><b>12.5</b> L’autoapprentissage en R</a></li>
<li class="chapter" data-level="12.6" data-path="chapitre-ml.html"><a href="chapitre-ml.html#les-k-plus-proches-voisins"><i class="fa fa-check"></i><b>12.6</b> Les <em>k</em> plus proches voisins</a><ul>
<li class="chapter" data-level="12.6.1" data-path="chapitre-ml.html"><a href="chapitre-ml.html#exemple-dapplication-1"><i class="fa fa-check"></i><b>12.6.1</b> Exemple d’application</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="chapitre-ml.html"><a href="chapitre-ml.html#les-arbres-decisionnels"><i class="fa fa-check"></i><b>12.7</b> Les arbres décisionnels</a></li>
<li class="chapter" data-level="12.8" data-path="chapitre-ml.html"><a href="chapitre-ml.html#les-reseaux-neuronaux"><i class="fa fa-check"></i><b>12.8</b> Les réseaux neuronaux</a><ul>
<li class="chapter" data-level="12.8.1" data-path="chapitre-ml.html"><a href="chapitre-ml.html#les-reseaux-neuronaux-sur-r-avec-neuralnet"><i class="fa fa-check"></i><b>12.8.1</b> Les réseaux neuronaux sur R avec neuralnet</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="chapitre-ml.html"><a href="chapitre-ml.html#les-processus-gaussiens"><i class="fa fa-check"></i><b>12.9</b> Les processus gaussiens</a><ul>
<li class="chapter" data-level="12.9.1" data-path="chapitre-ml.html"><a href="chapitre-ml.html#un-approche-intuitive"><i class="fa fa-check"></i><b>12.9.1</b> Un approche intuitive</a></li>
<li class="chapter" data-level="12.9.2" data-path="chapitre-ml.html"><a href="chapitre-ml.html#les-processus-gaussiens-en-r"><i class="fa fa-check"></i><b>12.9.2</b> Les processus gaussiens en <code>R</code></a></li>
<li class="chapter" data-level="12.9.3" data-path="chapitre-ml.html"><a href="chapitre-ml.html#application-pratique"><i class="fa fa-check"></i><b>12.9.3</b> Application pratique</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="chapitre-geo.html"><a href="chapitre-geo.html"><i class="fa fa-check"></i><b>13</b> Les données spatiales</a></li>
<li class="chapter" data-level="14" data-path="chapitre-ode.html"><a href="chapitre-ode.html"><i class="fa fa-check"></i><b>14</b> Modélisation déterministe</a><ul>
<li class="chapter" data-level="14.1" data-path="chapitre-ode.html"><a href="chapitre-ode.html#equations-differentielles"><i class="fa fa-check"></i><b>14.1</b> Équations différentielles</a></li>
<li class="chapter" data-level="14.2" data-path="chapitre-ode.html"><a href="chapitre-ode.html#les-equations-differentielles-ordinaires-en-modelisation-ecologique"><i class="fa fa-check"></i><b>14.2</b> Les équations différentielles ordinaires en modélisation écologique</a><ul>
<li class="chapter" data-level="14.2.1" data-path="chapitre-ode.html"><a href="chapitre-ode.html#evolution-dune-seule-population-en-fonction-du-temps"><i class="fa fa-check"></i><b>14.2.1</b> Évolution d’une seule population en fonction du temps</a></li>
<li class="chapter" data-level="14.2.2" data-path="chapitre-ode.html"><a href="chapitre-ode.html#population-exploitee"><i class="fa fa-check"></i><b>14.2.2</b> Population exploitée</a></li>
<li class="chapter" data-level="14.2.3" data-path="chapitre-ode.html"><a href="chapitre-ode.html#interactions-biologiques"><i class="fa fa-check"></i><b>14.2.3</b> Interactions biologiques</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="chapitre-ode.html"><a href="chapitre-ode.html#les-equations-differentielles-partielles-en-modelisation-ecologique"><i class="fa fa-check"></i><b>14.3</b> Les équations différentielles partielles en modélisation écologique</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analyse et modélisation d’agroécosystèmes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapitre-ordination" class="section level1">
<h1><span class="header-section-number">8</span> Association, partitionnement et ordination</h1>
<hr />
<p>️ <strong>Objectifs spécifiques</strong>:</p>
<p>À la fin de ce chapitre, vous</p>
<ul>
<li>serez en mesure d’effectuer des calculs permettant de mesurer des différence entre des observations, des groupes d’observation ou des variables observées</li>
<li>serez en mesure d’effection des analyses de partitionnement hiérarchiques et non-hiérarchiques</li>
<li>serez en mesure d’effectuer des calculs d’ordination à l’aide des techniques de réduction d’axe communes: analyse en composante principale, analyse discriminante linéaire, l’analyse de correspondance, l’analyse factorielle, l’analyse en coordonnées principales et l’analyse de redondance.</li>
</ul>
<hr />
<p>Les données écologiques incluent généralement plusieurs variables qui doivent être analysées conjointement. Les techniques pour l’analyse multivariée de données écologiques ont grandi en nombre et en complexité, laissant émerger l’écologie numérique, un nouveau domaine d’étude scientifique initié par Pierre Legendre et Louis Legendre dont l’ouvrage <em>Numerical Ecology</em>, aujourd’hui à sa troisième édition, reste un incontournable pour qui s’intéresse aux mathématiques sous-jacentes au domaine. Pour la rédaction de ces notes, c’est toutefois le livre <em>Numerical ecology with R</em>, écrit par Borcard et al. (2011) pour offrir un guide à qui voudrait une approche plus appliquée.</p>
<p>L’écologie numérique sera effleurée dans ce chapitre, qui introduit à trois concepts.</p>
<ol style="list-style-type: decimal">
<li>Les <strong>associations</strong> permettent de quantifier la ressemblance ou la différence entre deux observation (échantillons) ou variables (descripteurs). Lorsque l’on a plus de deux variables ou plus de deux site, nous obtenons des matrices d’association.</li>
<li>Le <strong>partitionnement</strong> permet de regrouper des observations ou des variables selon des métriques d’association.</li>
<li>L’<strong>ordination</strong> vise par l’intermédiaire de techniques de réduction d’axe à mettre de l’ordre dans des données dont le nombre élevé de variables peut amener à des difficultés d’appréciation et d’interprétaion.</li>
</ol>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;tidyverse&quot;</span>)</code></pre>
<pre><code>## ── Attaching packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──</code></pre>
<pre><code>## ✔ ggplot2 3.1.0     ✔ purrr   0.3.0
## ✔ tibble  2.0.1     ✔ dplyr   0.8.0
## ✔ tidyr   0.8.2     ✔ stringr 1.4.0
## ✔ readr   1.3.1     ✔ forcats 0.3.0</code></pre>
<pre><code>## ── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<div id="espaces-danalyse" class="section level2">
<h2><span class="header-section-number">8.1</span> Espaces d’analyse</h2>
<div id="abondance-et-occurence" class="section level3">
<h3><span class="header-section-number">8.1.1</span> Abondance et occurence</h3>
<p>L’abondance est le décompte d’espèces observées, tandis que l’occurence est la présence ou l’absence d’une espèce. Le tableau suivant contient des données d’abondance.</p>
<pre class="sourceCode r"><code class="sourceCode r">abundance &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="st">&#39;Bruant familier&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>),
                    <span class="st">&#39;Citelle à poitrine rousse&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>),
                    <span class="st">&#39;Colibri à gorge rubis&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),
                    <span class="st">&#39;Geai bleu&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">0</span>),
                    <span class="st">&#39;Bruant chanteur&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">5</span>, <span class="dv">2</span>),
                    <span class="st">&#39;Chardonneret&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">9</span>, <span class="dv">6</span>, <span class="dv">0</span>),
                    <span class="st">&#39;Bruant à gorge blanche&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>),
                    <span class="st">&#39;Mésange à tête noire&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">20</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>),
                    <span class="st">&#39;Jaseur boréal&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">66</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))</code></pre>
<p>Ce tableau peut être rapidement transformé en données d’occurence, qui ne comprennent que l’information booléenne de présence (noté 1) et d’absence (noté 0).</p>
<pre class="sourceCode r"><code class="sourceCode r">occurence &lt;-<span class="st"> </span>abundance <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">transmute_all</span>(<span class="kw">funs</span>(<span class="kw">if_else</span>(. <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)))</code></pre>
<pre><code>## Warning: funs() is soft deprecated as of dplyr 0.8.0
## please use list() instead
## 
## # Before:
## funs(name = f(.)
## 
## # After: 
## list(name = ~f(.))
## This warning is displayed once per session.</code></pre>
<p>L’<strong>espace des espèces</strong> (ou des variables ou descripteurs) est celui où les espèces forment les axes et où les sites sont positionnés dans cet espace. Il s’agit d’une perspective en <em>mode R</em>, qui permet principalement d’identifier quels espèces se retrouvent plus courrament ensemble.</p>
<pre class="sourceCode r"><code class="sourceCode r">abundance <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(<span class="st">&quot;Bruant chanteur&quot;</span>, <span class="st">&quot;Chardonneret&quot;</span>, <span class="st">&quot;Mésange à tête noire&quot;</span>)</code></pre>
<pre><code>## # A tibble: 4 x 3
##   `Bruant chanteur` Chardonneret `Mésange à tête noire`
##               &lt;dbl&gt;        &lt;dbl&gt;                  &lt;dbl&gt;
## 1                 1            0                     20
## 2                 0            9                      1
## 3                 5            6                      1
## 4                 2            0                      0</code></pre>
<p>Dans l’<strong>espace des sites</strong> (ou les échantillons ou objets), on transpose la matrice d’abondance. On passe ici en <em>mode Q</em>, où chaque point est une espèce, et où l’on peut observer quels échantillons sont similaires.</p>
<pre class="sourceCode r"><code class="sourceCode r">abundance <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span>.[<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), ] <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">t</span>(.)</code></pre>
<pre><code>##                           [,1] [,2] [,3]
## Bruant familier              1    0    0
## Citelle à poitrine rousse    1    0    0
## Colibri à gorge rubis        0    1    0
## Geai bleu                    3    2    0
## Bruant chanteur              1    0    5
## Chardonneret                 0    9    6
## Bruant à gorge blanche       1    0    0
## Mésange à tête noire        20    1    1
## Jaseur boréal               66    0    0</code></pre>
</div>
<div id="environnement" class="section level3">
<h3><span class="header-section-number">8.1.2</span> Environnement</h3>
<p>L’<strong>espace de l’environnement</strong> comprend souvent un autre tableau contenant l’information sur l’environnement où se trouve les espèces: les coordonnées et l’élévation, la pente, le pH du sol, la pluviométrie, etc.</p>
</div>
</div>
<div id="analyse-dassociation" class="section level2">
<h2><span class="header-section-number">8.2</span> Analyse d’association</h2>
<p>Nous utiliserons le terme <em>association</em> come une <strong>mesure pour quantifier la ressemblance ou la différence entre deux objets (échantillons) ou variables (descripteurs)</strong>.</p>
<p>Alors que la corrélation et la covariance sont des mesures d’association entre des variables (analyse en <em>mode R</em>), la <strong>similarité</strong> et la <strong>distance</strong> sont deux types de une mesure d’association entre des objets (analyse en <em>mode Q</em>). Une distance de 0 est mesurée chez deux objets identiques. La distance augmente au fur et à mesure que les objets sont dissociés. Une similarité ayant une valeur de 0 indique aucune association, tandis qu’une valeur de 1 indique une association parfaite. À l’opposé, la dissimilarité est égale à 1-similarité.</p>
<p>La distance peut être liée à la similarité par la relation:</p>
<p><span class="math display">\[distance=\sqrt{1-similarité}\]</span></p>
<p>ou</p>
<p><span class="math display">\[distance=\sqrt{dissimilarité}\]</span></p>
<p>La racine carrée permet, pour certains indices de similarité, d’obtenir des propriétés euclédiennes. Pour plus de détails, voyez le tableau 7.2 de <a href="https://www.elsevier.com/books/numerical-ecology/legendre/978-0-444-53868-0">Legendre et Legendre (2012)</a>.</p>
<p>Les matrices d’association sont généralement présentées comme des matrices carrées, dont les dimensions sont égales au nombre d’objets (<em>mode Q</em>) ou de vrariables (<em>mode R</em>) dans le tableau. Chaque élément (“cellule”) de la matrice est un indice d’association entre un objet (ou une variable) et un autre. Ainsi, la diagonale de la matrice est un vecteur nul (distance ou dissimilarité) ou unitaire (similarité), car elle correspond à l’association entre un objet et lui-même.</p>
<p>Puisque l’association entre A et B est la même qu’entre B et A, et puisque la diagonale retourne une valeur convenue, il est possible d’exprimer une matrice d’association en mode “compact”, sous forme de vecteur. Le vecteur d’association entre des objets A, B et C contiendra toute l’information nécessaire en un vecteur de trois chiffres, <code>[AB, AC, BC]</code>, plutôt qu’une matrice de dimension <span class="math inline">\(3 \times 3\)</span>. L’impact sur la mémoire vive peut être considérable pour les calculs comprenant de nombreuses dimensions.</p>
<p>En R, les calculs de similarité et de distances peuvent être effectués avec le module vegan. La fonction <code>vegdist</code> permet de calculer les indices d’association en forme carrée.</p>
<p>Nous verons plus tard les méthodes de mesure de similarité et de distance plus loin. Pour l’instant, utilisons la méthode de <em>Jaccard</em> pour une démonstration sur des données d’occurence.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;vegan&quot;</span>)</code></pre>
<pre><code>## Loading required package: permute</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## This is vegan 2.5-4</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">vegdist</span>(occurence, <span class="dt">method =</span> <span class="st">&quot;jaccard&quot;</span>,
        <span class="dt">diag =</span> <span class="ot">TRUE</span>, <span class="dt">upper =</span> <span class="ot">TRUE</span>)</code></pre>
<pre><code>##           1         2         3         4
## 1 0.0000000 0.7777778 0.7500000 0.7142857
## 2 0.7777778 0.0000000 0.6000000 1.0000000
## 3 0.7500000 0.6000000 0.0000000 0.7500000
## 4 0.7142857 1.0000000 0.7500000 0.0000000</code></pre>
<p>Remarquez que <code>vegdist</code> retourne une matrice dont la diagonale est de 0 (on l’affiche en spécifiant <code>diag = TRUE</code>). La diagonale est l’association d’un objet avec lui-même. Or la similarité d’un objet avec lui-même devrait être de 1! En fait, par convention <code>vegdist</code> retourne des dissimilarités, non pas des similarités. La matrice de distance serait donc calculée en extrayant la racine carrée des éléments de la matrice de dissimilarité:</p>
<pre class="sourceCode r"><code class="sourceCode r">dissimilarity &lt;-<span class="st"> </span><span class="kw">vegdist</span>(occurence, <span class="dt">method =</span> <span class="st">&quot;jaccard&quot;</span>,
                         <span class="dt">diag =</span> <span class="ot">TRUE</span>, <span class="dt">upper =</span> <span class="ot">TRUE</span>)
distance &lt;-<span class="st"> </span><span class="kw">sqrt</span>(dissimilarity)
distance</code></pre>
<pre><code>##           1         2         3         4
## 1 0.0000000 0.8819171 0.8660254 0.8451543
## 2 0.8819171 0.0000000 0.7745967 1.0000000
## 3 0.8660254 0.7745967 0.0000000 0.8660254
## 4 0.8451543 1.0000000 0.8660254 0.0000000</code></pre>
<p>Dans le chapitre sur l’analyse compositionnelle, nous avons abordé les significations différentes que peuvent prendre le zéro. L’information fournie par un zéro peut être différente selon les circonstances. Dans le cas d’une variable continue, un zéro signifie généralement une mesure sous le seuil de détection. Deux tissus dont la concentration en cuivre est nulle ont une afinité sous la perspective de la concentration en cuivre. Dans le cas de mesures d’abondance (décompte) ou d’occurence (présence-absence), on pourra décrire comme similaires deux niches écologiques où l’on retrouve une espèce en particulier. Mais deux sites où l’on de retouve pas d’ours polaires ne correspondent pas nécessairement à des niches similaires! En effet, il peut exister de nombreuses raisons écologiques et méthodologiques pour lesquelles l’espèces ou les espèces n’ont pas été observées. C’est le problème des <strong>double-zéros</strong> (espèces non observées à deux sites), problème qui est amplifié avec les grilles comprenant des espèces rares.</p>
<p>La ressemblance entre des objets comprenant des données continues devrait être calculée grâce à des indicateurs <em>symétriques</em>. Inversement, les affinités entre les objets décrits par des données d’abondance ou d’occurence susceptibles de générer des problèmes de double-zéros devraient être évaluées grâce à des indicateurs <em>asymétriques</em>. Un défi supplémentaire arrive lorsque les données sont de type mixte.</p>
<p>Nous utiliserons la convention de <code>scipy</code> et nous calculerons la dissimilarité, non pas la similarité. Les mesures de dissimilarité sont calculées sur des données d’abondance ou des données d’occurence. Notons qu’il existe beaucoup de confusion dans la littérature sur la manière de nommer les dissimilarités (ce qui n’est pas le cas des distances, dont les noms sont reconnus). Dans les sections suivantes, nous noterons la dissimilarité avec un <span class="math inline">\(d\)</span> minuscule et la distance avec un <span class="math inline">\(D\)</span> majuscule.</p>
<div id="association-entre-objets-mode-q" class="section level3">
<h3><span class="header-section-number">8.2.1</span> Association entre objets (mode Q)</h3>
<div id="objets-abondance" class="section level4">
<h4><span class="header-section-number">8.2.1.1</span> Objets: Abondance</h4>
<p>La <strong>dissimilarité de Bray-Curtis</strong> est asymétrique. Elle est aussi appelée l’indice de Steinhaus, de Czekanowski ou de Sørensen. Il est important de s’assurer de bien s’entendre la méthode à laquelle on fait référence. L’équation enlève toute ambiguité. La dissimilarité de Bray-Curtis entre les points A et B est calculée comme suit.</p>
<p><span class="math display">\[d_{AB} =  \frac {\sum \left| A_{i} - B_{i} \right| }{\sum \left(A_{i}+B_{i}\right)}\]</span></p>
<p>Utilisons <code>vegdist</code> pour générer les matrices d’association. Le format “liste” de R est pratique pour enregistrer la collection d’objets, dont les matrice d’association que nous allons créer dans cette section.</p>
<pre class="sourceCode r"><code class="sourceCode r">associations_abund &lt;-<span class="st"> </span><span class="kw">list</span>()
associations_abund[[<span class="st">&#39;BrayCurtis&#39;</span>]] &lt;-<span class="st"> </span><span class="kw">vegdist</span>(abundance, <span class="dt">method =</span> <span class="st">&quot;bray&quot;</span>)
associations_abund[[<span class="st">&#39;BrayCurtis&#39;</span>]]</code></pre>
<pre><code>##           1         2         3
## 2 0.9433962                    
## 3 0.9619048 0.4400000          
## 4 0.9591837 1.0000000 0.7647059</code></pre>
<p>La dissimilarité de Bray-Curtis est souvent utilisée dans la littérature. Toutefois, la version originale de Bray-Curtis n’est pas tout à fait métrique (semimétrique). Conséquemment, la <strong>dissimilarité de Ruzicka</strong> (une variante de la dissimilarité de Jaccard pour les données d’abondance) est métrique, et devrait probablement être préféré à Bary-Curtis (<a href="http://ocw.um.es/ciencias/geobotanica/otros-recursos-1/documentos/vegantutorial.pdf">Oksanen, 2006</a>).</p>
<p><span class="math display">\[d_{AB, Ruzicka} =  \frac { 2 \times d_{AB, Bray-Curtis} }{1 + d_{AB, Bray-Curtis}}\]</span></p>
<pre class="sourceCode r"><code class="sourceCode r">associations_abund[[<span class="st">&#39;Ruzicka&#39;</span>]] &lt;-<span class="st"> </span>associations_abund[[<span class="st">&#39;BrayCurtis&#39;</span>]] <span class="op">*</span><span class="st"> </span><span class="dv">2</span> <span class="op">/</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>associations_abund[[<span class="st">&#39;BrayCurtis&#39;</span>]])</code></pre>
<p>La <strong>dissimilarité de Kulczynski</strong> (aussi écrit Kulsinski) est asymétrique et semimétrique, tout comme celle de Bray-Curtis. Elle est calculée comme suit.</p>
<p><span class="math display">\[d_{AB} = 1-\frac{1}{2} \times \left[ \frac{\sum min(A_i, B_i)}{\sum A_i} + \frac{\sum min(A_i, B_i)}{\sum B_i} \right]\]</span></p>
<pre class="sourceCode r"><code class="sourceCode r">associations_abund[[<span class="st">&#39;Kulczynski&#39;</span>]] &lt;-<span class="st"> </span><span class="kw">vegdist</span>(abundance, <span class="dt">method =</span> <span class="st">&quot;kulczynski&quot;</span>)</code></pre>
<p>Une approche commune pour mesurer l’association entre sites décrits par des données d’abondance est la <strong>distance de Hellinger</strong>. Notez qu’il s’agit ici d’une distance, non pas d’une dissimilarité. Pour l’obtenir, on doit d’abord diviser chaque donnée d’abondance par l’abondance totale pour chaque site pour obtenir les espèces en tant que proportions, puis on extrait la racine carrée de chaque élément. Enfin, on calcule la distance euclidienne entre les proportions de chaque site. Pour rappel, une distance euclidienne est la généralisation en plusieurs dimensions du théorème de Pythagore, <span class="math inline">\(c = \sqrt{a^2 + b^2}\)</span>.</p>
<p><span class="math display">\[D_{AB} = \sqrt {\sum \left( \frac{A_i}{\sum A_i} - \frac{B_i}{\sum B_i} \right)^2}\]</span></p>
<table style="width:93%;">
<colgroup>
<col width="26%" />
<col width="66%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="left">😱 <strong>Attention</strong></td>
<td>La distance d’Hellinger hérite des biais liées aux données compositionnelles. Elle peut être substitiée par une matrice de distances d’Aitchison.</td>
</tr>
</tbody>
</table>
<pre class="sourceCode r"><code class="sourceCode r">associations_abund[[<span class="st">&#39;Hellinger&#39;</span>]] &lt;-<span class="st"> </span><span class="kw">dist</span>(<span class="kw">decostand</span>(abundance, <span class="dt">method=</span><span class="st">&quot;hellinger&quot;</span>))</code></pre>
<p>Toute comme la distance d’Hellinger, la <strong>distance de chord</strong> est calculée par une distance euclidienne sur des données d’abondance transformées de sorte que chaque ligne ait une longueur (norme) de 1.</p>
<pre class="sourceCode r"><code class="sourceCode r">associations_abund[[<span class="st">&#39;Chord&#39;</span>]] &lt;-<span class="st"> </span><span class="kw">dist</span>(<span class="kw">decostand</span>(abundance, <span class="dt">method=</span><span class="st">&quot;normalize&quot;</span>))</code></pre>
<p>La <strong>métrique du chi-carré</strong>, ou <span class="math inline">\(\chi\)</span>-carré, ou chi-square, donne davantage de poids aux espèces rares qu’aux espèces communes. Son utilisation est recommandée lorsque les espèces rares sont de bons indicateurs de conditions écologiques particulières (<a href="https://www.elsevier.com/books/numerical-ecology/legendre/978-0-444-53868-0">Legendre et Legendre, 2012</a>, p. 308).</p>
<p><span class="math display">\[  d_{AB} = \sqrt{\sum _j \frac{1}{\sum y_j} \left( \frac{A_j}{\sum A} - \frac{B_j}{\sum B} \right)^2 }  \]</span></p>
<p>La métrique peut être transformée en distance en la multipliant par la racine carrée de la somme totale des espèces dans la matric d’abondance (<span class="math inline">\(X\)</span>).</p>
<p><span class="math display">\[ D_{AB} = \sqrt{\sum X} \times d_{AB} \]</span></p>
<pre class="sourceCode r"><code class="sourceCode r">associations_abund[[<span class="st">&#39;ChiSquare&#39;</span>]] &lt;-<span class="st"> </span><span class="kw">dist</span>(<span class="kw">decostand</span>(abundance, <span class="dt">method=</span><span class="st">&quot;chi.square&quot;</span>))</code></pre>
<p>Une mannière visuellement plus intéressante de présenter une matrice d’association est un graphique de type <em>heatmap</em>.</p>
<pre class="sourceCode r"><code class="sourceCode r">associations_abund_df &lt;-<span class="st"> </span><span class="kw">list</span>()

<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(associations_abund)) {
  associations_abund_df[[i]] &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="kw">as.matrix</span>(associations_abund[[i]]))
  <span class="kw">colnames</span>(associations_abund_df[[i]]) &lt;-<span class="st"> </span><span class="kw">rownames</span>(associations_abund_df[[i]])
  associations_abund_df[[i]]<span class="op">$</span>row &lt;-<span class="st"> </span><span class="kw">rownames</span>(associations_abund_df[[i]])
  associations_abund_df[[i]] &lt;-<span class="st"> </span>associations_abund_df[[i]] <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">gather</span>(<span class="dt">key=</span>row)
  associations_abund_df[[i]]<span class="op">$</span>column =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, <span class="dv">4</span>)
  associations_abund_df[[i]]<span class="op">$</span>dist &lt;-<span class="st"> </span><span class="kw">names</span>(associations_abund)[i]
}
associations_abund_df &lt;-<span class="st"> </span><span class="kw">do.call</span>(rbind, associations_abund_df)

<span class="kw">ggplot</span>(associations_abund_df, <span class="kw">aes</span>(<span class="dt">x=</span>row, <span class="dt">y=</span>column)) <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_wrap</span>(. <span class="op">~</span><span class="st"> </span>dist, <span class="dt">nrow =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_tile</span>(<span class="kw">aes</span>(<span class="dt">fill =</span> value)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">label =</span> <span class="kw">round</span>(value, <span class="dv">2</span>))) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_fill_gradient2</span>(<span class="dt">low =</span> <span class="st">&quot;#00ccff&quot;</span>, <span class="dt">mid =</span> <span class="st">&quot;#aad400&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;#ff0066&quot;</span>, <span class="dt">midpoint =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Site&quot;</span>, <span class="dt">y=</span><span class="st">&quot;Site&quot;</span>)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Peu importe le type d’association utilisée, les <em>heatmaps</em> montrent les mêmes tendances. Les assocaitions de dissimilarité (Bray-Curtis, Kulczynski et Ruzicka) s’étalent de 0 à 1, tandis que les distances (Chi-Square, Chord et Hellinger) partent de zéro, mais n’ont pas de limite supérieure. On note les plus grandes différences entre les sites 2 et 4, tandis que les sites 2 et 3 sont les plus semblables pour toutes les mesures d’association à l’exception de la dissimilarité de Kulczynski.</p>
</div>
<div id="objets-occurence-presence-absence" class="section level4">
<h4><span class="header-section-number">8.2.1.2</span> Objets: Occurence (présence-absence)</h4>
<p>Des indices d’association différents devraient être utilisés lorsque des données sont compilées sous forme booléenne. En général, les tableaux de données d’occurence seront compilés avec des 1 (présence) et des 0 (absence).</p>
<p>La <strong>similarité de Jaccard</strong> entre le site A et le site B est la proportion de double 1 (présences de 1 dans A et B) parmi les espèces. La dissimilarié est la proportion complémentaire (comprenant [1, 0], [0, 1] et [0, 0]). La distance de Jaccard est la racine carrée de la dissimilarité.</p>
<pre class="sourceCode r"><code class="sourceCode r">associations_occ &lt;-<span class="st"> </span><span class="kw">list</span>()
associations_occ[[<span class="st">&#39;Jaccard&#39;</span>]] &lt;-<span class="st"> </span><span class="kw">vegdist</span>(occurence, <span class="dt">method =</span> <span class="st">&quot;jaccard&quot;</span>)</code></pre>
<p>Les <strong>distances d’Hellinger, de chord et de chi-carré</strong> sont aussi appropriées pour les calculs de distances sur des tableaux d’occurence.</p>
<pre class="sourceCode r"><code class="sourceCode r">associations_occ[[<span class="st">&#39;Hellinger&#39;</span>]] &lt;-<span class="st"> </span><span class="kw">dist</span>(<span class="kw">decostand</span>(occurence, <span class="dt">method=</span><span class="st">&quot;hellinger&quot;</span>))
associations_occ[[<span class="st">&#39;Chord&#39;</span>]] &lt;-<span class="st"> </span><span class="kw">dist</span>(<span class="kw">decostand</span>(occurence, <span class="dt">method=</span><span class="st">&quot;normalize&quot;</span>))
associations_occ[[<span class="st">&#39;ChiSquare&#39;</span>]] &lt;-<span class="st"> </span><span class="kw">dist</span>(<span class="kw">decostand</span>(occurence, <span class="dt">method=</span><span class="st">&quot;chi.square&quot;</span>))</code></pre>
<p>Graphiquement,</p>
<pre class="sourceCode r"><code class="sourceCode r">associations_occ_df &lt;-<span class="st"> </span><span class="kw">list</span>()

<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(associations_occ)) {
  associations_occ_df[[i]] &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="kw">as.matrix</span>(associations_occ[[i]]))
  <span class="kw">colnames</span>(associations_occ_df[[i]]) &lt;-<span class="st"> </span><span class="kw">rownames</span>(associations_occ_df[[i]])
  associations_occ_df[[i]]<span class="op">$</span>row &lt;-<span class="st"> </span><span class="kw">rownames</span>(associations_occ_df[[i]])
  associations_occ_df[[i]] &lt;-<span class="st"> </span>associations_occ_df[[i]] <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">gather</span>(<span class="dt">key=</span>row)
  associations_occ_df[[i]]<span class="op">$</span>column =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, <span class="dv">4</span>)
  associations_occ_df[[i]]<span class="op">$</span>dist &lt;-<span class="st"> </span><span class="kw">names</span>(associations_occ)[i]
}
associations_occ_df &lt;-<span class="st"> </span><span class="kw">do.call</span>(rbind, associations_occ_df)

<span class="kw">ggplot</span>(associations_occ_df, <span class="kw">aes</span>(<span class="dt">x=</span>row, <span class="dt">y=</span>column)) <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_wrap</span>(. <span class="op">~</span><span class="st"> </span>dist) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_tile</span>(<span class="kw">aes</span>(<span class="dt">fill =</span> value)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">label =</span> <span class="kw">round</span>(value, <span class="dv">2</span>))) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_fill_gradient2</span>(<span class="dt">low =</span> <span class="st">&quot;#00ccff&quot;</span>, <span class="dt">mid =</span> <span class="st">&quot;#aad400&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;#ff0066&quot;</span>, <span class="dt">midpoint =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Site&quot;</span>, <span class="dt">y=</span><span class="st">&quot;Site&quot;</span>)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Il est attendu que les matrices d’association sur l’occurence sont semblables à celles sur l’abondance. Dans ce cas-ci, la distance d’Hellinger donne des résultats semblables à la dissimilarité de Jaccard.</p>
</div>
<div id="objets-donnees-quantitatives" class="section level4">
<h4><span class="header-section-number">8.2.1.3</span> Objets: Données quantitatives</h4>
<p>Les données quantitative en écologie peuvent décrire l’état de l’environnement: le climat, l’hydrologie, l’hydrogéochimie, la pédologie, etc. En règle générale, les coordonnées des sites ne sot pas des variables environnementales, à que l’on soupçonne la coordonnée elle-même d’être responsable d’effets sur notre système: mais il s’agira la plupart du temps d’effets confondants (par exemple, on peut mesurer un effet de lattitude sur le rendement des agrumes, mais il s’agira probablement avant tout d’effets dus aux conditions climatiques, qui elles changent en fonction de la lattitude). D’autre types de données quantitative pouvant être appréhendées par des distances sont les traits phénologiques, les ionomes, les génomes, etc.</p>
<p>La <strong>distance euclidienne</strong> est la racine carrée de la somme des carrés des distances sur tous les axes. Il s’agit d’une application multidimensionnelle du théorème de Pythagore. La <strong>distance d’Aitchison</strong>, couverte dans le chapitre 6, est une distance euclidienne calculée sur des données compositionnelles préalablement transformées. La distance euclidienne est sensible aux unités utilisés: utiliser des milimètres plutôt que des mètres enflera la distance euclidienne. Il est recommandé de porter une attention particulière aux unités, et de standardiser les données au besoin (par exemple, en centrant la moyenne à zéro et en fixant l’écart-type à 1).</p>
<p>On pourrait, par exemple, mesurer la distance entre des observations des dimensions de différentes espèces d’iris. Ce tableau est inclu dans R par défaut.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(iris)
iris <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">sample_n</span>(<span class="dv">5</span>)</code></pre>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
## 1          5.9         3.2          4.8         1.8 versicolor
## 2          5.8         2.6          4.0         1.2 versicolor
## 3          5.4         3.7          1.5         0.2     setosa
## 4          4.4         3.0          1.3         0.2     setosa
## 5          4.8         3.0          1.4         0.1     setosa</code></pre>
<p>Les mesures du tableau sont en centimètres. Pour éviter de donner davantage de poids aux longueur des sépales et en même temps de négliger la largeur des pétales, nous allons standardiser le tableau.</p>
<pre class="sourceCode r"><code class="sourceCode r">iris_sc &lt;-<span class="st"> </span>iris <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>Species) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">scale</span>(.)<span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">as_tibble</span>(.) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Species =</span> iris<span class="op">$</span>Species) 
iris_sc</code></pre>
<pre><code>## # A tibble: 150 x 5
##    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
##           &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;       &lt;dbl&gt; &lt;fct&gt;  
##  1       -0.898      1.02          -1.34       -1.31 setosa 
##  2       -1.14      -0.132         -1.34       -1.31 setosa 
##  3       -1.38       0.327         -1.39       -1.31 setosa 
##  4       -1.50       0.0979        -1.28       -1.31 setosa 
##  5       -1.02       1.25          -1.34       -1.31 setosa 
##  6       -0.535      1.93          -1.17       -1.05 setosa 
##  7       -1.50       0.786         -1.34       -1.18 setosa 
##  8       -1.02       0.786         -1.28       -1.31 setosa 
##  9       -1.74      -0.361         -1.34       -1.31 setosa 
## 10       -1.14       0.0979        -1.28       -1.44 setosa 
## # … with 140 more rows</code></pre>
<p>Pour les comparaisons des dimensions, prenons la moyenne des dimensions (mises à l’échelle) par espèce.</p>
<pre class="sourceCode r"><code class="sourceCode r">iris_means &lt;-<span class="st"> </span>iris_sc <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Species) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise_all</span>(mean) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>Species)
iris_means</code></pre>
<pre><code>## # A tibble: 3 x 4
##   Sepal.Length Sepal.Width Petal.Length Petal.Width
##          &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;       &lt;dbl&gt;
## 1       -1.01        0.850       -1.30       -1.25 
## 2        0.112      -0.659        0.284       0.166
## 3        0.899      -0.191        1.02        1.08</code></pre>
<p>Nous pouvons utiliser la distance euclidienne, commune en géométrie, pour comparer les espèces. La distance euclidienne est calculée comme suit.</p>
<p><span class="math display">\[ \mathcal{E} = \sqrt{\Sigma_i \left( A_i - B_i \right) ^2 } \]</span></p>
<pre class="sourceCode r"><code class="sourceCode r">associations_cont =<span class="st"> </span><span class="kw">list</span>()
associations_cont[[<span class="st">&#39;Euclidean&#39;</span>]] &lt;-<span class="st"> </span><span class="kw">dist</span>(iris_sc <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="op">-</span>Species), <span class="dt">method=</span><span class="st">&quot;euclidean&quot;</span>)</code></pre>
<p>La <strong>distance de Mahalanobis</strong> est semblable à la distance euclidienne, mais qui tient compte de la covariance de la matrice des objets. Cette covariance peut être utilisée pour décrire la structure d’un nuage de points. La figure suivante montre deux points verts qui se trouvent aux extrêmes d’un nuage de point. Ces points ont des distances euclidiennes par rapport au centre différentes: les lignes d’équidistance euclédienne sont tracées en rose. Toutefois, les deux points ont un distance de Mahalanobis égale à partir du centre.</p>
<img src="images/07_eucl-maha.png" width=400>
<p style="text-align: center">
Source: <a href="https://www.intechopen.com/books/soil-fertility/nutrient-balance-as-paradigm-of-plant-and-soil-chemometricsnutrient-balance-as-paradigm-of-soil-and-">Parent et al. (2012)</a>.
</p>
<p>La diastance de Mahalanobis se calcule comme suit.</p>
<p><span class="math display">\[\mathcal{M} = \sqrt{(A - B)^T S^{-1} (A-B)}\]</span></p>
<p>Notez qu’il s’agit d’une généralisation de la distance euclidienne, qui équivaut à une distance de Mahalanobis dont la matrice de covariance est une matrice identité.</p>
<p>La distance de Mahalanobis permet de représenter des distances dans un espace fortement corrélé. Elle est courramment utilisée pour détecter les valeurs aberrantes selon des critères de distance à partir du centre d’un jeu de données multivariées.</p>
<pre class="sourceCode r"><code class="sourceCode r">associations_cont[[<span class="st">&#39;Mahalanobis&#39;</span>]] &lt;-<span class="st"> </span><span class="kw">vegdist</span>(iris_sc <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="op">-</span>Species), <span class="st">&#39;mahalanobis&#39;</span>)</code></pre>
<p>La <strong>distance de Manhattan</strong> porte aussi le nom de distance de cityblock ou de taxi. C’est la distance que vous devrez parcourir pour vous rendre du point A au point B à Manhattan, c’est-à-dire selon une séquence de tronçons perpendiculaires.</p>
<p><span class="math display">\[ D_{AB} = \sum _i \left| A_i - B_i \right| \]</span></p>
<p>La distance de Manhattan est appropriée lorsque les gradients (changements d’un état à l’autre ou d’une région à l’autre) ne permettent pas des changements simultanés. Mieux vaut standardiser les variables pour éviter qu’une dimension soit prépondérante.</p>
<pre class="sourceCode r"><code class="sourceCode r">associations_cont[[<span class="st">&#39;Manhattan&#39;</span>]] &lt;-<span class="st"> </span><span class="kw">vegdist</span>(iris_sc <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="op">-</span>Species), <span class="st">&#39;manhattan&#39;</span>)</code></pre>
<p>Graphiquement</p>
<pre class="sourceCode r"><code class="sourceCode r">associations_cont_df &lt;-<span class="st"> </span><span class="kw">list</span>()

<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(associations_cont)) {
  associations_cont_df[[i]] &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="kw">as.matrix</span>(associations_cont[[i]]))
  <span class="kw">colnames</span>(associations_cont_df[[i]]) &lt;-<span class="st"> </span><span class="kw">rownames</span>(associations_cont_df[[i]])
  associations_cont_df[[i]]<span class="op">$</span>row &lt;-<span class="st"> </span><span class="kw">rownames</span>(associations_cont_df[[i]])
  associations_cont_df[[i]] &lt;-<span class="st"> </span>associations_cont_df[[i]] <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">gather</span>(<span class="dt">key=</span>row)
  associations_cont_df[[i]]<span class="op">$</span>column =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(iris), <span class="kw">nrow</span>(iris))
  associations_cont_df[[i]]<span class="op">$</span>dist &lt;-<span class="st"> </span><span class="kw">names</span>(associations_cont)[i]
}
associations_cont_df &lt;-<span class="st"> </span><span class="kw">do.call</span>(rbind, associations_cont_df)

<span class="kw">ggplot</span>(associations_cont_df, <span class="kw">aes</span>(<span class="dt">x=</span>row, <span class="dt">y=</span>column)) <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_wrap</span>(. <span class="op">~</span><span class="st"> </span>dist) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_tile</span>(<span class="kw">aes</span>(<span class="dt">fill =</span> value), <span class="dt">colour =</span> <span class="ot">NA</span>) <span class="op">+</span>
<span class="st">  </span><span class="co">#geom_text(aes(label = round(value, 2))) +</span>
<span class="st">  </span><span class="kw">scale_fill_gradient2</span>(<span class="dt">low =</span> <span class="st">&quot;#00ccff&quot;</span>, <span class="dt">mid =</span> <span class="st">&quot;#aad400&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;#ff0066&quot;</span>, <span class="dt">midpoint =</span> <span class="dv">5</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Site&quot;</span>, <span class="dt">y=</span><span class="st">&quot;Site&quot;</span>)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>Le tableau <code>iris</code> est ordonné par espèce. Les distances euclidienne et de Manhattan permettent aisément de distinguer les espèces selon les dimensions des pétales et des sépales. Toutefois, l’utilsation de la covariance avec la distance de Mahalanobis crée des distinction moins tranchées.</p>
</div>
<div id="objets-donnees-mixtes" class="section level4">
<h4><span class="header-section-number">8.2.1.4</span> Objets: Données mixtes</h4>
<p>Les données catégorielles ordinales peuvent être transformées en données continues par gradations linéaires ou quadratiques. Les données catégorielles nominales, quant à elles, peuvent être <em>dummyfiées</em> en données similaires à des occurences. Attention toutefois: contrairement à la régression linéaire qui demande d’exclure une catégorie, la <em>dummyfication</em> doit inclure toutes les catégories. Le comportement par défaut de la fonction <code>pandas.get_dummies</code> est de garder toutes les catégories. La <strong>similarité de Gower</strong> a été développée pour mesurer des associations entre des objets dont les données sont mixtes: booléennes, catégorielles et continues. La similarité de Gower est calculée en additionnant les distances calculées par colonne, individuellement. Si la colonne est booléenne, on utilise les distances de Jaccard (qui exclue les double-zéro) de manière univariée: une variable à la fois. Pour les variables continues, on utilise la distance de Manhattan divisée par la plage de valeurs de la variable (pour fin de standardisation). Puisqu’elle hérite de la particularité de la distance de Manhattan et de la similarité de Jaccard univariée, la <strong>similarité de Gower</strong> reste une combinaison linéaire de distances univariées.</p>
<pre class="sourceCode r"><code class="sourceCode r">X &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">ID =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">8</span>,
            <span class="dt">age =</span> <span class="kw">c</span>(<span class="dv">21</span>, <span class="dv">21</span>, <span class="dv">19</span>, <span class="dv">30</span>, <span class="dv">21</span>, <span class="dv">21</span>, <span class="dv">19</span>, <span class="dv">30</span>),
            <span class="dt">gender =</span> <span class="kw">c</span>(<span class="st">&#39;M&#39;</span>,<span class="st">&#39;M&#39;</span>,<span class="st">&#39;N&#39;</span>,<span class="st">&#39;M&#39;</span>,<span class="st">&#39;F&#39;</span>,<span class="st">&#39;F&#39;</span>,<span class="st">&#39;F&#39;</span>,<span class="st">&#39;F&#39;</span>),
            <span class="dt">civil_status =</span> <span class="kw">c</span>(<span class="st">&#39;MARRIED&#39;</span>,<span class="st">&#39;SINGLE&#39;</span>,<span class="st">&#39;SINGLE&#39;</span>,<span class="st">&#39;SINGLE&#39;</span>,<span class="st">&#39;MARRIED&#39;</span>,<span class="st">&#39;SINGLE&#39;</span>,<span class="st">&#39;WIDOW&#39;</span>,<span class="st">&#39;DIVORCED&#39;</span>),
            <span class="dt">salary =</span> <span class="kw">c</span>(<span class="fl">3000.0</span>,<span class="fl">1200.0</span> ,<span class="fl">32000.0</span>,<span class="fl">1800.0</span> ,<span class="fl">2900.0</span> ,<span class="fl">1100.0</span> ,<span class="fl">10000.0</span>,<span class="fl">1500.0</span>),
            <span class="dt">children =</span> <span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">FALSE</span>, <span class="ot">TRUE</span>, <span class="ot">TRUE</span>, <span class="ot">TRUE</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>, <span class="ot">TRUE</span>),
            <span class="dt">available_credit =</span> <span class="kw">c</span>(<span class="dv">2200</span>,<span class="dv">100</span>,<span class="dv">22000</span>,<span class="dv">1100</span>,<span class="dv">2000</span>,<span class="dv">100</span>,<span class="dv">6000</span>,<span class="dv">2200</span>))
X</code></pre>
<pre><code>## # A tibble: 8 x 7
##      ID   age gender civil_status salary children available_credit
##   &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;         &lt;dbl&gt; &lt;lgl&gt;               &lt;dbl&gt;
## 1     1    21 M      MARRIED        3000 TRUE                 2200
## 2     2    21 M      SINGLE         1200 FALSE                 100
## 3     3    19 N      SINGLE        32000 TRUE                22000
## 4     4    30 M      SINGLE         1800 TRUE                 1100
## 5     5    21 F      MARRIED        2900 TRUE                 2000
## 6     6    21 F      SINGLE         1100 TRUE                  100
## 7     7    19 F      WIDOW         10000 FALSE                6000
## 8     8    30 F      DIVORCED       1500 TRUE                 2200</code></pre>
<p>Il faut préalablement <em>dummifier</em> les variables catégorielles nominales.</p>
<pre class="sourceCode r"><code class="sourceCode r">X_dum &lt;-<span class="st"> </span><span class="kw">model.matrix</span>(<span class="op">~</span><span class="st"> </span><span class="dv">0</span> <span class="op">+</span><span class="st"> </span>., X[, <span class="dv">-1</span>])
X_dum</code></pre>
<pre><code>##   age genderF genderM genderN civil_statusMARRIED civil_statusSINGLE
## 1  21       0       1       0                   1                  0
## 2  21       0       1       0                   0                  1
## 3  19       0       0       1                   0                  1
## 4  30       0       1       0                   0                  1
## 5  21       1       0       0                   1                  0
## 6  21       1       0       0                   0                  1
## 7  19       1       0       0                   0                  0
## 8  30       1       0       0                   0                  0
##   civil_statusWIDOW salary childrenTRUE available_credit
## 1                 0   3000            1             2200
## 2                 0   1200            0              100
## 3                 0  32000            1            22000
## 4                 0   1800            1             1100
## 5                 0   2900            1             2000
## 6                 0   1100            1              100
## 7                 1  10000            0             6000
## 8                 0   1500            1             2200
## attr(,&quot;assign&quot;)
##  [1] 1 2 2 2 3 3 3 4 5 6
## attr(,&quot;contrasts&quot;)
## attr(,&quot;contrasts&quot;)$gender
## [1] &quot;contr.treatment&quot;
## 
## attr(,&quot;contrasts&quot;)$civil_status
## [1] &quot;contr.treatment&quot;
## 
## attr(,&quot;contrasts&quot;)$children
## [1] &quot;contr.treatment&quot;</code></pre>
<p>Calculons la dissimilarité de Gower (cette fois le graphique est fait avec <code>pheatmap</code>).</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;pheatmap&quot;</span>)
d_gow &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(<span class="kw">vegdist</span>(X_dum, <span class="st">&#39;gower&#39;</span>))
<span class="kw">colnames</span>(d_gow) &lt;-<span class="st"> </span><span class="kw">rownames</span>(d_gow) &lt;-<span class="st"> </span>X<span class="op">$</span>ID
<span class="kw">pheatmap</span>(d_gow)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>Les dendrogrammes apparaissants sur les axes du graphique sont issus d’un processus de partitionnement basé sur la distance, que nous verrons plus loin dans ce chapiter. Les profils des clients 4 et 7, ainsi que ceux des clients 3 et 7 diffèrent le plus. Les profils 3 et 4 sont néanmoins plutôt différents.</p>
</div>
</div>
<div id="associations-entre-variables-mode-r" class="section level3">
<h3><span class="header-section-number">8.2.2</span> Associations entre variables (mode R)</h3>
<p>Il existe de nombreuses approches pour mesurer les associations entre variables. La plus connue est la corrélation. Mais les données d’abondance et d’occurence demandent des approches différentes.</p>
<div id="variables-abondance" class="section level4">
<h4><span class="header-section-number">8.2.2.1</span> Variables: Abondance</h4>
<p>La distance du chi-carré est suggérée par <a href="http://www.springer.com/us/book/9781441979759">Borcard et al. (2011)</a>.</p>
<pre class="sourceCode r"><code class="sourceCode r">abundance_r &lt;-<span class="st"> </span><span class="kw">t</span>(abundance)
D_chisq_R &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(<span class="kw">dist</span>(<span class="kw">decostand</span>(abundance_r, <span class="dt">method=</span><span class="st">&quot;chi.square&quot;</span>)))
<span class="kw">pheatmap</span>(D_chisq_R, <span class="dt">display_numbers =</span> <span class="kw">round</span>(D_chisq_R, <span class="dv">2</span>))</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Des coabondances sont notables pour la mésange à tête noire, le jaseur boréal, la citelle à poitrine rousse et le bruant à gorge blanche (tache bleu au centre).</p>
</div>
<div id="variables-occurence" class="section level4">
<h4><span class="header-section-number">8.2.2.2</span> Variables: Occurence</h4>
<p>La dissimilarité de Jaccard peut être utilisée.</p>
<pre class="sourceCode r"><code class="sourceCode r">occurence_r &lt;-<span class="st"> </span><span class="kw">t</span>(occurence)
D_jacc_R &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(<span class="kw">vegdist</span>(occurence_r, <span class="dt">method =</span> <span class="st">&quot;jaccard&quot;</span>))
<span class="kw">pheatmap</span>(D_jacc_R, <span class="dt">display_numbers =</span> <span class="kw">round</span>(D_jacc_R, <span class="dv">2</span>))</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>Des cooccurences sont notables pour le jaseur boréal, la citelle à poitrine rousse et le bruant à gorge blanche (tache bleu au centre).</p>
</div>
<div id="variables-quantites" class="section level4">
<h4><span class="header-section-number">8.2.2.3</span> Variables: Quantités</h4>
<p>La matrice des corrélations de Pearson peut être utilisée pour les données continues. Quant aux variables ordinales, elles devraient idéalement être liées linéairement ou quadratiquement. Si ce n’est pas le cas, c’est-à-dire que les catégories sont ordonnées par rang seulement, vous pourrez avoir recours aux coefficients de corrélation de Spearman ou de Kendall.</p>
<pre class="sourceCode r"><code class="sourceCode r">iris_cor &lt;-<span class="st"> </span>iris <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>Species) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">cor</span>(.)
<span class="kw">pheatmap</span>(iris_cor, <span class="dt">cluster_rows =</span> <span class="ot">FALSE</span>, <span class="dt">cluster_cols =</span> <span class="ot">FALSE</span>,
         <span class="dt">display_numbers =</span> <span class="kw">round</span>(iris_cor, <span class="dv">2</span>))</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
</div>
</div>
<div id="conclusion-sur-les-associations" class="section level3">
<h3><span class="header-section-number">8.2.3</span> Conclusion sur les associations</h3>
<p>Il n’existe pas de règle claire pour déterminer quelle technique d’association utiliser. Cela dépend en premier lieu de vos données. Vous sélectionnerez votre méthode d’association selon le type de données que vous abordez, la question à laquelle vous désirez répondre ainsi l’expérience dans la littérature comme celle de vos collègues scientifiques. S’il n’existe pas de règle clair, c’est qu’il existe des dizaines de méthodes différentes, et la plupart d’entre elles vous donneront une perspective juste et valide. Il faut néanmoins faire attention pour éviter de sélectionner les méthodes qui ne sont pas appropriées.</p>
</div>
</div>
<div id="partitionnement" class="section level2">
<h2><span class="header-section-number">8.3</span> Partitionnement</h2>
<p>Les données suivantes ont été générées par <a href="https://github.com/scikit-learn-contrib/hdbscan/blob/master/notebooks/clusterable_data.npy">Leland McInnes</a> (Tutte institute of mathematics, Ottawa). Êtes-vous en mesure d’identifier des groupes? Combien en trouvez-vous?</p>
<pre class="sourceCode r"><code class="sourceCode r">df_mcinnes &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/clusterable_data.csv&quot;</span>, <span class="dt">col_names =</span> <span class="kw">c</span>(<span class="st">&quot;x&quot;</span>, <span class="st">&quot;y&quot;</span>), <span class="dt">skip =</span> <span class="dv">1</span>)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   x = col_double(),
##   y = col_double()
## )</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(df_mcinnes, <span class="kw">aes</span>(<span class="dt">x=</span>x, <span class="dt">y=</span>y)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">coord_fixed</span>()</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>En 2D, l’oeil humain peut facilement détecter les groupes. En 3D, c’est toujours possible, mais au-delà de 3D, le partitionnement cognitive devient rapidement maladroite. Les algorithmes sont alors d’une aide précieuse. Mais ils transportent en pratique tout un baggage de limitations. Quel est le critère d’association entre les groupes? Combien de groupe devrions-nous créer? Comment distinguer une donnée trop bruitée pour être classifiée?</p>
<p>Le partitionnement de données (<em>clustering</em> en anglais), et inversement leur regroupement, permet de créer des ensembles selon des critères d’association. On suppose donc que Le partitionnement permet de créer des groupes selon l’information que l’on fait émerger des données. Il est conséquemment entendu que les données ne sont pas catégorisées à priori: <strong>il ne s’agit pas de prédire la catégorie d’un objet, mais bien de créer des catégories à partir des objets</strong> par exemple selon leurs dimensions, leurs couleurs, leurs signature chimique, leurs comportements, leurs gènes, etc.</p>
<p>Plusieurs méthodes sont aujourd’hui offertes aux analystes pour partitionner leurs données. Dans le cadre de ce manuel, nous couvrirons ici deux grandes tendances dans les algorithmes.</p>
<ol style="list-style-type: decimal">
<li><p><em>Méthodes hiérarchique et non hiérarchiques</em>. Dans un partitionnement hiérarchique, l’ensemble des objets forme un groupe, comprenant des sous-regroupements, des sous-sous-regroupements, etc., dont les objets forment l’ultime partitionnement. On pourra alors identifier comment se décline un partitionnement. À l’inverse, un partitionnement non-hiérarchique des algorhitmes permettent de créer les groupes non hiérarchisés les plus différents que possible.</p></li>
<li><p><em>Membership exclusif ou flou</em>. Certaines techniques attribuent à chaque une classe unique: l’appartenance sera indiquée par un 1 et la non appartenance par un 0. D’autres techniques vont attribuer un membership flou où le degré d’appartenance est une variable continue de 0 à 1. Parmi les méthodes floues, on retrouve les méthodes probabilistes.</p></li>
</ol>
<div id="evaluation-dun-partitionnement" class="section level3">
<h3><span class="header-section-number">8.3.1</span> Évaluation d’un partitionnement</h3>
<p>Le choix d’une technique de partitionnement parmi de nombreuses disponibles, ainsi que le choix des paramètres gouvernant chacune d’entre elles, est avant tout basé sur ce que l’on désire définir comme étant un groupe, ainsi que la manière d’interpréter les groupes. En outre, <strong>le nombre de groupe à départager est <em>toujours</em> une décision de l’analyste</strong>. Néanmoins, on peut se fier <a href="http://scikit-learn.org/stable/modules/clustering.html#clustering-performance-evaluation">des indicateurs de performance de partitionnement</a>. Parmis ceux-ci, retenons le score <a href="https://rdrr.io/cran/cluster/man/silhouette.html">silouhette</a> ainsi que l’<a href="https://www.tandfonline.com/doi/abs/10.1080/03610927408827101">indice de Calinski-Harabaz</a>.</p>
<div id="score-silouhette" class="section level4">
<h4><span class="header-section-number">8.3.1.1</span> Score silouhette</h4>
<p>En anglais, le <em>h</em> dans silouhette se trouve après le <em>l</em>: on parle donc de <em>silhouette coefficient</em> pour désigner le score de chacun des objets dans le partitionnement. Pour chaque objet, on calcule la distance moyenne qui le sépare des autres points de son groupe (<span class="math inline">\(a\)</span>) ainsi que la distance moyenne qui le sépare des points du groupe le plus rapproché.</p>
<p><span class="math display">\[s = \frac{b-a}{max \left(a, b \right)}\]</span></p>
<p>Un coefficient de -1 indique le pire classement, tandis qu’un coefficient de 1 indique le meilleur classement. La moyenne des coefficients silouhette est le score silouhette.</p>
</div>
<div id="indice-de-calinski-harabaz" class="section level4">
<h4><span class="header-section-number">8.3.1.2</span> Indice de Calinski-Harabaz</h4>
<p>L’indice de Calinski-Harabaz est proportionnel au ratio des dispersions intra-groupe et la moyenne des dispersions inter-groupes. Plus l’indice est élevé, mieux les groupes sont définis. La mathématique est décrite <a href="http://scikit-learn.org/stable/modules/clustering.html#calinski-harabaz-index">dans la documentation de scikit-learn</a>, un module d’analyse et autoapprentissage sur Python.</p>
<p><strong>Note</strong>. Les coefficients silouhette et l’indice de Calinski-Harabaz sont plus appropriés pour les formes de groupes convexes (cercles, sphères, hypersphères) que pour les formes irrégulières (notamment celles obtenues par la DBSCAN, discutée ci-desssous).</p>
</div>
</div>
<div id="partitionnement-non-hierarchique" class="section level3">
<h3><span class="header-section-number">8.3.2</span> Partitionnement non hiérarchique</h3>
<p>Il peut arriver que vous n’ayez pas besoin de comprendre la structure d’agglomération des objets (ou variables). Plusieurs techniques de partitionnement non hiérarchique <a href="http://scikit-learn.org/stable/modules/clustering.html">sont disponibles dans le module scikit-learn</a>. On s’intéressera en particulier à celles-ci.</p>
<p><strong>Kmeans</strong>. L’objectif des kmeans est de minimiser la distance euclédienne entre un nombre prédéfini de <em>k</em> groupes exclusifs.</p>
<ol style="list-style-type: decimal">
<li>L’algorhitme commence par placer une nombre <em>k</em> de centroides au hasard dans l’espace d’un nombre <em>p</em> de variables (vous devez fixer <em>k</em>, et <em>p</em> est le nombre de colonnes de vos données).</li>
<li>Ensuite, chaque objet est étiquetté comme appartenant au groupe du centroid le plus près.</li>
<li>La position du centroide est déplacée à la moyenne de chaque groupe.</li>
<li>Recommencer à partir de l’étape 2 jusqu’à ce que l’assignation des objets aux groupes ne change plus.</li>
</ol>
<img src="https://media.giphy.com/media/12vVAGkaqHUqCQ/giphy.gif" />
<center>
Source: <a href="https://dashee87.github.io/data%20science/general/Clustering-with-Scikit-with-GIFs/">David Sheehan</a>
</center>
<p>La technique des kmeans suppose que les groupes ont des distributions multinormales - représentées par des cercles en 2D, des sphères en 3D, des hypersphères en plus de 3D. Cette limitation est problématique lorsque les groupes se présentent sous des formes irrégulières, comme celles du nuage de points de Leland McInnes, présenté plus haut. De plus, la technique classique des kmeans est basée sur des distances euclidiennes: l’utilisation des kmeans n’est appropriée pour les données comprenant beaucoup de zéros, comme les données d’abondance, qui devraient préalablement être transformées en variables centrées et réduites (<a href="https://www.elsevier.com/books/numerical-ecology/legendre/978-0-444-53868-0">Legendre et Legendre, 2012</a>). La technique des <strong>mixtures gaussiennes</strong> (<a href="https://www.stat.washington.edu/mclust/"><em>gaussian mixtures</em></a>) est une généralisation des kmeans permettant d’intégrer la covariance des groupes. Les groupes ne sont plus des hyper-sphères, mais des hyper-ellipsoïdes.</p>
<p><strong>DBSCAN</strong>. La technique DBSCAN (* <strong>D</strong>ensity-<strong>B</strong>ased <strong>S</strong>patial <strong>C</strong>lustering of <strong>A</strong>pplications with <strong>N</strong>oise<em>) sousentend que les groupes sont composés de zones où l’on retrouve plus de points (zones denses) séparées par des zones de faible densité. Pour lancer l’algorithme, nous devons spécifier une mesure d’association critique (distance ou dissimilarité) </em>d* ainsi qu’un nombre de point critique <em>k</em> dans le voisinage de cette distance.</p>
<ol style="list-style-type: decimal">
<li>L’algorithme comme étiqueter chaque point selon l’une de ces catégories:</li>
</ol>
<ul>
<li><em>Noyau</em>: le point a au moins <em>k</em> points dans son voisinage, c’est-à-dire à une distance inférieure ou égale à <em>d</em>.</li>
<li><em>Bordure</em>: le point a moins de <em>k</em> points dans son voisinage, mais l’un de des points voisins est un <em>noyau</em>.</li>
<li><em>Bruit</em>: le cas échéant. Ces points sont considérés comme des outliers.</li>
</ul>
<p><img src="images/07_dbscan_1.svg" width=600></p>
<ol start="2" style="list-style-type: decimal">
<li>Les noyaux distancés de <em>d</em> ou moins sont connectés entre eux en englobant les bordures.</li>
</ol>
<p><img src="images/07_dbscan_2.svg" width=600></p>
<p>Le nombre de groupes est prescrit par l’algorithme DBSCAN, qui permet du coup de détecter des données trop bruitées pour être classées.</p>
<p><a href="https://doi.org/10.1145/2666310.2666417">Damiani et al. (2014)</a> a développé une approche utilisant la technique DBSCAN pour partitionner des zones d’escale pour les flux de populations migratoires.</p>
<div id="application" class="section level4">
<h4><span class="header-section-number">8.3.2.1</span> Application</h4>
<p>Nous pouvons utilisé la fonction <code>kmeans</code> de R. Toutefois, puisque l’on désire ici effectuer des tests de partitionnement pour plusieurs nombres de groupes, nous utiliserons <code>cascadeKM</code>, du module vegan. Notez que de nombreux paramètres par défaut sont utilisés dans les exécutions ci-dessous. Ces notes de cours ne forment pas un travail de recherche scientifique. Lors de travaux de recherche, l’utilsation d’un argument ou d’un autre dans une fonction doit être justifié: qu’un paramètre soit utilisé par défaut dans une fonction n’est a priori pas une justification convainquante.</p>
<p>Pour les kmeans, on doit fixer le nombre de groupes. Le graphique des données de Leland McInnes montrent 6 groupes. Toutefois, il est rare que l’on puisse visualiser des démarquations aussi tranchées que celles de l’exemple, qui plus est dans des cas où l’on doit traiter de plus de deux dimensions. Je vais donc lancer le partitionnement en boucle pour plusieurs nombres de groupes, de 3 à 10 et pour chaque groupe, évaluer le score silouhette et de Calinski-Habaraz. J’utilise un argument random_state pour m’assurer que les groupes seront les mêmes à chaque fois que la cellule sera lancée.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;vegan&quot;</span>)
mcinnes_kmeans &lt;-<span class="st"> </span><span class="kw">cascadeKM</span>(df_mcinnes, <span class="dt">inf.gr =</span> <span class="dv">3</span>, <span class="dt">sup.gr =</span> <span class="dv">10</span>, <span class="dt">criterion =</span> <span class="st">&quot;calinski&quot;</span>)
<span class="kw">str</span>(mcinnes_kmeans)</code></pre>
<pre><code>## List of 4
##  $ partition: int [1:2309, 1:8] 2 2 2 2 2 2 2 2 2 2 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:2309] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
##   .. ..$ : chr [1:8] &quot;3 groups&quot; &quot;4 groups&quot; &quot;5 groups&quot; &quot;6 groups&quot; ...
##  $ results  : num [1:2, 1:8] 85.1 2164.5 61.4 2294.6 51.4 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:2] &quot;SSE&quot; &quot;calinski&quot;
##   .. ..$ : chr [1:8] &quot;3 groups&quot; &quot;4 groups&quot; &quot;5 groups&quot; &quot;6 groups&quot; ...
##  $ criterion: chr &quot;calinski&quot;
##  $ size     : int [1:10, 1:8] 505 1243 561 NA NA NA NA NA NA NA ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:10] &quot;Group 1&quot; &quot;Group 2&quot; &quot;Group 3&quot; &quot;Group 4&quot; ...
##   .. ..$ : chr [1:8] &quot;3 groups&quot; &quot;4 groups&quot; &quot;5 groups&quot; &quot;6 groups&quot; ...
##  - attr(*, &quot;class&quot;)= chr &quot;cascadeKM&quot;</code></pre>
<p>L’objet <code>mcinnes_kmeans</code>, de type <code>cascadeKM</code>, peut être visualisé directement avec la fonction <code>plot</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(mcinnes_kmeans)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>On obtient un maximum de Calinski à 4 groupes, qui correspons à la deuxième simulation effectuée de 3 à 10.</p>
<p>Examinons les scoers silouhette (module: cluster).</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;cluster&quot;</span>)
asw &lt;-<span class="st"> </span><span class="kw">c</span>()
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">ncol</span>(mcinnes_kmeans<span class="op">$</span>partition)) {
  mcinnes_kmeans_silhouette &lt;-<span class="st"> </span><span class="kw">silhouette</span>(mcinnes_kmeans<span class="op">$</span>partition[, i], <span class="dt">dist =</span> <span class="kw">vegdist</span>(df_mcinnes, <span class="dt">method =</span> <span class="st">&quot;euclidean&quot;</span>))
  asw[i] &lt;-<span class="st"> </span><span class="kw">summary</span>(mcinnes_kmeans_silhouette)<span class="op">$</span>avg.width
}
<span class="kw">plot</span>(<span class="dv">3</span><span class="op">:</span><span class="dv">10</span>, asw, <span class="dt">type =</span> <span class="st">&#39;b&#39;</span>)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>Le score silouhette maximum est à 3 groupes. La forme des groupes n’étant pas convexe, il fallait s’attendre à ce que indicateurs maximaux pour les deux indicateurs soient différents. C’est d’ailleurs souvent le cas. Cet exemple supporte que le choix du nombre de groupe à départager repose sur l’analyste, non pas uniquement sur les indicateurs de performance. Choisissons 6 groupes, puisque que c’est visuellement ce que l’on devrait chercher pour ce cas d’étude.</p>
<pre class="sourceCode r"><code class="sourceCode r">kmeans_group &lt;-<span class="st"> </span>mcinnes_kmeans<span class="op">$</span>partition[, <span class="dv">4</span>]
mcinnes_kmeans<span class="op">$</span>partition <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>(<span class="dv">3</span>)</code></pre>
<pre><code>##   3 groups 4 groups 5 groups 6 groups 7 groups 8 groups 9 groups 10 groups
## 1        2        3        2        5        6        7        5         3
## 2        2        3        3        3        6        6        5         3
## 3        2        4        2        5        2        7        9         1</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">df_mcinnes <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">kmeans_group =</span> kmeans_group) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># ajouter une colonne de regoupement</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>x, <span class="dt">y=</span>y)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">colour =</span> <span class="kw">factor</span>(kmeans_group))) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_fixed</span>()</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>L’algorithme kmeans est loin d’être statisfaisant. Cela est attendu, puisque les kmeans recherchent des distribution gaussiennes sur des groupes vraisemblablement non-gaussiens.</p>
<p>Nous pouvons créer un graphique silouhette pour nos 6 groupes. Notez qu’à cause d’un bogue, il n’est pas possible de présenter les données clairement lorsqu’elles sont nombreuses.</p>
<pre class="sourceCode r"><code class="sourceCode r">sil &lt;-<span class="st"> </span><span class="kw">silhouette</span>(mcinnes_kmeans<span class="op">$</span>partition[, <span class="dv">6</span>],
                  <span class="dt">dist =</span> <span class="kw">vegdist</span>(df_mcinnes[, ], <span class="dt">method =</span> <span class="st">&quot;euclidean&quot;</span>))
sil &lt;-<span class="st"> </span><span class="kw">sortSilhouette</span>(sil)
<span class="kw">plot</span>(sil, <span class="dt">col =</span> <span class="st">&#39;black&#39;</span>)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-36-1.png" width="768" /></p>
<p>La technique <strong>DBSCAN</strong> n’est pas basée sur le nombre de groupe, mais sur la densité des points. L’argument <code>x</code> ne constitue pas les données, mais une matrice d’association. L’argument minPts spécifie le nombre minimal de points qui l’on doit retrouver à une distance critique d* pour la formation des *noyaux et la propagation des groupes, spécifiée dans l’argument eps. La distance d peut être estimée en prenant une fraction de la moyenne, mais on aura volontiers recours à sont bon jugement.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;dbscan&quot;</span>)
mcinnes_dbscan &lt;-<span class="st"> </span><span class="kw">dbscan</span>(<span class="dt">x =</span> <span class="kw">vegdist</span>(df_mcinnes[, ], <span class="dt">method =</span> <span class="st">&quot;euclidean&quot;</span>),
                         <span class="dt">eps =</span> <span class="fl">0.03</span>, <span class="dt">minPts =</span> <span class="dv">10</span>)
dbscan_group &lt;-<span class="st"> </span>mcinnes_dbscan<span class="op">$</span>cluster
<span class="kw">unique</span>(dbscan_group)</code></pre>
<pre><code>## [1] 1 0 2 6 3 4 5</code></pre>
<p>Les paramètres spécifiés donnent 5 groupes (<code>1, 2, ..., 5</code>) et des points trop bruités pour être classifiés (étiquetés <code>0</code>). Voyons comment les groupes ont été formés.</p>
<pre class="sourceCode r"><code class="sourceCode r">df_mcinnes <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">dbscan_group =</span> dbscan_group) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># ajouter une colonne de regoupement</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>x, <span class="dt">y=</span>y)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">colour =</span> <span class="kw">factor</span>(dbscan_group))) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_fixed</span>()</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>Le partitionnement semble plus conforme à ce que l’on recherche. Néanmoins, DBSCAN cré quelques petits groupes indésirables (groupe 6, en rose) ainsi qu’un grand groupe (violet) qui auraient lieu d’être partitionné. Ces défaut pourraient être réglés en jouant sur les paramètres <code>eps</code> et <code>minPts</code>.</p>
</div>
</div>
<div id="partitionnement-hierarchique" class="section level3">
<h3><span class="header-section-number">8.3.3</span> Partitionnement hiérarchique</h3>
<p>Les techniques de partitionnement hiérarchique sont basées sur les matrices d’association. La technique pour mesurer l’association (entre objets ou variables) déterminera en grande partie le paritionnement des données. Les partitionnements hiérarchiques ont l’avantage de pouvoir être représentés sous forme de dendrogramme (ou arbre) de partition. Un tel dendrogramme présente des sous-groupes qui se joignent en groupes jusqu’à former un seul ensemble.</p>
<p>Le partitionnement hiérarchique est abondamment utilisé en phylogénie, pour étudier les relations de parenté entre organismes vivants, populations d’organismes et espèces. La phénétique, branche empirique de la phylogénèse interspécifique, fait usage du partitionnement hiérarchique à partir d’associations génétiques entre unités taxonomiques. On retrouve de nombreuses ressources académiques en phylogénétique ainsi que des outils pour <a href="https://www.springer.com/us/book/9781461495413">R</a> et <a href="https://academic.oup.com/bioinformatics/article/26/12/1569/287181/DendroPy-a-Python-library-for-phylogenetic">Python</a>. Toutefois, la phylogénétique en particulier ne fait pas partie de la présente ittération de ce manuel.</p>
<div id="techniques-de-partitionnement-hierarchique" class="section level4">
<h4><span class="header-section-number">8.3.3.1</span> Techniques de partitionnement hiérarchique</h4>
<p>Le partitionnement hiérarchique est typiquement effectué avec une des quatres méthodes suivantes, dont chacune possède ses particularités, mais sont toutes agglomératives: à chaque étape d’agglomération, on fusionne les deux groupes ayant le plus d’affinité sur la base des deux sous-groupes les plus rapprochés.</p>
<p><strong>Single link</strong> (<code>single</code>). Les groupes sont agglomérés sur la base des deux points parmi les groupes, qui sont les plus proches.</p>
<p><strong>Complete link</strong> (<code>complete</code>). À la différence de la méthode <em>single</em>, on considère comme critère d’agglomération les éléments les plus éloignés de chaque groupe.</p>
<p><strong>Agglomération centrale</strong>. Il s’agit d’une fammille de méthode basées sur les différences entre les tendances centrales des objets ou des groupes.</p>
<ul>
<li><strong>Average</strong> (<code>average</code>). Appelée UPGMA (Unweighted Pair-Group Method unsing Average), les groupes sont agglomérés selon un centre calculés par la moyenne et le nombre d’objet pondère l’agglomération (le poids des groupes est retiré). Cette technique est historiquement utilisée en bioinformatique pour partitionner des groupes phylogénétiques (<a href="https://www.cabdirect.org/cabdirect/abstract/19730310919">Sneath et Sokal, 1973</a>).</li>
<li><strong>Weighted</strong> (<code>weighted</code>). La version de average, mais non pondérée (WPGMA).</li>
<li><strong>Centroid</strong> (<code>centroid</code>). Tout comme average, mais le centroïde (centre géométrique) est utilisé au lieu de la moyenne. Accronyme: UPGMC.</li>
<li><strong>Median</strong> (<code>median</code>). Appelée WPGMC. Devinez! ;)</li>
</ul>
<p><strong>Ward</strong> (<code>ward</code>). L’optimisation vise à minimiser les sommes des carrés par regroupement.</p>
</div>
<div id="quel-outil-de-partitionnement-hierarchique-utiliser" class="section level4">
<h4><span class="header-section-number">8.3.3.2</span> Quel outil de partitionnement hiérarchique utiliser?</h4>
<p>Alors que le choix de la matrice d’association dépend des données et de leur contexte, la technique de partitionnement hiérarchique peut, quant à elle, être basée sur un critère numérique. Il en existe plusieurs, mais le critère recommandé pour le choix d’une technique de partitionnement hiérarchique est la <strong>corrélation cophénétique</strong>. La distance cophénétique est la distance à laquelle deux objets ou deux sous-groupes deviennent membres d’un même groupe. La corrélation cophénétique est la corrélation de Pearson entre le vecteur d’association des objets et le vecteur de distances cophénétiques.</p>
</div>
<div id="application-1" class="section level4">
<h4><span class="header-section-number">8.3.3.3</span> Application</h4>
<p>Les techniques de partitionnement hiérarchique présentées ci-dessus sont disponibles dans le module <code>stats</code> de R, qui est chargé automatiquement lors de l’ouversture de R. Nous allons classifier les dimensions des iris grâce à la distance de Manhattan.</p>
<pre class="sourceCode r"><code class="sourceCode r">mcinnes_hclust_distmat &lt;-<span class="st"> </span><span class="kw">vegdist</span>(df_mcinnes, <span class="dt">method =</span> <span class="st">&quot;manhattan&quot;</span>)

clustering_methods &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;single&#39;</span>, <span class="st">&#39;complete&#39;</span>, <span class="st">&#39;average&#39;</span>, <span class="st">&#39;centroid&#39;</span>, <span class="st">&#39;ward&#39;</span>)

clust_l &lt;-<span class="st"> </span><span class="kw">list</span>()
coph_corr_l &lt;-<span class="st"> </span><span class="kw">c</span>()

<span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">seq_along</span>(clustering_methods)) {
  clust_l[[i]] &lt;-<span class="st"> </span><span class="kw">hclust</span>(mcinnes_hclust_distmat, <span class="dt">method =</span> clustering_methods[i])
  coph_corr_l[i] &lt;-<span class="st"> </span><span class="kw">cor</span>(mcinnes_hclust_distmat, <span class="kw">cophenetic</span>(clust_l[[i]]))
}</code></pre>
<pre><code>## The &quot;ward&quot; method has been renamed to &quot;ward.D&quot;; note new &quot;ward.D2&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tibble</span>(clustering_methods, <span class="dt">coph_corr =</span> coph_corr_l) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> clustering_methods, <span class="dt">y =</span> coph_corr)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>()</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>La méthode <code>average</code> retourne la corrélation la plus élevée. Pour plus de flexibilité, enchâssons le nom de la méthode dans une variable. Ainsi, en chageant le nom de cette variable, le reste du code sera conséquent.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(clust_l) &lt;-<span class="st"> </span>clustering_methods
best_method &lt;-<span class="st"> &quot;average&quot;</span></code></pre>
<p>Le partitionnement hiérarchique peut être visualisé par un dendrogramme.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(clust_l[[best_method]])</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-41-1.png" width="1440" /></p>
</div>
<div id="combien-de-groupes-utiliser" class="section level4">
<h4><span class="header-section-number">8.3.3.4</span> Combien de groupes utiliser?</h4>
<p>La longueur des lignes verticales est la distance séparant les groupes enfants. Bien que la sélection du nombre de groupe soit avant tout basée sur les besoins du problème, nous pouvons nous appuyer sur certains outils. La hauteur totale peut servir de critère pour définir un nombre de groupes adéquat. On pourra sélectionner le nombre de groupe où la hauteur se stabilise en fonction du nombre de groupe. On pourra aussi utiliser le <em>graphique silhouette</em>, comprenant une collection de <em>largeurs de silouhette</em>, représentant le degré d’appartenance à son groupe. La fonction <code>sklearn.metrics.silhouette_score</code>, du module scikit-learn, s’en occupe.</p>
<pre class="sourceCode r"><code class="sourceCode r">asw &lt;-<span class="st"> </span><span class="kw">c</span>()
num_groups &lt;-<span class="st"> </span><span class="dv">3</span><span class="op">:</span><span class="dv">10</span>
<span class="cf">for</span>(i <span class="cf">in</span> <span class="kw">seq_along</span>(num_groups)) {
  sil &lt;-<span class="st"> </span><span class="kw">silhouette</span>(<span class="kw">cutree</span>(clust_l[[best_method]], <span class="dt">k =</span> num_groups[i]), mcinnes_hclust_distmat)
  asw[i] &lt;-<span class="st"> </span><span class="kw">summary</span>(sil)<span class="op">$</span>avg.width
}

<span class="kw">plot</span>(num_groups, asw, <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>Le nombre optimal de groupes serait de 5. Coupons le dendrorgamme à la hauteur correspondant à 5 groupes avec la fonction <code>cutree</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r">k_opt &lt;-<span class="st"> </span>num_groups[<span class="kw">which.max</span>(asw)]
hclust_group &lt;-<span class="st"> </span><span class="kw">cutree</span>(clust_l[[best_method]], <span class="dt">k =</span> k_opt)
<span class="kw">plot</span>(clust_l[[best_method]])
<span class="kw">rect.hclust</span>(clust_l[[best_method]], <span class="dt">k =</span> k_opt)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-43-1.png" width="1440" /></p>
<p>La classification hiérarchique, uniquement basée sur la distance, peut être inappropriée pour définir des formes complexes.</p>
<pre class="sourceCode r"><code class="sourceCode r">df_mcinnes <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">hclust_group =</span> hclust_group) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># ajouter une colonne de regoupement</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>x, <span class="dt">y=</span>y)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">colour =</span> <span class="kw">factor</span>(hclust_group))) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_fixed</span>()</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
</div>
</div>
<div id="partitionnement-hierarchique-basee-sur-la-densite-des-points" class="section level3">
<h3><span class="header-section-number">8.3.4</span> Partitionnement hiérarchique basée sur la densité des points</h3>
<p>La tecchinque HDBSCAN, dont l’algorithme est relativement récent (<a href="https://link.springer.com/chapter/10.1007%2F978-3-642-37456-2_14">Campello et al., 2013</a>), permet une partitionnement hiérarchique sur le même principe des zones de densité de la technique DBSCAN. Le HDBSCAN a été utilisée pour partitionner les lieux d’escale d’oiseaux migrateurs en Chine (<a href="https://www.jstage.jst.go.jp/article/dsj/12/0/12_WDS-027/_article">Xu et al., 2013</a>).</p>
<p>Avec DBSCAN, un rayon est fixé dans une métrique appropriée. Pour chaque point, on compte le nombre de point voisins, c’est à dire le nombre de point se situant à une distance (ou une dissimilarité) égale ou inférieure au rayon fixé. Avec HDBSCAN, on spécifie le nombre de points devant être recouverts et on calcule le rayon nécessaire pour les recouvrir. Ainsi, chaque point est associé à un rayon critique que l’on nommera <span class="math inline">\(d_{noyau}\)</span>. La métrique initiale est ensuite altérée: on remplace les associations entre deux objets A et B par la valeur maximale entre cette association, le rayon critique de A et le rayon critique de B. Cette nouvelle distance est appelée la <em>distance d’atteinte mutuelle</em>: elle accentue les distances pour les points se trouvant dans des zones peu denses. On applique par la suite un algorithme semblable à la partition hiérarchique <em>single link</em>: En s’élargissant, les rayons se superposent, chaque superposition de rayon forment graduellement des groupes qui s’agglomèrent ainsi de manière hiérarchique. Au lieu d’effectuer une tranche à une hauteur donnée dans un dendrogramme de partitionnement, la technique HDBSCAN se base sur un dendrogramme condensé qui discarte les sous-groupes comprenant moins de <em>n</em> objets (<span class="math inline">\(n_{gr min}\)</span>). Dans nouveau dendrogramme, on recherche des groupes qui occupent bien l’espace d’analyse. Pour ce faitre, on utilise l’inverse de la distance pour créer un indicateur de <em>persistance</em> (semblable à la similarité), <span class="math inline">\(\lambda\)</span>. Pour chaque groupe hiérarchique dans le dendrogramme condensé, on peut calculer la persistance où le groupe prend naissance. De plus, pour chaque objet d’un groupe, on peut aussi calculer une distance à laquelle il quitte le groupe. La <em>stabilité</em> d’un groupe est la domme des différences de persistance entre la persistance à la naissance et les persistances des objets. On descend dans le dendrogramme. Si la somme des stabilité des groupes enfants est plus grande que la stabilité du groupe parent, on accepte la division. Sinon, le parent forme le groupe. La <a href="http://hdbscan.readthedocs.io/en/latest/how_hdbscan_works.html">documentation du module <code>hdbscan</code></a> pour Python offre une description intuitive et plus exhaustive des principes et algorithme de HDBSCAN.</p>
<div id="parametres" class="section level4">
<h4><span class="header-section-number">8.3.4.1</span> Paramètres</h4>
<p>Outre la métrique d’association dont nous avons discuté, HDBSCAN demande d’être nourri avec <a href="https://www.rdocumentation.org/packages/dbscan/versions/1.1-3/topics/hdbscan">quelques paramètres importants</a>. En particulier, le <strong>nombre minimum d’objets par groupe</strong>, <span class="math inline">\(n_{gr min}\)</span> dépend de la quantité de données que vous avez à votre disposition, ainsi que de la quantité d’objets que vous jugez suffisante pour créer des groupes. Nous utiliserons l’implémentation de HDBSCAN du module dbscan. Si vous désirez davantage d’options, vous préférerez probablement l’<a href="https://www.rdocumentation.org/packages/largeVis/versions/0.2.1.1/topics/hdbscan">implémentation du module largeVis</a>.</p>
<pre class="sourceCode r"><code class="sourceCode r">mcinnes_hdbscan &lt;-<span class="st"> </span><span class="kw">hdbscan</span>(<span class="dt">x =</span> <span class="kw">vegdist</span>(df_mcinnes, <span class="dt">method =</span> <span class="st">&quot;euclidean&quot;</span>),
                           <span class="dt">minPts =</span> <span class="dv">20</span>,
                           <span class="dt">gen_hdbscan_tree =</span> <span class="ot">TRUE</span>,
                           <span class="dt">gen_simplified_tree =</span> <span class="ot">FALSE</span>)
hdbscan_group &lt;-<span class="st"> </span>mcinnes_hdbscan<span class="op">$</span>cluster
<span class="kw">unique</span>(hdbscan_group)</code></pre>
<pre><code>## [1] 6 0 4 3 5 1 2</code></pre>
<p>Nous avons 6 groupes, numérotés de 1 à 6, ainsi que des étiquettes identifiant des objets désignés comme étant du bruit de fond, numéroté 0. Le dendrogramme non condensé peu être produit.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(mcinnes_hdbscan<span class="op">$</span>hdbscan_tree)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<p>Difficile d’y voir clair avec autant d’objets. L’objet <code>mcinnes_hdbscan</code> a un nombre minimum d’objets par groupe de 20. Ce qui permet de présenter le dendrogramme de manière condensée.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(mcinnes_hdbscan)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-47-1.png" width="1440" /></p>
<p>Enfin, un aperçu des stratégies de partitionnement utilisés jusqu’ici.</p>
<pre class="sourceCode r"><code class="sourceCode r">clustering_group &lt;-<span class="st"> </span>df_mcinnes <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(kmeans_group,
         hclust_group,
         dbscan_group,
         hdbscan_group) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">gather</span>(<span class="op">-</span>x, <span class="op">-</span>y, <span class="dt">key =</span> <span class="st">&quot;method&quot;</span>, <span class="dt">value =</span> <span class="st">&quot;cluster&quot;</span>)</code></pre>
<pre><code>## Warning: attributes are not identical across measure variables;
## they will be dropped</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">clustering_group<span class="op">$</span>cluster &lt;-<span class="st"> </span><span class="kw">factor</span>(clustering_group<span class="op">$</span>cluster)
clustering_group <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">colour =</span> cluster)) <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>method, <span class="dt">ncol =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_equal</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>()</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-48-1.png" width="768" /></p>
<p>Clairement, le partitionnement avec HDBSCAN donne les meilleurs résultats.</p>
</div>
</div>
<div id="conclusion-sur-le-partitionnement" class="section level3">
<h3><span class="header-section-number">8.3.5</span> Conclusion sur le partitionnement</h3>
<p>Au chapitre 4, nous avons vu avec le jeu de données “datasaurus” que la visualisation peut permettre de détecter des structures en segmentant les données selon des groupes.</p>
<p><img src="images/07_datasaurus_mix.png" width=400></p>
<p><img src="images/07_datasaurus_facet.png"></p>
<p>Or, si les données n’étaient pas étiquetées, leur structure serait indétectable avec les algorithmes disponibles actuellement. Le partitionnement permet d’explorer des données, de détecter des tendances et de dégager des groupes permettant la prise de décision.</p>
<p>Plusieurs techniques de partitionnement ont été présentées. Le choix de la technique sera déterminante sur la manière dont les groupes seront partitionnés. La définition d’un groupe variant d’un cas à l’autre, il n’existe pas de règle pour prescrire une méthode ou une autre. La partitionnement hiérarchique a l’avantage de permetre de visualiser comment les groupes s’agglomèrent. Parmi les méthodes de partitionnement hiérarchique disponibles, les méthodes basées sur la densité permettent une grande flexibilité, ainsi qu’une détection d’observations ne faisant partie d’aucun goupe.</p>
</div>
</div>
<div id="ordination" class="section level2">
<h2><span class="header-section-number">8.4</span> Ordination</h2>
<p>En écologie, biologie, agronommie comme en foresterie, la plupart des tableaux de données comprennent de nombreuses variables: pH, nutriments, climat, espèces ou cultivars, etc. L’ordination vise à mettre de l’ordre dans des données dont le nombre élevé de variables peut amener à des difficultés d’appréciation et d’interprétaion (<a href="https://www.elsevier.com/books/numerical-ecology/legendre/978-0-444-53868-0">Legendre et Legendre, 2012</a>). Plus précisément, le terme ordination est utilisé en écologie pour désigner les techniques de réduction d’axe. L’analyse en composante principale est probablement la plus connue de ces techniques. Mais de nombreuses techniques d’ordination ont été développées au cours des dernières années, chacune ayant ses domaines d’application.</p>
<p>Les techniques de réduction d’axe permettent de dégager l’information la plus importante en projetant une synthèse des relations entre les observations et entre les variables. Les techniques ne supposant aucune structure <em>a priori</em> sont dites <em>non-contraignantes</em>: elles ne comprennent pas de tests statistiques. À l’inverse, les ordinations contraignantes lient des variables descriptives avec une ou plusieurs variables prédictives.</p>
<p>La référence en la matière est indiscutablement (<a href="https://www.elsevier.com/books/numerical-ecology/legendre/978-0-444-53868-0">Legendre et Legendre, 2012</a>). Cette section en couvrira quelques unes et vous guidera vers la technique la plus appropriée pour vos données.</p>
<div id="ordination-non-contraignante" class="section level3">
<h3><span class="header-section-number">8.4.1</span> Ordination non contraignante</h3>
<p>Cette section couvrira l’<strong>analyse en composantes principales</strong> (ACP), l’<strong>analyse de correspondance</strong> (AC), <strong>l’analyse factorielle</strong> (AF) ainsi que l’<strong>analyse en coordonnées principales</strong> (ACoP).</p>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th>Méthode</th>
<th>Distance préservée</th>
<th>Variables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Analyse en composantes principales (ACP)</td>
<td>Distance euclidienne</td>
<td>Données quantitatives, relations linéaires (attention aux double-zéros)</td>
</tr>
<tr class="even">
<td>Analyse de correspondance (AC)</td>
<td>Distance de <span class="math inline">\(\chi^2\)</span></td>
<td>Données non-négatives, dimentionnellement homogènes ou binaires, abondance ou occurence</td>
</tr>
<tr class="odd">
<td>Positionnement multidimensionnel (PoMd)</td>
<td>Toute mesure de dissimilarité</td>
<td>Données quantitatives, qualitatives nominales/ordinales ou mixtes</td>
</tr>
</tbody>
</table>
<p>Source: Adapté de (<a href="https://www.elsevier.com/books/numerical-ecology/legendre/978-0-444-53868-0">Legendre et Legendre, 2012</a>, chapitre 9)</p>
<div id="analyse-en-composantes-principales" class="section level4">
<h4><span class="header-section-number">8.4.1.1</span> Analyse en composantes principales</h4>
<p>L’objectif d’une ACP est de représenter les données dans un nombre réduit de dimensions représentant le plus possible la variation d’un tableau de données: elle permet de projetter les données dans un espace où les variables sont combinées en axes orthogonaux dont le premier axe capte le maximum de variance. L’ACP peut par exemple être utilisée pour analyser des corrélations entre variables ou dégager l’information la plus pertinente d’un tableau de données météo ou de signal en un nombre plus retreint de variables.</p>
<p>L’ACP effectue est une rotation des axes à partir du centre (moyenne) du nuage de points effectuée de manière à ce que le premier axe définisse la direction où l’on retrouve la variance maximale. Ce premier axe est une combinaison linéaire des variables et forme la première composante principale. Une fois cet axe définit, on trouve de deuxième axe, orthogonal au premier, où l’on retouve la variance maximale - cet axe forme la deuxième composante principale, et ainsi de suite jusqu’à ce que le nombre d’axe corresponde au nombre de variables. Les projections des observations sur ces axes principaux sont appelés les <strong>scores</strong>. Les projections des variables sur les axes principaux sont les <strong>vecteurs propres</strong> (<em>eigenvectors</em>, ou <em>loadings</em>). La variance des composantes principales diminue de la première à la dernière, et peut être calculée comme une proportion de la variance totale: c’est le <strong>pourcentage d’inertie</strong>. Par convention, on utilise les <strong>valeurs propres</strong> (<em>eigenvalues</em>) pour mesurer l’importance des axes. Si la première composante principale a une inertie de 50% et la deuxième a une intertie de 30%, la représentation en 2D des projection représentera 80% de la variance du nuage de points.</p>
<p>L’hétérogénéité des échelles de mesure peut avoir une grande importance sur les résultats d’une ACP (les données doivent être dimensionnellement homogènes). En effet, la hauteur d’un ceriser aura une variance plus grande que le diamètre d’une cerise exprimé dans les mêmes unités, et cette dernière aura plus de variance que la teneur en cuivre d’une feuille. Il est conséquemment avisé de mettre les données à l’échelle en centrant la moyenne à zéro et l’écart-type à 1 avant de procéder à une ACP.</p>
<p>L’ACP a été conçue pour projetter en un nombre moindre de dimensions des observations dont les distributions sont multinormales. Bien que l’ACP soit une technique robuste, il est préférable de transformer préalablement les variables dont la distribution est particulièrement asymétriques (<a href="https://www.elsevier.com/books/numerical-ecology/legendre/978-0-444-53868-0">Legendre et Legendre, 2012, p. 450</a>). Le cas échéant, les valeurs extrêmes pourraient faire dévier les vecteurs propres et biaiser l’analyse. En particulier, les données ACP menées sur des données compositionnelles sont réputées pour générer des analyses biaisées (<a href="http://sp.lyellcollection.org/content/specpubgsl/264/1/1.full.pdf">Pawlowsky-Glahn and Egozcue, 2006</a>). Le test de Mardia (<a href="https://journal.r-project.org/archive/2014-2/korkmaz-goksuluk-zararsiz.pdf">Korkmaz, 2014</a>) peut être utilisé pour tester la multinormalité. Une distribution multinormale devrait générer des scores en forme d’hypersphère (en forme de cercle sur un biplot: voir plus loin).</p>
<div id="vecteurs-propres-et-valeurs-propres" class="section level5">
<h5><span class="header-section-number">8.4.1.1.1</span> Vecteurs propres et valeurs propres</h5>
<p>Une matrice carrée (comme une matrice de covariance <span class="math inline">\(\Sigma\)</span>) multipliée par un vecteur propre <span class="math inline">\(e\)</span> est égale aux valeurs propres <span class="math inline">\(\lambda\)</span> multipliées par les vecteurs propres <span class="math inline">\(e\)</span>.</p>
<p><span class="math display">\[ \Sigma e = \lambda e \]</span></p>
<p>De manière intuitive, les vecteurs propres indiquent l’orientation de la covariance, et les valeurs propres indique la longueur associée à cette direction. L’ACP est basée sur le calcul des vecteurs propres et des valeurs propres de la matrice de covariance des variables. Pour d’abord obtenir les valeurs propres <span class="math inline">\(\lambda\)</span>, il faut résoudre l’équation</p>
<p><span class="math display">\[ det(cov(X) - \lambda I) = 0 \]</span>,</p>
<p>où <span class="math inline">\(det\)</span> est l’opération permettant de calculer le déterminant, <span class="math inline">\(cov\)</span> est l’opération pour calculer la covariance, <span class="math inline">\(X\)</span> est la matrice de données, <span class="math inline">\(\lambda\)</span> sont les valeurs propres et <span class="math inline">\(I\)</span> est une matrice d’identité.</p>
<p>Pour <span class="math inline">\(p\)</span> variables dans votre tableau <span class="math inline">\(X\)</span>, vous obtiendrex <span class="math inline">\(p\)</span> valeurs propres. Ensuite, on trouve les vecteurs propres en résolvant l’équation $ e = e $.</p>
<p>Bien qu’il soit possible d’<a href="https://www.youtube.com/watch?v=2fCBE7DWgd0&amp;list=PLBv09BD7ez_5_yapAg86Od6JeeypkS4YM">effectuer cette opération à la main</a> pour des cas très simples, vous aurez avantage à utiliser un langage de programmation.</p>
<p>Chargeons les données d’iris, puis isolons seulement les deux dimensions des sépales l’espèce <em>setosa</em>.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(<span class="st">&quot;iris&quot;</span>)
setosa_sepal &lt;-<span class="st"> </span>iris <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(Species <span class="op">==</span><span class="st"> &quot;setosa&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(<span class="kw">starts_with</span>(<span class="st">&quot;Sepal&quot;</span>))
setosa_sepal</code></pre>
<pre><code>##    Sepal.Length Sepal.Width
## 1           5.1         3.5
## 2           4.9         3.0
## 3           4.7         3.2
## 4           4.6         3.1
## 5           5.0         3.6
## 6           5.4         3.9
## 7           4.6         3.4
## 8           5.0         3.4
## 9           4.4         2.9
## 10          4.9         3.1
## 11          5.4         3.7
## 12          4.8         3.4
## 13          4.8         3.0
## 14          4.3         3.0
## 15          5.8         4.0
## 16          5.7         4.4
## 17          5.4         3.9
## 18          5.1         3.5
## 19          5.7         3.8
## 20          5.1         3.8
## 21          5.4         3.4
## 22          5.1         3.7
## 23          4.6         3.6
## 24          5.1         3.3
## 25          4.8         3.4
## 26          5.0         3.0
## 27          5.0         3.4
## 28          5.2         3.5
## 29          5.2         3.4
## 30          4.7         3.2
## 31          4.8         3.1
## 32          5.4         3.4
## 33          5.2         4.1
## 34          5.5         4.2
## 35          4.9         3.1
## 36          5.0         3.2
## 37          5.5         3.5
## 38          4.9         3.6
## 39          4.4         3.0
## 40          5.1         3.4
## 41          5.0         3.5
## 42          4.5         2.3
## 43          4.4         3.2
## 44          5.0         3.5
## 45          5.1         3.8
## 46          4.8         3.0
## 47          5.1         3.8
## 48          4.6         3.2
## 49          5.3         3.7
## 50          5.0         3.3</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;MVN&quot;</span>)</code></pre>
<pre><code>## sROC 0.1-2 loaded</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">setosa_sepal_mvn &lt;-<span class="st"> </span><span class="kw">mvn</span>(setosa_sepal, <span class="dt">mvnTest =</span> <span class="st">&quot;mardia&quot;</span>)
setosa_sepal_mvn<span class="op">$</span>multivariateNormality</code></pre>
<pre><code>##              Test          Statistic           p value Result
## 1 Mardia Skewness  0.759503524380438 0.943793240544741    YES
## 2 Mardia Kurtosis 0.0934600553610254 0.925538081956867    YES
## 3             MVN               &lt;NA&gt;              &lt;NA&gt;    YES</code></pre>
<p>Pour considérer la distribution comme multinormale, la p-value de la distortion (<code>Mardia Skewness</code>) <strong>et</strong> la statistique de Kurtosis (<code>Mardia Kurtosis</code>) doit être égale ou plus élevée que 0.05 (<a href="https://www.rdocumentation.org/packages/MVN/versions/5.6/topics/mvn">Kormaz, 2019, fiche d’aide de la fonction <code>mvn</code> de R</a>). C’est bien le cas pour les données du tableau <code>setosa_sepal</code>.</p>
<p>Retirons de la matrice de covariance les valeurs et vecteurs propres avec la fonction <code>eigen</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r">setosa_eigen &lt;-<span class="st"> </span><span class="kw">eigen</span>(<span class="kw">cov</span>(setosa_sepal))
setosa_eigenval &lt;-<span class="st"> </span>setosa_eigen<span class="op">$</span>values
setosa_eigenvec &lt;-<span class="st"> </span>setosa_eigen<span class="op">$</span>vectors</code></pre>
<p>Le premier vecteur propre correspond à la première colonne, et le second à la deuxième. Les coordonnées x et y sont les premières et deuxièmes lignes. Les vecteurs propres ont une longueur unitaire (norme de 1). Ils peuvent être mis à l’échelles à la racine carrée des valeurs propres.</p>
<pre class="sourceCode r"><code class="sourceCode r">setosa_eigenvec_sc &lt;-<span class="st"> </span>setosa_eigenvec <span class="op">%*%</span><span class="st"> </span><span class="kw">diag</span>(<span class="kw">sqrt</span>(setosa_eigen<span class="op">$</span>values))</code></pre>
<p>Pour effectuer une translation des vecteurs propres au centre du nuage de point, nous avons besoin du centroïde.</p>
<pre class="sourceCode r"><code class="sourceCode r">centroid &lt;-<span class="st"> </span>setosa_sepal <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">apply</span>(., <span class="dv">2</span>, mean)</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(setosa_sepal, <span class="dt">asp =</span> <span class="dv">1</span>)

<span class="co"># vecteurs propres brutes</span>
<span class="kw">lines</span>(<span class="dt">x=</span><span class="kw">c</span>(centroid[<span class="dv">1</span>], centroid[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>setosa_eigenvec[<span class="dv">1</span>, <span class="dv">1</span>]),
      <span class="dt">y=</span><span class="kw">c</span>(centroid[<span class="dv">2</span>], centroid[<span class="dv">2</span>] <span class="op">+</span><span class="st"> </span>setosa_eigenvec[<span class="dv">2</span>, <span class="dv">1</span>]), <span class="dt">col =</span> <span class="st">&quot;green&quot;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>) <span class="co"># vecteur propre 1</span>
<span class="kw">lines</span>(<span class="dt">x=</span><span class="kw">c</span>(centroid[<span class="dv">1</span>], centroid[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>setosa_eigenvec[<span class="dv">1</span>, <span class="dv">2</span>]),
      <span class="dt">y=</span><span class="kw">c</span>(centroid[<span class="dv">2</span>], centroid[<span class="dv">2</span>] <span class="op">+</span><span class="st"> </span>setosa_eigenvec[<span class="dv">2</span>, <span class="dv">2</span>]), <span class="dt">col =</span> <span class="st">&quot;green&quot;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>) <span class="co"># vecteur propre 1</span>

<span class="co"># vecteurs propres à l&#39;échelle</span>
<span class="kw">lines</span>(<span class="dt">x=</span><span class="kw">c</span>(centroid[<span class="dv">1</span>], centroid[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>setosa_eigenvec_sc[<span class="dv">1</span>, <span class="dv">1</span>]),
      <span class="dt">y=</span><span class="kw">c</span>(centroid[<span class="dv">2</span>], centroid[<span class="dv">2</span>] <span class="op">+</span><span class="st"> </span>setosa_eigenvec_sc[<span class="dv">2</span>, <span class="dv">1</span>]), <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">lwd =</span> <span class="dv">4</span>) <span class="co"># vecteur propre 1</span>
<span class="kw">lines</span>(<span class="dt">x=</span><span class="kw">c</span>(centroid[<span class="dv">1</span>], centroid[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>setosa_eigenvec_sc[<span class="dv">1</span>, <span class="dv">2</span>]),
      <span class="dt">y=</span><span class="kw">c</span>(centroid[<span class="dv">2</span>], centroid[<span class="dv">2</span>] <span class="op">+</span><span class="st"> </span>setosa_eigenvec_sc[<span class="dv">2</span>, <span class="dv">2</span>]), <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">lwd =</span> <span class="dv">4</span>) <span class="co"># vecteur propre 1</span>

<span class="kw">points</span>(<span class="dt">x=</span>centroid[<span class="dv">1</span>], <span class="dt">y=</span>centroid[<span class="dv">2</span>], <span class="dt">pch =</span> <span class="dv">16</span>, <span class="dt">cex =</span> <span class="dv">2</span>, <span class="dt">col  =</span><span class="st">&quot;blue&quot;</span>) <span class="co"># centroid</span></code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<p>On peut observer que, comme je l’ai mentionné plus haut, <strong>les vecteurs propres indiquent l’orientation de la covariance, et les valeurs propres indique la longueur associée à cette direction</strong>.</p>
</div>
<div id="biplot" class="section level5">
<h5><span class="header-section-number">8.4.1.1.2</span> Biplot</h5>
<p>Imaginez un nuage de points en 3D, axes y compris. Vous tournez votre nuage de points pour trouver la perspective en 2D qui fera en sorte que vos données soient les plus dispersées possibles. Avec une lampe de poche, vous illuminez votre nuage de points dans l’axe de cette perspective: vous venez d’effectuer une analyse en composantes principales, et l’ombre des points et des axes sur le mur formera votre biplot.</p>
<p>Pour créer un biplot, on juxtapose les descripteurs (variables) en tant que vecteurs propres, représentés par des flèches, et les objets (observations) en tant que scores, représentés par des points. Les résultats d’une ordination peuvent être présentés selon deux types de biplots (<a href="https://www.elsevier.com/books/numerical-ecology/legendre/978-0-444-53868-0">Legendre et Legendre, 2012</a>).</p>
<p><img src="images/07_bipolot-meteo-sc2.svg" /></p>
<center>
Biplot de corrélation permettant de visualiser les corrélations entre des variables météorologiques. Source: <a href="">Parent, 2017</a>
</center>
<p>Deux types de projection sont courramment utilisés.</p>
<p><strong>Biplot de distance</strong>. Ce type de projection permet de visualiser la position des objets entre eux et par rapport aux descripteurs et d’apprécier la contribution des descripteurs pour créer les composantes principales. Pour créer un biplot de distance, on projette directement les vecteurs propres (<span class="math inline">\(U\)</span>) en guise de descripteurs. Pour ce qui est des objets, on utilise les scores de l’ACP (<span class="math inline">\(F\)</span>). De cette manière,</p>
<ol style="list-style-type: decimal">
<li>les distances euclidiennes entre les scores sont des approximations des distances euclidiennes dans l’espace multidimentionnel,</li>
<li>la projection d’un objet sur un descripteur perpendiculairement à ce dernier est une approximation de la position de l’objet sur le descripteur et</li>
<li>la projection d’un descripteur sur un axe principal est proportionnelle à sa contribution pour générer l’axe.</li>
</ol>
<p><strong>Biplot de corrélation</strong>. Cette projection permet d’apprécier les corrélations entre les descripteurs. Pour ce faire, les objets et les valeurs propres doivent être transformés. Pour générer les descripteurs, les vecteurs propres (<span class="math inline">\(U\)</span>) doivent être multipliés par la matrice diagonalisée de la racine carrée des valeurs propres (<span class="math inline">\(\Lambda\)</span>), c’est-à-dire <span class="math inline">\(U \Lambda ^{\frac{1}{2}}\)</span>. En ce qui a trait aux objets, on multiplie les scores par (<span class="math inline">\(F\)</span>) par la racine carrée négative des valeurs propres diagonalisées, c’est-à-dire <span class="math inline">\(F \Lambda ^{- \frac{1}{2}}\)</span>. De cette manière,</p>
<ol style="list-style-type: decimal">
<li>tout comme c’est le cas pour le biplot de distance, la projection d’un objet sur un descripteur perpendiculairement à ce dernier est une approximation de la position de l’objet sur le descripteur,</li>
<li>la projection d’un descripteur sur un axe principal est proportionnelle à son écart-type et</li>
<li>les <strong>angles</strong> entre les descripteurs sont proportionnelles à leur corrélation (et non pas leur proximité).</li>
</ol>
<p>En d’autres mots, le bilot de distances devrait être utilisé pour apprécier la distance entre les objets et le biplot de corrélation devrait être utilisé pour apprécier les corrélations entre les descripteurs. Mais dans tous les cas, <strong>le type de biplot utilisé doit être indiqué</strong>.</p>
<p>Le <em>triplot</em> est une forme apparentée au biplot, auquel on ajoute des variables prédictives. Le triplot est utile pour représenter les résultats des ordinations contraignantes comme les analyses de redondance et les analyse de correspondance canoniques.</p>
</div>
<div id="application-2" class="section level5">
<h5><span class="header-section-number">8.4.1.1.3</span> Application</h5>
<p>Bien que l’ACP puisse être effectuée grâce à des modules de base de R, nous utiliserons le module vegan. Le tableau <a href="https://rdrr.io/rforge/vegan/man/varechem.html"><code>varechem</code></a> comprend des données issues d’analyse de sols identifiés par leur composition chimique, leur pH, leur profondeur totale et la profondeur de l’humus publiées dans <a href="http://onlinelibrary.wiley.com/doi/10.2307/3236351/abstract">Väre et al. (1995)</a> et exportées du module <a href="https://rdrr.io/rforge/vegan/">vegan</a>.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;vegan&quot;</span>)
<span class="kw">data</span>(<span class="st">&quot;varechem&quot;</span>)
varechem <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">sample_n</span>(<span class="dv">5</span>)</code></pre>
<pre><code>##      N    P     K    Ca   Mg    S    Al   Fe    Mn   Zn  Mo Baresoil
## 1 24.2 31.0 138.2 394.6 45.3 27.1  74.2  9.8  24.4  5.2 0.3     29.8
## 2 19.8 42.1 139.9 519.4 90.0 32.3  39.0 40.9  58.1  4.5 0.3     43.9
## 3 19.1 26.4  61.1 259.1 37.0 21.4 155.1 81.4  20.6  4.0 0.6      5.8
## 4 26.2 61.9 202.2 741.2 86.3 48.6 124.3 23.6  94.5 10.2 0.6     56.9
## 5 22.8 50.6 151.7 648.0 64.8 30.2  12.1  2.3 122.9  8.1 0.2     23.7
##   Humdepth  pH
## 1      2.0 2.8
## 2      2.2 2.7
## 3      1.9 3.0
## 4      2.5 2.9
## 5      2.6 2.9</code></pre>
<p>Comme nous l’avons vu précdemment, les données de concentration sont de type <em>compositionnelles</em>. Les données compositionnelles du tableau <code>varechem</code> mériteraient d’être transformées (<a href="http://doi.wiley.com/10.1111/1467-9876.00275">Aitchison et Greenacre, 2002</a>). Utilisons les log-ratios centrés (<em>clr</em>).</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;compositions&quot;</span>)</code></pre>
<pre><code>## Loading required package: tensorA</code></pre>
<pre><code>## 
## Attaching package: &#39;tensorA&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     norm</code></pre>
<pre><code>## Loading required package: robustbase</code></pre>
<pre><code>## Loading required package: energy</code></pre>
<pre><code>## Loading required package: bayesm</code></pre>
<pre><code>## Welcome to compositions, a package for compositional data analysis.
## Find an intro with &quot;? compositions&quot;</code></pre>
<pre><code>## 
## Attaching package: &#39;compositions&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     cor, cov, dist, var</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     %*%, scale, scale.default</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">varecomp &lt;-<span class="st"> </span>varechem <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>Baresoil, <span class="op">-</span>Humdepth, <span class="op">-</span>pH) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Fv =</span> <span class="kw">apply</span>(., <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fl">1e6</span> <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(x)))
vareclr &lt;-<span class="st"> </span>varecomp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">acomp</span>(.) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">clr</span>(.) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">as_tibble</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">bind_cols</span>(varechem <span class="op">%&gt;%</span>
<span class="st">              </span><span class="kw">select</span>(Baresoil, Humdepth, pH))</code></pre>
<pre><code>## Warning: Calling `as_tibble()` on a vector is discouraged, because the behavior is likely to change in the future. Use `enframe(name = NULL)` instead.
## This warning is displayed once per session.</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">vareclr <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">sample_n</span>(<span class="dv">5</span>)</code></pre>
<pre><code>## # A tibble: 5 x 15
##        N      P       K    Ca     Mg      S     Al    Fe     Mn    Zn    Mo
##    &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 -1.02  -0.187 1.01     2.47  0.649 -0.509 -0.999 -3.09 -0.272 -2.30 -5.39
## 2 -0.860 -0.822 0.00250  1.09 -0.337 -1.06   1.42   1.02 -1.64  -3.34 -4.99
## 3 -1.78  -0.613 0.354    1.72 -0.174 -0.645  0.932 -1.02 -0.935 -2.31 -4.85
## 4 -1.76  -0.553 0.565    2.11  0.575 -0.706  0.159 -1.20 -1.30  -1.95 -4.99
## 5 -1.27  -0.187 1.16     2.43  0.551 -0.589 -1.56  -2.81  0.588 -1.92 -5.90
## # … with 4 more variables: Fv &lt;dbl&gt;, Baresoil &lt;dbl&gt;, Humdepth &lt;dbl&gt;,
## #   pH &lt;dbl&gt;</code></pre>
<p>Effectuons l’ACP. Pour cet exemple, nous standardiserons les données étant données que les colonnes Baresoil, Humedepth et pH ne sont pas à la même échelle que les colonnes des clr.</p>
<pre class="sourceCode r"><code class="sourceCode r">vareclr_sc &lt;-<span class="st"> </span><span class="kw">scale</span>(vareclr)
vare_pca &lt;-<span class="st"> </span><span class="kw">rda</span>(vareclr_sc) <span class="co"># ou bien rda(vareclr, scale = TRUE, mais la mise à l&#39;échelle préalable est plus explicite)</span></code></pre>
<p>L’objet <code>vareclr_pca</code> contient l’information nécessaire pour mener notre ACP.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(vare_pca, <span class="dt">scaling =</span> <span class="dv">2</span>) <span class="co"># scaling = 2 pour obtenir les infos pour les biplots de corrélation</span></code></pre>
<pre><code>## 
## Call:
## rda(X = vareclr_sc) 
## 
## Partitioning of variance:
##               Inertia Proportion
## Total              15          1
## Unconstrained      15          1
## 
## Eigenvalues, and their contribution to the variance 
## 
## Importance of components:
##                          PC1    PC2    PC3     PC4     PC5     PC6     PC7
## Eigenvalue            7.1523 2.4763 2.1122 0.93015 0.57977 0.48786 0.36646
## Proportion Explained  0.4768 0.1651 0.1408 0.06201 0.03865 0.03252 0.02443
## Cumulative Proportion 0.4768 0.6419 0.7827 0.84473 0.88338 0.91590 0.94034
##                           PC8     PC9    PC10     PC11     PC12     PC13
## Eigenvalue            0.29432 0.19686 0.15434 0.107357 0.095635 0.042245
## Proportion Explained  0.01962 0.01312 0.01029 0.007157 0.006376 0.002816
## Cumulative Proportion 0.95996 0.97308 0.98337 0.990527 0.996902 0.999719
##                            PC14
## Eigenvalue            0.0042200
## Proportion Explained  0.0002813
## Cumulative Proportion 1.0000000
## 
## Scaling 2 for species and site scores
## * Species are scaled proportional to eigenvalues
## * Sites are unscaled: weighted dispersion equal on all dimensions
## * General scaling constant of scores:  4.309777 
## 
## 
## Species scores
## 
##              PC1     PC2     PC3      PC4        PC5       PC6
## N         0.1437  0.7606 -0.6792  0.19837  0.1128526 -0.050149
## P         0.8670 -0.3214 -0.2950 -0.22940  0.1437960 -0.042884
## K         0.9122 -0.3857  0.2357  0.03469  0.2737020  0.075717
## Ca        0.9649 -0.3362 -0.2147  0.17757 -0.2188717  0.008051
## Mg        0.8263 -0.2723  0.1035  0.52135 -0.1495399 -0.342214
## S         0.8825 -0.3169  0.3539 -0.21216  0.1176279 -0.191386
## Al       -1.0105 -0.2442  0.2146  0.02674 -0.1005560 -0.043569
## Fe       -1.0338 -0.2464  0.1492  0.13162  0.1512218  0.081571
## Mn        0.9556  0.1041 -0.1256 -0.21300  0.2565831  0.275275
## Zn        0.7763 -0.1031 -0.3123 -0.36493 -0.5665691  0.153089
## Mo       -0.2152  0.8717  0.4065 -0.33643 -0.2134335 -0.167725
## Fv        0.2360  0.5776 -0.8112  0.12736  0.1280097 -0.109737
## Baresoil  0.5147  0.4210  0.4472  0.54980 -0.1438570  0.463148
## Humdepth  0.7455  0.4379  0.5194  0.16493  0.0004757 -0.273056
## pH       -0.5754 -0.5864 -0.5957  0.23408 -0.1517661 -0.056641
## 
## 
## Site scores (weighted sums of species scores)
## 
##            PC1       PC2      PC3      PC4      PC5      PC6
## sit1   0.16862  0.423777  0.46731  0.91175  1.10380  1.06421
## sit2  -0.09705 -0.097482  0.61143 -0.29049  1.14916  0.40622
## sit3   0.02831 -0.795737  0.74176 -0.19097 -2.43337 -0.81762
## sit4   1.39081 -0.354376 -0.19377 -0.45160  0.46020 -0.31446
## sit5   1.30346  0.357866  0.29887  0.76856  0.20913 -0.64145
## sit6   0.43636  0.495037  1.21722  1.18128 -0.98242 -0.74474
## sit7   1.07306  0.467575 -0.32245  0.03717  0.13956 -0.64972
## sit8   0.02545  0.659714 -0.28861 -0.01424  0.47105  0.45173
## sit9   1.42005  0.007356 -0.29000 -0.78474  0.97592 -0.80263
## sit10 -0.50638 -0.220909  1.52981  0.26289  0.42135  0.94054
## sit11  0.45392  0.649297  0.44573 -0.26620 -0.74522 -0.53228
## sit12  0.18623  0.259640  0.89112  0.21096 -0.51393  2.24361
## sit13  1.26264  0.225744 -0.96668 -0.69334  0.61990  0.43312
## sit14 -1.48685  0.739545 -0.20926  1.09256  0.61856 -0.87999
## sit15 -0.50622  1.108685 -2.61287 -1.00433 -1.35383  1.21964
## sit16 -1.28653  0.898663 -0.38778 -0.47556 -0.02449 -0.29419
## sit17 -1.72773  0.476962 -0.48878  0.71156  1.06398 -1.33473
## sit18 -0.82844 -0.296515  1.20315 -1.49821 -0.18330  1.05231
## sit19 -1.00247 -0.609253  0.25185 -0.85420  0.71031  0.14854
## sit20 -0.43405 -0.338912  0.55348 -1.35776 -0.81986 -1.02468
## sit21 -0.05083  0.122645 -0.04611 -0.56047 -0.26151 -0.98053
## sit22  0.17891 -2.315489 -0.69084 -0.19547  0.80628  0.04291
## sit23 -0.46443 -2.592018 -1.21615  1.56359 -0.62334  0.28748
## sit24  0.46316  0.728185 -0.49843  1.89726 -0.80791  0.72671</code></pre>
<p>La deuxième ligne de <code>Importance of components</code>, <code>Proportion Explained</code>, indique la proportion de la variance totale captée successivement par les axes principaux. Le premier axe principal comporte 47.68% de la variance. Le deuxième axe principal ajoutant une proportion de 16,51%, une représentation en deux axes principaux présentent 64.19 % de la variance.</p>
<pre class="sourceCode r"><code class="sourceCode r">prop_expl &lt;-<span class="st"> </span>vare_pca<span class="op">$</span>CA<span class="op">$</span>eig <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(vare_pca<span class="op">$</span>CA<span class="op">$</span>eig)
prop_expl</code></pre>
<pre><code>##          PC1          PC2          PC3          PC4          PC5 
## 0.4768180610 0.1650859388 0.1408156459 0.0620101490 0.0386511040 
##          PC6          PC7          PC8          PC9         PC10 
## 0.0325238535 0.0244303815 0.0196215021 0.0131238464 0.0102890284 
##         PC11         PC12         PC13         PC14 
## 0.0071571089 0.0063756951 0.0028163495 0.0002813359</code></pre>
<p>La décision du nombre d’axes principaux à retenir est arbitraire. Elle peut dépendre d’un nombre maximal de paramètre à retenir pour éviter de surdimensionner un modèle (<em>curse of dimensionality</em>, section 11) ou d’un seuil de pourcentage de variance minimal à retenir, par exemple 75%. Ou bien, vous retiendrez deux composantes principales si vous désirez présenter un seul biplot.</p>
<p>L’approche de <em>Kaiser-Guttmann</em> (<a href="http://www.springer.com/us/book/9781441979759">Borcard et al., 2011</a>) consiste à sélectionner les composantes principales dont la valeur propre est supérieure à leur moyenne.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="dt">x =</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(vare_pca<span class="op">$</span>CA<span class="op">$</span>eig),
     <span class="dt">y =</span> vare_pca<span class="op">$</span>CA<span class="op">$</span>eig,
     <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;Rang de la valeur propre&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Valeur propre&quot;</span>)
<span class="kw">abline</span>(<span class="dt">h =</span> <span class="kw">mean</span>(vare_pca<span class="op">$</span>CA<span class="op">$</span>eig), <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">lty =</span> <span class="dv">2</span>)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
<p>L’approche du <em>broken stick</em> consiste à couper un bâton d’une longueur de 1 en n tranches. La première tranche est de longueur <span class="math inline">\(\frac{1}{n}\)</span>. La tranche suivante est d’une longueur de la tranche précédente à laquelle on aditionne <span class="math inline">\(\frac{1}{longueur~restante}\)</span>. Puis on place les longueurs en ordre décroissant. On retient les composantes principales dont les valeurs propres cumulées sont plus grandes que le broken stick.</p>
<pre class="sourceCode r"><code class="sourceCode r">broken_stick &lt;-<span class="st"> </span><span class="cf">function</span>(x) {
  bsm &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&quot;numeric&quot;</span>, <span class="dt">length =</span> x)
  bsm[<span class="dv">1</span>] &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">/</span>x
  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="op">:</span>x) {
    bsm[i] &lt;-<span class="st"> </span>bsm[i<span class="dv">-1</span>] <span class="op">+</span><span class="st"> </span><span class="dv">1</span><span class="op">/</span>(x<span class="op">+</span><span class="dv">1</span><span class="op">-</span>i)
  }
  bsm &lt;-<span class="st"> </span><span class="kw">rev</span>(bsm<span class="op">/</span>x)
  <span class="kw">return</span>(bsm)
}</code></pre>
<p>Le graphique du <em>broken stick</em>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="dt">x =</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(vare_pca<span class="op">$</span>CA<span class="op">$</span>eig),
     <span class="dt">y =</span> prop_expl,
     <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;Rang de la valeur propre&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Valeur propre&quot;</span>)
<span class="kw">lines</span>(<span class="dt">x =</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(vare_pca<span class="op">$</span>CA<span class="op">$</span>eig),
      <span class="dt">y =</span> <span class="kw">broken_stick</span>(<span class="kw">length</span>(vare_pca<span class="op">$</span>CA<span class="op">$</span>eig)),
      <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>,
      <span class="dt">lty =</span> <span class="dv">2</span>)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
<p>Les approches <em>Kaiser-Guttmann</em> et <em>broken stick</em> suggèrent que les trois premières composantes sont suffisantes pour décrire la dispersion des données.</p>
<p>Examinons les loadings (vecteurs propres) plus en particulier. Dans le langage du module vegan, les vecteurs propres sont les espèces (<code>species</code>) et les scores sont les <code>sites</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r">vare_eigenvec &lt;-<span class="st"> </span><span class="kw">scores</span>(vare_pca, <span class="dt">scaling =</span> <span class="dv">2</span>, <span class="dt">display =</span> <span class="st">&quot;species&quot;</span>, <span class="dt">choices =</span> <span class="dv">1</span><span class="op">:</span>(<span class="kw">ncol</span>(vareclr)<span class="op">-</span><span class="dv">1</span>))
vare_eigenvec</code></pre>
<pre><code>##                 PC1        PC2        PC3        PC4           PC5
## N         0.1437343  0.7606006 -0.6792046  0.1983670  0.1128526122
## P         0.8669892 -0.3213683 -0.2949864 -0.2294036  0.1437959857
## K         0.9122089 -0.3857245  0.2356904  0.0346904  0.2737019601
## Ca        0.9648855 -0.3361651 -0.2147486  0.1775746 -0.2188716732
## Mg        0.8263327 -0.2723055  0.1035276  0.5213484 -0.1495399242
## S         0.8824519 -0.3169039  0.3538854 -0.2121562  0.1176278503
## Al       -1.0105173 -0.2441785  0.2145614  0.0267422 -0.1005559874
## Fe       -1.0337676 -0.2463987  0.1491865  0.1316173  0.1512218115
## Mn        0.9555632  0.1041030 -0.1256178 -0.2130047  0.2565830557
## Zn        0.7763480 -0.1030878 -0.3122919 -0.3649341 -0.5665691228
## Mo       -0.2152399  0.8717229  0.4064967 -0.3364279 -0.2134335302
## Fv        0.2360040  0.5775863 -0.8111953  0.1273582  0.1280096553
## Baresoil  0.5147445  0.4209983  0.4472351  0.5497950 -0.1438569673
## Humdepth  0.7455213  0.4379436  0.5193895  0.1649306  0.0004756685
## pH       -0.5753858 -0.5863743 -0.5957495  0.2340826 -0.1517660977
##                   PC6         PC7         PC8          PC9        PC10
## N        -0.050148980 -0.09111164 -0.06122008  0.315645453  0.08090232
## P        -0.042883754  0.26894062  0.34111276  0.021124287  0.08756299
## K         0.075717162 -0.21662612 -0.01641260  0.143099440 -0.08737113
## Ca        0.008050762  0.03630015  0.04775616 -0.073609828 -0.10601799
## Mg       -0.342213793  0.04617838 -0.12098602 -0.051599273  0.18373857
## S        -0.191386377 -0.26825994  0.15822845  0.038378858  0.05100717
## Al       -0.043569364 -0.22737412  0.10598673  0.040586196 -0.14473132
## Fe        0.081571443  0.10553041 -0.09254655 -0.079426433  0.09908706
## Mn        0.275275174  0.20224538 -0.19347804 -0.038859808 -0.07637994
## Zn        0.153089144 -0.12332232 -0.14862229  0.024026151  0.02643462
## Mo       -0.167725160  0.13788948  0.17165900  0.032981311  0.01419924
## Fv       -0.109737235 -0.20911147  0.11289753 -0.281443886 -0.08391004
## Baresoil  0.463148072 -0.02103009  0.23028292  0.004554036  0.02604286
## Humdepth -0.273056212  0.17061078 -0.11310394  0.027515405 -0.23068827
## pH       -0.056640816  0.19890884  0.12152266  0.150118818 -0.15240317
##                  PC11         PC12        PC13         PC14
## N        -0.019251478  0.045420621  0.05020956  0.002340519
## P        -0.045741546  0.145128883 -0.03337551 -0.010109130
## K         0.183005607  0.002260341 -0.10566808  0.001169065
## Ca        0.161460554  0.041210064  0.14341793  0.007419161
## Mg       -0.009862571 -0.063493608 -0.03782662 -0.023575986
## S        -0.138785063 -0.117144869  0.06075094  0.025874035
## Al       -0.089462074  0.058212507  0.01983102 -0.037901576
## Fe       -0.006376211  0.049837173 -0.01169516  0.036048221
## Mn       -0.083300112 -0.133353213  0.02679781 -0.021373612
## Zn       -0.064973307  0.051057277 -0.06538348  0.010896560
## Mo        0.128814989 -0.114803631 -0.01989539 -0.001335923
## Fv       -0.012456867 -0.020157331 -0.05448619  0.005707928
## Baresoil -0.061147847 -0.019696758 -0.01640490  0.003823725
## Humdepth -0.102189307  0.109293684 -0.02485030  0.016559206
## pH       -0.037691048 -0.153813168 -0.04523353  0.014193061
## attr(,&quot;const&quot;)
## [1] 4.309777</code></pre>
<p>L’ordre d’importance des vecteurs propres est établi en ordre croissant des élément des vecteurs propres associées. Un vecteur propre est une combinaison linéaire des variables. Par exemple, le premier vecteur propre pointe surtout dans la direction du Fe (-1.497) et de l’Al (-1.463). Le deuxième pointe surtout vers le Mo (2.145). Les vecteurs (<em>loadings</em>) d’un biplot de distance présentant les des deux premières composantes principales prendront les coordonnées des deux premières colonnes. Le vecteur Al aura la coordonnée [-1.463 ; -0.601], le vecteur de Fe sera placé à [-1.497 ; -0.606] et le vecteur Mo à [-0.312 ; 2.145]. Il existe différentes fonctions d’affichage des biplots. Notez que leur longueur peut être magnifiée pour améliorer la visualisation.</p>
<p>Lançons la fonction <code>biplot</code> pour créer un biplot de distance et un autre de corrélation.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))
<span class="kw">biplot</span>(vare_pca, <span class="dt">scaling =</span> <span class="dv">1</span>, <span class="dt">main =</span> <span class="st">&quot;Biplot de distance&quot;</span>)
<span class="kw">biplot</span>(vare_pca, <span class="dt">scaling =</span> <span class="dv">2</span>, <span class="dt">main =</span> <span class="st">&quot;Biplot de corrélation&quot;</span>)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
<p>Le biplot de distance permet de dégager les variables qui expliquent davantage la variabilité dans notre tableau: les clr du Fe et de l’Al forment en grande partie le premier axe principal, alors que le clr du Mo forme en grande partie le second axe. Le biplot de corrélation montre que les clr du Fe et du Al sont corrélés dans le même sens, mais das le sens contraire du clr du Mn. L’information sur la teneur en Fe et celle de l’Al est en grande partie redondante. Toutefois, le clr du Mo est presque indépendant du clr du Fe, ceux-ci étant à angle presque droit (~90°). Ces relations peuvent être explorées directement.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))
<span class="kw">plot</span>(vareclr<span class="op">$</span>Al, vareclr<span class="op">$</span>Fe)
<span class="kw">plot</span>(vareclr<span class="op">$</span>Mo, vareclr<span class="op">$</span>Fe)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
<p>Nous avons mentionné que l’ACP est une rotation. Prenons un second exemple pour bien en saisir les tenants et aboutissants. Le tableau de données que nous chargerons provient d’un infographie d’un dauphin, intitullée <em>Bottlenose Dolphin</em>, conçu par l’artiste <a href="https://www.blendswap.com/blends/view/83681">Tarnyloo</a>. Les points correspondent à la surface d’un dauphin. J’ai ajouté une colonne <code>anatomy</code>, qui indique à quelle partie anatomique le point appartient.</p>
<pre class="sourceCode r"><code class="sourceCode r">dolphin &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/07_dolphin.csv&quot;</span>)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   x = col_double(),
##   y = col_double(),
##   z = col_double(),
##   anatomy = col_character()
## )</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">dolphin <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">sample_n</span>(<span class="dv">5</span>)</code></pre>
<pre><code>## # A tibble: 5 x 4
##        x      y        z anatomy
##    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;  
## 1 0.163  -0.382 -0.00500 Head   
## 2 0.106  -0.444 -0.0987  Head   
## 3 0.0665 -0.547 -0.102   Head   
## 4 0.179  -0.305 -0.00840 Head   
## 5 0.0770 -0.392 -0.0444  Head</code></pre>
<p>Voici en vue isométrique ce en quoi consiste ce nuage de points.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;scatterplot3d&quot;</span>)
<span class="kw">scatterplot3d</span>(<span class="dt">x =</span> dolphin<span class="op">$</span>x, <span class="dt">y =</span> dolphin<span class="op">$</span>y, <span class="dt">z =</span> dolphin<span class="op">$</span>z, <span class="dt">pch =</span> <span class="dv">16</span>, <span class="dt">cex.symbols =</span> <span class="fl">0.2</span>)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-67-1.png" width="672" /></p>
<p>Effectuons l’ACP sur le dauphin.</p>
<pre class="sourceCode r"><code class="sourceCode r">dolph_pca &lt;-<span class="st"> </span><span class="kw">rda</span>(dolphin <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(x, y, z), <span class="dt">scale =</span> <span class="ot">FALSE</span>)
<span class="kw">biplot</span>(dolph_pca, <span class="dt">scaling =</span> <span class="dv">2</span>)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p>On n’y voit pas grand chose, mais si l’on extrait les scores et que l’on raccourcit les vecteurs:</p>
<pre class="sourceCode r"><code class="sourceCode r">dolph_scores &lt;-<span class="st"> </span><span class="kw">scores</span>(dolph_pca, <span class="dt">display =</span> <span class="st">&quot;sites&quot;</span>)
dolph_loads &lt;-<span class="st"> </span><span class="kw">scores</span>(dolph_pca, <span class="dt">display =</span> <span class="st">&quot;species&quot;</span>)
dolph_loads</code></pre>
<pre><code>##           PC1         PC2
## x -0.02990131  0.01608095
## y -7.13731672 -1.43221776
## z -4.56612084  2.23859843
## attr(,&quot;const&quot;)
## [1] 9.089026</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(dolph_scores, <span class="dt">pch =</span> <span class="dv">16</span>, <span class="dt">cex =</span> <span class="fl">0.2</span>, <span class="dt">asp =</span> <span class="dv">1</span>)
<span class="kw">segments</span>(<span class="dt">x0 =</span> <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">3</span>), <span class="dt">y0 =</span> <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">3</span>),
         <span class="dt">x =</span> dolph_loads[, <span class="dv">1</span>]<span class="op">/</span><span class="dv">50</span>,
         <span class="dt">y =</span> dolph_loads[, <span class="dv">2</span>]<span class="op">/</span><span class="dv">50</span>,
         <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">lwd =</span> <span class="dv">4</span>)</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<p>La meilleure représentation du dauphin en 2D, selon la variance, est son profil - en effet, il est plus long et haut que large.</p>
<div class="alert alert-block alert-info">
<strong>Note</strong>. Une ACP effectue seulement une rotation des points. Les distances euclidiennes entre les points sont maintenues.
</div>
<div class="alert alert-block alert-info">
<strong>Note</strong>. L’ACP a été conçue pour projetter en un nombre moindre de dimensions des observations dont les distributions sont multinormales (ce n’est évidemment pas le cas du dauphin).
</div>
<div class="alert alert-block alert-info">
<strong>Note</strong>. Les axes principaux d’une ACP sont des variables aléatoires. Elles peuvent être assujetties à des tests ststistiques, des modèles, du partitionnement de données, etc.
</div>

</div>
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chapitre-explorer.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chapitre-outliers.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
